/-
Copyright (c) 2026 Cameron Freer. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Cameron Freer
-/
import ComputableModelTheory.Computability.OraclePred
import ComputableModelTheory.ModelTheory.Computable.AgeChain
import ComputableModelTheory.ModelTheory.Computable.AgeChainSchedule
import ComputableModelTheory.ModelTheory.Computable.AgeChainSteps
import ComputableModelTheory.ModelTheory.Computable.AgeChainWitness
import ComputableModelTheory.ModelTheory.Computable.AtomicEquiv
import ComputableModelTheory.ModelTheory.Computable.AtomicEquivComputability
import ComputableModelTheory.ModelTheory.Computable.AtomicSatisfaction
import ComputableModelTheory.ModelTheory.Computable.CePresentation
import ComputableModelTheory.ModelTheory.Computable.CeStructureChain
import ComputableModelTheory.ModelTheory.Computable.ChainShiftExample
import ComputableModelTheory.ModelTheory.Computable.CeStructureLimit
import ComputableModelTheory.ModelTheory.Computable.CeStructureLimitEval
import ComputableModelTheory.ModelTheory.Computable.CeStructureLimitPresentation
import ComputableModelTheory.ModelTheory.Computable.CeStructureOmegaLimit
import ComputableModelTheory.ModelTheory.Computable.CeStructureOmegaTuple
import ComputableModelTheory.ModelTheory.Computable.ChainPresentation
import ComputableModelTheory.ModelTheory.Computable.ComputableIso
import ComputableModelTheory.ModelTheory.Computable.ConstantExample
import ComputableModelTheory.ModelTheory.Computable.DecidablePresentation
import ComputableModelTheory.ModelTheory.Computable.Diagram
import ComputableModelTheory.ModelTheory.Computable.GeneratedImageIso
import ComputableModelTheory.ModelTheory.Computable.GeneratedPresentation
import ComputableModelTheory.ModelTheory.Computable.GraphExample
import ComputableModelTheory.ModelTheory.Computable.InitialSegmentPresentation
import ComputableModelTheory.ModelTheory.Computable.PartialAge
import ComputableModelTheory.ModelTheory.Computable.PartialAgeSemantics
import ComputableModelTheory.ModelTheory.Computable.PartialPotentialTransport
import ComputableModelTheory.ModelTheory.Computable.PartialComputableIso
import ComputableModelTheory.ModelTheory.Computable.RepresentationIso
import ComputableModelTheory.ModelTheory.Computable.RepresentationConjugation
import ComputableModelTheory.ModelTheory.Computable.RepresentationWitnessTransport
import ComputableModelTheory.ModelTheory.Computable.PartialAgeSteps
import ComputableModelTheory.ModelTheory.Computable.PartialAllUniv
import ComputableModelTheory.ModelTheory.Computable.PartialCHP
import ComputableModelTheory.ModelTheory.Computable.PartialCHPReconciliation
import ComputableModelTheory.ModelTheory.Computable.PartialCAP
import ComputableModelTheory.ModelTheory.Computable.PartialCAPBridge
import ComputableModelTheory.ModelTheory.Computable.PartialCAPReconciliation
import ComputableModelTheory.ModelTheory.Computable.PartialCJEP
import ComputableModelTheory.ModelTheory.Computable.PartialCJEPReconciliation
import ComputableModelTheory.ModelTheory.Computable.PartialCePresentation
import ComputableModelTheory.ModelTheory.Computable.PartialFiniteChecker
import ComputableModelTheory.ModelTheory.Computable.PartialFiniteRoute
import ComputableModelTheory.ModelTheory.Computable.PartialMemberEmbedding
import ComputableModelTheory.ModelTheory.Computable.PartialTermEvaluation
import ComputableModelTheory.ModelTheory.Computable.PartialSameClass
import ComputableModelTheory.ModelTheory.Computable.PartialTheorem28
import ComputableModelTheory.ModelTheory.Computable.PartialTupleReindex
import ComputableModelTheory.ModelTheory.Computable.PartialWitnessBridge
import ComputableModelTheory.ModelTheory.Computable.QFSatisfaction
import ComputableModelTheory.ModelTheory.Computable.RankPresentation
import ComputableModelTheory.ModelTheory.Computable.Structure
import ComputableModelTheory.ModelTheory.Computable.SuccExample
import ComputableModelTheory.ModelTheory.Computable.TermClosure
import ComputableModelTheory.ModelTheory.Computable.TupleReindex
import ComputableModelTheory.ModelTheory.Computable.TermEvaluation
import Mathlib.ModelTheory.Basic
import Mathlib.ModelTheory.Semantics

/-!
# Computable structures

Umbrella module for the computable-structure layer: ω-presented computable structures,
computable term evaluation, atomic and quantifier-free satisfaction, and the signed atomic and
quantifier-free diagram predicates at fixed width; generated computable presentations, atomic
equivalence of tuples with its generator-preserving closure-equivalence characterization,
effective term enumeration over tuple closures, and the r.e. failure of atomic equivalence
between presentations; c.e.-domain, decidable-domain and partial presentations with computable
isomorphisms, canonical transport, presentation chains and their limits; and the partial
(possibly-empty carrier) age setting with its potential-embedding realization theory, effective
witness interfaces, finite-carrier embedding decision procedure, and computable isomorphism of
representations with transport of embedding data along covers.
-/
