/-
Copyright (c) 2026 Cameron Freer. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Cameron Freer
-/
import Mathlib.ModelTheory.Substructures

/-!
# Finite tuples and semantic tuple closure

The tuple and closure infrastructure of the roadmap: list-backed finite tuples with a
fixed-width view, the substructure generated by a tuple, and the central semantic gate

```
x ∈ Substructure.closure L (Set.range a) ↔ ∃ t : L.Term (Fin k), t.realize a = x
```

specializing mathlib's `Substructure.mem_closure_iff_exists_term` — whose terms have
the generating set's subtype as variables — to finite tuples through a
relabeling/preimage argument. `Generates` records that a tuple's closure is the whole
structure, characterized as every element being a term value.

Tuples are lists, not a dependent sigma: the fixed-width view `Tuple.view` recovers
the function form `Fin a.length → M` when needed, and all width-generic statements
are phrased over `Fin k → M` at a fixed `k`. Effective term enumeration over the
closure is deliberately deferred to a later tranche.

The fixed-width gate is an upstream candidate for mathlib.
-/

open FirstOrder Language

namespace FirstOrder.Language

variable {L : Language} {M : Type*} [L.Structure M]

/-- A finite tuple over `M`: list-backed, avoiding a dependent sigma encoding. -/
abbrev Tuple (M : Type*) := List M

namespace Tuple

/-- The fixed-width view of a tuple. -/
def view (a : Tuple M) : Fin a.length → M :=
  a.get

@[simp]
theorem view_eq_get (a : Tuple M) (i : Fin a.length) : a.view i = a.get i :=
  rfl

/-- The range of a tuple's view is its set of entries. -/
theorem range_view (a : Tuple M) : Set.range a.view = {x | x ∈ a} := by
  ext x
  constructor
  · rintro ⟨i, rfl⟩
    exact a.get_mem i
  · intro hx
    obtain ⟨i, hi⟩ := List.mem_iff_get.1 hx
    exact ⟨i, hi⟩

/-- The substructure generated by a tuple's entries. -/
def closure (L : Language) [L.Structure M] (a : Tuple M) : L.Substructure M :=
  Substructure.closure L {x | x ∈ a}

theorem closure_eq (a : Tuple M) :
    Tuple.closure L a = Substructure.closure L (Set.range a.view) := by
  rw [range_view]
  rfl

end Tuple

section TupleClosure

variable {k : ℕ}

/-- The central semantic gate: membership in the closure of a tuple's range is
realization of a term over the tuple. The finite-tuple specialization of
`Substructure.mem_closure_iff_exists_term`, by relabeling terms along the tuple and
along chosen preimages. -/
theorem mem_closure_range_iff_exists_term (a : Fin k → M) {x : M} :
    x ∈ Substructure.closure L (Set.range a) ↔
      ∃ t : L.Term (Fin k), t.realize a = x := by
  rw [Substructure.mem_closure_iff_exists_term]
  constructor
  · rintro ⟨t, rfl⟩
    refine ⟨t.relabel fun s ↦ (Set.mem_range.1 s.2).choose, ?_⟩
    rw [Term.realize_relabel]
    congr 1
    funext s
    exact (Set.mem_range.1 s.2).choose_spec
  · rintro ⟨t, rfl⟩
    exact ⟨t.relabel fun i ↦ ⟨a i, Set.mem_range_self i⟩, by
      rw [Term.realize_relabel]
      rfl⟩

/-- The list form of the gate: membership in a tuple's closure is realization of a
term over the tuple's view. -/
theorem Tuple.mem_closure_iff_exists_term (a : Tuple M) {x : M} :
    x ∈ Tuple.closure L a ↔ ∃ t : L.Term (Fin a.length), t.realize a.view = x := by
  rw [Tuple.closure_eq, mem_closure_range_iff_exists_term]

/-- A list tuple generates the structure when its closure is everything. -/
def Tuple.Generates (L : Language) [L.Structure M] (a : Tuple M) : Prop :=
  Tuple.closure L a = ⊤

/-- A list tuple generates exactly when every element is a term value over its view. -/
theorem Tuple.generates_iff (a : Tuple M) :
    Tuple.Generates L a ↔
      ∀ x : M, ∃ t : L.Term (Fin a.length), t.realize a.view = x := by
  constructor
  · intro h x
    exact (Tuple.mem_closure_iff_exists_term a).1 (h ▸ Substructure.mem_top x)
  · intro h
    refine eq_top_iff.2 fun x _ ↦ ?_
    exact (Tuple.mem_closure_iff_exists_term a).2 (h x)

/-- List-form monotonicity: entry containment yields closure containment. -/
theorem Tuple.closure_mono {a b : Tuple M} (h : ∀ x ∈ a, x ∈ b) :
    Tuple.closure L a ≤ Tuple.closure L b :=
  Substructure.closure_mono h

/-- A fixed-width tuple generates the structure when its closure is everything. -/
def Generates (L : Language) [L.Structure M] (a : Fin k → M) : Prop :=
  Substructure.closure L (Set.range a) = ⊤

/-- A tuple generates the structure exactly when every element is a term value. -/
theorem generates_iff (a : Fin k → M) :
    Generates L a ↔ ∀ x : M, ∃ t : L.Term (Fin k), t.realize a = x := by
  constructor
  · intro h x
    exact (mem_closure_range_iff_exists_term a).1 (h ▸ Substructure.mem_top x)
  · intro h
    refine eq_top_iff.2 fun x _ ↦ ?_
    exact (mem_closure_range_iff_exists_term a).2 (h x)

/-- Tuple-closure monotonicity: covering every entry yields containment. -/
theorem closure_range_mono {m : ℕ} {a : Fin k → M} {b : Fin m → M}
    (h : ∀ i, ∃ j, b j = a i) :
    Substructure.closure L (Set.range a) ≤ Substructure.closure L (Set.range b) :=
  Substructure.closure_mono (by rintro x ⟨i, rfl⟩; exact h i)

variable {N : Type*} [L.Structure N]

/-- A homomorphism maps the closure of a tuple onto the closure of its image tuple. -/
theorem map_closure_range (f : M →[L] N) (a : Fin k → M) :
    (Substructure.closure L (Set.range a)).map f =
      Substructure.closure L (Set.range (f ∘ a)) := by
  rw [Substructure.map_closure, Set.range_comp]

/-- A homomorphism maps a list tuple's closure onto the mapped tuple's closure. -/
theorem Tuple.map_closure (f : M →[L] N) (a : Tuple M) :
    (Tuple.closure L a).map f = Tuple.closure L (a.map f) := by
  rw [Tuple.closure, Tuple.closure, Substructure.map_closure]
  congr 1
  ext x
  simp

end TupleClosure

end FirstOrder.Language
