/-
Copyright (c) 2026 Cameron Freer. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Cameron Freer
-/
import ComputableModelTheory.ModelTheory.Computable.AutomorphismExtension
import ComputableModelTheory.ModelTheory.Computable.Theorem39Forward
import ComputableModelTheory.ModelTheory.Computable.ListAgeCAP
import ComputableModelTheory.Util.AssertAxioms

/-!
# Audit: Corollary 3.5

* **The core takes no oracle inclusion** (`test_core_no_inclusion`): structures at `O`, the
  self-representation and the homogeneity selector at an arbitrary `E`, nothing relating them.
* **The decisive row: a nontrivial prescribed isomorphism, with its action proved**
  (`test_decisive_swap`). The fixture is the Theorem 3.9 run structure on the list age — pure sets,
  proved computably homogeneous by the production theorem `runStructure_fraisseLimit` — at `E = O`.
  The prescribed isomorphism swaps `0` and `1` on the substructure they generate. The computable
  automorphism `corollary_3_5` produces sends `0 ↦ 1` and `1 ↦ 0`, so it is not the identity.
* **The tuple-extension package on the same swap** (`test_seed_swap`): the seed
  `([0, 1], [1, 0])` is matched, and the automorphism built from it carries `0 ↦ 1`, `1 ↦ 0`.
* **Repeated coordinates** (`test_seed_repeated`): the seed `([0, 0, 1], [1, 1, 0])` is matched,
  and both repeated positions of `0` read the same image.
* **The offset, on a nonempty seed** (`test_seed_offset`): from the length-three repeated seed, the
  tuples have length `3 + 2 * n` and `n` is discovered at `3 + 2 * n` (source) and `3 + 2 * n + 1`
  (target). The empty specialization alone cannot test the shift.
* **Standard axioms** for the production module and every row.
-/

open Encodable FirstOrder Language

namespace FirstOrder.Language

/-! ### The core, with no oracle inclusion -/

/-- **No `O ⊆ E` in the core**: the self-representation and the selector are data at `E`. -/
theorem test_core_no_inclusion {O E : Set (ℕ →. ℕ)} {L : Language} [L.EffectiveLanguage]
    {F : ComputableStructureIn O L} (r : RepresentationIsoIn E F.canonicalAge F.canonicalAge)
    (H : ComputablyHomogeneousIn E F) :
    letI : L.Structure ℕ := F.inst
    ∀ {A B : L.Substructure ℕ}, A.FG → ∀ e : A ≃[L] B,
      ∃ α : ComputableStructureIsoIn E F F, ∀ x : A, α.toFun x = (e x : ℕ) :=
  exists_automorphism_extending r H

/-! ### The fixture: the run structure on the list age -/

section Fixture

variable (O : Set (ℕ →. ℕ))

/-- The Theorem 3.9 run structure on the list age: a computable pure set. -/
noncomputable abbrev fixF : ComputableStructureIn O Language.empty :=
  PartialAgeIn.runStructure (listAge O) (listAge.capWitness O) (encode [0])
    listAge.base_nonempty (listAge.runLimit_cert O)

/-- Its computable homogeneity, from the production theorem. -/
noncomputable def fixH : ComputablyHomogeneousIn O (fixF O) :=
  (PartialAgeIn.runStructure_fraisseLimit (listAge.capWitness O) (encode [0])
    listAge.base_nonempty listAge.mappedPartialCHPIn listAge.partialCJEPIn
    (listAge.runLimit_cert O)).1.some

/-- The self-representation at `E = O`: the identity. -/
noncomputable def fixR : RepresentationIsoIn O (fixF O).canonicalAge (fixF O).canonicalAge :=
  RepresentationIsoIn.refl _ subset_rfl

/-- The substructure generated by `0` and `1`. -/
noncomputable def pairSub : @Substructure Language.empty ℕ (fixF O).inst :=
  @Substructure.closure Language.empty ℕ (fixF O).inst {0, 1}

theorem zero_mem_pairSub : (0 : ℕ) ∈ pairSub O :=
  @Substructure.subset_closure Language.empty ℕ (fixF O).inst _ _ (by simp)

theorem one_mem_pairSub : (1 : ℕ) ∈ pairSub O :=
  @Substructure.subset_closure Language.empty ℕ (fixF O).inst _ _ (by simp)

/-- **The prescribed isomorphism**: the swap of `0` and `1` on the substructure they generate. -/
noncomputable def swapE :
    letI : Language.empty.Structure ℕ := (fixF O).inst
    pairSub O ≃[Language.empty] pairSub O :=
  letI : Language.empty.Structure ℕ := (fixF O).inst
  StrongHomClass.toEquiv (Equiv.swap (⟨0, zero_mem_pairSub O⟩ : pairSub O) ⟨1, one_mem_pairSub O⟩)

theorem swapE_zero :
    letI : Language.empty.Structure ℕ := (fixF O).inst
    ((swapE O ⟨0, zero_mem_pairSub O⟩ : pairSub O) : ℕ) = 1 := by
  simp [swapE]

theorem swapE_one :
    letI : Language.empty.Structure ℕ := (fixF O).inst
    ((swapE O ⟨1, one_mem_pairSub O⟩ : pairSub O) : ℕ) = 0 := by
  simp [swapE]

/-! ### The decisive row -/

/-- **A nontrivial prescribed isomorphism, with the automorphism's action proved.** The computable
automorphism extending the swap sends `0 ↦ 1` and `1 ↦ 0`; in particular it is not the identity. -/
theorem test_decisive_swap :
    ∃ α : ComputableStructureIsoIn O (fixF O) (fixF O),
      α.toFun 0 = 1 ∧ α.toFun 1 = 0 ∧ α.toFun ≠ id := by
  let : Language.empty.Structure ℕ := (fixF O).inst
  obtain ⟨α, hα⟩ := corollary_3_5 (fixH O) (A := pairSub O) (B := pairSub O)
    (Substructure.fg_closure (Set.toFinite _)) (swapE O)
  have h0 : α.toFun 0 = 1 := (hα ⟨0, zero_mem_pairSub O⟩).trans (swapE_zero O)
  have h1 : α.toFun 1 = 0 := (hα ⟨1, one_mem_pairSub O⟩).trans (swapE_one O)
  refine ⟨α, h0, h1, fun h ↦ ?_⟩
  have := congrFun h 0
  rw [h0] at this
  exact absurd this (by decide)

/-! ### The tuple-extension package -/

theorem mem_pairSub_of_mem {x : ℕ} (hx : x ∈ [0, 1]) : x ∈ pairSub O := by
  simp only [List.mem_cons, List.not_mem_nil, or_false] at hx
  rcases hx with rfl | rfl
  · exact zero_mem_pairSub O
  · exact one_mem_pairSub O

theorem equivExtend_swapE_zero :
    letI : Language.empty.Structure ℕ := (fixF O).inst
    equivExtend (swapE O) 0 = 1 := by
  let : Language.empty.Structure ℕ := (fixF O).inst
  rw [equivExtend_of_mem _ (zero_mem_pairSub O)]
  exact swapE_zero O

theorem equivExtend_swapE_one :
    letI : Language.empty.Structure ℕ := (fixF O).inst
    equivExtend (swapE O) 1 = 0 := by
  let : Language.empty.Structure ℕ := (fixF O).inst
  rw [equivExtend_of_mem _ (one_mem_pairSub O)]
  exact swapE_one O

/-- The swap seed `([0, 1], [1, 0])` is matched. -/
theorem swapSeed_matched : (⟨[0, 1], [1, 0]⟩ : BackForthState).Matched (fixF O) (fixF O) := by
  let : Language.empty.Structure ℕ := (fixF O).inst
  have h := matched_seed (F := fixF O) (swapE O) [0, 1] fun x hx ↦ mem_pairSub_of_mem O hx
  rwa [List.map_cons, List.map_cons, List.map_nil, equivExtend_swapE_zero,
    equivExtend_swapE_one] at h

/-- The repeated seed `([0, 0, 1], [1, 1, 0])` is matched. -/
theorem repeatedSeed_matched :
    (⟨[0, 0, 1], [1, 1, 0]⟩ : BackForthState).Matched (fixF O) (fixF O) := by
  let : Language.empty.Structure ℕ := (fixF O).inst
  have h := matched_seed (F := fixF O) (swapE O) [0, 0, 1] fun x hx ↦
    mem_pairSub_of_mem O (by simpa using hx)
  rwa [List.map_cons, List.map_cons, List.map_cons, List.map_nil, equivExtend_swapE_zero,
    equivExtend_swapE_one] at h

/-- **The swap seed is extended**: the automorphism built from `([0, 1], [1, 0])` sends `0 ↦ 1`
and `1 ↦ 0`. -/
theorem test_seed_swap :
    (extendToAutomorphism (fixR O) (fixH O) _ (swapSeed_matched O)).toFun 0 = 1 ∧
      (extendToAutomorphism (fixR O) (fixH O) _ (swapSeed_matched O)).toFun 1 = 0 := by
  have h0 := extendToAutomorphism_extends (fixR O) (fixH O) (swapSeed_matched O)
    (i := 0) (x := 0) rfl
  have h1 := extendToAutomorphism_extends (fixR O) (fixH O) (swapSeed_matched O)
    (i := 1) (x := 1) rfl
  exact ⟨(Option.some.inj h0).symm, (Option.some.inj h1).symm⟩

/-- **Repeated coordinates**: from `([0, 0, 1], [1, 1, 0])`, both positions of `0` read the image
`1`, and `1 ↦ 0`. -/
theorem test_seed_repeated :
    let α := extendToAutomorphism (fixR O) (fixH O) _ (repeatedSeed_matched O)
    ([1, 1, 0] : Tuple ℕ)[0]? = some (α.toFun 0) ∧ ([1, 1, 0] : Tuple ℕ)[1]? = some (α.toFun 0) ∧
      α.toFun 1 = 0 := by
  intro α
  have h0 := extendToAutomorphism_extends (fixR O) (fixH O) (repeatedSeed_matched O)
    (i := 0) (x := 0) rfl
  have h1 := extendToAutomorphism_extends (fixR O) (fixH O) (repeatedSeed_matched O)
    (i := 1) (x := 0) rfl
  have h2 := extendToAutomorphism_extends (fixR O) (fixH O) (repeatedSeed_matched O)
    (i := 2) (x := 1) rfl
  exact ⟨h0, h1, (Option.some.inj h2).symm⟩

/-- **The offset, on the length-three seed.** -/
theorem test_seed_offset (n : ℕ) :
    let s₀ : BackForthState := ⟨[0, 0, 1], [1, 1, 0]⟩
    let run := BackForthState.stateAt (fixR O).forward (fixR O).backward (fixH O) (fixH O) s₀
    (run n).sourceTuple.length = 3 + 2 * n ∧ (run n).targetTuple.length = 3 + 2 * n ∧
      (run (n + 1)).sourceTuple[3 + 2 * n]? = some n ∧
        (run (n + 1)).targetTuple[3 + 2 * n + 1]? = some n := by
  intro s₀ run
  exact ⟨BackForthState.stateAt_sourceTuple_length _ _ _ _ s₀ n,
    BackForthState.stateAt_targetTuple_length _ _ _ _ s₀ n,
    BackForthState.stateAt_sourceTuple_getElem?_two_mul _ _ _ _ s₀ n,
    BackForthState.stateAt_targetTuple_getElem?_two_mul_succ _ _ _ _ s₀ n⟩

end Fixture

end FirstOrder.Language

#assert_standard_axioms FirstOrder.Language.test_core_no_inclusion
#assert_standard_axioms FirstOrder.Language.test_decisive_swap
#assert_standard_axioms FirstOrder.Language.test_seed_swap
#assert_standard_axioms FirstOrder.Language.test_seed_repeated
#assert_standard_axioms FirstOrder.Language.test_seed_offset

#assert_module_standard_axioms ComputableModelTheory.ModelTheory.Computable.AutomorphismExtension
