/-
Copyright (c) 2026 Cameron Freer. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Cameron Freer
-/
import ComputableModelTheory.ModelTheory.Computable.BackForth
import ComputableModelTheory.Util.AssertAxioms

/-!
# Audit: the back-and-forth state — landing 1

Three obligations, each about a boundary rather than a computation.

**The map oracle is independent of the presentation oracle.** `test_map_oracle_independent` takes an
isomorphism at an **arbitrary** `E` over structures at `O`, with no relation between them assumed,
and reads back all six laws — only two of which mention `E` at all. `test_symm_needs_no_inclusion`
makes the same point for the groupoid operation. If a later refactor introduced `O ⊆ E`, these rows
would stop elaborating.

**The state is proof-free, and coded now rather than later.**
`test_state_is_proof_free` builds a state from two *arbitrary* tuples — `BackForthState` does not
even mention `O`, `L`, `S` or `T`, so there is nowhere for an invariant to hide.
`test_state_is_computably_coded` reads back all three coding facts together, because the stage
recursion needs to take a state apart *and* put one back together; supplying only the projections
would leave the transition function unbuildable.

**The invariant is cross-family and tight.** `test_matched_is_cross_family` records that the source
member is drawn from `S.canonicalAge` and the target from `T.canonicalAge`, so the single-family
`PartialRealizes` genuinely does not apply here. `test_tight_map_targets_its_range` pins the datum's
two indices: the codomain is `encode targetTuple` and the range tuple is `targetTuple`, so the target
member is exactly the one generated by the tuple the state records — which is what lets the
corestriction lemma apply without further hypotheses.

Deliberately absent: consistency of repeated coordinates, the base case, cover and homogeneity
consumption, and the two half-steps. Those are later landings.
-/

open Encodable FirstOrder Language

namespace FirstOrder.Language

variable {O : Set (ℕ →. ℕ)} {L : Language} [L.EffectiveLanguage]

/-! ### The map oracle is independent -/

/-- **`E` is unrelated to `O`.** The structures are presented at `O`, the maps are computable at an
arbitrary `E`, and no inclusion between them is assumed or used. Of the six laws, only the two
computability fields mention `E`. -/
theorem test_map_oracle_independent {E : Set (ℕ →. ℕ)} {S T : ComputableStructureIn O L}
    (i : ComputableStructureIsoIn E S T) :
    (ComputableIn E i.toFun ∧ ComputableIn E i.invFun) ∧
      (∀ x, i.invFun (i.toFun x) = x) ∧ (∀ y, i.toFun (i.invFun y) = y) ∧
      (∀ (n : ℕ) (f : L.Functions n) (v : Fin n → ℕ),
        i.toFun (@Structure.funMap L ℕ S.inst n f v)
          = @Structure.funMap L ℕ T.inst n f fun k ↦ i.toFun (v k)) ∧
      ∀ (n : ℕ) (R : L.Relations n) (v : Fin n → ℕ),
        @Structure.RelMap L ℕ T.inst n R (fun k ↦ i.toFun (v k))
          ↔ @Structure.RelMap L ℕ S.inst n R v :=
  ⟨⟨i.toFun_computableIn, i.invFun_computableIn⟩, i.left_inv, i.right_inv,
    i.toFun_funMap, i.toFun_relMap⟩

/-- Symmetry needs no inclusion either — it swaps the stored maps and reads the laws backwards. -/
theorem test_symm_needs_no_inclusion {E : Set (ℕ →. ℕ)} {S T : ComputableStructureIn O L}
    (i : ComputableStructureIsoIn E S T) :
    Nonempty (ComputableStructureIsoIn E T S) ∧ i.symm.toFun = i.invFun :=
  ⟨⟨i.symm⟩, rfl⟩

/-- The forward map is a bijection, as the two total inverse laws force. -/
theorem test_toFun_bijective {E : Set (ℕ →. ℕ)} {S T : ComputableStructureIn O L}
    (i : ComputableStructureIsoIn E S T) : Function.Bijective i.toFun :=
  i.toFun_bijective

/-! ### The state -/

/-- **Proof-free.** Any two tuples make a state, with no side condition — and `BackForthState`
mentions neither the structures nor the language, so there is nowhere for an invariant to hide. -/
theorem test_state_is_proof_free (a b : Tuple ℕ) :
    ∃ s : BackForthState, s.sourceTuple = a ∧ s.targetTuple = b :=
  ⟨⟨a, b⟩, rfl, rfl⟩

/-- **Coded now, not later.** All three facts together: the stage recursion must take a state apart
*and* build one, so projections alone would leave the transition function unbuildable. -/
theorem test_state_is_computably_coded :
    ComputableIn O BackForthState.sourceTuple ∧ ComputableIn O BackForthState.targetTuple ∧
      ComputableIn O fun p : Tuple ℕ × Tuple ℕ ↦ (⟨p.1, p.2⟩ : BackForthState) :=
  ⟨BackForthState.sourceTuple_computableIn, BackForthState.targetTuple_computableIn,
    BackForthState.mk_computableIn⟩

/-- The tight map is computable too, since the recursion forms it at every stage. -/
theorem test_tightMap_computableIn : ComputableIn O BackForthState.tightMap :=
  BackForthState.tightMap_computableIn

/-! ### The invariant -/

/-- **Cross-family.** The source member is drawn from `S.canonicalAge` and the target from
`T.canonicalAge`, so `PartialRealizesBetween` is required and the single-family `PartialRealizes`
does not typecheck here. -/
theorem test_matched_is_cross_family {S T : ComputableStructureIn O L} {s : BackForthState} :
    s.Matched S T ↔
      ∃ f, PartialAgeIn.PartialRealizesBetween S.canonicalAge T.canonicalAge
        (PotentialEmbeddingData.ofTriple
          (encode s.sourceTuple, encode s.targetTuple, s.targetTuple)) f :=
  BackForthState.matched_iff

/-- **The datum is tight**: its codomain index is `encode targetTuple` and its range tuple is
`targetTuple`, so the target member is exactly the one generated by the tuple the state records.
That is what will let the corestriction lemma apply with no further hypothesis. -/
theorem test_tight_map_targets_its_range (s : BackForthState) :
    s.tightMap.domIdx = encode s.sourceTuple ∧
      s.tightMap.codIdx = encode s.targetTuple ∧
        s.tightMap.rangeTuple = s.targetTuple :=
  ⟨rfl, rfl, rfl⟩

/-- Lengths agree on a matched state — the realizer's length equation, read through
`gens (encode t) = t`. -/
theorem test_matched_lengths {S T : ComputableStructureIn O L} {s : BackForthState}
    (h : s.Matched S T) : s.sourceTuple.length = s.targetTuple.length :=
  BackForthState.length_eq_of_matched h

/-- The realizer of a matched state is unique, so "the" embedding is unambiguous. -/
theorem test_matched_realizer_unique {S T : ComputableStructureIn O L} {s : BackForthState}
    {f g : (S.canonicalAge.memberAt s.tightMap.domIdx).domain ↪[L]
      (T.canonicalAge.memberAt s.tightMap.codIdx).domain}
    (hf : PartialAgeIn.PartialRealizesBetween S.canonicalAge T.canonicalAge s.tightMap f)
    (hg : PartialAgeIn.PartialRealizesBetween S.canonicalAge T.canonicalAge s.tightMap g) :
    f = g :=
  BackForthState.matched_unique hf hg

/-! ### Coordinate consistency

Three distinct facts, so that the interface is pinned from both sides rather than only by its
negative constraints.

**Repetition is permitted.** `test_repeated_state_is_matched` exhibits an actual matched state whose
source tuple repeats a point — the identity realizer on `[a, a] ↦ [a, a]`, over an arbitrary
computable structure. Without this row, the two negative results would be equally consistent with
"no matched state ever repeats a coordinate", and a later step could silently deduplicate.

**Both consistency directions bite.** The two negative rows are not symmetric restatements: the first
is the realizer's functionality, the second its injectivity. Each is stated over *arbitrary* `S` and
`T`, so neither leans on a fixture. -/

section Consistency

/-- **No deduplication.** A genuine matched state with a repeated source coordinate: the identity
member embedding realizes `[a, a] ↦ [a, a]` over any computable structure. The second conjunct
records that the repetition is really there. -/
theorem test_repeated_state_is_matched (S : ComputableStructureIn O L) (a : ℕ) :
    (⟨[a, a], [a, a]⟩ : BackForthState).Matched S S ∧
      (⟨[a, a], [a, a]⟩ : BackForthState).sourceTuple[0]?
        = (⟨[a, a], [a, a]⟩ : BackForthState).sourceTuple[1]? := by
  have hgens : S.canonicalAge.gens (encode [a, a]) = [a, a] := allTupleFor_encode _
  have hlen : (S.canonicalAge.gens
      (⟨[a, a], [a, a]⟩ : BackForthState).tightMap.domIdx).length
      = (⟨[a, a], [a, a]⟩ : BackForthState).tightMap.rangeTuple.length := by
    show (S.canonicalAge.gens (encode [a, a])).length = ([a, a] : Tuple ℕ).length
    rw [hgens]
  refine ⟨⟨PartialAgeIn.memberEmbedding rfl (Set.Subset.refl _), hlen, fun k ↦ ?_⟩, rfl⟩
  show ((S.canonicalAge.gens (encode [a, a])).get k : ℕ)
    = ([a, a] : Tuple ℕ).get (Fin.cast hlen k)
  rw [List.get_eq_getElem, List.get_eq_getElem]
  exact List.getElem_of_eq hgens k.2

/-- **Functionality bites.** A state repeating a source point but sending the two positions to
different images cannot be matched — over any pair of computable structures. -/
theorem test_repeated_source_unequal_target_not_matched {S T : ComputableStructureIn O L} :
    ¬ (⟨[7, 7], [3, 5]⟩ : BackForthState).Matched S T := by
  intro h
  have h01 := BackForthState.target_getElem?_eq_of_source_getElem?_eq (i := 0) (j := 1) h rfl
  simp at h01

/-- **Injectivity bites.** Dually, a state repeating an image but recording different source points
at those positions cannot be matched. Not a restatement of the previous row: that one is the
realizer being a function, this one is its being an embedding. -/
theorem test_repeated_target_unequal_source_not_matched {S T : ComputableStructureIn O L} :
    ¬ (⟨[3, 5], [7, 7]⟩ : BackForthState).Matched S T := by
  intro h
  have h01 := BackForthState.source_getElem?_eq_of_target_getElem?_eq (i := 0) (j := 1) h rfl
  simp at h01

/-- **Global and cast-free.** Both consequences apply at *any* pair of indices, with no bound and no
length hypothesis — out of range they say `none = none`, which is what makes them composable in the
inverse-law proofs. -/
theorem test_consistency_is_global {S T : ComputableStructureIn O L} {s : BackForthState}
    (h : s.Matched S T) (i j : ℕ) :
    (s.sourceTuple[i]? = s.sourceTuple[j]? → s.targetTuple[i]? = s.targetTuple[j]?) ∧
      (s.targetTuple[i]? = s.targetTuple[j]? → s.sourceTuple[i]? = s.sourceTuple[j]?) :=
  ⟨BackForthState.target_getElem?_eq_of_source_getElem?_eq h,
    BackForthState.source_getElem?_eq_of_target_getElem?_eq h⟩

/-- Out of range on both sides, with no hypothesis about the state beyond matching. -/
theorem test_consistency_out_of_range {S T : ComputableStructureIn O L} {s : BackForthState}
    (h : s.Matched S T) {i j : ℕ} (hi : s.sourceTuple.length ≤ i)
    (hj : s.sourceTuple.length ≤ j) : s.targetTuple[i]? = s.targetTuple[j]? :=
  BackForthState.target_getElem?_eq_of_source_getElem?_eq h
    (by rw [List.getElem?_eq_none hi, List.getElem?_eq_none hj])

end Consistency

/-! ### The base case

Two things to gate, and only two: that the empty state is matched at all, and that the hypothesis is
a **forward cover** rather than anything larger.

The signature row is the substantive one. `test_empty_from_forward_cover_only` derives the base case
from an arbitrary `RepresentationCoverIn E S.canonicalAge T.canonicalAge`, with `E` unrelated to `O`
and no inclusion between them — so no homogeneity, computability, or oracle hypothesis can have crept
in. `test_empty_orientation_is_structural` then shows what a full `RepresentationIsoIn` buys: its
`forward` field gives `empty.Matched S T` and its `backward` field gives `empty.Matched T S`. The two
are different statements, and which one a proof gets is fixed by the cover's direction rather than by
which field it happens to project.

Nonvacuity is already gated elsewhere: `CanonicalRangeAudit`'s constant-language rows show the
empty-generator corestriction is surjective onto a **nonempty** carrier, which is exactly the content
that would be missing if the empty case were only exercised where `D_⟨⟩` is empty. -/

section BaseCase

variable {E : Set (ℕ →. ℕ)}

/-- The empty state records nothing. -/
theorem test_empty_state_is_empty :
    BackForthState.empty.sourceTuple = [] ∧ BackForthState.empty.targetTuple = [] :=
  ⟨rfl, rfl⟩

/-- **A forward cover suffices, and is all that is assumed.** `E` is unrelated to `O`; there is no
`O ⊆ E`, no homogeneity, and no computability hypothesis in sight. -/
theorem test_empty_from_forward_cover_only {S T : ComputableStructureIn O L}
    (r : RepresentationCoverIn E S.canonicalAge T.canonicalAge) :
    BackForthState.empty.Matched S T :=
  BackForthState.empty_matched r

/-- **The orientation is structural.** A full isomorphism of representations yields the base case in
*both* directions — but as two different statements, each from the cover pointing that way. A proof
cannot reach `Matched S T` through `backward`. -/
theorem test_empty_orientation_is_structural {S T : ComputableStructureIn O L}
    (r : RepresentationIsoIn E S.canonicalAge T.canonicalAge) :
    BackForthState.empty.Matched S T ∧ BackForthState.empty.Matched T S :=
  ⟨BackForthState.empty_matched r.forward, BackForthState.empty_matched r.backward⟩

/-- The base case is consistent, trivially: both consequences hold at every pair of indices, since
every lookup is `none`. Recorded so the recursion's invariant is visibly established at stage 0. -/
theorem test_empty_is_consistent {S T : ComputableStructureIn O L}
    (r : RepresentationCoverIn E S.canonicalAge T.canonicalAge) (i j : ℕ) :
    BackForthState.empty.targetTuple[i]? = BackForthState.empty.targetTuple[j]? ∧
      BackForthState.empty.sourceTuple[i]? = BackForthState.empty.sourceTuple[j]? :=
  ⟨BackForthState.target_getElem?_eq_of_source_getElem?_eq (BackForthState.empty_matched r) rfl,
    BackForthState.source_getElem?_eq_of_target_getElem?_eq (BackForthState.empty_matched r) rfl⟩

end BaseCase

end FirstOrder.Language

#assert_standard_axioms FirstOrder.Language.test_map_oracle_independent
#assert_standard_axioms FirstOrder.Language.test_symm_needs_no_inclusion
#assert_standard_axioms FirstOrder.Language.test_toFun_bijective
#assert_standard_axioms FirstOrder.Language.test_state_is_proof_free
#assert_standard_axioms FirstOrder.Language.test_state_is_computably_coded
#assert_standard_axioms FirstOrder.Language.test_tightMap_computableIn
#assert_standard_axioms FirstOrder.Language.test_matched_is_cross_family
#assert_standard_axioms FirstOrder.Language.test_tight_map_targets_its_range
#assert_standard_axioms FirstOrder.Language.test_matched_lengths
#assert_standard_axioms FirstOrder.Language.test_matched_realizer_unique
#assert_standard_axioms FirstOrder.Language.test_repeated_state_is_matched
#assert_standard_axioms FirstOrder.Language.test_repeated_source_unequal_target_not_matched
#assert_standard_axioms FirstOrder.Language.test_repeated_target_unequal_source_not_matched
#assert_standard_axioms FirstOrder.Language.test_consistency_is_global
#assert_standard_axioms FirstOrder.Language.test_consistency_out_of_range
#assert_standard_axioms FirstOrder.Language.test_empty_state_is_empty
#assert_standard_axioms FirstOrder.Language.test_empty_from_forward_cover_only
#assert_standard_axioms FirstOrder.Language.test_empty_orientation_is_structural
#assert_standard_axioms FirstOrder.Language.test_empty_is_consistent
