/-
Copyright (c) 2026 Cameron Freer. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Cameron Freer
-/
import ComputableModelTheory.ModelTheory.Computable.CanonicalRange
import ComputableModelTheory.ModelTheory.Computable.ComputableIso
import ComputableModelTheory.ModelTheory.Computable.RepresentationIso
import ComputableModelTheory.ModelTheory.Computable.ComputablyHomogeneous
import ComputableModelTheory.Computability.ListPredicates

/-!
# The back-and-forth state — CHMM Proposition 3.2, landing 1

The state of an effective back-and-forth between two computable structures, and the invariant it is
required to satisfy. Only those; the consistency consequences, the base case, and the two half-steps
land separately.

## The state is proof-free, and computably coded

`BackForthState` carries two tuples and nothing else. No invariant is bundled, for the same reason
`FiniteInjury.StageState` bundles none: a state carrying its own proof cannot be produced by a
recursion that only *later* establishes the property.

Because the recursion that will build it is itself a computable function of the stage, the coding
API is needed up front and is supplied here in full — `Primcodable`, both projections, and the
constructor. Adding any of the three later would mean revisiting the state's definition once the
transition function exists.

## The invariant is separate

`Matched` is an existential over a **cross-family** realizer: the source member lives in
`S.canonicalAge`, the target in `T.canonicalAge`, so the single-family `PartialRealizes` does not
typecheck. The datum is *tight* — its codomain index is `encode targetTuple` and its range tuple is
`targetTuple`, so the target member is exactly the one generated by the tuple the state records,
with nothing left implicit.

Reading it off: `PartialRealizesBetween`'s length equation becomes
`sourceTuple.length = targetTuple.length`, since `S.canonicalAge.gens (encode t) = t`; and its
coordinate clauses say the realizer carries the `k`-th recorded generator to `targetTuple.get k`. So
`Matched` is exactly "the finite assignment `sourceTuple ↦ targetTuple` extends to an embedding of
the generated substructures", and `PartialRealizesBetween.unique` makes the realizer unambiguous.

**Repeated coordinates are legal** and the recursion will not remove them; that `Matched` forces
them to be consistent is landing 2's business, not stated here.
-/

open Encodable FirstOrder Language

namespace FirstOrder.Language

variable {O : Set (ℕ →. ℕ)} {L : Language} [L.EffectiveLanguage]

/-! ### The state -/

/-- The state of an effective back-and-forth: the source points matched so far, and their images.
**Proof-free** — the invariant is `Matched`, kept separate. -/
structure BackForthState where
  /-- The source points matched so far. -/
  sourceTuple : Tuple ℕ
  /-- Their images, positionally. -/
  targetTuple : Tuple ℕ

@[ext]
theorem BackForthState.ext {s t : BackForthState} (hs : s.sourceTuple = t.sourceTuple)
    (ht : s.targetTuple = t.targetTuple) : s = t := by
  cases s; cases t; cases hs; cases ht; rfl

/-- The code-level packaging of a state. -/
private def bfEquiv : BackForthState ≃ Tuple ℕ × Tuple ℕ where
  toFun s := (s.sourceTuple, s.targetTuple)
  invFun p := ⟨p.1, p.2⟩
  left_inv _ := rfl
  right_inv _ := rfl

instance : Primcodable BackForthState :=
  Primcodable.ofEquiv _ bfEquiv

namespace BackForthState

/-! #### Coding

All three pieces are supplied now, because the stage recursion is a computable function of the
stage and needs to take states apart and put them back together. -/

theorem primrec_sourceTuple : Primrec BackForthState.sourceTuple :=
  (Primrec.fst.comp (Primrec.of_equiv (e := bfEquiv))).of_eq fun _ ↦ rfl

theorem primrec_targetTuple : Primrec BackForthState.targetTuple :=
  (Primrec.snd.comp (Primrec.of_equiv (e := bfEquiv))).of_eq fun _ ↦ rfl

theorem sourceTuple_computableIn : ComputableIn O BackForthState.sourceTuple :=
  primrec_sourceTuple.to_comp.computableIn

theorem targetTuple_computableIn : ComputableIn O BackForthState.targetTuple :=
  primrec_targetTuple.to_comp.computableIn

/-- States are built from their two fields. -/
theorem primrec_mk : Primrec fun p : Tuple ℕ × Tuple ℕ ↦ (⟨p.1, p.2⟩ : BackForthState) :=
  (Primrec.of_equiv_symm (e := bfEquiv)).of_eq fun _ ↦ rfl

theorem mk_computableIn :
    ComputableIn O fun p : Tuple ℕ × Tuple ℕ ↦ (⟨p.1, p.2⟩ : BackForthState) :=
  primrec_mk.to_comp.computableIn

/-! #### The tight potential map -/

/-- The state's assignment as potential embedding data: source member at `encode sourceTuple`,
target member at `encode targetTuple`, range tuple `targetTuple`.

**Tight**: the codomain index is the code of the range tuple, so the target is exactly the member
generated by the tuple the state records. -/
def tightMap (s : BackForthState) : PotentialEmbeddingData :=
  PotentialEmbeddingData.ofTriple (encode s.sourceTuple, encode s.targetTuple, s.targetTuple)

@[simp] theorem tightMap_domIdx (s : BackForthState) :
    s.tightMap.domIdx = encode s.sourceTuple := rfl

@[simp] theorem tightMap_codIdx (s : BackForthState) :
    s.tightMap.codIdx = encode s.targetTuple := rfl

@[simp] theorem tightMap_rangeTuple (s : BackForthState) :
    s.tightMap.rangeTuple = s.targetTuple := rfl

theorem primrec_tightMap : Primrec BackForthState.tightMap := by
  have h : Primrec fun s : BackForthState ↦
      (Encodable.encode s.sourceTuple, Encodable.encode s.targetTuple, s.targetTuple) :=
    (Primrec.encode.comp primrec_sourceTuple).pair
      ((Primrec.encode.comp primrec_targetTuple).pair primrec_targetTuple)
  exact (PotentialEmbeddingData.primrec_ofTriple.comp h).of_eq fun _ ↦ rfl

theorem tightMap_computableIn : ComputableIn O BackForthState.tightMap :=
  primrec_tightMap.to_comp.computableIn

end BackForthState

/-! ### The invariant -/

/-- **The back-and-forth invariant**: the state's assignment extends to an embedding of the
generated substructures.

A *cross-family* realizer — source in `S.canonicalAge`, target in `T.canonicalAge` — so the
single-family `PartialRealizes` does not typecheck here. Kept apart from the state, which stays
proof-free. -/
def BackForthState.Matched (S T : ComputableStructureIn O L) (s : BackForthState) : Prop :=
  ∃ f, PartialAgeIn.PartialRealizesBetween S.canonicalAge T.canonicalAge s.tightMap f

theorem BackForthState.matched_iff {S T : ComputableStructureIn O L} {s : BackForthState} :
    s.Matched S T ↔
      ∃ f, PartialAgeIn.PartialRealizesBetween S.canonicalAge T.canonicalAge
        (PotentialEmbeddingData.ofTriple
          (encode s.sourceTuple, encode s.targetTuple, s.targetTuple)) f :=
  Iff.rfl

/-- The realizer is unique where it exists, so "the" embedding of a matched state is unambiguous. -/
theorem BackForthState.matched_unique {S T : ComputableStructureIn O L} {s : BackForthState}
    {f g : (S.canonicalAge.memberAt s.tightMap.domIdx).domain ↪[L]
      (T.canonicalAge.memberAt s.tightMap.codIdx).domain}
    (hf : PartialAgeIn.PartialRealizesBetween S.canonicalAge T.canonicalAge s.tightMap f)
    (hg : PartialAgeIn.PartialRealizesBetween S.canonicalAge T.canonicalAge s.tightMap g) :
    f = g :=
  PartialAgeIn.PartialRealizesBetween.unique hf hg

/-- Lengths agree on a matched state — the length equation of the realizer, read through
`gens (encode t) = t`. -/
theorem BackForthState.length_eq_of_matched {S T : ComputableStructureIn O L}
    {s : BackForthState} (h : s.Matched S T) : s.sourceTuple.length = s.targetTuple.length := by
  obtain ⟨-, hlen, -⟩ := h
  rwa [tightMap_domIdx, tightMap_rangeTuple, S.canonicalAge_gens, allTupleFor_encode] at hlen

/-! ### Coordinate consistency

The two facts the inverse laws will need, stated **positionally and globally**: no length
hypothesis, no bound hypothesis, no `Fin`. Both are `getElem?` equations between the two tuples at
the same pair of indices, so they compose without side conditions.

Each covers two cases at once. In bounds, the content is the realizer's: *functionality* gives
the forward direction (equal source entries are the same carrier point, so their images agree), and
*injectivity* gives the backward one. Out of bounds, `length_eq_of_matched` makes both lookups on
the other side `none`, and the mixed case cannot arise because `some ≠ none`. That is why the
length equality is derived here rather than demanded of the caller.

Repeated coordinates are legal — a state may record the same source point twice — and these lemmas
say exactly what that costs: the images must then agree, and conversely.
-/

namespace BackForthState

variable {S T : ComputableStructureIn O L} {s : BackForthState}

/-- The out-of-bounds bookkeeping, done once for both directions: a positional `getElem?` equation
transfers along any length-matched pair of tuples, given only the in-bounds content. -/
private theorem getElem?_transfer {a b : Tuple ℕ} (hab : a.length = b.length) {i j : ℕ}
    (hij : a[i]? = a[j]?)
    (hin : ∀ (hi : i < a.length) (hj : j < a.length),
      a[i] = a[j] → b[i]'(hab ▸ hi) = b[j]'(hab ▸ hj)) :
    b[i]? = b[j]? := by
  by_cases hi : i < a.length
  · by_cases hj : j < a.length
    · rw [List.getElem?_eq_getElem hi, List.getElem?_eq_getElem hj] at hij
      rw [List.getElem?_eq_getElem (hab ▸ hi), List.getElem?_eq_getElem (hab ▸ hj)]
      exact congrArg some (hin hi hj (Option.some.inj hij))
    · rw [List.getElem?_eq_getElem hi, List.getElem?_eq_none (by omega)] at hij
      exact absurd hij (by simp)
  · have hj : ¬ j < a.length := by
      intro hj
      rw [List.getElem?_eq_none (by omega), List.getElem?_eq_getElem hj] at hij
      exact absurd hij (by simp)
    rw [List.getElem?_eq_none (by omega), List.getElem?_eq_none (by omega)]

/-- Every entry of a tuple names a point of the canonical member it generates. -/
private theorem exists_coe_eq_getElem (S : ComputableStructureIn O L) (t : Tuple ℕ) {i : ℕ}
    (hi : i < t.length) :
    ∃ x : (S.canonicalAge.memberAt (encode t)).domain, (x : ℕ) = t[i] := by
  have hgens : S.canonicalAge.gens (encode t) = t := by simp
  have hi' : i < (S.canonicalAge.gens (encode t)).length := by rw [hgens]; exact hi
  refine ⟨S.canonicalAge.gensView (encode t) ⟨i, hi'⟩, ?_⟩
  rw [PartialAgeIn.gensView_coe, List.get_eq_getElem]
  exact List.getElem_of_eq hgens hi'

/-- **The realizer reads off the target tuple positionally.** For any carrier point named by the
`i`-th source entry, its image is the `i`-th target entry — stated as a `getElem?` equation, so no
bound on the target side has to be produced.

Public because the structure laws of the limit map consume it: they must know where a *specific*
carrier point of a matched stage goes, which the coordinate-consistency theorems below do not say. -/
theorem realizer_getElem?
    {f : (S.canonicalAge.memberAt s.tightMap.domIdx).domain ↪[L]
      (T.canonicalAge.memberAt s.tightMap.codIdx).domain}
    (hf : PartialAgeIn.PartialRealizesBetween S.canonicalAge T.canonicalAge s.tightMap f)
    {i : ℕ} (hi : i < s.sourceTuple.length)
    {x : (S.canonicalAge.memberAt s.tightMap.domIdx).domain}
    (hx : (x : ℕ) = s.sourceTuple[i]) :
    s.targetTuple[i]?
      = some ((f x : (T.canonicalAge.memberAt s.tightMap.codIdx).domain) : ℕ) := by
  refine PartialAgeIn.getElem?_of_realizes hf ?_
  have hgens : S.canonicalAge.gens s.tightMap.domIdx = s.sourceTuple := by simp [tightMap]
  rw [hgens, List.getElem?_eq_getElem hi, hx]

/-- **Functionality.** A matched state that records the same source point at two positions records
the same image at both — the two positions name one carrier point, and the realizer is a function.

Out of bounds it is the length equality that closes the case, which is why no length hypothesis
appears. -/
theorem target_getElem?_eq_of_source_getElem?_eq {i j : ℕ} (h : s.Matched S T)
    (hij : s.sourceTuple[i]? = s.sourceTuple[j]?) :
    s.targetTuple[i]? = s.targetTuple[j]? := by
  obtain ⟨f, hf⟩ := h
  refine getElem?_transfer (length_eq_of_matched ⟨f, hf⟩) hij fun hi hj hval ↦ ?_
  obtain ⟨x, hx⟩ := exists_coe_eq_getElem S s.sourceTuple hi
  have hi' := realizer_getElem? hf hi hx
  have hj' := realizer_getElem? hf hj (hx.trans hval)
  rw [List.getElem?_eq_getElem (length_eq_of_matched ⟨f, hf⟩ ▸ hi)] at hi'
  rw [List.getElem?_eq_getElem (length_eq_of_matched ⟨f, hf⟩ ▸ hj)] at hj'
  exact Option.some.inj (hi'.trans hj'.symm)

/-- **Injectivity.** Conversely, a matched state that records the same image at two positions must
have recorded the same source point at both — the realizer is an embedding.

The two directions are genuinely separate facts about the same realizer; neither implies the other,
and the recursion needs both to prove the two inverse laws. -/
theorem source_getElem?_eq_of_target_getElem?_eq {i j : ℕ} (h : s.Matched S T)
    (hij : s.targetTuple[i]? = s.targetTuple[j]?) :
    s.sourceTuple[i]? = s.sourceTuple[j]? := by
  obtain ⟨f, hf⟩ := h
  have hlen := length_eq_of_matched (S := S) (T := T) ⟨f, hf⟩
  refine getElem?_transfer hlen.symm hij fun hi hj hval ↦ ?_
  obtain ⟨x, hx⟩ := exists_coe_eq_getElem S s.sourceTuple (hlen.symm ▸ hi)
  obtain ⟨y, hy⟩ := exists_coe_eq_getElem S s.sourceTuple (hlen.symm ▸ hj)
  have hi' := realizer_getElem? hf (hlen.symm ▸ hi) hx
  have hj' := realizer_getElem? hf (hlen.symm ▸ hj) hy
  rw [List.getElem?_eq_getElem hi] at hi'
  rw [List.getElem?_eq_getElem hj] at hj'
  have : f x = f y :=
    Subtype.ext (Option.some.inj (hi'.symm.trans (by rw [hval]; exact hj')))
  rw [← hx, ← hy]
  exact congrArg (fun z : (S.canonicalAge.memberAt s.tightMap.domIdx).domain ↦ (z : ℕ))
    (f.injective this)

/-! ### The base case

The recursion starts from the state that has matched nothing. That this state is already matched is
**not** automatic from both empty-tuple members existing: `Matched` asks for an embedding of
`D_{⟨⟩}` into `D_{⟨⟩}`, and where the language has constants those carriers are nonempty, so
something must produce the map. A forward cover does.

The signature takes a `RepresentationCoverIn E S.canonicalAge T.canonicalAge` and nothing else. That
is sharper than accepting a `RepresentationIsoIn`, and it makes the orientation structural rather
than a matter of which field a proof happens to project: the base case needs only the direction that
maps source members into the target, so the backward cover cannot silently be relied on. Nor does
anything here need homogeneity, computability, or `O ⊆ E` — the cover is used purely semantically,
through the equivalence it already carries at one index.
-/

/-- The state that has matched nothing. -/
def empty : BackForthState := ⟨[], []⟩

@[simp] theorem empty_sourceTuple : empty.sourceTuple = [] := rfl

@[simp] theorem empty_targetTuple : empty.targetTuple = [] := rfl

/-- **The base case, from a forward cover alone.** At the index coding the empty tuple, the cover's
stored equivalence realizes the generator data, whose range tuple is empty because the source has no
recorded generators; corestricting it to its own generated range lands exactly the empty state's
tight map.

Only `S.canonicalAge → T.canonicalAge` is used. No homogeneity, no computability, no oracle
inclusion, no backward cover. -/
theorem empty_matched {E : Set (ℕ →. ℕ)} {S T : ComputableStructureIn O L}
    (r : RepresentationCoverIn E S.canonicalAge T.canonicalAge) : empty.Matched S T := by
  have hgens : S.canonicalAge.gens (encode ([] : Tuple ℕ)) = [] :=
    allTupleFor_encode _
  have hsg : r.sourceGensImage (encode ([] : Tuple ℕ)) = [] :=
    r.sourceGensImage_of_gens_nil hgens
  have hex : ∃ f, PartialAgeIn.PartialRealizesBetween S.canonicalAge T.canonicalAge
      (PotentialEmbeddingData.ofTriple (encode ([] : Tuple ℕ),
        encode (r.sourceGensImage (encode ([] : Tuple ℕ))),
        r.sourceGensImage (encode ([] : Tuple ℕ)))) f :=
    ⟨_, PartialAgeIn.PartialRealizesBetween.toCanonicalRangeEquiv_realizes
      (r.generatorEmbeddingData_realized (encode ([] : Tuple ℕ)))⟩
  have hdata : PotentialEmbeddingData.ofTriple (encode ([] : Tuple ℕ),
      encode (r.sourceGensImage (encode ([] : Tuple ℕ))),
      r.sourceGensImage (encode ([] : Tuple ℕ))) = empty.tightMap := by
    rw [hsg]; rfl
  exact PartialAgeIn.exists_partialRealizesBetween_congr hdata hex

end BackForthState

/-! ### Generator images over a canonical source

`RepresentationCoverIn.sourceGensImage_computableIn` needs `O ⊆ E` because reading an arbitrary
family's recorded generators touches presentation data. A **canonical** source records
`allTupleFor`, which is decoding and nothing else, so on that source the inclusion is not needed.

Kept here rather than in `RepresentationIso.lean`, which would otherwise have to import
`CanonicalAge` upward. The back half is its second consumer. -/

namespace RepresentationCoverIn

/-- **No `O ⊆ E` over a canonical source.** The generator list is `allTupleFor`, computable
outright. -/
theorem sourceGensImage_computableIn_canonicalSource {E : Set (ℕ →. ℕ)}
    {S : ComputableStructureIn O L} {B : PartialAgeIn O L}
    (r : RepresentationCoverIn E S.canonicalAge B) : ComputableIn E r.sourceGensImage := by
  have hgens : ComputableIn E S.canonicalAge.gens := allTupleFor_computableIn
  have hpart : RecursiveIn E fun i ↦ r.toTuplePart i (S.canonicalAge.gens i) :=
    r.toTuplePart_recursiveIn.comp (ComputableIn.id.pair hgens)
  exact hpart.computableIn_get _

end RepresentationCoverIn

/-! ### The forth half

One step of the back-and-forth, in the direction that takes a **new source point** and finds its
image. The construction is the paper's: push the point onto the source tuple, run the forward cover
on the pushed tuple, and ask the *target*'s homogeneity to extend the map that runs back along the
cover's image of what is already matched.

Three things are worth stating before the proofs.

**The query's orientation.** `⟨s.targetTuple, forthPrefix, forthNewPoint⟩` — the current target
tuple is `d⃗`, the cover's images of the already-matched source points are `g(d⃗)`, and the cover's
image of the new point is `x`. So `g` runs *from* the matched target tuple *to* the cover's image
tuple, and Definition 3.1's `h` inverts it, landing back on `s.targetTuple`. Swapping the first two
fields would typecheck and would be wrong.

**The new target tuple is not the answer's extension tuple.** `H.extensionTuple q` is the ambient
member `D_γ⃗` the extension lands in; the *tight* matched range is `s.targetTuple ++ [y]`, and that
is what the new state records. Using `γ⃗` would produce a state whose tight map is not realized.

**The off-by-one is explicit.** `forthImage = forthPrefix ++ [forthNewPoint]` is proved once, from
the cover's length equation, and it is the only place the boundary is argued. Both the homogeneity
query and the final composition read it back.
-/

section Forth

open PartialAgeIn PartialAgeIn.PartialRealizesBetween

variable {E : Set (ℕ →. ℕ)} {S T : ComputableStructureIn O L}

namespace BackForthState

/-- The index of the pushed source tuple. -/
def pushedIdx (s : BackForthState) (n : ℕ) : ℕ := encode (s.sourceTuple ++ [n])

/-- The recorded generators at a tuple's own code — used constantly below, and stated once so that
the rewrites do not have to go through `canonicalAge_gens` and `allTupleFor_encode` separately. -/
@[simp] theorem gens_encode (S : ComputableStructureIn O L) (t : Tuple ℕ) :
    S.canonicalAge.gens (encode t) = t :=
  allTupleFor_encode _

@[simp] theorem gens_pushedIdx (S : ComputableStructureIn O L) (s : BackForthState) (n : ℕ) :
    S.canonicalAge.gens (s.pushedIdx n) = s.sourceTuple ++ [n] :=
  allTupleFor_encode _

variable (r : RepresentationCoverIn E S.canonicalAge T.canonicalAge) (s : BackForthState) (n : ℕ)

/-- The forward cover's image of the **whole** pushed source tuple. -/
noncomputable def forthImage : Tuple ℕ := r.sourceGensImage (s.pushedIdx n)

theorem forthImage_length : (forthImage r s n).length = s.sourceTuple.length + 1 := by
  rw [forthImage, r.sourceGensImage_length, gens_pushedIdx]
  simp

/-- Its prefix: the images of the source points already matched. -/
noncomputable def forthPrefix : Tuple ℕ := (forthImage r s n).take s.sourceTuple.length

/-- Its final coordinate: the image of the new point. -/
noncomputable def forthNewPoint : ℕ := (forthImage r s n)[s.sourceTuple.length]!

@[simp] theorem forthPrefix_length : (forthPrefix r s n).length = s.sourceTuple.length := by
  rw [forthPrefix, List.length_take, forthImage_length]
  omega

theorem forthPrefix_getElem? {k : ℕ} (hk : k < s.sourceTuple.length) :
    (forthPrefix r s n)[k]? = (forthImage r s n)[k]? := by
  rw [forthPrefix, List.getElem?_take_of_lt hk]

/-- **The off-by-one boundary, explicitly.** The cover's image of the pushed tuple splits as the
prefix it assigns to the already-matched points, followed by the single image of the new point.

Everything downstream reads the boundary back from here: the homogeneity query is built from the two
pieces, and the final composition needs them re-joined. -/
theorem forthImage_split : forthImage r s n = forthPrefix r s n ++ [forthNewPoint r s n] := by
  have hlen := forthImage_length r s n
  have hlt : s.sourceTuple.length < (forthImage r s n).length := by omega
  have hnew : forthNewPoint r s n = (forthImage r s n)[s.sourceTuple.length]'hlt := by
    rw [forthNewPoint]
    exact getElem!_pos (forthImage r s n) s.sourceTuple.length hlt
  have h3 : (forthImage r s n).take (s.sourceTuple.length + 1) = forthImage r s n :=
    List.take_of_length_le (by omega)
  have h2 := List.take_add_one (l := forthImage r s n) (i := s.sourceTuple.length)
  rw [h3, List.getElem?_eq_getElem hlt] at h2
  rw [forthPrefix, hnew]
  exact h2

/-! #### The query -/

/-- **The homogeneity query, put to the target.** Current target tuple first, the cover's images of
the already-matched source points second, the cover's image of the new point third. -/
noncomputable def forthQuery : HomogeneityQueryData :=
  ⟨s.targetTuple, forthPrefix r s n, forthNewPoint r s n⟩

@[simp] theorem forthQuery_domainTuple : (forthQuery r s n).domainTuple = s.targetTuple := rfl

@[simp] theorem forthQuery_imageTuple : (forthQuery r s n).imageTuple = forthPrefix r s n := rfl

@[simp] theorem forthQuery_newPoint : (forthQuery r s n).newPoint = forthNewPoint r s n := rfl

/-- **The state after one forth step.** The new target entry is the answer's *returned point*, not
its extension tuple: `γ⃗` names the ambient member, while the matched range is the old target tuple
with `y` appended. -/
noncomputable def forthState (H : ComputablyHomogeneousIn E T) : BackForthState :=
  ⟨s.sourceTuple ++ [n], s.targetTuple ++ [H.imageOfNewPoint (forthQuery r s n)]⟩

@[simp] theorem forthState_sourceTuple (H : ComputablyHomogeneousIn E T) :
    (forthState r s n H).sourceTuple = s.sourceTuple ++ [n] := rfl

@[simp] theorem forthState_targetTuple (H : ComputablyHomogeneousIn E T) :
    (forthState r s n H).targetTuple
      = s.targetTuple ++ [H.imageOfNewPoint (forthQuery r s n)] := rfl

/-! #### Layer 1: the cover, corestricted -/

/-- The forward cover at the pushed index, corestricted onto the member its image generates. -/
noncomputable def forthCoverEquiv :
    (S.canonicalAge.memberAt (s.pushedIdx n)).domain ≃[L]
      (T.canonicalAge.memberAt (encode (forthImage r s n))).domain :=
  toCanonicalRangeEquiv (r.generatorEmbeddingData_realized (s.pushedIdx n))

theorem forthCoverEquiv_realizes :
    PartialRealizesBetween S.canonicalAge T.canonicalAge
      (PotentialEmbeddingData.ofTriple
        (s.pushedIdx n, encode (forthImage r s n), forthImage r s n))
      (forthCoverEquiv r s n).toEmbedding :=
  toCanonicalRangeEquiv_realizes (r.generatorEmbeddingData_realized (s.pushedIdx n))

/-! #### Layer 2: the query's map is actual -/

/-- **The map the query describes really is an embedding.** Run the matched equivalence *backwards*
from the current target tuple to the current source tuple, include that into the pushed source
member, and push forward along the cover; corestricting the composite lands on the member generated
by the cover's prefix, which is exactly `originalMap`.

This is where the direction of the query is forced: the composite starts at `s.targetTuple`. -/
theorem forthQuery_originalMap_actual (h : s.Matched S T) :
    T.canonicalAge.PartialIsEmbedding (forthQuery r s n).originalMap := by
  obtain ⟨m0, hm0⟩ := h
  have hlens : s.sourceTuple.length = s.targetTuple.length := length_eq_of_matched ⟨m0, hm0⟩
  -- the matched equivalence, run backwards
  obtain ⟨msym, hsymm⟩ : ∃ f, PartialRealizesBetween T.canonicalAge S.canonicalAge
      (PotentialEmbeddingData.ofTriple
        (encode s.targetTuple, encode s.sourceTuple, s.sourceTuple)) f :=
    PartialAgeIn.exists_partialRealizesBetween_congr
      (by rw [tightMap_domIdx, tightMap_rangeTuple, gens_encode])
      ⟨_, toCanonicalRangeEquiv_symm_realizes hm0⟩
  -- the canonical inclusion into the pushed member
  have hsub : S.canonicalAge.domainAt (encode s.sourceTuple)
      ⊆ S.canonicalAge.domainAt (s.pushedIdx n) := by
    refine S.canonicalAge_domainAt_subset fun x hx ↦ ?_
    rw [allTupleFor_encode] at hx
    refine S.mem_canonicalAge_domainAt_of_mem_gens ?_
    rw [show allTupleFor (s.pushedIdx n) = s.sourceTuple ++ [n] from allTupleFor_encode _]
    exact List.mem_append_left _ hx
  have hincl : PartialRealizesBetween S.canonicalAge S.canonicalAge
      (PotentialEmbeddingData.ofTriple (encode s.sourceTuple, s.pushedIdx n, s.sourceTuple))
      (PartialAgeIn.memberEmbedding rfl hsub) := by
    refine realizes_of_getElem? (by rw [gens_encode]) ?_
    intro k x hx
    rw [gens_encode] at hx
    exact hx
  -- both composites are packaged existentially: naming a composite in a stated type would force
  -- the realizer to be checked against `(ofTriple …).domIdx` rather than the index itself
  obtain ⟨f1, hstep1⟩ : ∃ f, PartialRealizesBetween T.canonicalAge S.canonicalAge
      (PotentialEmbeddingData.ofTriple
        (encode s.targetTuple, s.pushedIdx n, s.sourceTuple)) f :=
    ⟨_, realizes_comp hsymm hincl
      (fun k _ ↦ by rw [gens_encode])
      (fun _ _ ↦ rfl)
      (by rw [gens_encode, hlens])⟩
  obtain ⟨f2, hstep2⟩ : ∃ f, PartialRealizesBetween T.canonicalAge T.canonicalAge
      (PotentialEmbeddingData.ofTriple
        (encode s.targetTuple, encode (forthImage r s n), forthPrefix r s n)) f :=
    ⟨_, realizes_comp hstep1 (forthCoverEquiv_realizes r s n)
      (fun k hk ↦ by rw [gens_pushedIdx]; exact (List.getElem?_append_left hk).symm)
      (fun k hk ↦ forthPrefix_getElem? r s n hk)
      (by rw [gens_encode, forthPrefix_length, hlens])⟩
  exact ⟨_, toCanonicalRangeEquiv_realizes hstep2⟩

/-! #### Layer 3: preservation -/

/-- **The forth step preserves the invariant.** Homogeneity of the target extends the map along the
new point; corestricting its realizer and composing with the pushed cover equivalence realizes the
new state's tight map exactly.

The split equality is applied to the *packaged* existential, not to a fixed realizer, for the reason
recorded at `exists_partialRealizesBetween_congr`. -/
theorem forthState_matched (H : ComputablyHomogeneousIn E T) (h : s.Matched S T) :
    (forthState r s n H).Matched S T := by
  have hlens := length_eq_of_matched h
  have hact := H.extension_actual (forthQuery r s n) (forthQuery_originalMap_actual r s n h)
  have hdata : (forthQuery r s n).extensionMap (H.select (forthQuery r s n))
      = PotentialEmbeddingData.ofTriple (encode (forthImage r s n),
          encode (H.select (forthQuery r s n)).extensionTuple,
          s.targetTuple ++ [H.imageOfNewPoint (forthQuery r s n)]) := by
    rw [forthImage_split]; rfl
  obtain ⟨g, hg⟩ := PartialAgeIn.exists_partialRealizesBetween_congr
    (A := T.canonicalAge) (B := T.canonicalAge) hdata hact
  refine ⟨_, realizes_comp (forthCoverEquiv_realizes r s n)
    (toCanonicalRangeEquiv_realizes hg) ?_ (fun _ _ ↦ rfl) ?_⟩
  · intro k _
    rw [gens_encode]
  · simp [hlens]

/-! #### Effectivity

The stage recursion will be a computable function of `(stage, state)` — that argument order, because
`ComputableIn.nat_rec` recurses on the first component — so the step itself has to be computable in
that pair. In the **map** oracle `E`: the presentation oracle is never consulted, and no inclusion
between the two is assumed.

Each joint is named, so that a later change to any one piece is localised. The image is where
`sourceGensImage_computableIn_canonicalSource` is consumed, and it is the only place the absence of
`O ⊆ E` is doing real work: over an arbitrary source family the generator list would have to be read
from the presentation. -/

theorem pushedIdx_computableIn :
    ComputableIn E fun p : ℕ × BackForthState ↦ p.2.pushedIdx p.1 := by
  have hsrc : ComputableIn E fun p : ℕ × BackForthState ↦ p.2.sourceTuple :=
    sourceTuple_computableIn.comp ComputableIn.snd
  have hsingle : ComputableIn E fun p : ℕ × BackForthState ↦ [p.1] :=
    (Primrec.list_cons.to_comp.computableIn₂).comp ComputableIn.fst (ComputableIn.const [])
  exact (ComputableIn.encode.comp
    ((Primrec.list_append.to_comp.computableIn₂).comp hsrc hsingle)).of_eq fun _ ↦ rfl

theorem forthImage_computableIn :
    ComputableIn E fun p : ℕ × BackForthState ↦ forthImage r p.2 p.1 :=
  (r.sourceGensImage_computableIn_canonicalSource.comp pushedIdx_computableIn).of_eq fun _ ↦ rfl

/-- The source length, needed by both the prefix and the final coordinate. -/
private theorem sourceLength_computableIn :
    ComputableIn E fun p : ℕ × BackForthState ↦ p.2.sourceTuple.length :=
  Computable.list_length.computableIn.comp (sourceTuple_computableIn.comp ComputableIn.snd)

theorem forthPrefix_computableIn :
    ComputableIn E fun p : ℕ × BackForthState ↦ forthPrefix r p.2 p.1 :=
  ((Primrec.list_take.to_comp.computableIn₂).comp
    sourceLength_computableIn (forthImage_computableIn r)).of_eq fun _ ↦ rfl

/-- The final coordinate is a **total** lookup — out of range it returns the default rather than
diverging — so it composes directly against `Primrec.list_getElem!` at a variable index. -/
theorem forthNewPoint_computableIn :
    ComputableIn E fun p : ℕ × BackForthState ↦ forthNewPoint r p.2 p.1 :=
  ((Primrec.list_getElem!.to_comp.computableIn₂).comp
    (forthImage_computableIn r) sourceLength_computableIn).of_eq fun _ ↦ rfl

theorem forthQuery_computableIn :
    ComputableIn E fun p : ℕ × BackForthState ↦ forthQuery r p.2 p.1 := by
  have htriple : ComputableIn E fun p : ℕ × BackForthState ↦
      (p.2.targetTuple, forthPrefix r p.2 p.1, forthNewPoint r p.2 p.1) :=
    (targetTuple_computableIn.comp ComputableIn.snd).pair
      ((forthPrefix_computableIn r).pair (forthNewPoint_computableIn r))
  exact ((primrec_homogeneityQueryData.to_comp.computableIn).comp htriple).of_eq fun _ ↦ rfl

/-- **The forth step is computable in the map oracle.** On `(stage, state)`, in `E`, with `O`
untouched. -/
theorem forthState_computableIn (H : ComputablyHomogeneousIn E T) :
    ComputableIn E fun p : ℕ × BackForthState ↦ forthState r p.2 p.1 H := by
  have hsrc : ComputableIn E fun p : ℕ × BackForthState ↦ p.2.sourceTuple ++ [p.1] :=
    (Primrec.list_append.to_comp.computableIn₂).comp
      (sourceTuple_computableIn.comp ComputableIn.snd)
      ((Primrec.list_cons.to_comp.computableIn₂).comp ComputableIn.fst (ComputableIn.const []))
  have htgt : ComputableIn E fun p : ℕ × BackForthState ↦
      p.2.targetTuple ++ [H.imageOfNewPoint (forthQuery r p.2 p.1)] :=
    (Primrec.list_append.to_comp.computableIn₂).comp
      (targetTuple_computableIn.comp ComputableIn.snd)
      ((Primrec.list_cons.to_comp.computableIn₂).comp
        (H.imageOfNewPoint_computableIn.comp (forthQuery_computableIn r))
        (ComputableIn.const []))
  exact (mk_computableIn.comp (hsrc.pair htgt)).of_eq fun _ ↦ rfl

end BackForthState

end Forth

/-! ### The back half

The mirror image, and deliberately **not** an instance of a shared abstraction: the two halves
differ in which cover they run, which structure's homogeneity they consult, and — most visibly — in
how the final map is assembled.

Where forth pushes a new *source* point and runs the forward cover, back pushes a new *target* point
`n` and runs `r.backward`, then asks the **source**'s homogeneity to extend. The recorded state is
`⟨s.sourceTuple ++ [y], s.targetTuple ++ [n]⟩`: the source side gains the *returned* point, the
target side the point that was pushed. The two appends swap roles relative to forth.

**The assembly is inverted.** Forth composes two equivalences in their natural direction, because
both run source-to-target. Here both run target-to-source, so preservation inverts them, and the
order matters: the homogeneity extension's inverse first, from the enlarged source member onto the
member the backward cover's image generates, then the backward cover's own inverse onto the enlarged
target member. Composing them the other way is not merely wrong, it does not typecheck — which is
what `backExtension_symm_realizes` and `backCoverEquiv_symm_realizes` make visible, by naming the
two endpoint pairs.
-/

section Back

open PartialAgeIn PartialAgeIn.PartialRealizesBetween

variable {E : Set (ℕ →. ℕ)} {S T : ComputableStructureIn O L}

namespace BackForthState

/-- The index of the pushed **target** tuple. -/
def backPushedIdx (s : BackForthState) (n : ℕ) : ℕ := encode (s.targetTuple ++ [n])

@[simp] theorem gens_backPushedIdx (T : ComputableStructureIn O L) (s : BackForthState) (n : ℕ) :
    T.canonicalAge.gens (s.backPushedIdx n) = s.targetTuple ++ [n] :=
  allTupleFor_encode _

variable (rb : RepresentationCoverIn E T.canonicalAge S.canonicalAge) (s : BackForthState) (n : ℕ)

/-- The backward cover's image of the whole pushed target tuple. -/
noncomputable def backImage : Tuple ℕ := rb.sourceGensImage (s.backPushedIdx n)

theorem backImage_length : (backImage rb s n).length = s.targetTuple.length + 1 := by
  rw [backImage, rb.sourceGensImage_length, gens_backPushedIdx]
  simp

/-- Its prefix: the preimages of the target points already matched. -/
noncomputable def backPrefix : Tuple ℕ := (backImage rb s n).take s.targetTuple.length

/-- Its final coordinate: the backward cover's value at the new target point. -/
noncomputable def backNewPoint : ℕ := (backImage rb s n)[s.targetTuple.length]!

@[simp] theorem backPrefix_length : (backPrefix rb s n).length = s.targetTuple.length := by
  rw [backPrefix, List.length_take, backImage_length]
  omega

theorem backPrefix_getElem? {k : ℕ} (hk : k < s.targetTuple.length) :
    (backPrefix rb s n)[k]? = (backImage rb s n)[k]? := by
  rw [backPrefix, List.getElem?_take_of_lt hk]

/-- The off-by-one boundary on the back side, measured against the **target** tuple's length. -/
theorem backImage_split : backImage rb s n = backPrefix rb s n ++ [backNewPoint rb s n] := by
  have hlen := backImage_length rb s n
  have hlt : s.targetTuple.length < (backImage rb s n).length := by omega
  have hnew : backNewPoint rb s n = (backImage rb s n)[s.targetTuple.length]'hlt := by
    rw [backNewPoint]
    exact getElem!_pos (backImage rb s n) s.targetTuple.length hlt
  have h3 : (backImage rb s n).take (s.targetTuple.length + 1) = backImage rb s n :=
    List.take_of_length_le (by omega)
  have h2 := List.take_add_one (l := backImage rb s n) (i := s.targetTuple.length)
  rw [h3, List.getElem?_eq_getElem hlt] at h2
  rw [backPrefix, hnew]
  exact h2

/-- **The homogeneity query, put to the source.** Current *source* tuple first — the mirror of
forth, where it was the target tuple. -/
noncomputable def backQuery : HomogeneityQueryData :=
  ⟨s.sourceTuple, backPrefix rb s n, backNewPoint rb s n⟩

@[simp] theorem backQuery_domainTuple : (backQuery rb s n).domainTuple = s.sourceTuple := rfl

@[simp] theorem backQuery_imageTuple : (backQuery rb s n).imageTuple = backPrefix rb s n := rfl

@[simp] theorem backQuery_newPoint : (backQuery rb s n).newPoint = backNewPoint rb s n := rfl

/-- **The state after one back step.** The *source* side gains the returned point; the *target* side
gains the point that was pushed. -/
noncomputable def backState (Hs : ComputablyHomogeneousIn E S) : BackForthState :=
  ⟨s.sourceTuple ++ [Hs.imageOfNewPoint (backQuery rb s n)], s.targetTuple ++ [n]⟩

@[simp] theorem backState_sourceTuple (Hs : ComputablyHomogeneousIn E S) :
    (backState rb s n Hs).sourceTuple
      = s.sourceTuple ++ [Hs.imageOfNewPoint (backQuery rb s n)] := rfl

@[simp] theorem backState_targetTuple (Hs : ComputablyHomogeneousIn E S) :
    (backState rb s n Hs).targetTuple = s.targetTuple ++ [n] := rfl

/-! #### Layer 1: the backward cover, corestricted, and its inverse -/

/-- The backward cover at the pushed target index, corestricted onto the member its image
generates. -/
noncomputable def backCoverEquiv :
    (T.canonicalAge.memberAt (s.backPushedIdx n)).domain ≃[L]
      (S.canonicalAge.memberAt (encode (backImage rb s n))).domain :=
  toCanonicalRangeEquiv (rb.generatorEmbeddingData_realized (s.backPushedIdx n))

theorem backCoverEquiv_realizes :
    PartialRealizesBetween T.canonicalAge S.canonicalAge
      (PotentialEmbeddingData.ofTriple
        (s.backPushedIdx n, encode (backImage rb s n), backImage rb s n))
      (backCoverEquiv rb s n).toEmbedding :=
  toCanonicalRangeEquiv_realizes (rb.generatorEmbeddingData_realized (s.backPushedIdx n))

/-- **The second half of the inverted composite**, named so its endpoints are visible: it runs from
the member the cover's image generates *onto* the enlarged target member, with range tuple
`s.targetTuple ++ [n]`. -/
theorem backCoverEquiv_symm_realizes :
    ∃ f, PartialRealizesBetween S.canonicalAge T.canonicalAge
      (PotentialEmbeddingData.ofTriple
        (encode (backImage rb s n), s.backPushedIdx n, s.targetTuple ++ [n])) f := by
  refine PartialAgeIn.exists_partialRealizesBetween_congr ?_
    ⟨_, toCanonicalRangeEquiv_symm_realizes
      (rb.generatorEmbeddingData_realized (s.backPushedIdx n))⟩
  show PotentialEmbeddingData.ofTriple (encode (backImage rb s n), s.backPushedIdx n,
    T.canonicalAge.gens (s.backPushedIdx n)) = _
  rw [gens_backPushedIdx]

/-! #### Layer 2: the query's map is actual

The mirror of the forth step, and the place where the asymmetry is sharpest: forth ran the matched
equivalence **backwards**, here it runs **forwards**, because the query's domain tuple is now the
source tuple. -/

/-- The map the back query describes is an embedding: the matched equivalence forward, the canonical
inclusion into the pushed **target** member, then the backward cover. -/
theorem backQuery_originalMap_actual (h : s.Matched S T) :
    S.canonicalAge.PartialIsEmbedding (backQuery rb s n).originalMap := by
  obtain ⟨m0, hm0⟩ := h
  have hlens : s.sourceTuple.length = s.targetTuple.length := length_eq_of_matched ⟨m0, hm0⟩
  have hm : PartialRealizesBetween S.canonicalAge T.canonicalAge
      (PotentialEmbeddingData.ofTriple
        (encode s.sourceTuple, encode s.targetTuple, s.targetTuple))
      (toCanonicalRangeEquiv hm0).toEmbedding :=
    toCanonicalRangeEquiv_realizes hm0
  have hsub : T.canonicalAge.domainAt (encode s.targetTuple)
      ⊆ T.canonicalAge.domainAt (s.backPushedIdx n) := by
    refine T.canonicalAge_domainAt_subset fun x hx ↦ ?_
    rw [allTupleFor_encode] at hx
    refine T.mem_canonicalAge_domainAt_of_mem_gens ?_
    rw [show allTupleFor (s.backPushedIdx n) = s.targetTuple ++ [n] from allTupleFor_encode _]
    exact List.mem_append_left _ hx
  have hincl : PartialRealizesBetween T.canonicalAge T.canonicalAge
      (PotentialEmbeddingData.ofTriple (encode s.targetTuple, s.backPushedIdx n, s.targetTuple))
      (PartialAgeIn.memberEmbedding rfl hsub) := by
    refine realizes_of_getElem? (by rw [gens_encode]) ?_
    intro k x hx
    rw [gens_encode] at hx
    exact hx
  obtain ⟨f1, hstep1⟩ : ∃ f, PartialRealizesBetween S.canonicalAge T.canonicalAge
      (PotentialEmbeddingData.ofTriple
        (encode s.sourceTuple, s.backPushedIdx n, s.targetTuple)) f :=
    ⟨_, realizes_comp hm hincl
      (fun k _ ↦ by rw [gens_encode])
      (fun _ _ ↦ rfl)
      (by rw [gens_encode, hlens])⟩
  obtain ⟨f2, hstep2⟩ : ∃ f, PartialRealizesBetween S.canonicalAge S.canonicalAge
      (PotentialEmbeddingData.ofTriple
        (encode s.sourceTuple, encode (backImage rb s n), backPrefix rb s n)) f :=
    ⟨_, realizes_comp hstep1 (backCoverEquiv_realizes rb s n)
      (fun k hk ↦ by rw [gens_backPushedIdx]; exact (List.getElem?_append_left hk).symm)
      (fun k hk ↦ backPrefix_getElem? rb s n hk)
      (by rw [gens_encode, backPrefix_length, hlens])⟩
  exact ⟨_, toCanonicalRangeEquiv_realizes hstep2⟩

/-! #### Layer 3: preservation, by inverting both equivalences -/

/-- **The first half of the inverted composite**, named so its endpoints are visible: it runs from
the enlarged **source** member onto the member the backward cover's image generates.

Its codomain is the other half's domain, which is what fixes the order. -/
theorem backExtension_symm_realizes (Hs : ComputablyHomogeneousIn E S) (h : s.Matched S T) :
    ∃ f, PartialRealizesBetween S.canonicalAge S.canonicalAge
      (PotentialEmbeddingData.ofTriple
        (encode (s.sourceTuple ++ [Hs.imageOfNewPoint (backQuery rb s n)]),
          encode (backImage rb s n), backImage rb s n)) f := by
  have hact := Hs.extension_actual (backQuery rb s n) (backQuery_originalMap_actual rb s n h)
  have hdata : (backQuery rb s n).extensionMap (Hs.select (backQuery rb s n))
      = PotentialEmbeddingData.ofTriple (encode (backImage rb s n),
          encode (Hs.select (backQuery rb s n)).extensionTuple,
          s.sourceTuple ++ [Hs.imageOfNewPoint (backQuery rb s n)]) := by
    rw [backImage_split]; rfl
  obtain ⟨g, hg⟩ := PartialAgeIn.exists_partialRealizesBetween_congr
    (A := S.canonicalAge) (B := S.canonicalAge) hdata hact
  refine PartialAgeIn.exists_partialRealizesBetween_congr ?_
    ⟨_, toCanonicalRangeEquiv_symm_realizes hg⟩
  show PotentialEmbeddingData.ofTriple
    (encode (s.sourceTuple ++ [Hs.imageOfNewPoint (backQuery rb s n)]),
      encode (backImage rb s n), S.canonicalAge.gens (encode (backImage rb s n))) = _
  rw [gens_encode]

/-- **The back step preserves the invariant.** The two inverses compose in one order only: the
homogeneity extension's inverse lands where the backward cover's inverse starts. -/
theorem backState_matched (Hs : ComputablyHomogeneousIn E S) (h : s.Matched S T) :
    (backState rb s n Hs).Matched S T := by
  have hlens := length_eq_of_matched h
  obtain ⟨f1, hf1⟩ := backExtension_symm_realizes rb s n Hs h
  obtain ⟨f2, hf2⟩ := backCoverEquiv_symm_realizes rb s n
  refine ⟨_, realizes_comp hf1 hf2 ?_ (fun _ _ ↦ rfl) ?_⟩
  · intro k _
    rw [gens_encode]
  · rw [gens_encode]
    simp [hlens]

/-! #### Effectivity -/

theorem backPushedIdx_computableIn :
    ComputableIn E fun p : ℕ × BackForthState ↦ p.2.backPushedIdx p.1 := by
  have htgt : ComputableIn E fun p : ℕ × BackForthState ↦ p.2.targetTuple :=
    targetTuple_computableIn.comp ComputableIn.snd
  have hsingle : ComputableIn E fun p : ℕ × BackForthState ↦ [p.1] :=
    (Primrec.list_cons.to_comp.computableIn₂).comp ComputableIn.fst (ComputableIn.const [])
  exact (ComputableIn.encode.comp
    ((Primrec.list_append.to_comp.computableIn₂).comp htgt hsingle)).of_eq fun _ ↦ rfl

theorem backImage_computableIn :
    ComputableIn E fun p : ℕ × BackForthState ↦ backImage rb p.2 p.1 :=
  (rb.sourceGensImage_computableIn_canonicalSource.comp backPushedIdx_computableIn).of_eq
    fun _ ↦ rfl

private theorem targetLength_computableIn :
    ComputableIn E fun p : ℕ × BackForthState ↦ p.2.targetTuple.length :=
  Computable.list_length.computableIn.comp (targetTuple_computableIn.comp ComputableIn.snd)

theorem backPrefix_computableIn :
    ComputableIn E fun p : ℕ × BackForthState ↦ backPrefix rb p.2 p.1 :=
  ((Primrec.list_take.to_comp.computableIn₂).comp
    targetLength_computableIn (backImage_computableIn rb)).of_eq fun _ ↦ rfl

theorem backNewPoint_computableIn :
    ComputableIn E fun p : ℕ × BackForthState ↦ backNewPoint rb p.2 p.1 :=
  ((Primrec.list_getElem!.to_comp.computableIn₂).comp
    (backImage_computableIn rb) targetLength_computableIn).of_eq fun _ ↦ rfl

theorem backQuery_computableIn :
    ComputableIn E fun p : ℕ × BackForthState ↦ backQuery rb p.2 p.1 := by
  have htriple : ComputableIn E fun p : ℕ × BackForthState ↦
      (p.2.sourceTuple, backPrefix rb p.2 p.1, backNewPoint rb p.2 p.1) :=
    (sourceTuple_computableIn.comp ComputableIn.snd).pair
      ((backPrefix_computableIn rb).pair (backNewPoint_computableIn rb))
  exact ((primrec_homogeneityQueryData.to_comp.computableIn).comp htriple).of_eq fun _ ↦ rfl

/-- **The back step is computable in the map oracle**, on the same `(stage, state)` pair. -/
theorem backState_computableIn (Hs : ComputablyHomogeneousIn E S) :
    ComputableIn E fun p : ℕ × BackForthState ↦ backState rb p.2 p.1 Hs := by
  have hsrc : ComputableIn E fun p : ℕ × BackForthState ↦
      p.2.sourceTuple ++ [Hs.imageOfNewPoint (backQuery rb p.2 p.1)] :=
    (Primrec.list_append.to_comp.computableIn₂).comp
      (sourceTuple_computableIn.comp ComputableIn.snd)
      ((Primrec.list_cons.to_comp.computableIn₂).comp
        (Hs.imageOfNewPoint_computableIn.comp (backQuery_computableIn rb))
        (ComputableIn.const []))
  have htgt : ComputableIn E fun p : ℕ × BackForthState ↦ p.2.targetTuple ++ [p.1] :=
    (Primrec.list_append.to_comp.computableIn₂).comp
      (targetTuple_computableIn.comp ComputableIn.snd)
      ((Primrec.list_cons.to_comp.computableIn₂).comp ComputableIn.fst (ComputableIn.const []))
  exact (mk_computableIn.comp (hsrc.pair htgt)).of_eq fun _ ↦ rfl

end BackForthState

end Back

end FirstOrder.Language
