/-
Copyright (c) 2026 Cameron Freer. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Cameron Freer
-/
import ComputableModelTheory.ModelTheory.Computable.BackForth
import ComputableModelTheory.Util.AssertAxioms

/-!
# Audit: the back-and-forth state — landing 1

Three obligations, each about a boundary rather than a computation.

**The map oracle is independent of the presentation oracle.** `test_map_oracle_independent` takes an
isomorphism at an **arbitrary** `E` over structures at `O`, with no relation between them assumed,
and reads back all six laws — only two of which mention `E` at all. `test_symm_needs_no_inclusion`
makes the same point for the groupoid operation. If a later refactor introduced `O ⊆ E`, these rows
would stop elaborating.

**The state is proof-free, and coded now rather than later.**
`test_state_is_proof_free` builds a state from two *arbitrary* tuples — `BackForthState` does not
even mention `O`, `L`, `S` or `T`, so there is nowhere for an invariant to hide.
`test_state_is_computably_coded` reads back all three coding facts together, because the stage
recursion needs to take a state apart *and* put one back together; supplying only the projections
would leave the transition function unbuildable.

**The invariant is cross-family and tight.** `test_matched_is_cross_family` records that the source
member is drawn from `S.canonicalAge` and the target from `T.canonicalAge`, so the single-family
`PartialRealizes` genuinely does not apply here. `test_tight_map_targets_its_range` pins the datum's
two indices: the codomain is `encode targetTuple` and the range tuple is `targetTuple`, so the
target member is exactly the one generated by the tuple the state records — which is what lets the
corestriction lemma apply without further hypotheses.

Deliberately absent: consistency of repeated coordinates, the base case, cover and homogeneity
consumption, and the two half-steps. Those are later landings.
-/

open Encodable FirstOrder Language

namespace FirstOrder.Language

variable {O : Set (ℕ →. ℕ)} {L : Language} [L.EffectiveLanguage]

/-! ### The map oracle is independent -/

/-- **`E` is unrelated to `O`.** The structures are presented at `O`, the maps are computable at an
arbitrary `E`, and no inclusion between them is assumed or used. Of the six laws, only the two
computability fields mention `E`. -/
theorem test_map_oracle_independent {E : Set (ℕ →. ℕ)} {S T : ComputableStructureIn O L}
    (i : ComputableStructureIsoIn E S T) :
    (ComputableIn E i.toFun ∧ ComputableIn E i.invFun) ∧
      (∀ x, i.invFun (i.toFun x) = x) ∧ (∀ y, i.toFun (i.invFun y) = y) ∧
      (∀ (n : ℕ) (f : L.Functions n) (v : Fin n → ℕ),
        i.toFun (@Structure.funMap L ℕ S.inst n f v)
          = @Structure.funMap L ℕ T.inst n f fun k ↦ i.toFun (v k)) ∧
      ∀ (n : ℕ) (R : L.Relations n) (v : Fin n → ℕ),
        @Structure.RelMap L ℕ T.inst n R (fun k ↦ i.toFun (v k))
          ↔ @Structure.RelMap L ℕ S.inst n R v :=
  ⟨⟨i.toFun_computableIn, i.invFun_computableIn⟩, i.left_inv, i.right_inv,
    i.toFun_funMap, i.toFun_relMap⟩

/-- Symmetry needs no inclusion either — it swaps the stored maps and reads the laws backwards. -/
theorem test_symm_needs_no_inclusion {E : Set (ℕ →. ℕ)} {S T : ComputableStructureIn O L}
    (i : ComputableStructureIsoIn E S T) :
    Nonempty (ComputableStructureIsoIn E T S) ∧ i.symm.toFun = i.invFun :=
  ⟨⟨i.symm⟩, rfl⟩

/-- The forward map is a bijection, as the two total inverse laws force. -/
theorem test_toFun_bijective {E : Set (ℕ →. ℕ)} {S T : ComputableStructureIn O L}
    (i : ComputableStructureIsoIn E S T) : Function.Bijective i.toFun :=
  i.toFun_bijective

/-! ### The state -/

/-- **Proof-free.** Any two tuples make a state, with no side condition — and `BackForthState`
mentions neither the structures nor the language, so there is nowhere for an invariant to hide. -/
theorem test_state_is_proof_free (a b : Tuple ℕ) :
    ∃ s : BackForthState, s.sourceTuple = a ∧ s.targetTuple = b :=
  ⟨⟨a, b⟩, rfl, rfl⟩

/-- **Coded now, not later.** All three facts together: the stage recursion must take a state apart
*and* build one, so projections alone would leave the transition function unbuildable. -/
theorem test_state_is_computably_coded :
    ComputableIn O BackForthState.sourceTuple ∧ ComputableIn O BackForthState.targetTuple ∧
      ComputableIn O fun p : Tuple ℕ × Tuple ℕ ↦ (⟨p.1, p.2⟩ : BackForthState) :=
  ⟨BackForthState.sourceTuple_computableIn, BackForthState.targetTuple_computableIn,
    BackForthState.mk_computableIn⟩

/-- The tight map is computable too, since the recursion forms it at every stage. -/
theorem test_tightMap_computableIn : ComputableIn O BackForthState.tightMap :=
  BackForthState.tightMap_computableIn

/-! ### The invariant -/

/-- **Cross-family.** The source member is drawn from `S.canonicalAge` and the target from
`T.canonicalAge`, so `PartialRealizesBetween` is required and the single-family `PartialRealizes`
does not typecheck here. -/
theorem test_matched_is_cross_family {S T : ComputableStructureIn O L} {s : BackForthState} :
    s.Matched S T ↔
      ∃ f, PartialAgeIn.PartialRealizesBetween S.canonicalAge T.canonicalAge
        (PotentialEmbeddingData.ofTriple
          (encode s.sourceTuple, encode s.targetTuple, s.targetTuple)) f :=
  BackForthState.matched_iff

/-- **The datum is tight**: its codomain index is `encode targetTuple` and its range tuple is
`targetTuple`, so the target member is exactly the one generated by the tuple the state records.
That is what will let the corestriction lemma apply with no further hypothesis. -/
theorem test_tight_map_targets_its_range (s : BackForthState) :
    s.tightMap.domIdx = encode s.sourceTuple ∧
      s.tightMap.codIdx = encode s.targetTuple ∧
        s.tightMap.rangeTuple = s.targetTuple :=
  ⟨rfl, rfl, rfl⟩

/-- Lengths agree on a matched state — the realizer's length equation, read through
`gens (encode t) = t`. -/
theorem test_matched_lengths {S T : ComputableStructureIn O L} {s : BackForthState}
    (h : s.Matched S T) : s.sourceTuple.length = s.targetTuple.length :=
  BackForthState.length_eq_of_matched h

/-- The realizer of a matched state is unique, so "the" embedding is unambiguous. -/
theorem test_matched_realizer_unique {S T : ComputableStructureIn O L} {s : BackForthState}
    {f g : (S.canonicalAge.memberAt s.tightMap.domIdx).domain ↪[L]
      (T.canonicalAge.memberAt s.tightMap.codIdx).domain}
    (hf : PartialAgeIn.PartialRealizesBetween S.canonicalAge T.canonicalAge s.tightMap f)
    (hg : PartialAgeIn.PartialRealizesBetween S.canonicalAge T.canonicalAge s.tightMap g) :
    f = g :=
  BackForthState.matched_unique hf hg

/-! ### Coordinate consistency

Three distinct facts, so that the interface is pinned from both sides rather than only by its
negative constraints.

**Repetition is permitted.** `test_repeated_state_is_matched` exhibits an actual matched state whose
source tuple repeats a point — the identity realizer on `[a, a] ↦ [a, a]`, over an arbitrary
computable structure. Without this row, the two negative results would be equally consistent with
"no matched state ever repeats a coordinate", and a later step could silently deduplicate.

**Both consistency directions bite.** The two negative rows are not symmetric restatements: the
first is the realizer's functionality, the second its injectivity. Each is stated over *arbitrary*
`S` and `T`, so neither leans on a fixture. -/

section Consistency

/-- **No deduplication.** A genuine matched state with a repeated source coordinate: the identity
member embedding realizes `[a, a] ↦ [a, a]` over any computable structure. The second conjunct
records that the repetition is really there. -/
theorem test_repeated_state_is_matched (S : ComputableStructureIn O L) (a : ℕ) :
    (⟨[a, a], [a, a]⟩ : BackForthState).Matched S S ∧
      (⟨[a, a], [a, a]⟩ : BackForthState).sourceTuple[0]?
        = (⟨[a, a], [a, a]⟩ : BackForthState).sourceTuple[1]? := by
  have hgens : S.canonicalAge.gens (encode [a, a]) = [a, a] := allTupleFor_encode _
  have hlen : (S.canonicalAge.gens
      (⟨[a, a], [a, a]⟩ : BackForthState).tightMap.domIdx).length
      = (⟨[a, a], [a, a]⟩ : BackForthState).tightMap.rangeTuple.length := by
    show (S.canonicalAge.gens (encode [a, a])).length = ([a, a] : Tuple ℕ).length
    rw [hgens]
  refine ⟨⟨PartialAgeIn.memberEmbedding rfl (Set.Subset.refl _), hlen, fun k ↦ ?_⟩, rfl⟩
  show ((S.canonicalAge.gens (encode [a, a])).get k : ℕ)
    = ([a, a] : Tuple ℕ).get (Fin.cast hlen k)
  rw [List.get_eq_getElem, List.get_eq_getElem]
  exact List.getElem_of_eq hgens k.2

/-- **Functionality bites.** A state repeating a source point but sending the two positions to
different images cannot be matched — over any pair of computable structures. -/
theorem test_repeated_source_unequal_target_not_matched {S T : ComputableStructureIn O L} :
    ¬ (⟨[7, 7], [3, 5]⟩ : BackForthState).Matched S T := by
  intro h
  have h01 := BackForthState.target_getElem?_eq_of_source_getElem?_eq (i := 0) (j := 1) h rfl
  simp at h01

/-- **Injectivity bites.** Dually, a state repeating an image but recording different source points
at those positions cannot be matched. Not a restatement of the previous row: that one is the
realizer being a function, this one is its being an embedding. -/
theorem test_repeated_target_unequal_source_not_matched {S T : ComputableStructureIn O L} :
    ¬ (⟨[3, 5], [7, 7]⟩ : BackForthState).Matched S T := by
  intro h
  have h01 := BackForthState.source_getElem?_eq_of_target_getElem?_eq (i := 0) (j := 1) h rfl
  simp at h01

/-- **Global and cast-free.** Both consequences apply at *any* pair of indices, with no bound and no
length hypothesis — out of range they say `none = none`, which is what makes them composable in the
inverse-law proofs. -/
theorem test_consistency_is_global {S T : ComputableStructureIn O L} {s : BackForthState}
    (h : s.Matched S T) (i j : ℕ) :
    (s.sourceTuple[i]? = s.sourceTuple[j]? → s.targetTuple[i]? = s.targetTuple[j]?) ∧
      (s.targetTuple[i]? = s.targetTuple[j]? → s.sourceTuple[i]? = s.sourceTuple[j]?) :=
  ⟨BackForthState.target_getElem?_eq_of_source_getElem?_eq h,
    BackForthState.source_getElem?_eq_of_target_getElem?_eq h⟩

/-- Out of range on both sides, with no hypothesis about the state beyond matching. -/
theorem test_consistency_out_of_range {S T : ComputableStructureIn O L} {s : BackForthState}
    (h : s.Matched S T) {i j : ℕ} (hi : s.sourceTuple.length ≤ i)
    (hj : s.sourceTuple.length ≤ j) : s.targetTuple[i]? = s.targetTuple[j]? :=
  BackForthState.target_getElem?_eq_of_source_getElem?_eq h
    (by rw [List.getElem?_eq_none hi, List.getElem?_eq_none hj])

end Consistency

/-! ### The base case

Two things to gate, and only two: that the empty state is matched at all, and that the hypothesis is
a **forward cover** rather than anything larger.

The signature row is the substantive one. `test_empty_from_forward_cover_only` derives the base case
from an arbitrary `RepresentationCoverIn E S.canonicalAge T.canonicalAge`, with `E` unrelated to `O`
and no inclusion between them — so no homogeneity, computability, or oracle hypothesis can have
crept in. `test_empty_orientation_is_structural` then shows what a full `RepresentationIsoIn` buys:
its `forward` field gives `empty.Matched S T` and its `backward` field gives `empty.Matched T S`.
The two are different statements, and which one a proof gets is fixed by the cover's direction
rather than by which field it happens to project.

Nonvacuity is already gated elsewhere: `CanonicalRangeAudit`'s constant-language rows show the
empty-generator corestriction is surjective onto a **nonempty** carrier, which is exactly the
content that would be missing if the empty case were only exercised where `D_⟨⟩` is empty. -/

section BaseCase

variable {E : Set (ℕ →. ℕ)}

/-- The empty state records nothing. -/
theorem test_empty_state_is_empty :
    BackForthState.empty.sourceTuple = [] ∧ BackForthState.empty.targetTuple = [] :=
  ⟨rfl, rfl⟩

/-- **A forward cover suffices, and is all that is assumed.** `E` is unrelated to `O`; there is no
`O ⊆ E`, no homogeneity, and no computability hypothesis in sight. -/
theorem test_empty_from_forward_cover_only {S T : ComputableStructureIn O L}
    (r : RepresentationCoverIn E S.canonicalAge T.canonicalAge) :
    BackForthState.empty.Matched S T :=
  BackForthState.empty_matched r

/-- **The orientation is structural.** A full isomorphism of representations yields the base case in
*both* directions — but as two different statements, each from the cover pointing that way. A proof
cannot reach `Matched S T` through `backward`. -/
theorem test_empty_orientation_is_structural {S T : ComputableStructureIn O L}
    (r : RepresentationIsoIn E S.canonicalAge T.canonicalAge) :
    BackForthState.empty.Matched S T ∧ BackForthState.empty.Matched T S :=
  ⟨BackForthState.empty_matched r.forward, BackForthState.empty_matched r.backward⟩

/-- The base case is consistent, trivially: both consequences hold at every pair of indices, since
every lookup is `none`. Recorded so the recursion's invariant is visibly established at stage 0. -/
theorem test_empty_is_consistent {S T : ComputableStructureIn O L}
    (r : RepresentationCoverIn E S.canonicalAge T.canonicalAge) (i j : ℕ) :
    BackForthState.empty.targetTuple[i]? = BackForthState.empty.targetTuple[j]? ∧
      BackForthState.empty.sourceTuple[i]? = BackForthState.empty.sourceTuple[j]? :=
  ⟨BackForthState.target_getElem?_eq_of_source_getElem?_eq (BackForthState.empty_matched r) rfl,
    BackForthState.source_getElem?_eq_of_target_getElem?_eq (BackForthState.empty_matched r) rfl⟩

end BaseCase

/-! ### The forth half

Six obligations. Two are about *shape* — the query's field order and the off-by-one split — and
they are the ones a plausible-looking rewrite would silently break.

**Orientation.** `test_forth_query_orientation` pins all three fields and then reads the consequence
off `originalMap`: the map the query describes starts at `encode s.targetTuple`. Swapping the first
two fields typechecks — both are `Tuple ℕ` — and would ask homogeneity to extend a map running the
wrong way, so the field-order row alone would not catch it. The `originalMap.domIdx` conjunct is
what makes the orientation observable.

**The split.** `test_forth_final_coordinate` gates the boundary from both sides: the image tuple has
length `sourceTuple.length + 1`, its prefix has length `sourceTuple.length`, and the two pieces
rejoin. An off-by-one in `take`/`getElem!` would leave one of the three false.

**The two appends are different facts.** The source append is the pushed point itself; the target
append is the *returned point* `y`, not the answer's extension tuple `γ⃗`.
`test_forth_target_is_returned_point` records both halves of that: what the state stores, and that
`γ⃗` merely names an ambient member containing `y`. Recording `γ⃗` instead would give a state whose
tight map nothing realizes.

**No oracle inclusion.** `test_forth_no_oracle_inclusion` runs the entire step with `E` unrelated to
`O`, and `test_canonical_source_needs_no_inclusion` gates the enabling computability lemma the same
way. -/

section Forth

variable {E : Set (ℕ →. ℕ)} {S T : ComputableStructureIn O L}
  (r : RepresentationCoverIn E S.canonicalAge T.canonicalAge) (s : BackForthState) (n : ℕ)

/-- **The query's orientation.** Current target tuple, then the cover's images of the
already-matched points, then the cover's image of the new point — and the consequence that fixes
it: the map the query describes *starts* at the member generated by `s.targetTuple`. -/
theorem test_forth_query_orientation :
    (BackForthState.forthQuery r s n).domainTuple = s.targetTuple ∧
      (BackForthState.forthQuery r s n).imageTuple = BackForthState.forthPrefix r s n ∧
        (BackForthState.forthQuery r s n).newPoint = BackForthState.forthNewPoint r s n ∧
          (BackForthState.forthQuery r s n).originalMap.domIdx = encode s.targetTuple :=
  ⟨rfl, rfl, rfl, rfl⟩

/-- **The off-by-one boundary**, gated from both sides: the two lengths, and the rejoining. -/
theorem test_forth_final_coordinate :
    (BackForthState.forthImage r s n).length = s.sourceTuple.length + 1 ∧
      (BackForthState.forthPrefix r s n).length = s.sourceTuple.length ∧
        BackForthState.forthImage r s n
          = BackForthState.forthPrefix r s n ++ [BackForthState.forthNewPoint r s n] :=
  ⟨BackForthState.forthImage_length r s n, BackForthState.forthPrefix_length r s n,
    BackForthState.forthImage_split r s n⟩

/-- The source side of the step: the new point, appended. -/
theorem test_forth_source_append (H : ComputablyHomogeneousIn E T) :
    (BackForthState.forthState r s n H).sourceTuple = s.sourceTuple ++ [n] :=
  rfl

/-- **The target side records the returned point, not the extension tuple.** `γ⃗` names the ambient
member the extension lands in — it contains `y`, as the second conjunct says — but the *tight*
matched range is the old target tuple with `y` appended, and that is what the state stores. -/
theorem test_forth_target_is_returned_point (H : ComputablyHomogeneousIn E T) :
    (BackForthState.forthState r s n H).targetTuple
        = s.targetTuple ++ [H.imageOfNewPoint (BackForthState.forthQuery r s n)] ∧
      H.imageOfNewPoint (BackForthState.forthQuery r s n)
        ∈ T.canonicalAge.domainAt
          (encode (H.extensionTuple (BackForthState.forthQuery r s n))) :=
  ⟨rfl, H.imageOfNewPoint_mem _⟩

/-- **The step preserves the invariant.** -/
theorem test_forth_preserves_matched (H : ComputablyHomogeneousIn E T) (h : s.Matched S T) :
    (BackForthState.forthState r s n H).Matched S T :=
  BackForthState.forthState_matched r s n H h

/-- **No `O ⊆ E`.** The families are presented at `O`, the cover and the homogeneity selector live
at an arbitrary `E`, and the step goes through with no relation between them assumed. -/
theorem test_forth_no_oracle_inclusion (H : ComputablyHomogeneousIn E T) (h : s.Matched S T) :
    (BackForthState.forthState r s n H).Matched S T ∧
      (BackForthState.forthState r s n H).sourceTuple = s.sourceTuple ++ [n] :=
  ⟨BackForthState.forthState_matched r s n H h, rfl⟩

/-- The enabling computability lemma, gated the same way: over a **canonical** source the generator
images are computable in the cover's own oracle, with no inclusion. -/
theorem test_canonical_source_needs_no_inclusion {B : PartialAgeIn O L}
    (r' : RepresentationCoverIn E S.canonicalAge B) : ComputableIn E r'.sourceGensImage :=
  r'.sourceGensImage_computableIn_canonicalSource

/-- **The step is computable in the map oracle**, on `(stage, state)` — the argument order
`ComputableIn.nat_rec` will need. `E` is again unrelated to `O`: the presentation oracle is never
consulted, which is exactly what the canonical-source generator-image lemma buys. -/
theorem test_forth_computableIn (H : ComputablyHomogeneousIn E T) :
    ComputableIn E fun p : ℕ × BackForthState ↦ BackForthState.forthState r p.2 p.1 H :=
  BackForthState.forthState_computableIn r H

/-- Each joint of the chain is separately computable, so a later change is localised. -/
theorem test_forth_chain_computableIn :
    ComputableIn E (fun p : ℕ × BackForthState ↦ p.2.pushedIdx p.1) ∧
      ComputableIn E (fun p : ℕ × BackForthState ↦ BackForthState.forthImage r p.2 p.1) ∧
        ComputableIn E (fun p : ℕ × BackForthState ↦ BackForthState.forthPrefix r p.2 p.1) ∧
          ComputableIn E (fun p : ℕ × BackForthState ↦ BackForthState.forthNewPoint r p.2 p.1) ∧
            ComputableIn E fun p : ℕ × BackForthState ↦ BackForthState.forthQuery r p.2 p.1 :=
  ⟨BackForthState.pushedIdx_computableIn, BackForthState.forthImage_computableIn r,
    BackForthState.forthPrefix_computableIn r, BackForthState.forthNewPoint_computableIn r,
    BackForthState.forthQuery_computableIn r⟩

end Forth

/-! ### The back half

The mirror rows, plus one the forth half has no analogue of.

**The orientation swaps.** `test_back_query_orientation` puts the *source* tuple first, where forth
put the target tuple, and reads the consequence off `originalMap.domIdx`.
`test_back_appends_swap` records the other swap: the source side gains the *returned* point and the
target side gains the *pushed* point, which is the reverse of forth on both counts.

**The inversion order is auditable.** `test_back_inversion_order` names the two inverted
equivalences by their endpoints and records that the first's codomain index is the second's domain
index — `encode (backImage …)`, the member the backward cover's image generates. That is the fact
that makes the order forced: composed the other way the two do not meet.
`test_back_inversion_numeric` pins the same boundary numerically. -/

section Back

variable {E : Set (ℕ →. ℕ)} {S T : ComputableStructureIn O L}
  (rb : RepresentationCoverIn E T.canonicalAge S.canonicalAge) (s : BackForthState) (n : ℕ)

/-- **The back query's orientation** — source tuple first, the mirror of forth. -/
theorem test_back_query_orientation :
    (BackForthState.backQuery rb s n).domainTuple = s.sourceTuple ∧
      (BackForthState.backQuery rb s n).imageTuple = BackForthState.backPrefix rb s n ∧
        (BackForthState.backQuery rb s n).newPoint = BackForthState.backNewPoint rb s n ∧
          (BackForthState.backQuery rb s n).originalMap.domIdx = encode s.sourceTuple :=
  ⟨rfl, rfl, rfl, rfl⟩

/-- The back split, measured against the **target** tuple's length. -/
theorem test_back_final_coordinate :
    (BackForthState.backImage rb s n).length = s.targetTuple.length + 1 ∧
      (BackForthState.backPrefix rb s n).length = s.targetTuple.length ∧
        BackForthState.backImage rb s n
          = BackForthState.backPrefix rb s n ++ [BackForthState.backNewPoint rb s n] :=
  ⟨BackForthState.backImage_length rb s n, BackForthState.backPrefix_length rb s n,
    BackForthState.backImage_split rb s n⟩

/-- **Both appends swap.** The source side gains the returned point `y`; the target side gains the
point `n` that was pushed. In the forth step it is the other way round. -/
theorem test_back_appends_swap (Hs : ComputablyHomogeneousIn E S) :
    (BackForthState.backState rb s n Hs).sourceTuple
        = s.sourceTuple ++ [Hs.imageOfNewPoint (BackForthState.backQuery rb s n)] ∧
      (BackForthState.backState rb s n Hs).targetTuple = s.targetTuple ++ [n] :=
  ⟨rfl, rfl⟩

/-- **The inversion order, by endpoints.** The homogeneity extension's inverse runs from the enlarged
source member to the member the backward cover's image generates; the cover's inverse runs from there
to the enlarged target member. The middle index is shared, and it is the only way the two compose. -/
theorem test_back_inversion_order (Hs : ComputablyHomogeneousIn E S) (h : s.Matched S T) :
    (∃ f, PartialAgeIn.PartialRealizesBetween S.canonicalAge S.canonicalAge
        (PotentialEmbeddingData.ofTriple
          (encode (s.sourceTuple ++ [Hs.imageOfNewPoint (BackForthState.backQuery rb s n)]),
            encode (BackForthState.backImage rb s n),
            BackForthState.backImage rb s n)) f) ∧
      (∃ f, PartialAgeIn.PartialRealizesBetween S.canonicalAge T.canonicalAge
        (PotentialEmbeddingData.ofTriple
          (encode (BackForthState.backImage rb s n), s.backPushedIdx n,
            s.targetTuple ++ [n])) f) ∧
        (PotentialEmbeddingData.ofTriple
            (encode (s.sourceTuple ++ [Hs.imageOfNewPoint (BackForthState.backQuery rb s n)]),
              encode (BackForthState.backImage rb s n),
              BackForthState.backImage rb s n)).codIdx
          = (PotentialEmbeddingData.ofTriple
            (encode (BackForthState.backImage rb s n), s.backPushedIdx n,
              s.targetTuple ++ [n])).domIdx :=
  ⟨BackForthState.backExtension_symm_realizes rb s n Hs h,
    BackForthState.backCoverEquiv_symm_realizes rb s n, rfl⟩

/-- The same boundary numerically: the composite's two ends are the enlarged tuples, each one longer
than what the state recorded. -/
theorem test_back_inversion_numeric (Hs : ComputablyHomogeneousIn E S) (h : s.Matched S T) :
    (BackForthState.backState rb s n Hs).sourceTuple.length = s.sourceTuple.length + 1 ∧
      (BackForthState.backState rb s n Hs).targetTuple.length = s.targetTuple.length + 1 ∧
        (BackForthState.backState rb s n Hs).sourceTuple.length
          = (BackForthState.backState rb s n Hs).targetTuple.length := by
  refine ⟨by simp, by simp, ?_⟩
  simp [BackForthState.length_eq_of_matched h]

/-- **The back step preserves the invariant.** -/
theorem test_back_preserves_matched (Hs : ComputablyHomogeneousIn E S) (h : s.Matched S T) :
    (BackForthState.backState rb s n Hs).Matched S T :=
  BackForthState.backState_matched rb s n Hs h

/-- **No `O ⊆ E`** on the back side either. -/
theorem test_back_no_oracle_inclusion (Hs : ComputablyHomogeneousIn E S) (h : s.Matched S T) :
    (BackForthState.backState rb s n Hs).Matched S T ∧
      (BackForthState.backState rb s n Hs).targetTuple = s.targetTuple ++ [n] :=
  ⟨BackForthState.backState_matched rb s n Hs h, rfl⟩

/-- The back step is computable on the same `(stage, state)` pair, in the same oracle. -/
theorem test_back_computableIn (Hs : ComputablyHomogeneousIn E S) :
    ComputableIn E fun p : ℕ × BackForthState ↦ BackForthState.backState rb p.2 p.1 Hs :=
  BackForthState.backState_computableIn rb Hs

end Back

end FirstOrder.Language

#assert_standard_axioms FirstOrder.Language.test_map_oracle_independent
#assert_standard_axioms FirstOrder.Language.test_symm_needs_no_inclusion
#assert_standard_axioms FirstOrder.Language.test_toFun_bijective
#assert_standard_axioms FirstOrder.Language.test_state_is_proof_free
#assert_standard_axioms FirstOrder.Language.test_state_is_computably_coded
#assert_standard_axioms FirstOrder.Language.test_tightMap_computableIn
#assert_standard_axioms FirstOrder.Language.test_matched_is_cross_family
#assert_standard_axioms FirstOrder.Language.test_tight_map_targets_its_range
#assert_standard_axioms FirstOrder.Language.test_matched_lengths
#assert_standard_axioms FirstOrder.Language.test_matched_realizer_unique
#assert_standard_axioms FirstOrder.Language.test_repeated_state_is_matched
#assert_standard_axioms FirstOrder.Language.test_repeated_source_unequal_target_not_matched
#assert_standard_axioms FirstOrder.Language.test_repeated_target_unequal_source_not_matched
#assert_standard_axioms FirstOrder.Language.test_consistency_is_global
#assert_standard_axioms FirstOrder.Language.test_consistency_out_of_range
#assert_standard_axioms FirstOrder.Language.test_empty_state_is_empty
#assert_standard_axioms FirstOrder.Language.test_empty_from_forward_cover_only
#assert_standard_axioms FirstOrder.Language.test_empty_orientation_is_structural
#assert_standard_axioms FirstOrder.Language.test_empty_is_consistent
#assert_standard_axioms FirstOrder.Language.test_forth_query_orientation
#assert_standard_axioms FirstOrder.Language.test_forth_final_coordinate
#assert_standard_axioms FirstOrder.Language.test_forth_source_append
#assert_standard_axioms FirstOrder.Language.test_forth_target_is_returned_point
#assert_standard_axioms FirstOrder.Language.test_forth_preserves_matched
#assert_standard_axioms FirstOrder.Language.test_forth_no_oracle_inclusion
#assert_standard_axioms FirstOrder.Language.test_canonical_source_needs_no_inclusion
#assert_standard_axioms FirstOrder.Language.test_forth_computableIn
#assert_standard_axioms FirstOrder.Language.test_forth_chain_computableIn
#assert_standard_axioms FirstOrder.Language.test_back_query_orientation
#assert_standard_axioms FirstOrder.Language.test_back_final_coordinate
#assert_standard_axioms FirstOrder.Language.test_back_appends_swap
#assert_standard_axioms FirstOrder.Language.test_back_inversion_order
#assert_standard_axioms FirstOrder.Language.test_back_inversion_numeric
#assert_standard_axioms FirstOrder.Language.test_back_preserves_matched
#assert_standard_axioms FirstOrder.Language.test_back_no_oracle_inclusion
#assert_standard_axioms FirstOrder.Language.test_back_computableIn
