/-
Copyright (c) 2026 Cameron Freer. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Cameron Freer
-/
import ComputableModelTheory.ModelTheory.Computable.CanonicalRange
import ComputableModelTheory.ModelTheory.Computable.ComputableIso

/-!
# The back-and-forth state — CHMM Proposition 3.2, landing 1

The state of an effective back-and-forth between two computable structures, and the invariant it is
required to satisfy. Only those; the consistency consequences, the base case, and the two half-steps
land separately.

## The state is proof-free, and computably coded

`BackForthState` carries two tuples and nothing else. No invariant is bundled, for the same reason
`FiniteInjury.StageState` bundles none: a state carrying its own proof cannot be produced by a
recursion that only *later* establishes the property.

Because the recursion that will build it is itself a computable function of the stage, the coding
API is needed up front and is supplied here in full — `Primcodable`, both projections, and the
constructor. Adding any of the three later would mean revisiting the state's definition once the
transition function exists.

## The invariant is separate

`Matched` is an existential over a **cross-family** realizer: the source member lives in
`S.canonicalAge`, the target in `T.canonicalAge`, so the single-family `PartialRealizes` does not
typecheck. The datum is *tight* — its codomain index is `encode targetTuple` and its range tuple is
`targetTuple`, so the target member is exactly the one generated by the tuple the state records,
with nothing left implicit.

Reading it off: `PartialRealizesBetween`'s length equation becomes
`sourceTuple.length = targetTuple.length`, since `S.canonicalAge.gens (encode t) = t`; and its
coordinate clauses say the realizer carries the `k`-th recorded generator to `targetTuple.get k`. So
`Matched` is exactly "the finite assignment `sourceTuple ↦ targetTuple` extends to an embedding of
the generated substructures", and `PartialRealizesBetween.unique` makes the realizer unambiguous.

**Repeated coordinates are legal** and the recursion will not remove them; that `Matched` forces
them to be consistent is landing 2's business, not stated here.
-/

open Encodable FirstOrder Language

namespace FirstOrder.Language

variable {O : Set (ℕ →. ℕ)} {L : Language} [L.EffectiveLanguage]

/-! ### The state -/

/-- The state of an effective back-and-forth: the source points matched so far, and their images.
**Proof-free** — the invariant is `Matched`, kept separate. -/
structure BackForthState where
  /-- The source points matched so far. -/
  sourceTuple : Tuple ℕ
  /-- Their images, positionally. -/
  targetTuple : Tuple ℕ

@[ext]
theorem BackForthState.ext {s t : BackForthState} (hs : s.sourceTuple = t.sourceTuple)
    (ht : s.targetTuple = t.targetTuple) : s = t := by
  cases s; cases t; cases hs; cases ht; rfl

/-- The code-level packaging of a state. -/
private def bfEquiv : BackForthState ≃ Tuple ℕ × Tuple ℕ where
  toFun s := (s.sourceTuple, s.targetTuple)
  invFun p := ⟨p.1, p.2⟩
  left_inv _ := rfl
  right_inv _ := rfl

instance : Primcodable BackForthState :=
  Primcodable.ofEquiv _ bfEquiv

namespace BackForthState

/-! #### Coding

All three pieces are supplied now, because the stage recursion is a computable function of the
stage and needs to take states apart and put them back together. -/

theorem primrec_sourceTuple : Primrec BackForthState.sourceTuple :=
  (Primrec.fst.comp (Primrec.of_equiv (e := bfEquiv))).of_eq fun _ ↦ rfl

theorem primrec_targetTuple : Primrec BackForthState.targetTuple :=
  (Primrec.snd.comp (Primrec.of_equiv (e := bfEquiv))).of_eq fun _ ↦ rfl

theorem sourceTuple_computableIn : ComputableIn O BackForthState.sourceTuple :=
  primrec_sourceTuple.to_comp.computableIn

theorem targetTuple_computableIn : ComputableIn O BackForthState.targetTuple :=
  primrec_targetTuple.to_comp.computableIn

/-- States are built from their two fields. -/
theorem primrec_mk : Primrec fun p : Tuple ℕ × Tuple ℕ ↦ (⟨p.1, p.2⟩ : BackForthState) :=
  (Primrec.of_equiv_symm (e := bfEquiv)).of_eq fun _ ↦ rfl

theorem mk_computableIn :
    ComputableIn O fun p : Tuple ℕ × Tuple ℕ ↦ (⟨p.1, p.2⟩ : BackForthState) :=
  primrec_mk.to_comp.computableIn

/-! #### The tight potential map -/

/-- The state's assignment as potential embedding data: source member at `encode sourceTuple`,
target member at `encode targetTuple`, range tuple `targetTuple`.

**Tight**: the codomain index is the code of the range tuple, so the target is exactly the member
generated by the tuple the state records. -/
def tightMap (s : BackForthState) : PotentialEmbeddingData :=
  PotentialEmbeddingData.ofTriple (encode s.sourceTuple, encode s.targetTuple, s.targetTuple)

@[simp] theorem tightMap_domIdx (s : BackForthState) :
    s.tightMap.domIdx = encode s.sourceTuple := rfl

@[simp] theorem tightMap_codIdx (s : BackForthState) :
    s.tightMap.codIdx = encode s.targetTuple := rfl

@[simp] theorem tightMap_rangeTuple (s : BackForthState) :
    s.tightMap.rangeTuple = s.targetTuple := rfl

theorem primrec_tightMap : Primrec BackForthState.tightMap := by
  have h : Primrec fun s : BackForthState ↦
      (Encodable.encode s.sourceTuple, Encodable.encode s.targetTuple, s.targetTuple) :=
    (Primrec.encode.comp primrec_sourceTuple).pair
      ((Primrec.encode.comp primrec_targetTuple).pair primrec_targetTuple)
  exact (PotentialEmbeddingData.primrec_ofTriple.comp h).of_eq fun _ ↦ rfl

theorem tightMap_computableIn : ComputableIn O BackForthState.tightMap :=
  primrec_tightMap.to_comp.computableIn

end BackForthState

/-! ### The invariant -/

/-- **The back-and-forth invariant**: the state's assignment extends to an embedding of the
generated substructures.

A *cross-family* realizer — source in `S.canonicalAge`, target in `T.canonicalAge` — so the
single-family `PartialRealizes` does not typecheck here. Kept apart from the state, which stays
proof-free. -/
def BackForthState.Matched (S T : ComputableStructureIn O L) (s : BackForthState) : Prop :=
  ∃ f, PartialAgeIn.PartialRealizesBetween S.canonicalAge T.canonicalAge s.tightMap f

theorem BackForthState.matched_iff {S T : ComputableStructureIn O L} {s : BackForthState} :
    s.Matched S T ↔
      ∃ f, PartialAgeIn.PartialRealizesBetween S.canonicalAge T.canonicalAge
        (PotentialEmbeddingData.ofTriple
          (encode s.sourceTuple, encode s.targetTuple, s.targetTuple)) f :=
  Iff.rfl

/-- The realizer is unique where it exists, so "the" embedding of a matched state is unambiguous. -/
theorem BackForthState.matched_unique {S T : ComputableStructureIn O L} {s : BackForthState}
    {f g : (S.canonicalAge.memberAt s.tightMap.domIdx).domain ↪[L]
      (T.canonicalAge.memberAt s.tightMap.codIdx).domain}
    (hf : PartialAgeIn.PartialRealizesBetween S.canonicalAge T.canonicalAge s.tightMap f)
    (hg : PartialAgeIn.PartialRealizesBetween S.canonicalAge T.canonicalAge s.tightMap g) :
    f = g :=
  PartialAgeIn.PartialRealizesBetween.unique hf hg

/-- Lengths agree on a matched state — the length equation of the realizer, read through
`gens (encode t) = t`. -/
theorem BackForthState.length_eq_of_matched {S T : ComputableStructureIn O L}
    {s : BackForthState} (h : s.Matched S T) : s.sourceTuple.length = s.targetTuple.length := by
  obtain ⟨-, hlen, -⟩ := h
  rwa [tightMap_domIdx, tightMap_rangeTuple, S.canonicalAge_gens, allTupleFor_encode] at hlen

end FirstOrder.Language
