/-
Copyright (c) 2026 Cameron Freer. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Cameron Freer
-/
import ComputableModelTheory.ModelTheory.Computable.BackForth
import ComputableModelTheory.Util.AssertAxioms

/-!
# Audit: the back-and-forth state — landing 1

Three obligations, each about a boundary rather than a computation.

**The map oracle is independent of the presentation oracle.** `test_map_oracle_independent` takes an
isomorphism at an **arbitrary** `E` over structures at `O`, with no relation between them assumed,
and reads back all six laws — only two of which mention `E` at all. `test_symm_needs_no_inclusion`
makes the same point for the groupoid operation. If a later refactor introduced `O ⊆ E`, these rows
would stop elaborating.

**The state is proof-free, and coded now rather than later.**
`test_state_is_proof_free` builds a state from two *arbitrary* tuples — `BackForthState` does not
even mention `O`, `L`, `S` or `T`, so there is nowhere for an invariant to hide.
`test_state_is_computably_coded` reads back all three coding facts together, because the stage
recursion needs to take a state apart *and* put one back together; supplying only the projections
would leave the transition function unbuildable.

**The invariant is cross-family and tight.** `test_matched_is_cross_family` records that the source
member is drawn from `S.canonicalAge` and the target from `T.canonicalAge`, so the single-family
`PartialRealizes` genuinely does not apply here. `test_tight_map_targets_its_range` pins the datum's
two indices: the codomain is `encode targetTuple` and the range tuple is `targetTuple`, so the target
member is exactly the one generated by the tuple the state records — which is what lets the
corestriction lemma apply without further hypotheses.

Deliberately absent: consistency of repeated coordinates, the base case, cover and homogeneity
consumption, and the two half-steps. Those are later landings.
-/

open Encodable FirstOrder Language

namespace FirstOrder.Language

variable {O : Set (ℕ →. ℕ)} {L : Language} [L.EffectiveLanguage]

/-! ### The map oracle is independent -/

/-- **`E` is unrelated to `O`.** The structures are presented at `O`, the maps are computable at an
arbitrary `E`, and no inclusion between them is assumed or used. Of the six laws, only the two
computability fields mention `E`. -/
theorem test_map_oracle_independent {E : Set (ℕ →. ℕ)} {S T : ComputableStructureIn O L}
    (i : ComputableStructureIsoIn E S T) :
    (ComputableIn E i.toFun ∧ ComputableIn E i.invFun) ∧
      (∀ x, i.invFun (i.toFun x) = x) ∧ (∀ y, i.toFun (i.invFun y) = y) ∧
      (∀ (n : ℕ) (f : L.Functions n) (v : Fin n → ℕ),
        i.toFun (@Structure.funMap L ℕ S.inst n f v)
          = @Structure.funMap L ℕ T.inst n f fun k ↦ i.toFun (v k)) ∧
      ∀ (n : ℕ) (R : L.Relations n) (v : Fin n → ℕ),
        @Structure.RelMap L ℕ T.inst n R (fun k ↦ i.toFun (v k))
          ↔ @Structure.RelMap L ℕ S.inst n R v :=
  ⟨⟨i.toFun_computableIn, i.invFun_computableIn⟩, i.left_inv, i.right_inv,
    i.toFun_funMap, i.toFun_relMap⟩

/-- Symmetry needs no inclusion either — it swaps the stored maps and reads the laws backwards. -/
theorem test_symm_needs_no_inclusion {E : Set (ℕ →. ℕ)} {S T : ComputableStructureIn O L}
    (i : ComputableStructureIsoIn E S T) :
    Nonempty (ComputableStructureIsoIn E T S) ∧ i.symm.toFun = i.invFun :=
  ⟨⟨i.symm⟩, rfl⟩

/-- The forward map is a bijection, as the two total inverse laws force. -/
theorem test_toFun_bijective {E : Set (ℕ →. ℕ)} {S T : ComputableStructureIn O L}
    (i : ComputableStructureIsoIn E S T) : Function.Bijective i.toFun :=
  i.toFun_bijective

/-! ### The state -/

/-- **Proof-free.** Any two tuples make a state, with no side condition — and `BackForthState`
mentions neither the structures nor the language, so there is nowhere for an invariant to hide. -/
theorem test_state_is_proof_free (a b : Tuple ℕ) :
    ∃ s : BackForthState, s.sourceTuple = a ∧ s.targetTuple = b :=
  ⟨⟨a, b⟩, rfl, rfl⟩

/-- **Coded now, not later.** All three facts together: the stage recursion must take a state apart
*and* build one, so projections alone would leave the transition function unbuildable. -/
theorem test_state_is_computably_coded :
    ComputableIn O BackForthState.sourceTuple ∧ ComputableIn O BackForthState.targetTuple ∧
      ComputableIn O fun p : Tuple ℕ × Tuple ℕ ↦ (⟨p.1, p.2⟩ : BackForthState) :=
  ⟨BackForthState.sourceTuple_computableIn, BackForthState.targetTuple_computableIn,
    BackForthState.mk_computableIn⟩

/-- The tight map is computable too, since the recursion forms it at every stage. -/
theorem test_tightMap_computableIn : ComputableIn O BackForthState.tightMap :=
  BackForthState.tightMap_computableIn

/-! ### The invariant -/

/-- **Cross-family.** The source member is drawn from `S.canonicalAge` and the target from
`T.canonicalAge`, so `PartialRealizesBetween` is required and the single-family `PartialRealizes`
does not typecheck here. -/
theorem test_matched_is_cross_family {S T : ComputableStructureIn O L} {s : BackForthState} :
    s.Matched S T ↔
      ∃ f, PartialAgeIn.PartialRealizesBetween S.canonicalAge T.canonicalAge
        (PotentialEmbeddingData.ofTriple
          (encode s.sourceTuple, encode s.targetTuple, s.targetTuple)) f :=
  BackForthState.matched_iff

/-- **The datum is tight**: its codomain index is `encode targetTuple` and its range tuple is
`targetTuple`, so the target member is exactly the one generated by the tuple the state records.
That is what will let the corestriction lemma apply with no further hypothesis. -/
theorem test_tight_map_targets_its_range (s : BackForthState) :
    s.tightMap.domIdx = encode s.sourceTuple ∧
      s.tightMap.codIdx = encode s.targetTuple ∧
        s.tightMap.rangeTuple = s.targetTuple :=
  ⟨rfl, rfl, rfl⟩

/-- Lengths agree on a matched state — the realizer's length equation, read through
`gens (encode t) = t`. -/
theorem test_matched_lengths {S T : ComputableStructureIn O L} {s : BackForthState}
    (h : s.Matched S T) : s.sourceTuple.length = s.targetTuple.length :=
  BackForthState.length_eq_of_matched h

/-- The realizer of a matched state is unique, so "the" embedding is unambiguous. -/
theorem test_matched_realizer_unique {S T : ComputableStructureIn O L} {s : BackForthState}
    {f g : (S.canonicalAge.memberAt s.tightMap.domIdx).domain ↪[L]
      (T.canonicalAge.memberAt s.tightMap.codIdx).domain}
    (hf : PartialAgeIn.PartialRealizesBetween S.canonicalAge T.canonicalAge s.tightMap f)
    (hg : PartialAgeIn.PartialRealizesBetween S.canonicalAge T.canonicalAge s.tightMap g) :
    f = g :=
  BackForthState.matched_unique hf hg

end FirstOrder.Language

#assert_standard_axioms FirstOrder.Language.test_map_oracle_independent
#assert_standard_axioms FirstOrder.Language.test_symm_needs_no_inclusion
#assert_standard_axioms FirstOrder.Language.test_toFun_bijective
#assert_standard_axioms FirstOrder.Language.test_state_is_proof_free
#assert_standard_axioms FirstOrder.Language.test_state_is_computably_coded
#assert_standard_axioms FirstOrder.Language.test_tightMap_computableIn
#assert_standard_axioms FirstOrder.Language.test_matched_is_cross_family
#assert_standard_axioms FirstOrder.Language.test_tight_map_targets_its_range
#assert_standard_axioms FirstOrder.Language.test_matched_lengths
#assert_standard_axioms FirstOrder.Language.test_matched_realizer_unique
