/-
Copyright (c) 2026 Cameron Freer. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Cameron Freer
-/
import ComputableModelTheory.ModelTheory.Computable.CanonicalRange
import ComputableModelTheory.ModelTheory.Computable.ComputableIso
import ComputableModelTheory.ModelTheory.Computable.RepresentationIso

/-!
# The back-and-forth state — CHMM Proposition 3.2, landing 1

The state of an effective back-and-forth between two computable structures, and the invariant it is
required to satisfy. Only those; the consistency consequences, the base case, and the two half-steps
land separately.

## The state is proof-free, and computably coded

`BackForthState` carries two tuples and nothing else. No invariant is bundled, for the same reason
`FiniteInjury.StageState` bundles none: a state carrying its own proof cannot be produced by a
recursion that only *later* establishes the property.

Because the recursion that will build it is itself a computable function of the stage, the coding
API is needed up front and is supplied here in full — `Primcodable`, both projections, and the
constructor. Adding any of the three later would mean revisiting the state's definition once the
transition function exists.

## The invariant is separate

`Matched` is an existential over a **cross-family** realizer: the source member lives in
`S.canonicalAge`, the target in `T.canonicalAge`, so the single-family `PartialRealizes` does not
typecheck. The datum is *tight* — its codomain index is `encode targetTuple` and its range tuple is
`targetTuple`, so the target member is exactly the one generated by the tuple the state records,
with nothing left implicit.

Reading it off: `PartialRealizesBetween`'s length equation becomes
`sourceTuple.length = targetTuple.length`, since `S.canonicalAge.gens (encode t) = t`; and its
coordinate clauses say the realizer carries the `k`-th recorded generator to `targetTuple.get k`. So
`Matched` is exactly "the finite assignment `sourceTuple ↦ targetTuple` extends to an embedding of
the generated substructures", and `PartialRealizesBetween.unique` makes the realizer unambiguous.

**Repeated coordinates are legal** and the recursion will not remove them; that `Matched` forces
them to be consistent is landing 2's business, not stated here.
-/

open Encodable FirstOrder Language

namespace FirstOrder.Language

variable {O : Set (ℕ →. ℕ)} {L : Language} [L.EffectiveLanguage]

/-! ### The state -/

/-- The state of an effective back-and-forth: the source points matched so far, and their images.
**Proof-free** — the invariant is `Matched`, kept separate. -/
structure BackForthState where
  /-- The source points matched so far. -/
  sourceTuple : Tuple ℕ
  /-- Their images, positionally. -/
  targetTuple : Tuple ℕ

@[ext]
theorem BackForthState.ext {s t : BackForthState} (hs : s.sourceTuple = t.sourceTuple)
    (ht : s.targetTuple = t.targetTuple) : s = t := by
  cases s; cases t; cases hs; cases ht; rfl

/-- The code-level packaging of a state. -/
private def bfEquiv : BackForthState ≃ Tuple ℕ × Tuple ℕ where
  toFun s := (s.sourceTuple, s.targetTuple)
  invFun p := ⟨p.1, p.2⟩
  left_inv _ := rfl
  right_inv _ := rfl

instance : Primcodable BackForthState :=
  Primcodable.ofEquiv _ bfEquiv

namespace BackForthState

/-! #### Coding

All three pieces are supplied now, because the stage recursion is a computable function of the
stage and needs to take states apart and put them back together. -/

theorem primrec_sourceTuple : Primrec BackForthState.sourceTuple :=
  (Primrec.fst.comp (Primrec.of_equiv (e := bfEquiv))).of_eq fun _ ↦ rfl

theorem primrec_targetTuple : Primrec BackForthState.targetTuple :=
  (Primrec.snd.comp (Primrec.of_equiv (e := bfEquiv))).of_eq fun _ ↦ rfl

theorem sourceTuple_computableIn : ComputableIn O BackForthState.sourceTuple :=
  primrec_sourceTuple.to_comp.computableIn

theorem targetTuple_computableIn : ComputableIn O BackForthState.targetTuple :=
  primrec_targetTuple.to_comp.computableIn

/-- States are built from their two fields. -/
theorem primrec_mk : Primrec fun p : Tuple ℕ × Tuple ℕ ↦ (⟨p.1, p.2⟩ : BackForthState) :=
  (Primrec.of_equiv_symm (e := bfEquiv)).of_eq fun _ ↦ rfl

theorem mk_computableIn :
    ComputableIn O fun p : Tuple ℕ × Tuple ℕ ↦ (⟨p.1, p.2⟩ : BackForthState) :=
  primrec_mk.to_comp.computableIn

/-! #### The tight potential map -/

/-- The state's assignment as potential embedding data: source member at `encode sourceTuple`,
target member at `encode targetTuple`, range tuple `targetTuple`.

**Tight**: the codomain index is the code of the range tuple, so the target is exactly the member
generated by the tuple the state records. -/
def tightMap (s : BackForthState) : PotentialEmbeddingData :=
  PotentialEmbeddingData.ofTriple (encode s.sourceTuple, encode s.targetTuple, s.targetTuple)

@[simp] theorem tightMap_domIdx (s : BackForthState) :
    s.tightMap.domIdx = encode s.sourceTuple := rfl

@[simp] theorem tightMap_codIdx (s : BackForthState) :
    s.tightMap.codIdx = encode s.targetTuple := rfl

@[simp] theorem tightMap_rangeTuple (s : BackForthState) :
    s.tightMap.rangeTuple = s.targetTuple := rfl

theorem primrec_tightMap : Primrec BackForthState.tightMap := by
  have h : Primrec fun s : BackForthState ↦
      (Encodable.encode s.sourceTuple, Encodable.encode s.targetTuple, s.targetTuple) :=
    (Primrec.encode.comp primrec_sourceTuple).pair
      ((Primrec.encode.comp primrec_targetTuple).pair primrec_targetTuple)
  exact (PotentialEmbeddingData.primrec_ofTriple.comp h).of_eq fun _ ↦ rfl

theorem tightMap_computableIn : ComputableIn O BackForthState.tightMap :=
  primrec_tightMap.to_comp.computableIn

end BackForthState

/-! ### The invariant -/

/-- **The back-and-forth invariant**: the state's assignment extends to an embedding of the
generated substructures.

A *cross-family* realizer — source in `S.canonicalAge`, target in `T.canonicalAge` — so the
single-family `PartialRealizes` does not typecheck here. Kept apart from the state, which stays
proof-free. -/
def BackForthState.Matched (S T : ComputableStructureIn O L) (s : BackForthState) : Prop :=
  ∃ f, PartialAgeIn.PartialRealizesBetween S.canonicalAge T.canonicalAge s.tightMap f

theorem BackForthState.matched_iff {S T : ComputableStructureIn O L} {s : BackForthState} :
    s.Matched S T ↔
      ∃ f, PartialAgeIn.PartialRealizesBetween S.canonicalAge T.canonicalAge
        (PotentialEmbeddingData.ofTriple
          (encode s.sourceTuple, encode s.targetTuple, s.targetTuple)) f :=
  Iff.rfl

/-- The realizer is unique where it exists, so "the" embedding of a matched state is unambiguous. -/
theorem BackForthState.matched_unique {S T : ComputableStructureIn O L} {s : BackForthState}
    {f g : (S.canonicalAge.memberAt s.tightMap.domIdx).domain ↪[L]
      (T.canonicalAge.memberAt s.tightMap.codIdx).domain}
    (hf : PartialAgeIn.PartialRealizesBetween S.canonicalAge T.canonicalAge s.tightMap f)
    (hg : PartialAgeIn.PartialRealizesBetween S.canonicalAge T.canonicalAge s.tightMap g) :
    f = g :=
  PartialAgeIn.PartialRealizesBetween.unique hf hg

/-- Lengths agree on a matched state — the length equation of the realizer, read through
`gens (encode t) = t`. -/
theorem BackForthState.length_eq_of_matched {S T : ComputableStructureIn O L}
    {s : BackForthState} (h : s.Matched S T) : s.sourceTuple.length = s.targetTuple.length := by
  obtain ⟨-, hlen, -⟩ := h
  rwa [tightMap_domIdx, tightMap_rangeTuple, S.canonicalAge_gens, allTupleFor_encode] at hlen

/-! ### Coordinate consistency

The two facts the inverse laws will need, stated **positionally and globally**: no length hypothesis,
no bound hypothesis, no `Fin`. Both are `getElem?` equations between the two tuples at the same pair
of indices, so they compose without side conditions.

Each covers two cases at once. In bounds, the content is the realizer's: *functionality* gives the
forward direction (equal source entries are the same carrier point, so their images agree), and
*injectivity* gives the backward one. Out of bounds, `length_eq_of_matched` makes both lookups on the
other side `none`, and the mixed case cannot arise because `some ≠ none`. That is why the length
equality is derived here rather than demanded of the caller.

Repeated coordinates are legal — a state may record the same source point twice — and these lemmas
say exactly what that costs: the images must then agree, and conversely.
-/

namespace BackForthState

variable {S T : ComputableStructureIn O L} {s : BackForthState}

/-- The out-of-bounds bookkeeping, done once for both directions: a positional `getElem?` equation
transfers along any length-matched pair of tuples, given only the in-bounds content. -/
private theorem getElem?_transfer {a b : Tuple ℕ} (hab : a.length = b.length) {i j : ℕ}
    (hij : a[i]? = a[j]?)
    (hin : ∀ (hi : i < a.length) (hj : j < a.length),
      a[i] = a[j] → b[i]'(hab ▸ hi) = b[j]'(hab ▸ hj)) :
    b[i]? = b[j]? := by
  by_cases hi : i < a.length
  · by_cases hj : j < a.length
    · rw [List.getElem?_eq_getElem hi, List.getElem?_eq_getElem hj] at hij
      rw [List.getElem?_eq_getElem (hab ▸ hi), List.getElem?_eq_getElem (hab ▸ hj)]
      exact congrArg some (hin hi hj (Option.some.inj hij))
    · rw [List.getElem?_eq_getElem hi, List.getElem?_eq_none (by omega)] at hij
      exact absurd hij (by simp)
  · have hj : ¬ j < a.length := by
      intro hj
      rw [List.getElem?_eq_none (by omega), List.getElem?_eq_getElem hj] at hij
      exact absurd hij (by simp)
    rw [List.getElem?_eq_none (by omega), List.getElem?_eq_none (by omega)]

/-- Every entry of a tuple names a point of the canonical member it generates. -/
private theorem exists_coe_eq_getElem (S : ComputableStructureIn O L) (t : Tuple ℕ) {i : ℕ}
    (hi : i < t.length) :
    ∃ x : (S.canonicalAge.memberAt (encode t)).domain, (x : ℕ) = t[i] := by
  have hgens : S.canonicalAge.gens (encode t) = t := by simp
  have hi' : i < (S.canonicalAge.gens (encode t)).length := by rw [hgens]; exact hi
  refine ⟨S.canonicalAge.gensView (encode t) ⟨i, hi'⟩, ?_⟩
  rw [PartialAgeIn.gensView_coe, List.get_eq_getElem]
  exact List.getElem_of_eq hgens hi'

/-- **The realizer reads off the target tuple positionally.** For any carrier point named by the
`i`-th source entry, its image is the `i`-th target entry — stated as a `getElem?` equation, so no
bound on the target side has to be produced. -/
private theorem realizer_getElem?
    {f : (S.canonicalAge.memberAt s.tightMap.domIdx).domain ↪[L]
      (T.canonicalAge.memberAt s.tightMap.codIdx).domain}
    (hf : PartialAgeIn.PartialRealizesBetween S.canonicalAge T.canonicalAge s.tightMap f)
    {i : ℕ} (hi : i < s.sourceTuple.length)
    {x : (S.canonicalAge.memberAt s.tightMap.domIdx).domain}
    (hx : (x : ℕ) = s.sourceTuple[i]) :
    s.targetTuple[i]?
      = some ((f x : (T.canonicalAge.memberAt s.tightMap.codIdx).domain) : ℕ) := by
  have hgens : S.canonicalAge.gens s.tightMap.domIdx = s.sourceTuple := by simp [tightMap]
  have hi' : i < (S.canonicalAge.gens s.tightMap.domIdx).length := by rw [hgens]; exact hi
  obtain ⟨hlen, hcoord⟩ := hf
  have hxi : x = S.canonicalAge.gensView s.tightMap.domIdx ⟨i, hi'⟩ := by
    refine Subtype.ext ?_
    rw [hx, PartialAgeIn.gensView_coe, List.get_eq_getElem]
    exact (List.getElem_of_eq hgens hi').symm
  rw [hxi, hcoord ⟨i, hi'⟩]
  have hti : i < s.targetTuple.length := by
    rw [← hgens] at hi; exact hlen ▸ hi
  rw [List.getElem?_eq_getElem hti]
  rfl

/-- **Functionality.** A matched state that records the same source point at two positions records
the same image at both — the two positions name one carrier point, and the realizer is a function.

Out of bounds it is the length equality that closes the case, which is why no length hypothesis
appears. -/
theorem target_getElem?_eq_of_source_getElem?_eq {i j : ℕ} (h : s.Matched S T)
    (hij : s.sourceTuple[i]? = s.sourceTuple[j]?) :
    s.targetTuple[i]? = s.targetTuple[j]? := by
  obtain ⟨f, hf⟩ := h
  refine getElem?_transfer (length_eq_of_matched ⟨f, hf⟩) hij fun hi hj hval ↦ ?_
  obtain ⟨x, hx⟩ := exists_coe_eq_getElem S s.sourceTuple hi
  have hi' := realizer_getElem? hf hi hx
  have hj' := realizer_getElem? hf hj (hx.trans hval)
  rw [List.getElem?_eq_getElem (length_eq_of_matched ⟨f, hf⟩ ▸ hi)] at hi'
  rw [List.getElem?_eq_getElem (length_eq_of_matched ⟨f, hf⟩ ▸ hj)] at hj'
  exact Option.some.inj (hi'.trans hj'.symm)

/-- **Injectivity.** Conversely, a matched state that records the same image at two positions must
have recorded the same source point at both — the realizer is an embedding.

The two directions are genuinely separate facts about the same realizer; neither implies the other,
and the recursion needs both to prove the two inverse laws. -/
theorem source_getElem?_eq_of_target_getElem?_eq {i j : ℕ} (h : s.Matched S T)
    (hij : s.targetTuple[i]? = s.targetTuple[j]?) :
    s.sourceTuple[i]? = s.sourceTuple[j]? := by
  obtain ⟨f, hf⟩ := h
  have hlen := length_eq_of_matched (S := S) (T := T) ⟨f, hf⟩
  refine getElem?_transfer hlen.symm hij fun hi hj hval ↦ ?_
  obtain ⟨x, hx⟩ := exists_coe_eq_getElem S s.sourceTuple (hlen.symm ▸ hi)
  obtain ⟨y, hy⟩ := exists_coe_eq_getElem S s.sourceTuple (hlen.symm ▸ hj)
  have hi' := realizer_getElem? hf (hlen.symm ▸ hi) hx
  have hj' := realizer_getElem? hf (hlen.symm ▸ hj) hy
  rw [List.getElem?_eq_getElem hi] at hi'
  rw [List.getElem?_eq_getElem hj] at hj'
  have : f x = f y :=
    Subtype.ext (Option.some.inj (hi'.symm.trans (by rw [hval]; exact hj')))
  rw [← hx, ← hy]
  exact congrArg (fun z : (S.canonicalAge.memberAt s.tightMap.domIdx).domain ↦ (z : ℕ))
    (f.injective this)

/-! ### The base case

The recursion starts from the state that has matched nothing. That this state is already matched is
**not** automatic from both empty-tuple members existing: `Matched` asks for an embedding of
`D_{⟨⟩}` into `D_{⟨⟩}`, and where the language has constants those carriers are nonempty, so
something must produce the map. A forward cover does.

The signature takes a `RepresentationCoverIn E S.canonicalAge T.canonicalAge` and nothing else. That
is sharper than accepting a `RepresentationIsoIn`, and it makes the orientation structural rather
than a matter of which field a proof happens to project: the base case needs only the direction that
maps source members into the target, so the backward cover cannot silently be relied on. Nor does
anything here need homogeneity, computability, or `O ⊆ E` — the cover is used purely semantically,
through the equivalence it already carries at one index.
-/

/-- The state that has matched nothing. -/
def empty : BackForthState := ⟨[], []⟩

@[simp] theorem empty_sourceTuple : empty.sourceTuple = [] := rfl

@[simp] theorem empty_targetTuple : empty.targetTuple = [] := rfl

/-- **The base case, from a forward cover alone.** At the index coding the empty tuple, the cover's
stored equivalence realizes the generator data, whose range tuple is empty because the source has no
recorded generators; corestricting it to its own generated range lands exactly the empty state's
tight map.

Only `S.canonicalAge → T.canonicalAge` is used. No homogeneity, no computability, no oracle
inclusion, no backward cover. -/
theorem empty_matched {E : Set (ℕ →. ℕ)} {S T : ComputableStructureIn O L}
    (r : RepresentationCoverIn E S.canonicalAge T.canonicalAge) : empty.Matched S T := by
  have hgens : S.canonicalAge.gens (encode ([] : Tuple ℕ)) = [] :=
    allTupleFor_encode _
  have hsg : r.sourceGensImage (encode ([] : Tuple ℕ)) = [] :=
    r.sourceGensImage_of_gens_nil hgens
  have hex : ∃ f, PartialAgeIn.PartialRealizesBetween S.canonicalAge T.canonicalAge
      (PotentialEmbeddingData.ofTriple (encode ([] : Tuple ℕ),
        encode (r.sourceGensImage (encode ([] : Tuple ℕ))),
        r.sourceGensImage (encode ([] : Tuple ℕ)))) f :=
    ⟨_, PartialAgeIn.PartialRealizesBetween.toCanonicalRangeEquiv_realizes
      (r.generatorEmbeddingData_realized (encode ([] : Tuple ℕ)))⟩
  have hdata : PotentialEmbeddingData.ofTriple (encode ([] : Tuple ℕ),
      encode (r.sourceGensImage (encode ([] : Tuple ℕ))),
      r.sourceGensImage (encode ([] : Tuple ℕ))) = empty.tightMap := by
    rw [hsg]; rfl
  exact Eq.mp (congrArg (fun F ↦ ∃ f,
    PartialAgeIn.PartialRealizesBetween S.canonicalAge T.canonicalAge F f) hdata) hex

end BackForthState

end FirstOrder.Language
