/-
Copyright (c) 2026 Cameron Freer. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Cameron Freer
-/
import ComputableModelTheory.ModelTheory.Computable.CanonicalAgeBackwardCover

/-!
# The forward cover `𝕂_𝒟 → K`

The second of the two covers of CHMM Theorem 2.10(⇐), and the one whose compatibility the paper's
forward implication *assumes*. A canonical query `e` names a tuple of ω-codes; the tuple pullback
moves it to one scheduled stage; the hereditary property selects a member of `K` generated by it
there. That member answers the query — and the selection is why the core carries a `sourceIndex`.

**One answer, one `.get`.** `forwardAnswerPart` returns the stage, the pulled tuple and the selected
index *together*, and is totalized once. Totalizing the three separately would let them drift: the
tuple is only valid at its own stage, and the selected member is only related to that tuple.

**The hypothesis split is visible and deliberate.** Totality of the answer needs the
`InfinitudeCertificate` — the pullback can diverge if a code names no limit element — but **not**
`RepresentedByRawRep`: carrier validity of the pulled tuple comes from
`mem_domainAt_of_mem_rankTupleAtStagePart` and `scheduledStage_domain`, neither of which says
anything about how carrier codes are named. `RepresentedByRawRep` enters only at self-matching,
because that is where `forall₂_omegaStageEmbedding` — the statement that the pullback's ω-image is
the query — is used.

**No coordinate bookkeeping.** `MappedCHPSpec` hands the selection over as potential embedding data
with a realizer, so the producer never touches CHP's length equation or coordinate family;
`partialIsEmbedding_ofTriple` did that once and for all. The program is then the same
`idFun → applyPotentialPart → rankStageMap` shape as the backward cover's, and the generator
compatibility at the end is `fromCanonicalAgeCover_generatorCompatible` verbatim.
-/

open Encodable Part FirstOrder Language

namespace FirstOrder.Language

namespace PartialAgeIn

variable {O : Set (ℕ →. ℕ)} {L : Language} [L.EffectiveLanguage]

/-! ### The selector-facing form of the hereditary property

The mirror of `JointSpec`: downstream runs `applyPotentialPart` on the answer, so it wants the
answer as `PotentialEmbeddingData` with a realizer rather than as a length equation plus a
coordinate family. -/

/-- **What a consumer of the hereditary property actually needs**, as reusable data: for every valid
query, the selected member's index together with potential embedding data that is *actual*. -/
def MappedCHPSpec (K : PartialAgeIn O L) (sel : ℕ → List ℕ →. ℕ) : Prop :=
  ∀ (e : ℕ) (s : List ℕ), (∀ x ∈ s, x ∈ K.domainAt e) →
    ∃ c ∈ sel e s, K.PartialIsEmbedding (PotentialEmbeddingData.ofTriple (c, e, s))

/-- CHP delivers exactly that, with a computable selector. The extraction is
`partialIsEmbedding_ofTriple` applied to the contract's own witnesses — no coordinate bookkeeping
crosses this boundary. -/
theorem MappedPartialCHPIn.exists_chpSpec {E : Set (ℕ →. ℕ)} {K : PartialAgeIn O L}
    (h : MappedPartialCHPIn E K) :
    ∃ sel : ℕ → List ℕ →. ℕ,
      RecursiveIn E (fun p : ℕ × List ℕ ↦ sel p.1 p.2) ∧ K.MappedCHPSpec sel := by
  obtain ⟨sel, hsel, hspec⟩ := h
  refine ⟨sel, hsel, fun e s hs ↦ ?_⟩
  obtain ⟨c, hc, hlen, F, hF⟩ := hspec e s hs
  exact ⟨c, hc, partialIsEmbedding_ofTriple hlen F hF⟩

/-! ### The answer pipeline -/

variable {K : PartialAgeIn O L} {sel : ℕ → ℕ → PartialJointEmbeddingData} {baseIdx : ℕ}
variable {hne : ∀ n, (K.domainAt (cjepSchedule sel baseIdx n)).Nonempty}
variable {hspec : K.JointSpec sel} {hsel : ComputableIn O fun p : ℕ × ℕ ↦ sel p.1 p.2}
variable (Z : (selfChain K sel baseIdx hne hspec hsel).LimitIn)
variable (chpSel : ℕ → List ℕ →. ℕ)

/-- **The whole answer to a canonical query**: pull the query's tuple back to a common scheduled
stage, then ask the hereditary property there. The stage, the pulled tuple and the selected index
come out together, and are totalized together — separately they could drift, since the tuple is
valid only at its own stage. -/
noncomputable def forwardAnswerPart (e : ℕ) : Part ((ℕ × List ℕ) × ℕ) :=
  (Z.rankTupleAtStagePart (allTupleFor e)).bind fun p ↦
    (chpSel (cjepSchedule sel baseIdx p.1) p.2).map fun c ↦ (p, c)

/-- **The pulled tuple is a valid query at its stage.** Pure carrier bookkeeping: the pullback lands
in the chain stage's carrier, and totalizing a scheduled member did not move it. Nothing here
depends on how carrier codes are named. -/
theorem mem_domainAt_of_mem_rankTuple {e : ℕ} {p : ℕ × List ℕ}
    (hp : p ∈ Z.rankTupleAtStagePart (allTupleFor e)) :
    ∀ x ∈ p.2, x ∈ K.domainAt (cjepSchedule sel baseIdx p.1) := by
  intro x hx
  have h := Z.mem_domainAt_of_mem_rankTupleAtStagePart hp x hx
  rwa [selfChain_stageAt, scheduledStage_domain] at h

/-- **Totality of the answer needs the certificate — and nothing else.** The pullback is the only
part that can diverge; the selector halts because the pulled tuple is a valid query. In particular
`RepresentedByRawRep` is *not* used, which is what keeps it out of the producer. -/
theorem forwardAnswerPart_dom (cert : Z.presentation.InfinitudeCertificate)
    (hchpSpec : K.MappedCHPSpec chpSel) (e : ℕ) : (forwardAnswerPart Z chpSel e).Dom := by
  obtain ⟨p, hp⟩ := Part.dom_iff_mem.1 (Z.rankTupleAtStagePart_dom cert (allTupleFor e))
  obtain ⟨c, hc, -⟩ := hchpSpec _ _ (mem_domainAt_of_mem_rankTuple Z hp)
  exact Part.dom_iff_mem.2 ⟨(p, c), Part.mem_bind_iff.2
    ⟨p, hp, (Part.mem_map_iff _).2 ⟨c, hc, rfl⟩⟩⟩

/-- Partial recursive in the oracle. -/
theorem forwardAnswerPart_recursiveIn
    (hchp : RecursiveIn O fun q : ℕ × List ℕ ↦ chpSel q.1 q.2) :
    RecursiveIn O (forwardAnswerPart Z chpSel) := by
  have hA : RecursiveIn O fun e : ℕ ↦ Z.rankTupleAtStagePart (allTupleFor e) :=
    Z.rankTupleAtStagePart_recursiveIn.comp allTupleFor_computableIn
  have hB : RecursiveIn O fun q : ℕ × (ℕ × List ℕ) ↦
      (chpSel (cjepSchedule sel baseIdx q.2.1) q.2.2).map fun c ↦ (q.2, c) :=
    RecursiveIn.map
      (hchp.comp
        (((cjepSchedule_computableIn sel baseIdx hsel).comp
          (ComputableIn.fst.comp ComputableIn.snd)).pair
          (ComputableIn.snd.comp ComputableIn.snd)))
      (((ComputableIn.snd.comp ComputableIn.fst).pair ComputableIn.snd).to₂)
  exact RecursiveIn.bind hA hB.to₂

/-! ### The totalized answer and its projections -/

variable (cert : Z.presentation.InfinitudeCertificate) (hchpSpec : K.MappedCHPSpec chpSel)

include cert hchpSpec in
/-- The answer, totalized **once**. -/
noncomputable def forwardAnswer (e : ℕ) : (ℕ × List ℕ) × ℕ :=
  (forwardAnswerPart Z chpSel e).get (forwardAnswerPart_dom Z chpSel cert hchpSpec e)

include cert hchpSpec in
theorem mem_forwardAnswerPart (e : ℕ) :
    forwardAnswer Z chpSel cert hchpSpec e ∈ forwardAnswerPart Z chpSel e :=
  Part.get_mem _

/-- The common stage the query's tuple was pulled back to. -/
noncomputable def forwardStage (e : ℕ) : ℕ :=
  (forwardAnswer Z chpSel cert hchpSpec e).1.1

/-- The pulled-back tuple, valid at that stage. -/
noncomputable def forwardTuple (e : ℕ) : List ℕ :=
  (forwardAnswer Z chpSel cert hchpSpec e).1.2

/-- The member of `K` the hereditary property selected — the source index of the forward cover. -/
noncomputable def forwardIndex (e : ℕ) : ℕ :=
  (forwardAnswer Z chpSel cert hchpSpec e).2

include cert hchpSpec in
/-- The stage and tuple are a genuine pullback of the query. -/
theorem mem_rankTupleAtStagePart (e : ℕ) :
    (forwardStage Z chpSel cert hchpSpec e, forwardTuple Z chpSel cert hchpSpec e)
      ∈ Z.rankTupleAtStagePart (allTupleFor e) := by
  obtain ⟨p, hp, hmap⟩ := Part.mem_bind_iff.1 (mem_forwardAnswerPart Z chpSel cert hchpSpec e)
  obtain ⟨c, -, heq⟩ := (Part.mem_map_iff _).1 hmap
  have h1 : forwardStage Z chpSel cert hchpSpec e = p.1 := congrArg (fun r ↦ r.1.1) heq.symm
  have h2 : forwardTuple Z chpSel cert hchpSpec e = p.2 := congrArg (fun r ↦ r.1.2) heq.symm
  rw [h1, h2]
  exact hp

include cert hchpSpec in
/-- And the selected index is the selector's answer to that query. -/
theorem mem_chpSel (e : ℕ) :
    forwardIndex Z chpSel cert hchpSpec e
      ∈ chpSel (cjepSchedule sel baseIdx (forwardStage Z chpSel cert hchpSpec e))
        (forwardTuple Z chpSel cert hchpSpec e) := by
  obtain ⟨p, hp, hmap⟩ := Part.mem_bind_iff.1 (mem_forwardAnswerPart Z chpSel cert hchpSpec e)
  obtain ⟨c, hc, heq⟩ := (Part.mem_map_iff _).1 hmap
  have h1 : forwardStage Z chpSel cert hchpSpec e = p.1 := congrArg (fun r ↦ r.1.1) heq.symm
  have h2 : forwardTuple Z chpSel cert hchpSpec e = p.2 := congrArg (fun r ↦ r.1.2) heq.symm
  have h3 : forwardIndex Z chpSel cert hchpSpec e = c := congrArg (fun r ↦ r.2) heq.symm
  rw [h1, h2, h3]
  exact hc

/-! ### The selected embedding data -/

include cert hchpSpec in
/-- The selection, as potential embedding data. -/
noncomputable def forwardData (e : ℕ) : PotentialEmbeddingData :=
  PotentialEmbeddingData.ofTriple
    (forwardIndex Z chpSel cert hchpSpec e,
      cjepSchedule sel baseIdx (forwardStage Z chpSel cert hchpSpec e),
      forwardTuple Z chpSel cert hchpSpec e)

include cert hchpSpec in
/-- **It is actual** — from `MappedCHPSpec`, with no coordinate argument. -/
theorem forwardData_partialIsEmbedding (e : ℕ) :
    K.PartialIsEmbedding (forwardData Z chpSel cert hchpSpec e) := by
  obtain ⟨c, hc, hemb⟩ := hchpSpec _ _
    (mem_domainAt_of_mem_rankTuple Z (mem_rankTupleAtStagePart Z chpSel cert hchpSpec e))
  have : c = forwardIndex Z chpSel cert hchpSpec e :=
    Part.mem_unique hc (mem_chpSel Z chpSel cert hchpSpec e)
  rw [forwardData, ← this]
  exact hemb

include cert hchpSpec in
/-- The realizer of the selection. Noncomputable — `PartialIsEmbedding` is an existential — which is
why the program is carried separately. -/
noncomputable def forwardRealizer (e : ℕ) :
    (K.memberAt (forwardIndex Z chpSel cert hchpSpec e)).domain ↪[L]
      (K.memberAt (cjepSchedule sel baseIdx (forwardStage Z chpSel cert hchpSpec e))).domain :=
  (forwardData_partialIsEmbedding Z chpSel cert hchpSpec e).choose

include cert hchpSpec in
theorem forwardRealizer_mem_applyPotentialPart {e x : ℕ}
    (hx : x ∈ K.domainAt (forwardIndex Z chpSel cert hchpSpec e)) :
    ((forwardRealizer Z chpSel cert hchpSpec e ⟨x, hx⟩ :
        (K.memberAt (cjepSchedule sel baseIdx (forwardStage Z chpSel cert hchpSpec e))).domain) : ℕ)
      ∈ K.applyPotentialPart (forwardData Z chpSel cert hchpSpec e) x :=
  applyPotentialPart_mem_realizer
    (forwardData_partialIsEmbedding Z chpSel cert hchpSpec e).choose_spec hx

/-! ### The program and the semantic embedding -/

include cert hchpSpec in
/-- **The program, guarded.** The same shape as the backward cover's: the first bind makes the
domain exact, and the two that follow are the selected embedding and the recoded stage map. -/
noncomputable def forwardMap (e : ℕ) : ℕ →. ℕ :=
  fun x ↦ (K.idFun (forwardIndex Z chpSel cert hchpSpec e, x)).bind fun x' ↦
    (K.applyPotentialPart (forwardData Z chpSel cert hchpSpec e) x').bind fun y ↦
      Z.rankStageMap (forwardStage Z chpSel cert hchpSpec e) y

include cert hchpSpec in
/-- **The semantic embedding of the selected member into the ω-limit**: the CHP realizer, the
carrier crossing at the pulled-back stage, and the recoded stage embedding. -/
noncomputable def forwardEmbedding (e : ℕ) :
    @Language.Embedding L (K.memberAt (forwardIndex Z chpSel cert hchpSpec e)).domain ℕ _
      (limitStructure Z cert).inst :=
  letI : L.Structure ℕ := Z.presentation.rankStr
  (Z.omegaStageEmbedding (forwardStage Z chpSel cert hchpSpec e)).comp
    ((scheduledStageEquiv (hne := hne) (hOE := Set.Subset.refl O)
        (forwardStage Z chpSel cert hchpSpec e)).toEmbedding.comp
      (forwardRealizer Z chpSel cert hchpSpec e))

include cert hchpSpec in
/-- **The two sides agree**, one membership per stage of the pipeline. -/
theorem forwardEmbedding_mem_forwardMap (e : ℕ)
    (x : (K.memberAt (forwardIndex Z chpSel cert hchpSpec e)).domain) :
    forwardEmbedding Z chpSel cert hchpSpec e x ∈ forwardMap Z chpSel cert hchpSpec e (x : ℕ) := by
  refine Part.mem_bind_iff.2 ⟨(x : ℕ), K.mem_idFun.2 ⟨rfl, x.2⟩, ?_⟩
  refine Part.mem_bind_iff.2
    ⟨((forwardRealizer Z chpSel cert hchpSpec e x :
        (K.memberAt (cjepSchedule sel baseIdx
          (forwardStage Z chpSel cert hchpSpec e))).domain) : ℕ),
      forwardRealizer_mem_applyPotentialPart Z chpSel cert hchpSpec x.2, ?_⟩
  exact Z.omegaStageEmbedding_apply_mem (forwardStage Z chpSel cert hchpSpec e)
    (scheduledStageEquiv (hne := hne) (hOE := Set.Subset.refl O)
      (forwardStage Z chpSel cert hchpSpec e) (forwardRealizer Z chpSel cert hchpSpec e x))

include cert hchpSpec in
/-- **The guard alone gives the hard direction** — certificate-free in the same sense as the
backward cover's: a successful composite proves `K.idFun` halted. -/
theorem mem_domainAt_of_forwardMap_dom {e x : ℕ}
    (h : (forwardMap Z chpSel cert hchpSpec e x).Dom) :
    x ∈ K.domainAt (forwardIndex Z chpSel cert hchpSpec e) := by
  obtain ⟨y, hy⟩ := Part.dom_iff_mem.1 h
  obtain ⟨x', hx', -⟩ := Part.mem_bind_iff.1 hy
  exact (K.mem_idFun.1 hx').2

include cert hchpSpec in
/-- **Exact domain.** -/
theorem forwardMap_dom (e x : ℕ) :
    (forwardMap Z chpSel cert hchpSpec e x).Dom
      ↔ x ∈ K.domainAt (forwardIndex Z chpSel cert hchpSpec e) := by
  refine ⟨mem_domainAt_of_forwardMap_dom Z chpSel cert hchpSpec, fun hx ↦ ?_⟩
  exact Part.dom_iff_mem.2 ⟨_, forwardEmbedding_mem_forwardMap Z chpSel cert hchpSpec e ⟨x, hx⟩⟩

/-! ### Effectivity -/

include cert hchpSpec in
/-- Everything the producer needs from the answer is computable, because the answer is. -/
theorem forwardAnswer_computableIn
    (hchp : RecursiveIn O fun q : ℕ × List ℕ ↦ chpSel q.1 q.2) :
    ComputableIn O (forwardAnswer Z chpSel cert hchpSpec) :=
  RecursiveIn.computableIn_get (forwardAnswerPart_recursiveIn Z chpSel hchp)
    (forwardAnswerPart_dom Z chpSel cert hchpSpec)

include cert hchpSpec in
theorem forwardIndex_computableIn
    (hchp : RecursiveIn O fun q : ℕ × List ℕ ↦ chpSel q.1 q.2) :
    ComputableIn O (forwardIndex Z chpSel cert hchpSpec) :=
  (Primrec.snd.to_comp.computableIn).comp (forwardAnswer_computableIn Z chpSel cert hchpSpec hchp)

include cert hchpSpec in
theorem forwardStage_computableIn
    (hchp : RecursiveIn O fun q : ℕ × List ℕ ↦ chpSel q.1 q.2) :
    ComputableIn O (forwardStage Z chpSel cert hchpSpec) :=
  ((Primrec.fst.comp Primrec.fst).to_comp.computableIn).comp
    (forwardAnswer_computableIn Z chpSel cert hchpSpec hchp)

include cert hchpSpec in
theorem forwardData_computableIn
    (hchp : RecursiveIn O fun q : ℕ × List ℕ ↦ chpSel q.1 q.2) :
    ComputableIn O (forwardData Z chpSel cert hchpSpec) := by
  have hans := forwardAnswer_computableIn Z chpSel cert hchpSpec hchp
  have hidx : ComputableIn O (forwardIndex Z chpSel cert hchpSpec) :=
    forwardIndex_computableIn Z chpSel cert hchpSpec hchp
  have hstage : ComputableIn O fun e ↦
      cjepSchedule sel baseIdx (forwardStage Z chpSel cert hchpSpec e) :=
    (cjepSchedule_computableIn sel baseIdx hsel).comp
      (forwardStage_computableIn Z chpSel cert hchpSpec hchp)
  have htuple : ComputableIn O (forwardTuple Z chpSel cert hchpSpec) :=
    ((Primrec.snd.comp Primrec.fst).to_comp.computableIn).comp hans
  exact (PotentialEmbeddingData.primrec_ofTriple.to_comp.computableIn).comp
    (hidx.pair (hstage.pair htuple))

include cert hchpSpec in
/-- Uniformly partial recursive in the query. -/
theorem forwardMap_uniform
    (hchp : RecursiveIn O fun q : ℕ × List ℕ ↦ chpSel q.1 q.2) :
    RecursiveIn O fun p : ℕ × ℕ ↦ forwardMap Z chpSel cert hchpSpec p.1 p.2 := by
  have hidx : ComputableIn O (forwardIndex Z chpSel cert hchpSpec) :=
    forwardIndex_computableIn Z chpSel cert hchpSpec hchp
  have hdata : ComputableIn O (forwardData Z chpSel cert hchpSpec) :=
    forwardData_computableIn Z chpSel cert hchpSpec hchp
  have hstage : ComputableIn O (forwardStage Z chpSel cert hchpSpec) :=
    forwardStage_computableIn Z chpSel cert hchpSpec hchp
  have h₁ : RecursiveIn O fun p : ℕ × ℕ ↦
      K.idFun (forwardIndex Z chpSel cert hchpSpec p.1, p.2) :=
    K.idFun_recursiveIn.comp ((hidx.comp ComputableIn.fst).pair ComputableIn.snd)
  have h₂ : RecursiveIn O fun q : (ℕ × ℕ) × ℕ ↦
      K.applyPotentialPart (forwardData Z chpSel cert hchpSpec q.1.1) q.2 :=
    RecursiveIn.comp (O := O) (α := (ℕ × ℕ) × ℕ) (β := PotentialEmbeddingData × ℕ) (σ := ℕ)
      (f := fun r : PotentialEmbeddingData × ℕ ↦ K.applyPotentialPart r.1 r.2)
      (g := fun q : (ℕ × ℕ) × ℕ ↦ (forwardData Z chpSel cert hchpSpec q.1.1, q.2))
      K.applyPotentialPart_recursiveIn
      ((hdata.comp (ComputableIn.fst.comp ComputableIn.fst)).pair ComputableIn.snd)
  have h₃ : RecursiveIn O fun r : ((ℕ × ℕ) × ℕ) × ℕ ↦
      Z.rankStageMap (forwardStage Z chpSel cert hchpSpec r.1.1.1) r.2 :=
    RecursiveIn.comp (O := O) (α := ((ℕ × ℕ) × ℕ) × ℕ) (β := ℕ × ℕ) (σ := ℕ)
      (f := fun p : ℕ × ℕ ↦ Z.rankStageMap p.1 p.2)
      (g := fun r : ((ℕ × ℕ) × ℕ) × ℕ ↦
        (forwardStage Z chpSel cert hchpSpec r.1.1.1, r.2))
      Z.rankStageMap_recursiveIn
      ((hstage.comp (ComputableIn.fst.comp (ComputableIn.fst.comp ComputableIn.fst))).pair
        ComputableIn.snd)
  exact RecursiveIn.bind h₁ (RecursiveIn.bind h₂ h₃.to₂).to₂

/-! ### The package -/

include cert hchpSpec in
/-- **The selected embedding of `K` into its own ω-limit**, query-indexed by the canonical age. -/
noncomputable def toSelectedEmbedding
    (hchp : RecursiveIn O fun q : ℕ × List ℕ ↦ chpSel q.1 q.2) :
    UniformSelectedEmbeddingIntoIn O K (limitStructure Z cert) where
  sourceIndex := forwardIndex Z chpSel cert hchpSpec
  sourceIndex_computableIn := forwardIndex_computableIn Z chpSel cert hchpSpec hchp
  embedding := forwardEmbedding Z chpSel cert hchpSpec
  map := forwardMap Z chpSel cert hchpSpec
  map_uniform := forwardMap_uniform Z chpSel cert hchpSpec hchp
  map_dom := forwardMap_dom Z chpSel cert hchpSpec
  map_apply_mem := forwardEmbedding_mem_forwardMap Z chpSel cert hchpSpec

/-! ### Self-matching

The one place `RepresentedByRawRep` enters, because it is where `forall₂_omegaStageEmbedding` is
used: the pullback's ω-image is the query, coordinatewise. Composed with the selection's own
coordinates, that says the program carries the selected member's generators exactly onto the
query's tuple — which is `imageTuple e = allTupleFor e`. -/

include cert hchpSpec in
/-- The selection's realizer contract, with the `ofTriple` projections reduced — the form the list
theorem consumes. -/
theorem forwardRealizer_spec (e : ℕ) :
    ∃ hlen : (K.gens (forwardIndex Z chpSel cert hchpSpec e)).length
        = (forwardTuple Z chpSel cert hchpSpec e).length,
      ∀ k : Fin (K.gens (forwardIndex Z chpSel cert hchpSpec e)).length,
        ((forwardRealizer Z chpSel cert hchpSpec e
            (K.gensView (forwardIndex Z chpSel cert hchpSpec e) k) :
          (K.memberAt (cjepSchedule sel baseIdx
            (forwardStage Z chpSel cert hchpSpec e))).domain) : ℕ)
          = (forwardTuple Z chpSel cert hchpSpec e).get (Fin.cast hlen k) :=
  (forwardData_partialIsEmbedding Z chpSel cert hchpSpec e).choose_spec

include cert hchpSpec in
/-- **The list-level theorem.** The program carries the selected member's recorded generators onto
the canonical query's tuple. Two coordinate families composed: the selection's (from its realizer)
and the pullback's (from `forall₂_omegaStageEmbedding`). -/
theorem forall₂_forwardMap_gens (hrep : Z.RepresentedByRawRep) (e : ℕ) :
    List.Forall₂ (fun x y ↦ y ∈ forwardMap Z chpSel cert hchpSpec e x)
      (K.gens (forwardIndex Z chpSel cert hchpSpec e)) (allTupleFor e) := by
  obtain ⟨hlen, hF⟩ := forwardRealizer_spec Z chpSel cert hchpSpec e
  have hco : List.Forall₂
      (fun n y ↦ ∃ hy : y ∈ ((selfChain K sel baseIdx hne hspec hsel).stageAt
          (forwardStage Z chpSel cert hchpSpec e)).domain,
        Z.omegaStageEmbedding (forwardStage Z chpSel cert hchpSpec e) ⟨y, hy⟩ = n)
      (allTupleFor e) (forwardTuple Z chpSel cert hchpSpec e) :=
    Z.forall₂_omegaStageEmbedding hrep (mem_rankTupleAtStagePart Z chpSel cert hchpSpec e)
  obtain ⟨hcoLen, hcoGet⟩ := List.forall₂_iff_get.1 hco
  refine List.forall₂_iff_get.2 ⟨?_, ?_⟩
  · rw [hlen, ← hcoLen]
  · intro n h₁ h₂
    have hlt : n < (forwardTuple Z chpSel cert hchpSpec e).length := by
      rw [← hlen]; exact h₁
    obtain ⟨hy, hyeq⟩ := hcoGet n h₂ hlt
    have hx : (K.gens (forwardIndex Z chpSel cert hchpSpec e)).get ⟨n, h₁⟩
        ∈ K.domainAt (forwardIndex Z chpSel cert hchpSpec e) :=
      K.gens_mem_domainAt ⟨n, h₁⟩
    refine Part.mem_bind_iff.2 ⟨_, K.mem_idFun.2 ⟨rfl, hx⟩, ?_⟩
    refine Part.mem_bind_iff.2 ⟨(forwardTuple Z chpSel cert hchpSpec e).get ⟨n, hlt⟩, ?_, ?_⟩
    · have hmem := forwardRealizer_mem_applyPotentialPart Z chpSel cert hchpSpec hx
      have hval : ((forwardRealizer Z chpSel cert hchpSpec e ⟨_, hx⟩ :
            (K.memberAt (cjepSchedule sel baseIdx
              (forwardStage Z chpSel cert hchpSpec e))).domain) : ℕ)
          = (forwardTuple Z chpSel cert hchpSpec e).get ⟨n, hlt⟩ := hF ⟨n, h₁⟩
      rwa [hval] at hmem
    · rw [← hyeq]
      exact Z.omegaStageEmbedding_apply_mem _ ⟨_, hy⟩

include cert hchpSpec in
/-- **Self-matching.** The image tuple of the query is the query's own recorded tuple — the single
equality that both identifies the canonical source index and yields generator compatibility. -/
theorem imageTuple_eq_allTupleFor (hrep : Z.RepresentedByRawRep)
    (hchp : RecursiveIn O fun q : ℕ × List ℕ ↦ chpSel q.1 q.2) (e : ℕ) :
    (toSelectedEmbedding Z chpSel cert hchpSpec hchp).imageTuple e = allTupleFor e :=
  Part.mem_unique (Part.get_mem _)
    (mem_listMapPart_iff.2 (forall₂_forwardMap_gens Z chpSel cert hchpSpec hrep e))

/-! ### The cover -/

include cert hchpSpec in
/-- **The forward cover `𝕂_𝒟 → K`.** An application of `fromCanonicalAgeCover`: its index map is
the hereditary property's selected member, with no inverse-index assumption. -/
noncomputable def forwardCover (hrep : Z.RepresentedByRawRep)
    (hchp : RecursiveIn O fun q : ℕ × List ℕ ↦ chpSel q.1 q.2) :
    RepresentationCoverIn O (limitStructure Z cert).canonicalAge K :=
  (toSelectedEmbedding Z chpSel cert hchpSpec hchp).fromCanonicalAgeCover (Set.Subset.refl O)
    (imageTuple_eq_allTupleFor Z chpSel cert hchpSpec hrep hchp)

include cert hchpSpec in
@[simp] theorem forwardCover_indexMap (hrep : Z.RepresentedByRawRep)
    (hchp : RecursiveIn O fun q : ℕ × List ℕ ↦ chpSel q.1 q.2) (e : ℕ) :
    (forwardCover Z chpSel cert hchpSpec hrep hchp).indexMap e
      = forwardIndex Z chpSel cert hchpSpec e :=
  rfl

include cert hchpSpec in
/-- **The forward cover is generator-compatible** — the generic theorem verbatim. This is the
compatibility CHMM's forward implication assumes and, per `CanonicalAgeSeparationAudit`, cannot get
for free; the reverse implication constructs it here. -/
theorem forwardCover_generatorCompatible (hrep : Z.RepresentedByRawRep)
    (hchp : RecursiveIn O fun q : ℕ × List ℕ ↦ chpSel q.1 q.2) :
    (forwardCover Z chpSel cert hchpSpec hrep hchp).GeneratorCompatible :=
  (toSelectedEmbedding Z chpSel cert hchpSpec hchp).fromCanonicalAgeCover_generatorCompatible
    (Set.Subset.refl O) (imageTuple_eq_allTupleFor Z chpSel cert hchpSpec hrep hchp)

end PartialAgeIn

end FirstOrder.Language
