/-
Copyright (c) 2026 Cameron Freer. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Cameron Freer
-/
import ComputableModelTheory.ModelTheory.Computable.PartialTupleReindex
import ComputableModelTheory.ModelTheory.Computable.TupleReindex
import ComputableModelTheory.ModelTheory.Computable.PartialTheorem28
import ComputableModelTheory.ModelTheory.Computable.PartialCJEP
import ComputableModelTheory.ModelTheory.Computable.RepresentationWitnessTransport

/-!
# The canonical representation of the age of a computable structure — CHMM Definition 2.4

> Let `D` be a computable structure. Let `{ā_i : i ∈ ω}` be an enumeration of all the tuples from
> `D`, and let `A_i` be the substructure of `D` generated by `ā_i`. Let `K_D = {(A_i, ā_i)}`.

`allTupleFor` is that enumeration of tuples, and `canonicalAge` is `K_D`. Three choices are
decisions rather than consequences, and are pinned by the `simp` lemmas below:

* **One ambient structure.** `structureAt i` is `S.inst` for *every* `i`, so the members are
  literally substructures of one structure and every embedding between them is an inclusion. That
  is what makes Lemma 2.6 cheap.
* **The empty tuple is included.** `allTupleFor` hits `[]`, whose member is the closure of the
  constants — genuinely empty in a constant-free relational language. `PartialAgeIn` is
  empty-capable exactly so that "all the tuples" can be taken literally.
* **The index is the tuple code**, so `gens (encode t) = t` definitionally. This is what makes the
  hereditary-property selector of Lemma 2.6 total rather than a search.

The enumeration is the bounded-decode machine of `PartialTermEvaluation`, run at the
single-presentation layer: decoding an `L.Term (Fin (allTupleFor i).length)` would put the tuple's
length in a *type*, and no uniform-in-`i` decode exists for that. Decoding an `L.Term ℕ` under
`Term.boundedDecode` keeps the length a value, and `Term.VarsBelow` decides which codes the machine
halts on — so the enumeration is a total computable `Option`-valued function even though its engine
is partial. This is the same crossing `PartialAgeIn.genEnum?` makes, at a structure rather than a
family.

**This file constructs `𝕂_𝒟` only.** Whether a representation computably isomorphic to it inherits
the effective properties is a separate question with a negative answer in general — see
`RepresentationWitnessTransport` and `CHPSeparationAudit`.
-/

open Encodable Part FirstOrder Language

namespace FirstOrder.Language

variable {O : Set (ℕ →. ℕ)} {L : Language} [L.EffectiveLanguage]

/-- The tuple recorded at a tuple's own code is that tuple. -/
@[simp] theorem allTupleFor_encode (t : Tuple ℕ) : allTupleFor (encode t) = t := by
  rw [allTupleFor, Denumerable.ofNat_encode]

namespace ComputableStructureIn

variable (S : ComputableStructureIn O L)

/-! ### The structure as a presentation on all of `ℕ`

The machine needs a `PartialCePresentationIn` to read its evaluator from. A computable structure
gives one whose domain is everything, which is what makes every environment below on-domain without
a side condition. -/

/-- A computable structure as a possibly-empty presentation — with carrier all of `ℕ`, enumerated
by the identity. -/
noncomputable def toPartialCePresentation : PartialCePresentationIn O L where
  str := S.inst
  enum? m := Option.some m
  enum?_computableIn := ComputableIn.option_some
  domain_closed := fun _ _ _ _ ↦ ⟨_, rfl⟩
  funEval := S.toCePresentation.funEval
  funEval_recursiveIn := S.toCePresentation.funEval_recursiveIn
  funEval_correct := fun d _ ↦ S.toCePresentation.funEval_correct d fun k ↦ ⟨d.args k, rfl⟩
  relEval := S.toCePresentation.relEval
  relEval_recursiveIn := S.toCePresentation.relEval_recursiveIn
  relEval_correct := fun d _ ↦ S.toCePresentation.relEval_correct d fun k ↦ ⟨d.args k, rfl⟩

@[simp] theorem toPartialCePresentation_str : S.toPartialCePresentation.str = S.inst := rfl

/-- Every natural number is in the carrier, so every environment is on-domain. -/
theorem mem_toPartialCePresentation_domain (x : ℕ) :
    x ∈ S.toPartialCePresentation.domain :=
  ⟨x, rfl⟩

/-! ### The enumeration of one member -/

/-- The enumeration of the substructure of `S` generated by the `i`-th tuple: decode a bounded
natural-variable term and realize it over that tuple. Codes naming no bounded term enumerate
nothing, so over the empty tuple in a constant-free relational language the enumeration is
genuinely empty. -/
noncomputable def canonicalEnum? (i m : ℕ) : Option ℕ :=
  (Term.boundedDecode (L := L) (allTupleFor i).length m).map fun t ↦
    @Term.realize L ℕ S.inst ℕ (ComputableAgeIn.envFun (allTupleFor i)) t

variable {S}

theorem canonicalEnum?_eq_some_iff {i m x : ℕ} :
    S.canonicalEnum? i m = Option.some x ↔
      ∃ t : L.Term ℕ,
        Term.boundedDecode (L := L) (allTupleFor i).length m = Option.some t ∧
          @Term.realize L ℕ S.inst ℕ (ComputableAgeIn.envFun (allTupleFor i)) t = x := by
  rw [canonicalEnum?, Option.map_eq_some_iff]

/-- **The member is the generated substructure.** The enumeration hits exactly the values of terms
over the tuple — the `Fin`-indexed form `PartialAgeIn` records, reached from the natural-variable
machine by the `restrictVar`/`relabel` bridge. -/
theorem exists_canonicalEnum?_eq_some_iff {i x : ℕ} :
    (∃ m, S.canonicalEnum? i m = Option.some x) ↔
      ∃ T : L.Term (Fin (allTupleFor i).length),
        x = @Term.realize L ℕ S.inst _ (Tuple.view (allTupleFor i)) T := by
  letI : L.Structure ℕ := S.inst
  set env := allTupleFor i with henv
  constructor
  · rintro ⟨m, hm⟩
    obtain ⟨t, hdec, hval⟩ := canonicalEnum?_eq_some_iff.1 hm
    have hvb := (Term.boundedDecode_eq_some_iff.1 hdec).2
    refine ⟨t.restrictVar fun v ↦ (⟨v.1, hvb v.1 v.2⟩ : Fin env.length), ?_⟩
    rw [← hval]
    exact Term.realize_envFun_restrictVar (L := L) (env := env) rfl t hvb
  · rintro ⟨T, rfl⟩
    obtain ⟨m, hm⟩ :=
      Term.exists_boundedDecode_eq_some (Term.varsBelow_relabel_val (k := env.length) T)
    exact ⟨m, canonicalEnum?_eq_some_iff.2
      ⟨T.relabel Fin.val, hm, Term.realize_envFun_relabel_val (L := L) (env := env) rfl T⟩⟩

variable (S)

/-- The enumeration is computable uniformly in the index: `Term.boundedDecode` admits only codes
the machine provably halts on, so the guarded call is a partial recursive function that is in fact
total. No step bound and no halting oracle. -/
theorem canonicalEnum?_computableIn :
    ComputableIn O fun p : ℕ × ℕ ↦ S.canonicalEnum? p.1 p.2 := by
  have henv : ComputableIn O fun p : ℕ × ℕ ↦ allTupleFor p.1 :=
    allTupleFor_computableIn.comp ComputableIn.fst
  have hdec : ComputableIn O fun p : ℕ × ℕ ↦
      Term.boundedDecode (L := L) (allTupleFor p.1).length p.2 :=
    (Term.primrec₂_boundedDecode (L := L)).to_comp.computableIn₂.comp
      ((Computable.list_length.computableIn).comp henv) ComputableIn.snd
  have hcall : RecursiveIn O fun q : (ℕ × ℕ) × L.Term ℕ ↦
      S.toPartialCePresentation.partialRealize (allTupleFor q.1.1) q.2 :=
    RecursiveIn.comp (O := O) (α := (ℕ × ℕ) × L.Term ℕ) (β := Tuple ℕ × L.Term ℕ) (σ := ℕ)
      (f := fun r : Tuple ℕ × L.Term ℕ ↦ S.toPartialCePresentation.partialRealize r.1 r.2)
      (g := fun q : (ℕ × ℕ) × L.Term ℕ ↦ (allTupleFor q.1.1, q.2))
      S.toPartialCePresentation.partialRealize_recursiveIn
      ((henv.comp ComputableIn.fst).pair ComputableIn.snd)
  have hpart : RecursiveIn O fun p : ℕ × ℕ ↦
      Option.casesOn (motive := fun _ ↦ Part (Option ℕ))
        (Term.boundedDecode (L := L) (allTupleFor p.1).length p.2)
        (Part.some Option.none)
        fun t ↦ (S.toPartialCePresentation.partialRealize (allTupleFor p.1) t).map Option.some :=
    RecursiveIn.option_casesOn_right (O := O) (α := ℕ × ℕ) (β := L.Term ℕ) (σ := Option ℕ)
      (o := fun p ↦ Term.boundedDecode (L := L) (allTupleFor p.1).length p.2)
      (f := fun _ ↦ Option.none)
      (g := fun p t ↦ (S.toPartialCePresentation.partialRealize (allTupleFor p.1) t).map
        Option.some)
      hdec (ComputableIn.const Option.none)
      ((RecursiveIn.map (O := O) (α := (ℕ × ℕ) × L.Term ℕ) (β := ℕ) (σ := Option ℕ)
        (f := fun q ↦ S.toPartialCePresentation.partialRealize (allTupleFor q.1.1) q.2)
        (g := fun _ (v : ℕ) ↦ Option.some v)
        hcall (ComputableIn.option_some.comp ComputableIn.snd).to₂).to₂)
  refine hpart.of_eq fun p ↦ ?_
  show _ = Part.some (S.canonicalEnum? p.1 p.2)
  rw [canonicalEnum?]
  rcases h : Term.boundedDecode (L := L) (allTupleFor p.1).length p.2 with - | t
  · rfl
  · show (S.toPartialCePresentation.partialRealize (allTupleFor p.1) t).map Option.some = _
    rw [PartialCePresentationIn.partialRealize_eq_some
      (fun x _ ↦ S.mem_toPartialCePresentation_domain x)
      (Term.boundedDecode_eq_some_iff.1 h).2]
    rfl

/-! ### The representation -/

/-- **CHMM Definition 2.4**: the canonical representation of the age of a computable structure —
the family of substructures generated by all the tuples of `S`, indexed by tuple codes.

Level 1 throughout: no member is claimed decidable and no isomorphism is claimed computable. -/
noncomputable def canonicalAge : PartialAgeIn O L where
  structureAt _ := S.inst
  enum? := S.canonicalEnum?
  enum?_computableIn := S.canonicalEnum?_computableIn
  gens := allTupleFor
  gens_computableIn := allTupleFor_computableIn
  funEval _ := S.toPartialCePresentation.funEval
  funEval_recursiveIn := S.toPartialCePresentation.funEval_recursiveIn.comp ComputableIn.snd
  funEval_correct := fun _ d _ ↦
    S.toPartialCePresentation.funEval_correct d
      fun k ↦ S.mem_toPartialCePresentation_domain (d.args k)
  relEval _ := S.toPartialCePresentation.relEval
  relEval_recursiveIn := S.toPartialCePresentation.relEval_recursiveIn.comp ComputableIn.snd
  relEval_correct := fun _ d _ ↦
    S.toPartialCePresentation.relEval_correct d
      fun k ↦ S.mem_toPartialCePresentation_domain (d.args k)
  generates := fun _ _ ↦ exists_canonicalEnum?_eq_some_iff

@[simp] theorem canonicalAge_structureAt (i : ℕ) : S.canonicalAge.structureAt i = S.inst := rfl

/-- The recorded generators are the enumerated tuples — so `gens (encode t) = t` on the nose. -/
@[simp] theorem canonicalAge_gens (i : ℕ) : S.canonicalAge.gens i = allTupleFor i := rfl

@[simp] theorem canonicalAge_enum? (i m : ℕ) :
    S.canonicalAge.enum? i m = S.canonicalEnum? i m := rfl

/-- Every tuple of `S` is recorded by some member. -/
theorem exists_canonicalAge_gens_eq (t : Tuple ℕ) : ∃ i, S.canonicalAge.gens i = t :=
  allTupleFor_surjective t

/-- **The carrier of a member is the substructure generated by its tuple.** -/
theorem canonicalAge_domainAt (i : ℕ) :
    S.canonicalAge.domainAt i =
      {x | ∃ T : L.Term (Fin (allTupleFor i).length),
        x = @Term.realize L ℕ S.inst _ (Tuple.view (allTupleFor i)) T} :=
  Set.ext fun _ ↦ exists_canonicalEnum?_eq_some_iff

/-! ### Lemma 2.6

> Let `D` be a computable structure. Then `K_D` has CJEP and CHP.

Both selectors are **total and computable** — no search and no partiality — because the index of a
member *is* the code of its recorded tuple. Neither statement uses any transport machinery: they
are proved on the construction. -/

/-- The carrier of a member, as a substructure closure. -/
theorem canonicalAge_domainAt_eq_closure (i : ℕ) :
    S.canonicalAge.domainAt i =
      ↑(@Substructure.closure L ℕ S.inst (Set.range (Tuple.view (allTupleFor i)))) := by
  letI : L.Structure ℕ := S.inst
  ext x
  rw [S.canonicalAge_domainAt, SetLike.mem_coe, mem_closure_range_iff_exists_term]
  exact ⟨fun ⟨T, hT⟩ ↦ ⟨T, hT.symm⟩, fun ⟨T, hT⟩ ↦ ⟨T, hT.symm⟩⟩

/-- **Carriers are monotone in the recorded tuple.** A member whose tuple is drawn from another
member's carrier has its carrier inside that one — the inclusion Lemma 2.6 embeds along. -/
theorem canonicalAge_domainAt_subset {i e : ℕ}
    (h : ∀ x ∈ allTupleFor i, x ∈ S.canonicalAge.domainAt e) :
    S.canonicalAge.domainAt i ⊆ S.canonicalAge.domainAt e := by
  letI : L.Structure ℕ := S.inst
  rw [S.canonicalAge_domainAt_eq_closure, S.canonicalAge_domainAt_eq_closure]
  refine SetLike.coe_subset_coe.2 (Substructure.closure_le.2 ?_)
  rintro _ ⟨k, rfl⟩
  rw [← S.canonicalAge_domainAt_eq_closure]
  exact h _ (List.get_mem _ _)

/-- Every entry of a member's recorded tuple lies in its carrier. -/
theorem mem_canonicalAge_domainAt_of_mem_gens {i x : ℕ} (hx : x ∈ allTupleFor i) :
    x ∈ S.canonicalAge.domainAt i := by
  obtain ⟨k, hk⟩ := List.mem_iff_get.1 hx
  exact hk ▸ S.canonicalAge.gens_mem_domainAt k

/-- **Lemma 2.6, hereditary half.** `K_D` has the computable hereditary property, in the repo's
**strong** form: the located member's recorded generators are the query *on the nose*, because its
index is the query's code. Answering takes no search — CHMM's "look for `k` such that `ā_k = c̄`"
is a total computable function here. -/
theorem canonicalAge_partialCHP : S.canonicalAge.PartialCHP := by
  refine ⟨fun _ s ↦ Part.some (encode s),
    (Computable.encode.comp Computable.snd).computableIn, ?_⟩
  intro e s hs
  have hgens : allTupleFor (encode s) = s := by
    rw [allTupleFor, Denumerable.ofNat_encode]
  exact ⟨encode s, Part.mem_some _, hgens, rfl,
    S.canonicalAge_domainAt_subset (by rw [hgens]; exact hs)⟩

/-- **Lemma 2.6, joint-embedding half.** The apex is the member recording the concatenation of the
two tuples, and both legs are inclusions — again with no search. -/
theorem canonicalAge_partialCJEP : S.canonicalAge.PartialCJEP := by
  refine ⟨fun i j ↦ PartialJointEmbeddingData.ofTriple
      (encode (allTupleFor i ++ allTupleFor j), allTupleFor i, allTupleFor j), ?_, ?_⟩
  · have hcode : ComputableIn O fun p : ℕ × ℕ ↦
        encode (allTupleFor p.1 ++ allTupleFor p.2) :=
      Computable.encode.computableIn.comp
        ((Computable.list_append.computableIn₂).comp
          (allTupleFor_computableIn.comp ComputableIn.fst)
          (allTupleFor_computableIn.comp ComputableIn.snd))
    exact (ComputableIn.comp
      (f := PartialJointEmbeddingData.ofTriple)
      (g := fun p : ℕ × ℕ ↦ (encode (allTupleFor p.1 ++ allTupleFor p.2),
        allTupleFor p.1, allTupleFor p.2))
      PartialJointEmbeddingData.primrec_ofTriple.to_comp.computableIn
      (hcode.pair ((allTupleFor_computableIn.comp ComputableIn.fst).pair
        (allTupleFor_computableIn.comp ComputableIn.snd)))).of_eq fun _ ↦ rfl
  · intro i j
    have hapex : allTupleFor (encode (allTupleFor i ++ allTupleFor j))
        = allTupleFor i ++ allTupleFor j := by
      rw [allTupleFor, Denumerable.ofNat_encode]
    have hleft : S.canonicalAge.domainAt i
        ⊆ S.canonicalAge.domainAt (encode (allTupleFor i ++ allTupleFor j)) :=
      S.canonicalAge_domainAt_subset fun x hx ↦
        S.mem_canonicalAge_domainAt_of_mem_gens
          (by rw [hapex]; exact List.mem_append_left _ hx)
    have hright : S.canonicalAge.domainAt j
        ⊆ S.canonicalAge.domainAt (encode (allTupleFor i ++ allTupleFor j)) :=
      S.canonicalAge_domainAt_subset fun x hx ↦
        S.mem_canonicalAge_domainAt_of_mem_gens
          (by rw [hapex]; exact List.mem_append_right _ hx)
    exact ⟨⟨rfl, PartialAgeIn.memberEmbedding rfl hleft, fun _ ↦ rfl⟩,
      ⟨rfl, PartialAgeIn.memberEmbedding rfl hright, fun _ ↦ rfl⟩⟩


/-- Membership in a member's carrier, stated at the recorded tuple rather than at its code — the
form every concrete computation wants, since it keeps the tuple's length out of a `Fin` under a
code. -/
theorem mem_canonicalAge_domainAt_of_gens {i : ℕ} {t : Tuple ℕ} (hi : allTupleFor i = t) {x : ℕ}
    (h : ∃ T : L.Term (Fin t.length), x = @Term.realize L ℕ S.inst _ (Tuple.view t) T) :
    x ∈ S.canonicalAge.domainAt i := by
  subst hi
  rw [S.canonicalAge_domainAt]
  exact h

end ComputableStructureIn

/-! ### Canonicality

CHMM Definition 2.4's second half, kept **literal**: a representation is a canonical age of `S`
exactly when it is computably isomorphic to `𝕂_𝒟`. No generator-compatibility condition is folded
in — Definition 2.3 does not contain one, and building it in here would formalize a repaired
definition rather than this one, hide the precise failure it repairs, and overstrengthen the uses
(semantic sameness, CJEP) where ordinary representation isomorphism already suffices.

The consequence is that the two effective properties behave differently under canonicality, and
the difference is not cosmetic:

* CJEP transports **unconditionally**;
* CHP does **not**, and the corrected implication carries compatibility on the cover running
  `𝕂_𝒟 → K` as an explicit hypothesis.

Since `𝕂_𝒟` itself has both (Lemma 2.6), the published forward implication of Theorem 2.10 reads
as if invariance were automatic. It is not — even with `𝕂_𝒟` as the source. -/

variable {S : ComputableStructureIn O L}

/-- **CHMM Definition 2.4**, second half: `K` is a canonical representation of the age of `S`. -/
def PartialAgeIn.IsCanonicalAgeOfIn (E : Set (ℕ →. ℕ)) (K : PartialAgeIn O L)
    (S : ComputableStructureIn O L) : Prop :=
  Nonempty (RepresentationIsoIn E S.canonicalAge K)

/-- A canonical age has CJEP, **unconditionally**. Nothing in `PartialCJEPIn`'s contract measures
the target family's recorded generators against anything a transport does not produce. -/
theorem PartialAgeIn.partialCJEPIn_of_canonicalAge {K : PartialAgeIn O L}
    {E : Set (ℕ →. ℕ)} (r : RepresentationIsoIn E S.canonicalAge K) (hOE : O ⊆ E) :
    K.PartialCJEPIn E :=
  PartialAgeIn.PartialCJEPIn.transport r hOE (S.canonicalAge_partialCJEP.mono hOE)

/-- **The corrected forward implication.** A canonical age has CHP *given* that the cover running
`𝕂_𝒟 → K` carries recorded generators to recorded generators.

The hypothesis is on `r.forward` and not on `r.backward`, because the forward cover is the one
running in the same direction as the transport: it determines the returned `K`-member, whose
recorded generators the hereditary contract measures, while the backward cover only carries the
query — a free tuple — into `𝕂_𝒟`.

The hypothesis cannot be dropped: see `CanonicalAgeSeparationAudit`. -/
theorem PartialAgeIn.mappedPartialCHPIn_of_canonicalAge {K : PartialAgeIn O L}
    {E : Set (ℕ →. ℕ)} (r : RepresentationIsoIn E S.canonicalAge K) (hOE : O ⊆ E)
    (hforward : r.forward.GeneratorCompatible) : K.MappedPartialCHPIn E :=
  PartialAgeIn.MappedPartialCHPIn.transport_of_iso r hforward
    (S.canonicalAge_partialCHP.mappedPartialCHP.mono hOE)

end FirstOrder.Language
