/-
Copyright (c) 2026 Cameron Freer. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Cameron Freer
-/
import ComputableModelTheory.ModelTheory.Computable.CanonicalAge
import ComputableModelTheory.Util.AssertAxioms

/-!
# Audit: the canonical representation of an age

Gates on `𝕂_𝒟` over the successor structure — an infinite generated closure, so nothing here can
lean on finite-carrier search — together with the empty-tuple boundary in a language with no
function symbols at all.

The rows worth naming:

* the index really is the tuple code (`gens (encode t) = t`), which is what makes Lemma 2.6's
  selector total rather than a search;
* a member's carrier is genuinely *generated*, not just the recorded tuple: `4` and `5` lie in the
  member recorded by `[3]`;
* the empty tuple is a real member with an **empty** carrier when the language has no constants —
  the case a nonemptiness fallback would silently paper over.
-/

open Encodable Part FirstOrder Language

namespace FirstOrder.Language

section

variable {O : Set (ℕ →. ℕ)}

attribute [local instance] succStructure

/-- The successor structure as a bundled computable structure. -/
noncomputable def succCS : ComputableStructureIn O succLang where
  inst := succStructure
  isComputable := succ_isComputable

/-- **The index is the tuple code.** -/
theorem test_canonicalAge_gens :
    (succCS (O := O)).canonicalAge.gens (encode ([3, 5] : List ℕ)) = [3, 5] := by
  rw [ComputableStructureIn.canonicalAge_gens, allTupleFor_encode]

/-- The recorded generator lies in its member's carrier. -/
theorem test_canonicalAge_mem_gen :
    3 ∈ (succCS (O := O)).canonicalAge.domainAt (encode ([3] : List ℕ)) := by
  exact (succCS (O := O)).mem_canonicalAge_domainAt_of_gens (allTupleFor_encode [3])
    ⟨Term.var ⟨0, by simp⟩, by simp [Tuple.view]⟩

/-- **The carrier is generated, not recorded.** `4` is the successor of the only generator, so it
lies in the member even though the tuple does not mention it. -/
theorem test_canonicalAge_closed_under_succ :
    4 ∈ (succCS (O := O)).canonicalAge.domainAt (encode ([3] : List ℕ)) := by
  exact (succCS (O := O)).mem_canonicalAge_domainAt_of_gens (allTupleFor_encode [3])
    ⟨Term.func SuccFunctions.succ fun _ ↦ Term.var ⟨0, by simp⟩, by simp [Tuple.view]; rfl⟩

/-- And two steps out, so the closure is not a one-step artifact. -/
theorem test_canonicalAge_closed_twice :
    5 ∈ (succCS (O := O)).canonicalAge.domainAt (encode ([3] : List ℕ)) := by
  exact (succCS (O := O)).mem_canonicalAge_domainAt_of_gens (allTupleFor_encode [3])
    ⟨Term.func SuccFunctions.succ fun _ ↦
      Term.func SuccFunctions.succ fun _ ↦ Term.var ⟨0, by simp⟩, by simp [Tuple.view]; rfl⟩

/-- **Lemma 2.6**, both halves, at a fixture whose members are infinite. -/
theorem test_canonicalAge_lemma26 :
    (succCS (O := O)).canonicalAge.PartialCHP ∧ (succCS (O := O)).canonicalAge.PartialCJEP :=
  ⟨ComputableStructureIn.canonicalAge_partialCHP _,
    ComputableStructureIn.canonicalAge_partialCJEP _⟩

/-- The strong hereditary form implies the paper-facing one, so the fixture also witnesses the
form the transport theorems consume. -/
theorem test_canonicalAge_mappedCHP :
    (succCS (O := O)).canonicalAge.MappedPartialCHP :=
  (ComputableStructureIn.canonicalAge_partialCHP _).mappedPartialCHP

end

section

variable {O : Set (ℕ →. ℕ)}

/-- Over a language with no function symbols there are no closed terms. -/
theorem empty_term_isEmpty : IsEmpty (Language.empty.Term (Fin 0)) :=
  ⟨fun T ↦ by
    induction T with
    | var k => exact k.elim0
    | func f _ _ => exact isEmptyElim f⟩

/-- **The empty tuple is a real member with an empty carrier.** In a language with no constants
the substructure generated by no elements is genuinely empty — the case that forces `PartialAgeIn`
to be empty-capable, and the one a nonemptiness fallback would silently paper over. -/
theorem test_canonicalAge_empty_tuple_empty_carrier
    (S : ComputableStructureIn O Language.empty) :
    S.canonicalAge.domainAt (encode ([] : List ℕ)) = ∅ := by
  refine Set.eq_empty_iff_forall_notMem.2 fun x hx ↦ ?_
  rw [ComputableStructureIn.canonicalAge_domainAt] at hx
  obtain ⟨T, -⟩ := hx
  rw [allTupleFor_encode] at T
  exact empty_term_isEmpty.elim T

/-- The empty tuple is nevertheless recorded as a member's generators, not skipped. -/
theorem test_canonicalAge_empty_tuple_recorded (S : ComputableStructureIn O Language.empty) :
    S.canonicalAge.gens (encode ([] : List ℕ)) = [] := by
  rw [ComputableStructureIn.canonicalAge_gens, allTupleFor_encode]

end

end FirstOrder.Language

#assert_standard_axioms FirstOrder.Language.test_canonicalAge_gens
#assert_standard_axioms FirstOrder.Language.test_canonicalAge_mem_gen
#assert_standard_axioms FirstOrder.Language.test_canonicalAge_closed_under_succ
#assert_standard_axioms FirstOrder.Language.test_canonicalAge_closed_twice
#assert_standard_axioms FirstOrder.Language.test_canonicalAge_lemma26
#assert_standard_axioms FirstOrder.Language.test_canonicalAge_mappedCHP
#assert_standard_axioms FirstOrder.Language.test_canonicalAge_empty_tuple_empty_carrier
#assert_standard_axioms FirstOrder.Language.test_canonicalAge_empty_tuple_recorded
