/-
Copyright (c) 2026 Cameron Freer. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Cameron Freer
-/
import ComputableModelTheory.ModelTheory.Computable.CanonicalAge

/-!
# The generated range of a realized embedding

The semantic keystone of the effective back-and-forth (CHMM Proposition 3.2): a realized embedding
of a finitely generated member into a **canonical age** has range exactly the canonical member
generated by its range tuple, so it corestricts to an *equivalence* there.

## Why this is one lemma and not three

Both half-steps of the back-and-forth need it, and so does the base case. Each of the three would
otherwise rebuild "the image of a generated structure is generated by the generator images" in
slightly different form, and the three would drift.

`range_eq_canonicalAge_domainAt` is the load-bearing fact; `toCanonicalRangeEmbedding` and
`toCanonicalRangeEquiv` are thin packaging over it.

## The target must be a canonical age

The statement rests on `gens (encode t) = t`, which is a `𝕂_𝒟` fact (`allTupleFor_encode`) and
nothing a general `PartialAgeIn` supplies: for an arbitrary target family the index
`encode F.rangeTuple` has no reason to denote the member generated by `F.rangeTuple`, and the
corestriction would land somewhere unrelated. The **source** may be any `PartialAgeIn` — it needs
only the `generates` field.

## Nothing here is effective

No computability statement, no oracle inclusion, no `Part.get`, and **no choice of a realizer or
computational witness** — the explicit embedding and its realization witness are all this needs,
which is why it can be stated and proved once and consumed on both sides of the construction. The
one use of classical choice is `Equiv.ofBijective`'s inverse packaging in `toCanonicalRangeEquiv`,
which is why that definition is `noncomputable`; nothing about *which* embedding is chosen depends
on it.
-/

open Encodable FirstOrder Language

namespace FirstOrder.Language

namespace PartialAgeIn

namespace PartialRealizesBetween

variable {O : Set (ℕ →. ℕ)} {L : Language} [L.EffectiveLanguage]
variable {A : PartialAgeIn O L} {S : ComputableStructureIn O L}
variable {F : PotentialEmbeddingData}
variable {f : (A.memberAt F.domIdx).domain ↪[L] (S.canonicalAge.memberAt F.codIdx).domain}

/-- **Terms pass through the embedding to terms over the range tuple.** The one computation the
range equality rests on, isolated: realize a term over the recorded generators, push it through `f`,
and read the underlying natural — the result is that term realized over `F.rangeTuple`, relabelled
along the length equation. -/
theorem realize_map (h : PartialRealizesBetween A S.canonicalAge F f)
    (T : L.Term (Fin (A.gens F.domIdx).length)) :
    ((f (T.realize (A.gensView F.domIdx)) :
        (S.canonicalAge.memberAt F.codIdx).domain) : ℕ)
      = @Term.realize L ℕ S.inst _ (Tuple.view F.rangeTuple) (T.relabel (Fin.cast h.choose)) := by
  letI : L.Structure ℕ := S.inst
  obtain ⟨hlen, hcoord⟩ := h
  rw [← HomClass.realize_term (L := L) f,
    (S.canonicalAge.memberAt F.codIdx).realize_domain_val _ T, Term.realize_relabel]
  refine congrArg (fun v ↦ @Term.realize L ℕ S.inst _ v T) (funext fun k ↦ ?_)
  exact hcoord k

/-- **The range of a realized embedding is the canonical member at its range tuple's code.**

Both inclusions are the same computation read in opposite directions: an element of the source is a
term over the recorded generators, `f` carries terms to terms, and a member of the canonical age is
a term over its own recorded tuple — which at index `encode F.rangeTuple` *is* `F.rangeTuple`. -/
theorem range_eq_canonicalAge_domainAt (h : PartialRealizesBetween A S.canonicalAge F f) :
    Set.range (fun x : (A.memberAt F.domIdx).domain ↦
        ((f x : (S.canonicalAge.memberAt F.codIdx).domain) : ℕ))
      = S.canonicalAge.domainAt (encode F.rangeTuple) := by
  letI : L.Structure ℕ := S.inst
  obtain ⟨hlen, hcoord⟩ := h
  ext y
  constructor
  · rintro ⟨x, rfl⟩
    obtain ⟨T, rfl⟩ := exists_realize_gensView x
    refine S.mem_canonicalAge_domainAt_of_gens (allTupleFor_encode F.rangeTuple) ?_
    exact ⟨T.relabel (Fin.cast hlen), realize_map ⟨hlen, hcoord⟩ T⟩
  · intro hy
    rw [S.canonicalAge_domainAt, allTupleFor_encode] at hy
    obtain ⟨T', hT'⟩ := hy
    refine ⟨(T'.relabel (Fin.cast hlen.symm)).realize (A.gensView F.domIdx), ?_⟩
    show ((f (((T'.relabel (Fin.cast hlen.symm))).realize (A.gensView F.domIdx)) :
      (S.canonicalAge.memberAt F.codIdx).domain) : ℕ) = y
    rw [realize_map ⟨hlen, hcoord⟩, hT', Term.realize_relabel, Term.realize_relabel]
    exact congrArg (fun v ↦ @Term.realize L ℕ S.inst _ v T') (funext fun k ↦ rfl)

/-- **The corestriction**, as an embedding onto the canonical member generated by the range tuple.
Thin packaging: the carrier map is unchanged, so the structure laws are `f`'s. -/
noncomputable def toCanonicalRangeEmbedding (h : PartialRealizesBetween A S.canonicalAge F f) :
    (A.memberAt F.domIdx).domain ↪[L]
      (S.canonicalAge.memberAt (encode F.rangeTuple)).domain where
  toFun x := ⟨((f x : (S.canonicalAge.memberAt F.codIdx).domain) : ℕ), by
    show ((f x : (S.canonicalAge.memberAt F.codIdx).domain) : ℕ)
      ∈ S.canonicalAge.domainAt (encode F.rangeTuple)
    rw [← range_eq_canonicalAge_domainAt h]
    exact ⟨x, rfl⟩⟩
  inj' x y hxy := by
    apply f.injective
    apply Subtype.ext
    exact congrArg (fun z : (S.canonicalAge.memberAt (encode F.rangeTuple)).domain ↦ (z : ℕ)) hxy
  map_fun' {n} g v := Subtype.ext (by
    show ((f (@Structure.funMap L (A.memberAt F.domIdx).domain _ n g v) :
        (S.canonicalAge.memberAt F.codIdx).domain) : ℕ) = _
    rw [HomClass.map_fun (L := L) f g v]
    rfl)
  map_rel' {n} R v := f.map_rel' R v

/-- **The application equation.** The corestriction's underlying natural is exactly `f`'s, so
nothing downstream has to unfold the corestriction. -/
@[simp] theorem toCanonicalRangeEmbedding_coe (h : PartialRealizesBetween A S.canonicalAge F f)
    (x : (A.memberAt F.domIdx).domain) :
    ((toCanonicalRangeEmbedding h x :
        (S.canonicalAge.memberAt (encode F.rangeTuple)).domain) : ℕ)
      = ((f x : (S.canonicalAge.memberAt F.codIdx).domain) : ℕ) :=
  rfl

theorem toCanonicalRangeEmbedding_surjective
    (h : PartialRealizesBetween A S.canonicalAge F f) :
    Function.Surjective (toCanonicalRangeEmbedding h) := by
  intro y
  have hy : (y : ℕ) ∈ S.canonicalAge.domainAt (encode F.rangeTuple) := y.2
  rw [← range_eq_canonicalAge_domainAt h] at hy
  obtain ⟨x, hx⟩ := hy
  exact ⟨x, Subtype.ext hx⟩

/-- **The keystone.** A realized embedding into a canonical age is an *equivalence* onto the member
generated by its range tuple.

Injectivity is the embedding's; surjectivity is the range equality read backwards; the structure
laws are carried over unchanged. -/
noncomputable def toCanonicalRangeEquiv (h : PartialRealizesBetween A S.canonicalAge F f) :
    (A.memberAt F.domIdx).domain ≃[L]
      (S.canonicalAge.memberAt (encode F.rangeTuple)).domain :=
  let g := toCanonicalRangeEmbedding h
  ⟨Equiv.ofBijective g ⟨g.injective, toCanonicalRangeEmbedding_surjective h⟩,
    g.map_fun', g.map_rel'⟩

@[simp] theorem toCanonicalRangeEquiv_coe (h : PartialRealizesBetween A S.canonicalAge F f)
    (x : (A.memberAt F.domIdx).domain) :
    ((toCanonicalRangeEquiv h x :
        (S.canonicalAge.memberAt (encode F.rangeTuple)).domain) : ℕ)
      = ((f x : (S.canonicalAge.memberAt F.codIdx).domain) : ℕ) :=
  rfl

/-- **The corestriction is itself realized**, at the data with the codomain moved to
`encode F.rangeTuple`.

Thin — the length equation is `h`'s and the coordinates are `toCanonicalRangeEquiv_coe` composed
with `h`'s — but the base case and both half-steps of the back-and-forth all need it, and would
otherwise each re-prove it. Proving it here seals the corestriction: consumers never reopen the
range equality. -/
theorem toCanonicalRangeEquiv_realizes (h : PartialRealizesBetween A S.canonicalAge F f) :
    PartialRealizesBetween A S.canonicalAge
      (PotentialEmbeddingData.ofTriple (F.domIdx, encode F.rangeTuple, F.rangeTuple))
      (toCanonicalRangeEquiv h).toEmbedding := by
  obtain ⟨hlen, hcoord⟩ := h
  refine ⟨hlen, fun k ↦ ?_⟩
  show ((toCanonicalRangeEquiv ⟨hlen, hcoord⟩ (A.gensView F.domIdx k) :
    (S.canonicalAge.memberAt (encode F.rangeTuple)).domain) : ℕ) = _
  rw [toCanonicalRangeEquiv_coe]
  exact hcoord k

end PartialRealizesBetween

end PartialAgeIn

end FirstOrder.Language
