/-
Copyright (c) 2026 Cameron Freer. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Cameron Freer
-/
import ComputableModelTheory.ModelTheory.Computable.CanonicalAge
import ComputableModelTheory.Computability.ListPredicates
import ComputableModelTheory.Util.AssertAxioms

/-!
# CHMM Theorem 2.10 (⇒) fails under the literal Definitions 2.3–2.4

CHMM proves the forward direction of Theorem 2.10 in three words — "Lemma 2.6" — which assumes that
the effective properties are invariant under computable isomorphism of representations. CJEP is.
CHP is **not**, and the failure survives even when the *source* is a canonical representation, so
the earlier `CHPSeparationAudit` does not settle this: that fixture's source is not a `𝕂_𝒟`.

The witness lives in the **empty language**, where every bijection is an isomorphism and no
computability is doing any of the work — the failure is entirely about which tuples a
representation *records*.

* `D := (ℕ, ∅)`, so a member of `𝕂_𝒟` is the finite set of entries of its tuple.
* `dupAge` records `(0,0,1,1,…,i-1,i-1)` at member `i`, whose carrier is `{0,…,i-1}`. Legitimate:
  over the empty language the term closure of that tuple is exactly its set of entries.
* The two are computably isomorphic. Forward: rank inside the deduplicated tuple, landing at the
  member of that width. Backward: the domain-restricted identity onto the member recorded by
  `List.range i`.
* `dupAge` fails CHP at the carrier-valid query `s = [0]` in member `1`: every recorded tuple has
  **even** length, so the required `(gens c).length = 1` is unsatisfiable.

The ranking helpers are deliberately audit-local rather than routed through
`CePresentationIn.rankIso`, which assumes a nonempty presentation — while `canonicalAge` contains
the genuinely empty member generated by `[]` — and would leave a further bridge to cross.
Deduplication makes the empty case automatic: `support i = []` gives maps defined nowhere in both
directions.

The conclusion is the last theorem: a representation can be a canonical age of a computable
structure, in the literal sense of Definition 2.4, and still lack CHP. CJEP is gated alongside it,
so the failed conjunct is isolated rather than inferred.
-/

open Encodable Part FirstOrder Language

namespace FirstOrder.Language

section

variable {O : Set (ℕ →. ℕ)}

/-! ### The empty language -/

/-- The empty-language structure on `ℕ` as a bundled computable structure. -/
noncomputable def emptyCS : ComputableStructureIn O Language.empty where
  isComputable := inferInstance

/-- Over a language with no function symbols every term is a variable. -/
private theorem empty_realize_eq_var {n : ℕ} (v : Fin n → ℕ)
    (T : Language.empty.Term (Fin n)) :
    ∃ k, @Term.realize Language.empty ℕ _ _ v T = v k := by
  induction T with
  | var k => exact ⟨k, rfl⟩
  | func f _ _ => exact isEmptyElim f

/-- **A canonical member's carrier is the set of entries of its tuple.** -/
private theorem mem_emptyCanonical_domainAt_iff {i x : ℕ} :
    x ∈ (emptyCS (O := O)).canonicalAge.domainAt i ↔ x ∈ allTupleFor i := by
  rw [ComputableStructureIn.canonicalAge_domainAt]
  constructor
  · rintro ⟨T, rfl⟩
    obtain ⟨k, hk⟩ := empty_realize_eq_var (Tuple.view (allTupleFor i)) T
    have hmem : (allTupleFor i).view k ∈ allTupleFor i := List.get_mem _ _
    rwa [← hk] at hmem
  · intro hx
    obtain ⟨k, hk⟩ := List.mem_iff_get.1 hx
    exact ⟨Term.var k, hk.symm⟩

/-! ### The duplicated-generator family -/

/-- `(0,0,1,1,…,i-1,i-1)`: every element of `{0,…,i-1}` listed twice, so every recorded tuple has
even length while the carrier is unchanged. -/
private def dupGens (i : ℕ) : Tuple ℕ :=
  (List.range i).flatMap fun x ↦ [x, x]

private theorem dupGens_succ (n : ℕ) : dupGens (n + 1) = dupGens n ++ [n, n] := by
  rw [dupGens, dupGens, List.range_succ, List.flatMap_append]
  rfl

private theorem dupGens_length (i : ℕ) : (dupGens i).length = 2 * i := by
  induction i with
  | zero => rfl
  | succ n ih =>
    rw [dupGens_succ, List.length_append, ih]
    rfl

private theorem mem_dupGens_iff {i x : ℕ} : x ∈ dupGens i ↔ x < i := by
  rw [dupGens, List.mem_flatMap]
  constructor
  · rintro ⟨y, hy, hx⟩
    rcases List.mem_cons.1 hx with rfl | hx
    · exact List.mem_range.1 hy
    · rw [List.mem_singleton.1 hx]
      exact List.mem_range.1 hy
  · intro hx
    exact ⟨x, List.mem_range.2 hx, List.mem_cons_self⟩

private theorem dupGens_computableIn : ComputableIn O dupGens :=
  ComputableIn.list_flatMap (Primrec.list_range.to_comp.computableIn)
    ((Computable.list_cons.comp Computable.snd
      (Computable.list_cons.comp Computable.snd
        (Computable.const []))).computableIn.to₂)

/-- Membership in `List.range i` through the enumeration. -/
private theorem exists_range_getElem_iff {i x : ℕ} :
    (∃ m : ℕ, (List.range i)[m]? = Option.some x) ↔ x < i := by
  constructor
  · rintro ⟨m, hm⟩
    obtain ⟨hlt, hval⟩ := List.getElem?_eq_some_iff.1 hm
    rw [← hval]
    exact List.mem_range.1 (List.getElem_mem hlt)
  · intro hx
    refine ⟨x, ?_⟩
    rw [List.getElem?_eq_getElem (by simpa using hx)]
    simp

/-- The duplicated-generator representation: member `i` has carrier `{0,…,i-1}`, recorded as
generated by each of its elements listed twice. -/
noncomputable def dupAge : PartialAgeIn O Language.empty where
  structureAt _ := inferInstance
  enum? i m := (List.range i)[m]?
  enum?_computableIn :=
    (Computable.list_getElem?.comp (Primrec.list_range.to_comp.comp Computable.fst)
      Computable.snd).computableIn
  gens := dupGens
  gens_computableIn := dupGens_computableIn
  funEval _ _ := Part.none
  funEval_recursiveIn := RecursiveIn.none
  funEval_correct := fun _ d _ ↦ isEmptyElim d
  relEval _ _ := Part.none
  relEval_recursiveIn := RecursiveIn.none
  relEval_correct := fun _ d _ ↦ isEmptyElim d
  generates := fun i x ↦ by
    show (∃ m, (List.range i)[m]? = Option.some x) ↔ _
    rw [exists_range_getElem_iff]
    constructor
    · intro hx
      obtain ⟨k, hk⟩ := List.mem_iff_get.1 (mem_dupGens_iff.2 hx)
      exact ⟨Term.var k, hk.symm⟩
    · rintro ⟨T, rfl⟩
      obtain ⟨k, hk⟩ := empty_realize_eq_var (Tuple.view (dupGens i)) T
      rw [hk]
      exact mem_dupGens_iff.1 (List.get_mem _ _)

private theorem mem_dupAge_domainAt_iff {i x : ℕ} :
    x ∈ (dupAge (O := O)).domainAt i ↔ x < i :=
  exists_range_getElem_iff

private theorem mem_dupAge_memberAt_iff {i x : ℕ} :
    x ∈ ((dupAge (O := O)).memberAt i).domain ↔ x < i :=
  exists_range_getElem_iff

/-! ### The forward cover: rank inside the deduplicated tuple

Deduplication is what makes the maps injective, and what makes the empty member automatic:
`support i = []` leaves both maps defined nowhere. -/

private def support (i : ℕ) : List ℕ := (allTupleFor i).dedup

private theorem mem_support_iff {i x : ℕ} : x ∈ support i ↔ x ∈ allTupleFor i :=
  List.mem_dedup

private theorem support_nodup (i : ℕ) : (support i).Nodup := List.nodup_dedup _

/-- Rank, as a partial map: defined exactly on the entries. -/
private def rankFun (i x : ℕ) : Option ℕ :=
  ((support i)[(support i).idxOf x]?).map fun _ ↦ (support i).idxOf x

private theorem rankFun_eq_some_iff {i x k : ℕ} :
    rankFun i x = Option.some k ↔ x ∈ support i ∧ (support i).idxOf x = k := by
  rw [rankFun, Option.map_eq_some_iff]
  constructor
  · rintro ⟨y, hy, rfl⟩
    exact ⟨List.idxOf_lt_length_iff.1 (List.getElem?_eq_some_iff.1 hy).1, rfl⟩
  · rintro ⟨hx, rfl⟩
    exact ⟨x, List.getElem?_idxOf hx, rfl⟩

private theorem rankFun_lt {i x k : ℕ} (h : rankFun i x = Option.some k) :
    k < (support i).length := by
  obtain ⟨hx, rfl⟩ := rankFun_eq_some_iff.1 h
  exact List.idxOf_lt_length_iff.2 hx

private theorem support_computableIn : ComputableIn O support :=
  ComputableIn.list_dedup allTupleFor_computableIn

private theorem rankFun_computableIn : ComputableIn O fun p : ℕ × ℕ ↦ rankFun p.1 p.2 := by
  have hsupp : ComputableIn O fun p : ℕ × ℕ ↦ support p.1 :=
    support_computableIn.comp ComputableIn.fst
  have hidx : ComputableIn O fun p : ℕ × ℕ ↦ (support p.1).idxOf p.2 :=
    ComputableIn.comp (O := O) (α := ℕ × ℕ) (β := ℕ × List ℕ) (σ := ℕ)
      (f := fun q : ℕ × List ℕ ↦ List.idxOf q.1 q.2)
      (g := fun p : ℕ × ℕ ↦ (p.2, support p.1))
      ((Primrec.list_idxOf (α := ℕ)).to_comp.computableIn) (ComputableIn.snd.pair hsupp)
  exact ComputableIn.option_map
    ((Computable.list_getElem?.computableIn₂).comp hsupp hidx)
    (hidx.comp ComputableIn.fst).to₂

/-! ### The two covers -/

/-- The forward cover `𝕂_𝒟 → dupAge`: rank inside the deduplicated tuple, landing at the member of
that width. -/
noncomputable def fwdCover :
    RepresentationCoverIn O (emptyCS (O := O)).canonicalAge (dupAge (O := O)) where
  indexMap i := (support i).length
  indexMap_computableIn :=
    (Computable.list_length.computableIn).comp support_computableIn
  isoAt i :=
    { toFun := fun x ↦ ((rankFun i x : Option ℕ) : Part ℕ)
      invFun := fun k ↦ (((support i)[k]? : Option ℕ) : Part ℕ)
      toFun_recursiveIn :=
        ComputableIn.ofOption
          ((rankFun_computableIn (O := O)).comp ((ComputableIn.const i).pair ComputableIn.id))
      invFun_recursiveIn :=
        ComputableIn.ofOption
          ((Computable.list_getElem?.comp (Computable.const (support i))
            Computable.id).computableIn)
      toFun_dom := fun x ↦ by
        rw [Part.dom_iff_mem, PartialAgeIn.memberAt_domain,
          mem_emptyCanonical_domainAt_iff, ← mem_support_iff]
        constructor
        · rintro ⟨k, hk⟩
          exact (rankFun_eq_some_iff.1 (Part.mem_ofOption.1 hk)).1
        · intro hx
          exact ⟨_, Part.mem_ofOption.2 (rankFun_eq_some_iff.2 ⟨hx, rfl⟩)⟩
      invFun_dom := fun k ↦ by
        rw [Part.dom_iff_mem, mem_dupAge_memberAt_iff]
        constructor
        · rintro ⟨x, hx⟩
          exact (List.getElem?_eq_some_iff.1 (Part.mem_ofOption.1 hx)).1
        · intro hk
          exact ⟨_, Part.mem_ofOption.2 (List.getElem?_eq_getElem hk)⟩
      toFun_mem := fun {_ k} h ↦
        mem_dupAge_memberAt_iff.2 (rankFun_lt (Part.mem_ofOption.1 h))
      invFun_toFun := fun {x k} h ↦ by
        obtain ⟨hx, rfl⟩ := rankFun_eq_some_iff.1 (Part.mem_ofOption.1 h)
        exact Part.mem_ofOption.2 (List.getElem?_idxOf hx)
      toFun_invFun := fun {k x} h ↦ by
        have hget := List.getElem?_eq_some_iff.1 (Part.mem_ofOption.1 h)
        obtain ⟨hk, hval⟩ := hget
        refine Part.mem_ofOption.2 (rankFun_eq_some_iff.2 ⟨hval ▸ List.getElem_mem hk, ?_⟩)
        rw [← hval]
        exact (support_nodup i).idxOf_getElem k hk
      toFun_funMap := fun _ f _ _ _ ↦ isEmptyElim f
      toFun_relMap := fun _ r _ _ _ ↦ isEmptyElim r }
  toFun_uniform :=
    ComputableIn.ofOption (rankFun_computableIn (O := O))
  invFun_uniform := by
    have h : ComputableIn O fun p : ℕ × ℕ ↦ (support p.1)[p.2]? :=
      (Computable.list_getElem?.computableIn₂).comp
        (support_computableIn.comp ComputableIn.fst) ComputableIn.snd
    exact ComputableIn.ofOption h

/-- The backward cover `dupAge → 𝕂_𝒟`: the domain-restricted identity onto the canonical member
recorded by `List.range i`, whose carrier is the same `{0,…,i-1}`. -/
noncomputable def bwdCover :
    RepresentationCoverIn O (dupAge (O := O)) (emptyCS (O := O)).canonicalAge where
  indexMap i := encode (List.range i)
  indexMap_computableIn :=
    (Computable.encode.comp Primrec.list_range.to_comp).computableIn
  isoAt i :=
    { toFun := fun x ↦ (dupAge (O := O)).idFun (i, x)
      invFun := fun y ↦ (dupAge (O := O)).idFun (i, y)
      toFun_recursiveIn :=
        (dupAge (O := O)).idFun_recursiveIn.comp ((ComputableIn.const i).pair ComputableIn.id)
      invFun_recursiveIn :=
        (dupAge (O := O)).idFun_recursiveIn.comp ((ComputableIn.const i).pair ComputableIn.id)
      toFun_dom := fun x ↦ (dupAge (O := O)).idFun_dom i x
      invFun_dom := fun y ↦ by
        rw [(dupAge (O := O)).idFun_dom i y, PartialAgeIn.memberAt_domain,
          mem_emptyCanonical_domainAt_iff, allTupleFor_encode, List.mem_range,
          mem_dupAge_domainAt_iff]
      toFun_mem := fun h ↦ by
        obtain ⟨rfl, hx⟩ := (dupAge (O := O)).mem_idFun.1 h
        rw [PartialAgeIn.memberAt_domain, mem_emptyCanonical_domainAt_iff,
          allTupleFor_encode, List.mem_range]
        exact mem_dupAge_domainAt_iff.1 hx
      invFun_toFun := fun h ↦ by
        obtain ⟨rfl, hx⟩ := (dupAge (O := O)).mem_idFun.1 h
        exact (dupAge (O := O)).mem_idFun.2 ⟨rfl, hx⟩
      toFun_invFun := fun h ↦ by
        obtain ⟨rfl, hx⟩ := (dupAge (O := O)).mem_idFun.1 h
        exact (dupAge (O := O)).mem_idFun.2 ⟨rfl, hx⟩
      toFun_funMap := fun _ f _ _ _ ↦ isEmptyElim f
      toFun_relMap := fun _ r _ _ _ ↦ isEmptyElim r }
  toFun_uniform := (dupAge (O := O)).idFun_recursiveIn.of_eq fun _ ↦ rfl
  invFun_uniform := (dupAge (O := O)).idFun_recursiveIn.of_eq fun _ ↦ rfl

/-- The two covers, as a computable isomorphism of representations. -/
noncomputable def dupIso :
    RepresentationIsoIn O (emptyCS (O := O)).canonicalAge (dupAge (O := O)) where
  forward := fwdCover
  backward := bwdCover

/-! ### The gates -/

/-- **`dupAge` is a canonical age**, in the literal sense of CHMM Definition 2.4. -/
theorem test_dupAge_isCanonicalAge :
    (dupAge (O := O)).IsCanonicalAgeOfIn O (emptyCS (O := O)) :=
  ⟨dupIso⟩

/-- Every recorded tuple has **even** length — the single fact the failure turns on. -/
theorem test_dupAge_gens_even (i : ℕ) : ((dupAge (O := O)).gens i).length = 2 * i :=
  dupGens_length i

/-- The carriers are unchanged by the duplication: member `i` still has carrier `{0,…,i-1}`. -/
theorem test_dupAge_carrier (i x : ℕ) : x ∈ (dupAge (O := O)).domainAt i ↔ x < i :=
  mem_dupAge_domainAt_iff

/-- **The forward cover is not generator compatible**, at the member recorded by `[0]`: the
canonical side records one generator there and `dupAge` records two. Length alone already
separates them, so no computation of the image tuple is needed. -/
theorem test_fwdCover_not_generatorCompatible :
    ¬ (dupIso (O := O)).forward.GeneratorCompatible := by
  intro hcompat
  have h := congrArg List.length (hcompat (encode ([0] : List ℕ)))
  rw [RepresentationCoverIn.sourceGensImage_length,
    ComputableStructureIn.canonicalAge_gens, allTupleFor_encode] at h
  have hsupport : support (encode ([0] : List ℕ)) = [0] := by
    rw [support, allTupleFor_encode]
    rfl
  rw [show (dupIso (O := O)).forward.indexMap (encode ([0] : List ℕ)) = 1 from by
    show (support (encode ([0] : List ℕ))).length = 1
    rw [hsupport]
    rfl] at h
  have h2 : ((dupAge (O := O)).gens 1).length = 2 := by
    show (dupGens 1).length = 2
    rw [dupGens_length]
  rw [h2] at h
  exact absurd h (by decide)

/-- **`dupAge` fails CHP**, at the carrier-valid query `[0]` in member `1`: any answer would need a
recorded tuple of length one, and every recorded tuple has even length. -/
theorem test_dupAge_not_mappedCHP : ¬ (dupAge (O := O)).MappedPartialCHPIn O := by
  rintro ⟨sel, -, hspec⟩
  obtain ⟨c, -, hlen, -⟩ := hspec 1 [0] (by
    intro x hx
    rw [List.mem_singleton.1 hx]
    exact mem_dupAge_domainAt_iff.2 Nat.one_pos)
  rw [test_dupAge_gens_even, List.length_singleton] at hlen
  omega

/-- **CJEP still transports**, so the failed conjunct is isolated rather than inferred: canonicality
delivers one of Theorem 2.10's two conclusions and not the other. -/
theorem test_dupAge_partialCJEP : (dupAge (O := O)).PartialCJEPIn O :=
  PartialAgeIn.partialCJEPIn_of_canonicalAge dupIso (subset_refl O)

/-- **CHMM Theorem 2.10 (⇒) is false under the literal definitions.** A representation can be a
canonical age of a computable structure — computably isomorphic to `𝕂_𝒟`, which is all Definition
2.4 asks — and still lack CHP, even though it does have CJEP.

`𝕂_𝒟` itself has both (Lemma 2.6), so the gap is exactly the unstated invariance step. What repairs
it is generator compatibility on the cover running `𝕂_𝒟 → K`, which this pair violates. -/
theorem test_canonical_age_without_chp :
    ∃ (S : ComputableStructureIn O Language.empty) (K : PartialAgeIn O Language.empty),
      K.IsCanonicalAgeOfIn O S ∧ K.PartialCJEPIn O ∧ ¬ K.MappedPartialCHPIn O :=
  ⟨emptyCS, dupAge, test_dupAge_isCanonicalAge, test_dupAge_partialCJEP,
    test_dupAge_not_mappedCHP⟩

end

end FirstOrder.Language

#assert_standard_axioms FirstOrder.Language.test_dupAge_isCanonicalAge
#assert_standard_axioms FirstOrder.Language.test_dupAge_gens_even
#assert_standard_axioms FirstOrder.Language.test_dupAge_carrier
#assert_standard_axioms FirstOrder.Language.test_fwdCover_not_generatorCompatible
#assert_standard_axioms FirstOrder.Language.test_dupAge_not_mappedCHP
#assert_standard_axioms FirstOrder.Language.test_dupAge_partialCJEP
#assert_standard_axioms FirstOrder.Language.test_canonical_age_without_chp
