/-
Copyright (c) 2026 Cameron Freer. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Cameron Freer
-/
import ComputableModelTheory.ModelTheory.Computable.CanonicalAge

/-!
# Computable homogeneity — CHMM Definition 3.1

> Given a computable structure `D`, and a tuple `d⃗ ∈ D`, we use `D_d⃗` to denote the substructure of
> `D` generated by `d⃗`. We say that `D` is **computably homogeneous** if there exists a computable
> function which, given a tuple `d⃗ ∈ D`, a map `g : d⃗ → D`, and `x ∈ D`, returns a tuple `γ⃗ ∈ D`
> and `y ∈ D_γ⃗` such that:
>
> * `D_d⃗ ⊆ D_γ⃗`; and
> * if `c⃗ = ⟨g(d⃗), x⟩`, and `g` extends to an embedding `D_d⃗ ↪ D`, then the function
>   `h : c⃗ → D_γ⃗` with `h(x) = y` and `h(g(z)) = z` for `z ∈ d⃗` extends to an embedding
>   `D_c⃗ ↪ D_γ⃗`.
>
> Even if `g` does not extend to an embedding, we still require that `D_d⃗ ⊆ D_γ⃗`.

The members `D_t` are `S.canonicalAge.memberAt (encode t)`, already built: `𝕂_𝒟` indexes by tuple
code, so `gens (encode t) = t` definitionally, and `structureAt i = S.inst` for every `i`, which is
what makes `D_d⃗ ⊆ D_γ⃗` a containment of **carriers** rather than a choice of embedding.

## `h` inverts `g`

The extension map sends the `k`-th entry of `g(d⃗)` back to the `k`-th entry of `d⃗`, and `x` to `y`.
So its range tuple is `domainTuple ++ [imageOfNewPoint]` — *not* `imageTuple ++ [imageOfNewPoint]`.
Both readings typecheck, since both are maps between the same two members; `ComputablyHomogeneousAudit`
separates them with a **non-involutive** fixture, because on a transposition `h(g(z)) = z` and
`h(z) = g(z)` describe the same map and the wrong reading would pass.

## Totality is decided by the query shape

`select` is **total**, with a `ComputableIn E` proof and no `Part`. What forces partiality elsewhere
is a query that carries a tuple whose membership in a c.e. carrier cannot be decided — that is why
`PartialCHP` and `MappedPartialCHPIn` are `Part`-valued. `PartialCJEPIn` is total over equally c.e.
carriers because a pair of indices needs no validation, and the effective witness interfaces
(`HPWitnessIn`, `JEPWitnessIn`, `CAPWitnessIn`) are total for the same reason. Here `S` has carrier
literally `ℕ`, so every tuple and every generator map is legitimate input and nothing needs
validating.

## Two unconditional clauses, one conditional

`extends_domain` and `imageOfNewPoint_mem` hold on **every** query, including malformed ones; only
`extension_actual` is guarded. This is `CAPWitnessIn`'s split, and the two unconditional clauses
have different provenance in the paper: containment because the definition reiterates it in its own
sentence after the bullets, membership of `y` because it belongs to the return specification stated
before them.

Malformed queries — unequal `domainTuple`/`imageTuple` lengths, or an `imageTuple` no embedding
realizes — are **valid input**. No guard is needed to arrange that: `PartialRealizes` carries the
length equation as a field, so a length mismatch makes the antecedent of `extension_actual`
unsatisfiable and the clause vacuous.

The interface needs no `O ⊆ E`: the selector's effectivity is the only thing mentioning `E`, and all
three guarantees are semantic. Constructors may need the inclusion, as the existing witness
interfaces do.
-/

open Encodable FirstOrder Language

namespace FirstOrder.Language

variable {O E : Set (ℕ →. ℕ)} {L : Language} [L.EffectiveLanguage]

/-! ### Query and answer data

Packed records, not curried arguments: a curried selector's codomain is a function type, which
carries no `Primcodable`, so `ComputableIn` could not be stated at all. -/

/-- The query of Definition 3.1: the generated substructure's tuple, the images of its generators,
and the new point to be matched. The map `g` **is** `imageTuple` — a map on generators carries no
more information than its tuple of images. -/
structure HomogeneityQueryData where
  /-- The paper's `d⃗`. -/
  domainTuple : Tuple ℕ
  /-- The paper's `g(d⃗)`. -/
  imageTuple : Tuple ℕ
  /-- The paper's `x`. -/
  newPoint : ℕ

@[ext]
theorem HomogeneityQueryData.ext {q r : HomogeneityQueryData}
    (hd : q.domainTuple = r.domainTuple) (hi : q.imageTuple = r.imageTuple)
    (hn : q.newPoint = r.newPoint) : q = r := by
  cases q; cases r; cases hd; cases hi; cases hn; rfl

/-- The answer of Definition 3.1: the extended tuple and the image of the new point. -/
structure HomogeneityAnswerData where
  /-- The paper's `γ⃗`. -/
  extensionTuple : Tuple ℕ
  /-- The paper's `y`. -/
  imageOfNewPoint : ℕ

@[ext]
theorem HomogeneityAnswerData.ext {a b : HomogeneityAnswerData}
    (he : a.extensionTuple = b.extensionTuple) (hi : a.imageOfNewPoint = b.imageOfNewPoint) :
    a = b := by
  cases a; cases b; cases he; cases hi; rfl

/-- The code-level packaging of a query. -/
private def hqEquiv : HomogeneityQueryData ≃ Tuple ℕ × Tuple ℕ × ℕ where
  toFun q := (q.domainTuple, q.imageTuple, q.newPoint)
  invFun p := ⟨p.1, p.2.1, p.2.2⟩
  left_inv _ := rfl
  right_inv _ := rfl

instance : Primcodable HomogeneityQueryData :=
  Primcodable.ofEquiv _ hqEquiv

/-- The code-level packaging of an answer. -/
private def haEquiv : HomogeneityAnswerData ≃ Tuple ℕ × ℕ where
  toFun a := (a.extensionTuple, a.imageOfNewPoint)
  invFun p := ⟨p.1, p.2⟩
  left_inv _ := rfl
  right_inv _ := rfl

instance : Primcodable HomogeneityAnswerData :=
  Primcodable.ofEquiv _ haEquiv

theorem HomogeneityQueryData.primrec_domainTuple : Primrec HomogeneityQueryData.domainTuple :=
  (Primrec.fst.comp (Primrec.of_equiv (e := hqEquiv))).of_eq fun _ ↦ rfl

theorem HomogeneityQueryData.primrec_imageTuple : Primrec HomogeneityQueryData.imageTuple :=
  ((Primrec.fst.comp Primrec.snd).comp (Primrec.of_equiv (e := hqEquiv))).of_eq fun _ ↦ rfl

theorem HomogeneityQueryData.primrec_newPoint : Primrec HomogeneityQueryData.newPoint :=
  ((Primrec.snd.comp Primrec.snd).comp (Primrec.of_equiv (e := hqEquiv))).of_eq fun _ ↦ rfl

theorem HomogeneityAnswerData.primrec_extensionTuple :
    Primrec HomogeneityAnswerData.extensionTuple :=
  (Primrec.fst.comp (Primrec.of_equiv (e := haEquiv))).of_eq fun _ ↦ rfl

theorem HomogeneityAnswerData.primrec_imageOfNewPoint :
    Primrec HomogeneityAnswerData.imageOfNewPoint :=
  (Primrec.snd.comp (Primrec.of_equiv (e := haEquiv))).of_eq fun _ ↦ rfl

/-- Queries are built from their three fields. -/
theorem primrec_homogeneityQueryData :
    Primrec fun p : Tuple ℕ × Tuple ℕ × ℕ ↦ (⟨p.1, p.2.1, p.2.2⟩ : HomogeneityQueryData) :=
  (Primrec.of_equiv_symm (e := hqEquiv)).of_eq fun _ ↦ rfl

/-- Answers are built from their two fields. -/
theorem primrec_homogeneityAnswerData :
    Primrec fun p : Tuple ℕ × ℕ ↦ (⟨p.1, p.2⟩ : HomogeneityAnswerData) :=
  (Primrec.of_equiv_symm (e := haEquiv)).of_eq fun _ ↦ rfl

/-! ### The two derived maps

Methods on the query: `originalMap` needs the query alone, `extensionMap` needs the answer too. -/

namespace HomogeneityQueryData

variable (q : HomogeneityQueryData)

/-- The map `g` as potential embedding data: `D_domainTuple → D_imageTuple`, sending the recorded
generators to `imageTuple`.

Taking the codomain to be `D_imageTuple` rather than all of `S` is not a strengthening: an embedding
extending `g` has image generated by `g(d⃗)`, which is exactly `D_imageTuple`. -/
def originalMap : PotentialEmbeddingData :=
  PotentialEmbeddingData.ofTriple (encode q.domainTuple, encode q.imageTuple, q.imageTuple)

/-- The map `h` as potential embedding data:
`D_(imageTuple ++ [newPoint]) → D_extensionTuple`, sending the `k`-th image back to the `k`-th
generator and `newPoint` to `imageOfNewPoint`.

**The range tuple is `domainTuple ++ [imageOfNewPoint]`.** `h` inverts `g`: the paper's clauses are
`h(g(z)) = z` and `h(x) = y`. -/
def extensionMap (a : HomogeneityAnswerData) : PotentialEmbeddingData :=
  PotentialEmbeddingData.ofTriple
    (encode (q.imageTuple ++ [q.newPoint]), encode a.extensionTuple,
      q.domainTuple ++ [a.imageOfNewPoint])

@[simp] theorem originalMap_domIdx : q.originalMap.domIdx = encode q.domainTuple := rfl
@[simp] theorem originalMap_codIdx : q.originalMap.codIdx = encode q.imageTuple := rfl
@[simp] theorem originalMap_rangeTuple : q.originalMap.rangeTuple = q.imageTuple := rfl

@[simp] theorem extensionMap_domIdx (a : HomogeneityAnswerData) :
    (q.extensionMap a).domIdx = encode (q.imageTuple ++ [q.newPoint]) := rfl

@[simp] theorem extensionMap_codIdx (a : HomogeneityAnswerData) :
    (q.extensionMap a).codIdx = encode a.extensionTuple := rfl

/-- **The direction, isolated.** The extension map's range tuple starts with `domainTuple`, so `h`
carries images back to generators. A reading in which it started with `imageTuple` would typecheck;
this equation is what distinguishes them. -/
@[simp] theorem extensionMap_rangeTuple (a : HomogeneityAnswerData) :
    (q.extensionMap a).rangeTuple = q.domainTuple ++ [a.imageOfNewPoint] := rfl

end HomogeneityQueryData

/-! ### The interface -/

/-- **CHMM Definition 3.1.** A total computable selector answering every homogeneity query, with two
unconditional guarantees and one conditional.

No `O ⊆ E`: the selector's effectivity is the only thing mentioning `E`, and all three guarantees
are semantic. -/
structure ComputablyHomogeneousIn (E : Set (ℕ →. ℕ)) (S : ComputableStructureIn O L) where
  /-- The selector: total, on packed query data. -/
  select : HomogeneityQueryData → HomogeneityAnswerData
  /-- It is computable in the selector oracle. -/
  select_computableIn : ComputableIn E select
  /-- **Unconditional**: the queried substructure sits inside the answer's. The paper reiterates
  this clause in its own sentence, precisely so that it survives a malformed `g`. -/
  extends_domain : ∀ q : HomogeneityQueryData,
    S.canonicalAge.domainAt (encode q.domainTuple)
      ⊆ S.canonicalAge.domainAt (encode (select q).extensionTuple)
  /-- **Unconditional**: the answer's point lies in the answer's substructure. This comes from the
  return specification rather than from a bullet, so it too is unguarded. -/
  imageOfNewPoint_mem : ∀ q : HomogeneityQueryData,
    (select q).imageOfNewPoint ∈ S.canonicalAge.domainAt (encode (select q).extensionTuple)
  /-- **Conditional**: when `g` is actual, so is the one-point extension running back along it. -/
  extension_actual : ∀ q : HomogeneityQueryData,
    S.canonicalAge.PartialIsEmbedding q.originalMap →
      S.canonicalAge.PartialIsEmbedding (q.extensionMap (select q))

namespace ComputablyHomogeneousIn

variable {S : ComputableStructureIn O L} (H : ComputablyHomogeneousIn E S)

/-- The answer's tuple, named. -/
def extensionTuple (q : HomogeneityQueryData) : Tuple ℕ :=
  (H.select q).extensionTuple

/-- The answer's point, named. -/
def imageOfNewPoint (q : HomogeneityQueryData) : ℕ :=
  (H.select q).imageOfNewPoint

theorem extensionTuple_computableIn : ComputableIn E H.extensionTuple :=
  HomogeneityAnswerData.primrec_extensionTuple.to_comp.computableIn.comp H.select_computableIn

theorem imageOfNewPoint_computableIn : ComputableIn E H.imageOfNewPoint :=
  HomogeneityAnswerData.primrec_imageOfNewPoint.to_comp.computableIn.comp H.select_computableIn

/-- Every generator of the query's tuple survives into the answer's substructure — the containment
clause, read at a point. -/
theorem mem_extension_of_mem_domainTuple {q : HomogeneityQueryData} {x : ℕ}
    (hx : x ∈ q.domainTuple) :
    x ∈ S.canonicalAge.domainAt (encode (H.select q).extensionTuple) := by
  refine H.extends_domain q ?_
  exact S.mem_canonicalAge_domainAt_of_mem_gens (by rwa [allTupleFor_encode])

end ComputablyHomogeneousIn

end FirstOrder.Language
