/-
Copyright (c) 2026 Cameron Freer. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Cameron Freer
-/
import ComputableModelTheory.ModelTheory.Computable.FraisseCriterion
import ComputableModelTheory.ModelTheory.Computable.RunChain
import ComputableModelTheory.ModelTheory.Computable.PartialTheorem28
import ComputableModelTheory.ModelTheory.Computable.PartialCJEP

/-!
# The bridge from one-point extensions to the full extension property

The scheduled construction fires only requirements whose target member is generated by **one more
generator** than the source (`StaticAdmissible`'s `(n+1)` clause), so a firing gives a one-point
extension. Lemma 3.8 (`FraisseChainData`) consumes the **full** extension property: every
`f : A ↪ D_r` and `g : A ↪ B` extend to some `h : B ↪ D_s`, `s ≥ r`, with the square closing in the
limit. This module is the bridge, in two named layers.

## Layer 2: the finite-prefix induction, abstractly

`OnePointExtension K Z` packages what a chain must provide: a member index at each stage, an
isomorphism of each stage with its member, and the one-point extension property with its square in
the limit. `OnePointExtension.extension` then proves the full extension property by induction over
the prefixes of the target's generators, with the commuting square carried throughout:

* the successive substructures of `B` generated by `g(gens A) ++ (gens B).take t` are **represented
  by members through the mapped hereditary property** (`HasMappedHP`, the semantic content of
  `MappedPartialCHPIn`), with recorded generator lists of exactly the prefix's length —
  **repetitions kept**, so consecutive widths differ by one and the `(n+1)` guard holds with no
  carrier growth required or claimed;
* at prefix zero, the source is identified with the member representing `g(gens A)` by the
  equivalence onto that image — not by an assumed identity of members;
* each step factors the previous representative through the next, applies the one-point property
  to the transported chain map and that factor, and composes squares;
* at the last prefix the representative contains `gens B`, so it is the whole of `B`.

Together with the stage isomorphisms this yields `FraisseChainData K Z`.

## Layer 1: the one-point extension property of the run

For the run of `ChainRun`/`RunChain`, the one-point property is extracted from firing:
`exists_firesAt_of_admissible` schedules the requirement, `exists_square_of_fire` returns the
selector's diagram with its conditional CAP soundness (the right leg actual, the square commuting
in the members), and `mem_transportTo_iff_transportPart` identifies the recorded transport with the
chain's, so `LimitIn.stageEmbedding_transport` and the step law move the member square into the
limit. `runOnePointExtension` packages this as an `OnePointExtension`, and step 3 applies the
criterion.

Everything here is semantic and classical; the effective half is a separate tranche.
-/

open Encodable FirstOrder Language Substructure

namespace FirstOrder.Language

variable {O E : Set (ℕ →. ℕ)} {L : Language}

/-! ### Member-embedding tools -/

section EmbeddingTools

variable {M N P : Type*} [L.Structure M] [L.Structure N] [L.Structure P]

/-- An embedding whose range lies in the range of another factors through it. -/
theorem exists_embedding_factor (e : M ↪[L] N) (ι : P ↪[L] N) (h : ∀ x, e x ∈ ι.toHom.range) :
    ∃ ψ : M ↪[L] P, ∀ x, ι (ψ x) = e x := by
  refine ⟨ι.equivRange.symm.toEmbedding.comp (e.codRestrict ι.toHom.range h), fun x ↦ ?_⟩
  have := ι.equivRange_apply (ι.equivRange.symm (e.codRestrict ι.toHom.range h x))
  rw [Equiv.apply_symm_apply] at this
  exact this.symm

/-- A surjective embedding is an isomorphism. -/
noncomputable def Embedding.equivOfSurjective (e : M ↪[L] N) (h : Function.Surjective e) :
    M ≃[L] N :=
  ⟨_root_.Equiv.ofBijective e ⟨e.injective, h⟩, e.map_fun', e.map_rel'⟩

@[simp] theorem Embedding.equivOfSurjective_apply (e : M ↪[L] N) (h : Function.Surjective e)
    (x : M) : e.equivOfSurjective h x = e x :=
  rfl

theorem Embedding.equivOfSurjective_symm_apply (e : M ↪[L] N) (h : Function.Surjective e)
    (x : M) : (e.equivOfSurjective h).symm (e x) = x :=
  (e.equivOfSurjective h).symm_apply_apply x

end EmbeddingTools

section Transport

universe u

variable {M N : Type u} [L.Structure M] [L.Structure N]

/-- Ultrahomogeneity transports along an isomorphism. -/
theorem IsUltrahomogeneous.of_equiv (e : M ≃[L] N) (h : L.IsUltrahomogeneous M) :
    L.IsUltrahomogeneous N := by
  intro S hS f
  obtain ⟨g, hg⟩ := h (S.map e.symm.toEmbedding.toHom) (hS.map _)
    (e.symm.toEmbedding.comp (f.comp (e.symm.toEmbedding.substructureEquivMap S).symm.toEmbedding))
  refine ⟨(e.comp g).comp e.symm, ?_⟩
  ext x
  have hx := DFunLike.congr_fun hg (e.symm.toEmbedding.substructureEquivMap S x)
  simp only [Embedding.comp_apply, Equiv.coe_toEmbedding, Equiv.symm_apply_apply,
    coe_subtype, Embedding.substructureEquivMap_apply] at hx
  change f x = e (g (e.symm x))
  rw [← hx, Equiv.apply_symm_apply]

/-- Being a Fraïssé limit transports along an isomorphism. -/
theorem IsFraisseLimit.of_equiv [Countable (Σ l, L.Functions l)] [Countable M] [Countable N]
    {C : Set (CategoryTheory.Bundled L.Structure)} (e : M ≃[L] N) (h : L.IsFraisseLimit C M) :
    L.IsFraisseLimit C N :=
  ⟨h.ultrahomogeneous.of_equiv e, e.age_eq_age.symm.trans h.age⟩

end Transport

/-- A presentation whose carrier is all of `ℕ` is its own ambient structure. -/
noncomputable def CePresentationIn.domainEquivUniv [L.EffectiveLanguage] (Q : CePresentationIn O L)
    (hQ : Q.domain = Set.univ) : @Language.Equiv L Q.domain ℕ Q.subtypeStr Q.str :=
  letI : L.Structure ℕ := Q.str
  { toFun := fun x ↦ x.1
    invFun := fun x ↦ ⟨x, hQ ▸ Set.mem_univ x⟩
    left_inv := fun _ ↦ rfl
    right_inv := fun _ ↦ rfl
    map_fun' := fun _ _ ↦ rfl
    map_rel' := fun _ _ ↦ Iff.rfl }

variable [L.EffectiveLanguage]

/-- The limit, as all of `ℕ` under an infinitude certificate: the rank recoding onto the ω
structure's carrier. -/
noncomputable def CeStructureChainIn.LimitIn.omegaEquiv {D : CeStructureChainIn E L}
    (Z : D.LimitIn) (cert : Z.presentation.InfinitudeCertificate) :
    @Language.Equiv L Z.presentation.domain ℕ _ (Z.omegaStructure cert).inst :=
  letI : L.Structure ℕ := Z.presentation.rankStr
  (Z.presentation.rankPresentation.domainEquivUniv
    (by rw [CePresentationIn.rankPresentation_domain, Z.presentation.range_posRank_eq_univ cert])).comp
      Z.presentation.rankIso.toEquiv

namespace PartialAgeIn

variable {K : PartialAgeIn O L}

/-- An embedding out of a member whose recorded generators land in the range of another embedding
factors through it on the whole member: the range is closed under term realization. -/
theorem memberEmbedding_mem_range_of_gens {c : ℕ} {M N : Type*} [L.Structure M] [L.Structure N]
    (e : (K.memberAt c).domain ↪[L] M) (ι : N ↪[L] M)
    (h : ∀ k, e (K.gensView c k) ∈ ι.toHom.range) : ∀ z, e z ∈ ι.toHom.range := by
  intro z
  obtain ⟨T, rfl⟩ := exists_realize_gensView z
  rw [← HomClass.realize_term (g := e)]
  exact Term.realize_mem T _ h

/-- An embedding into a member whose recorded generators it reaches is surjective. -/
theorem memberEmbedding_surjective_of_gens {a c : ℕ}
    (φ : (K.memberAt a).domain ↪[L] (K.memberAt c).domain)
    (h : ∀ k, K.gensView c k ∈ φ.toHom.range) : Function.Surjective φ := fun z ↦
  memberEmbedding_mem_range_of_gens (Embedding.refl L _) φ h z

/-! ### The mapped hereditary property, semantically -/

variable (K) in
/-- **The mapped hereditary property**, semantically: every finite list of elements of a member is
the recorded generator list of some member, coordinatewise — with the list's own length, repetitions
included. This is the semantic content of `MappedPartialCHPIn`, without the selector. -/
def HasMappedHP : Prop :=
  ∀ (e : ℕ) (s : List ℕ), (∀ x ∈ s, x ∈ K.domainAt e) →
    ∃ c : ℕ, ∃ hlen : (K.gens c).length = s.length,
      ∃ F : (K.memberAt c).domain ↪[L] (K.memberAt e).domain,
        ∀ k : Fin (K.gens c).length,
          ((F (K.gensView c k) : (K.memberAt e).domain) : ℕ) = s.get (Fin.cast hlen k)

/-- The selector form supplies the semantic one. -/
theorem MappedPartialCHPIn.hasMappedHP (h : MappedPartialCHPIn E K) : K.HasMappedHP := by
  obtain ⟨sel, -, hsel⟩ := h
  intro e s hs
  obtain ⟨c, -, hlen, F, hF⟩ := hsel e s hs
  exact ⟨c, hlen, F, hF⟩

/-- **What a representative gives, listwise**: its generators' images lie in the list, and every
entry of the list is an image. -/
theorem HasMappedHP.exists_represent (hHP : K.HasMappedHP) {e : ℕ} {s : List ℕ}
    (hs : ∀ x ∈ s, x ∈ K.domainAt e) :
    ∃ (c : ℕ) (F : (K.memberAt c).domain ↪[L] (K.memberAt e).domain),
      (K.gens c).length = s.length ∧
        (∀ k, ((F (K.gensView c k) : (K.memberAt e).domain) : ℕ) ∈ s) ∧
          ∀ y ∈ s, ∃ z, ((F z : (K.memberAt e).domain) : ℕ) = y := by
  obtain ⟨c, hlen, F, hF⟩ := hHP e s hs
  refine ⟨c, F, hlen, fun k ↦ by rw [hF k]; exact List.get_mem _ _, fun y hy ↦ ?_⟩
  obtain ⟨k, rfl⟩ := List.mem_iff_get.1 hy
  exact ⟨K.gensView c (Fin.cast hlen.symm k), hF _⟩

/-! ### Layer 2: from one-point extensions to the full extension property -/

/-- **The one-point extension data of a chain over `K`**: a member at each stage, an isomorphism
of each stage with its member, and the one-point extension property — for `f : A ↪ A_{idx r}` and
`g : A ↪ B` with `B` recorded on one more generator than `A`, a later stage and `h : B ↪ A_{idx s}`
whose square closes in the limit. -/
structure OnePointExtension (K : PartialAgeIn O L) {D : CeStructureChainIn E L}
    (Z : D.LimitIn) where
  /-- The member at each stage. -/
  idx : ℕ → ℕ
  /-- Each stage is its member. -/
  equiv : ∀ n, (K.memberAt (idx n)).domain ≃[L] (D.stageAt n).domain
  /-- The one-point extension property, with its square in the limit. -/
  one_point : ∀ (r a b : ℕ) (f : (K.memberAt a).domain ↪[L] (K.memberAt (idx r)).domain)
    (g : (K.memberAt a).domain ↪[L] (K.memberAt b).domain),
    (K.gens b).length = (K.gens a).length + 1 →
      ∃ s, r ≤ s ∧ ∃ h : (K.memberAt b).domain ↪[L] (K.memberAt (idx s)).domain,
        ∀ x, Z.stageEmbedding s (equiv s (h (g x))) = Z.stageEmbedding r (equiv r (f x))

namespace OnePointExtension

variable {D : CeStructureChainIn E L} {Z : D.LimitIn} (P : OnePointExtension K Z)

include P in
/-- Stage membership, as the criterion states it. -/
theorem stage_iso (r : ℕ) :
    ∃ i, Nonempty ((D.stageAt r).domain ≃[L] (K.memberAt i).domain) :=
  ⟨P.idx r, ⟨(P.equiv r).symm⟩⟩

/-! #### The prefix tuples -/

variable (K) in
/-- The `t`-th prefix tuple of the extension `g : A ↪ B`: the images of `A`'s generators, followed
by the first `t` generators of `B`. Repetitions are kept. -/
noncomputable def prefixTuple {a b : ℕ} (g : (K.memberAt a).domain ↪[L] (K.memberAt b).domain) (t : ℕ) :
    List ℕ :=
  (List.ofFn fun k ↦ ((g (K.gensView a k) : (K.memberAt b).domain) : ℕ)) ++ (K.gens b).take t

variable {a b : ℕ} (g : (K.memberAt a).domain ↪[L] (K.memberAt b).domain)

theorem prefixTuple_mem_domainAt (t : ℕ) : ∀ x ∈ prefixTuple K g t, x ∈ K.domainAt b := by
  intro x hx
  rcases List.mem_append.1 hx with hx | hx
  · obtain ⟨k, rfl⟩ := List.mem_ofFn.1 hx
    exact (g (K.gensView a k)).2
  · exact K.mem_domainAt_of_mem_gens (List.mem_of_mem_take hx)

theorem prefixTuple_length {t : ℕ} (ht : t ≤ (K.gens b).length) :
    (prefixTuple K g t).length = (K.gens a).length + t := by
  rw [prefixTuple, List.length_append, List.length_ofFn, List.length_take, Nat.min_eq_left ht]

theorem mem_prefixTuple_succ {t x : ℕ} (hx : x ∈ prefixTuple K g t) :
    x ∈ prefixTuple K g (t + 1) := by
  rcases List.mem_append.1 hx with hx | hx
  · exact List.mem_append_left _ hx
  · refine List.mem_append_right _ ?_
    rw [List.take_add_one]
    exact List.mem_append_left _ hx

theorem image_gens_mem_prefixTuple (t : ℕ) (k : Fin (K.gens a).length) :
    ((g (K.gensView a k) : (K.memberAt b).domain) : ℕ) ∈ prefixTuple K g t :=
  List.mem_append_left _ (List.mem_ofFn.2 ⟨k, rfl⟩)

theorem gens_mem_prefixTuple {t : ℕ} (ht : (K.gens b).length ≤ t) (k : Fin (K.gens b).length) :
    (K.gens b).get k ∈ prefixTuple K g t := by
  rw [prefixTuple, List.take_of_length_le ht]
  exact List.mem_append_right _ (List.get_mem _ _)

theorem mem_prefixTuple_zero {x : ℕ} (hx : x ∈ prefixTuple K g 0) :
    ∃ k, ((g (K.gensView a k) : (K.memberAt b).domain) : ℕ) = x := by
  rw [prefixTuple, List.take_zero, List.append_nil] at hx
  exact List.mem_ofFn.1 hx

/-! #### The induction invariant -/

variable {r : ℕ} (f : (K.memberAt a).domain ↪[L] (K.memberAt (P.idx r)).domain)

/-- **The invariant at prefix `t`**: a member `c` representing the `t`-th prefix tuple through
`e : A_c ↪ B`, the source factored through it by `φ`, and an embedding `h : A_c ↪ A_{idx s}` at a
stage `s ≥ r` whose square with `f` closes in the limit. -/
def PrefixState (t : ℕ) : Prop :=
  ∃ (c s : ℕ) (e : (K.memberAt c).domain ↪[L] (K.memberAt b).domain)
    (φ : (K.memberAt a).domain ↪[L] (K.memberAt c).domain)
    (h : (K.memberAt c).domain ↪[L] (K.memberAt (P.idx s)).domain),
    r ≤ s ∧ (K.gens c).length = (prefixTuple K g t).length ∧
      (∀ k, ((e (K.gensView c k) : (K.memberAt b).domain) : ℕ) ∈ prefixTuple K g t) ∧
        (∀ y ∈ prefixTuple K g t, ∃ z, ((e z : (K.memberAt b).domain) : ℕ) = y) ∧
          (∀ x, e (φ x) = g x) ∧
            ∀ x, Z.stageEmbedding s (P.equiv s (h (φ x))) = Z.stageEmbedding r (P.equiv r (f x))

/-- **Prefix zero**: the representative of `g(gens A)` is identified with `A` by the equivalence
onto that image; the chain map is `f` itself at stage `r`. -/
theorem prefixState_zero (hHP : K.HasMappedHP) : P.PrefixState g f 0 := by
  obtain ⟨c, e, hlen, hin, hout⟩ :=
    hHP.exists_represent (prefixTuple_mem_domainAt (K := K) g 0)
  -- `g` factors through `e`
  obtain ⟨φ, hφ⟩ := exists_embedding_factor g e
    (memberEmbedding_mem_range_of_gens g e fun k ↦ by
      obtain ⟨z, hz⟩ := hout _ (image_gens_mem_prefixTuple g 0 k)
      exact ⟨z, Subtype.ext hz⟩)
  -- and `φ` is onto, since `e`'s generators are images of `g`
  have hsurj : Function.Surjective φ :=
    memberEmbedding_surjective_of_gens φ fun k ↦ by
      obtain ⟨k', hk'⟩ := mem_prefixTuple_zero g (hin k)
      refine ⟨K.gensView a k', e.injective (Subtype.ext ?_)⟩
      change ((e (φ (K.gensView a k')) : (K.memberAt b).domain) : ℕ) = _
      rw [hφ]
      exact hk'
  refine ⟨c, r, e, φ, f.comp (φ.equivOfSurjective hsurj).symm.toEmbedding, le_rfl, hlen, hin, hout,
    hφ, fun x ↦ ?_⟩
  change Z.stageEmbedding r (P.equiv r (f ((φ.equivOfSurjective hsurj).symm (φ x)))) = _
  rw [Embedding.equivOfSurjective_symm_apply]

/-- **The step**: represent the next prefix, factor the current representative through it, fire
the one-point property on the transported chain map and that factor, and compose the squares. -/
theorem prefixState_succ (hHP : K.HasMappedHP) {t : ℕ} (ht : t < (K.gens b).length)
    (hS : P.PrefixState g f t) : P.PrefixState g f (t + 1) := by
  obtain ⟨c, s, e, φ, h, hrs, hlen, hin, hout, hφ, hsq⟩ := hS
  obtain ⟨c', e', hlen', hin', hout'⟩ :=
    hHP.exists_represent (prefixTuple_mem_domainAt (K := K) g (t + 1))
  -- `e` factors through `e'`
  obtain ⟨ψ, hψ⟩ := exists_embedding_factor e e'
    (memberEmbedding_mem_range_of_gens e e' fun k ↦ by
      obtain ⟨z, hz⟩ := hout' _ (mem_prefixTuple_succ g (hin k))
      exact ⟨z, Subtype.ext hz⟩)
  -- the widths differ by one
  have hw : (K.gens c').length = (K.gens c).length + 1 := by
    rw [hlen', hlen, prefixTuple_length g ht, prefixTuple_length g ht.le]
    omega
  obtain ⟨s', hss', h', hsq'⟩ := P.one_point s c c' h ψ hw
  refine ⟨c', s', e', ψ.comp φ, h', hrs.trans hss', hlen', hin', hout', fun x ↦ ?_, fun x ↦ ?_⟩
  · change e' (ψ (φ x)) = g x
    rw [hψ, hφ]
  · change Z.stageEmbedding s' (P.equiv s' (h' (ψ (φ x)))) = _
    rw [hsq', hsq]

theorem prefixState (hHP : K.HasMappedHP) :
    ∀ t, t ≤ (K.gens b).length → P.PrefixState g f t := by
  intro t
  induction t with
  | zero => exact fun _ ↦ P.prefixState_zero g f hHP
  | succ t ih => exact fun ht ↦ P.prefixState_succ g f hHP ht (ih (Nat.le_of_succ_le ht))

include P in
/-- **The full extension property**, in the form the criterion consumes: at the last prefix the
representative reaches all of `B`'s generators, so it is `B` itself. -/
theorem extension (hHP : K.HasMappedHP) (r i j : ℕ)
    (f : (K.memberAt i).domain ↪[L] (D.stageAt r).domain)
    (g : (K.memberAt i).domain ↪[L] (K.memberAt j).domain) :
    ∃ (s : ℕ) (h : (K.memberAt j).domain ↪[L] (D.stageAt s).domain),
      r ≤ s ∧ ∀ a, Z.stageEmbedding s (h (g a)) = Z.stageEmbedding r (f a) := by
  obtain ⟨c, s, e, φ, h, hrs, -, -, hout, hφ, hsq⟩ :=
    P.prefixState g ((P.equiv r).symm.toEmbedding.comp f) hHP (K.gens j).length le_rfl
  have hsurj : Function.Surjective e :=
    memberEmbedding_surjective_of_gens e fun k ↦ by
      obtain ⟨z, hz⟩ := hout _ (gens_mem_prefixTuple g le_rfl k)
      exact ⟨z, Subtype.ext hz⟩
  refine ⟨s, (P.equiv s).toEmbedding.comp (h.comp (e.equivOfSurjective hsurj).symm.toEmbedding),
    hrs, fun x ↦ ?_⟩
  have hx : (e.equivOfSurjective hsurj).symm (g x) = φ x := by
    rw [← hφ]
    exact Embedding.equivOfSurjective_symm_apply e hsurj (φ x)
  change Z.stageEmbedding s (P.equiv s (h ((e.equivOfSurjective hsurj).symm (g x)))) = _
  rw [hx, hsq]
  exact congrArg (Z.stageEmbedding r) ((P.equiv r).apply_symm_apply (f x))

include P in
/-- **The chain hypotheses of Lemma 3.8**, from one-point extension data and the mapped
hereditary property. -/
theorem toFraisseChainData (hHP : K.HasMappedHP) :
    CeStructureChainIn.LimitIn.FraisseChainData K Z :=
  ⟨P.stage_iso, P.extension hHP⟩

end OnePointExtension

/-! ### Semantic HP and JEP from the selector properties -/

/-- Every member is generated by its recorded generators. -/
theorem closure_range_gensView (c : ℕ) :
    closure L (Set.range (K.gensView c)) = (⊤ : L.Substructure (K.memberAt c).domain) :=
  eq_top_iff.2 fun z _ ↦ by
    obtain ⟨T, rfl⟩ := exists_realize_gensView z
    exact Term.realize_mem T _ fun k ↦ subset_closure ⟨k, rfl⟩

/-- **The mapped hereditary property gives the semantic one**: the closure of a tuple is the range
of the representative's embedding. -/
theorem HasMappedHP.hasHP (hHP : K.HasMappedHP) : K.HasHP := by
  intro i n t
  obtain ⟨c, F, -, hin, hout⟩ := hHP.exists_represent (e := i)
    (s := List.ofFn fun k ↦ ((t k : (K.memberAt i).domain) : ℕ)) fun x hx ↦ by
      obtain ⟨k, rfl⟩ := List.mem_ofFn.1 hx
      exact (t k).2
  have hrange : F.toHom.range = closure L (Set.range t) := by
    refine le_antisymm ?_ (closure_le.2 ?_)
    · rw [Hom.range_eq_map, ← closure_range_gensView c, embedding_map_closure_range]
      refine closure_le.2 ?_
      rintro _ ⟨k, rfl⟩
      obtain ⟨k', hk'⟩ := List.mem_ofFn.1 (hin k)
      exact subset_closure ⟨k', Subtype.ext hk'⟩
    · rintro _ ⟨k, rfl⟩
      obtain ⟨z, hz⟩ := hout _ (List.mem_ofFn.2 ⟨k, rfl⟩)
      exact ⟨z, Subtype.ext hz⟩
  exact ⟨c, ⟨((equivOfEq hrange).comp F.equivRange).symm⟩⟩

/-- **The joint embedding selector gives semantic JEP.** -/
theorem PartialCJEPIn.hasJEP (h : PartialCJEPIn E K) : K.HasJEP := by
  obtain ⟨sel, -, hsel⟩ := h
  intro i j
  obtain ⟨⟨-, Fi, -⟩, ⟨-, Fj, -⟩⟩ := hsel i j
  exact ⟨(sel i j).apexIdx, ⟨Fi⟩, ⟨Fj⟩⟩

/-! ### Stages are members -/

namespace EmbeddingChainData

variable (C : K.EmbeddingChainData) (h0 : (K.domainAt (C.d 0)).Nonempty) (hOE : O ⊆ E)
  (hd : ComputableIn E C.d) (hstep : ComputableIn E C.step)

/-- **Each assembled stage is its member**: totalizing moved neither the carrier nor the
structure. -/
noncomputable def stageEquiv (n : ℕ) :
    (K.memberAt (C.d n)).domain ≃[L] ((C.toChain h0 hOE hd hstep).stageAt n).domain where
  toFun x := ⟨x.1, (Set.ext_iff.1 (C.stage_domain h0 hOE n) x.1).2 x.2⟩
  invFun y := ⟨y.1, (Set.ext_iff.1 (C.stage_domain h0 hOE n) y.1).1 y.2⟩
  left_inv _ := rfl
  right_inv _ := rfl
  map_fun' _ _ := rfl
  map_rel' _ _ := Iff.rfl

@[simp] theorem stageEquiv_coe (n : ℕ) (x : (K.memberAt (C.d n)).domain) :
    ((C.stageEquiv h0 hOE hd hstep n x : ((C.toChain h0 hOE hd hstep).stageAt n).domain) : ℕ) =
      x :=
  rfl

@[simp] theorem stageEquiv_symm_coe (n : ℕ) (y : ((C.toChain h0 hOE hd hstep).stageAt n).domain) :
    (((C.stageEquiv h0 hOE hd hstep n).symm y : (K.memberAt (C.d n)).domain) : ℕ) = y :=
  rfl

end EmbeddingChainData

/-! ### Layer 1: the one-point extension property of the run -/

section Run

variable (K) (W : PartialCAPWitness E K) (i : ℕ) (hOE : O ⊆ E) (h0 : (K.domainAt i).Nonempty)

/-- Each stage of the run's chain is the member the run recorded there. -/
noncomputable def runStageEquiv (n : ℕ) :
    (K.memberAt (memberIdx K W i n)).domain ≃[L] ((runChain K W i hOE h0).stageAt n).domain :=
  (runChainData K W i).stageEquiv _ hOE _ _ n

variable {K W i}

/-- The history read at a reached stage is the run's member index there. -/
theorem dHist_run_eq {r s : ℕ} (hrs : r ≤ s) : (run K W i s).dHist r = memberIdx K W i r := by
  rw [RunState.dHist, List.getD_eq_getElem?_getD, history_agrees s r hrs]
  rfl

theorem chainMap_run_eq {s : ℕ} {q : RequirementData} (hq : q.chainStage ≤ s) :
    q.chainMap (run K W i s).dHist = q.chainMap (memberIdx K W i) := by
  unfold RequirementData.chainMap
  rw [dHist_run_eq hq]

/-- **A firing in the run, with its square.** If the coded maps of a requirement are actual, then at
the stage where its encoding fires the transported chain map composes with the requirement's map
into a span the selector amalgamates: its right leg is actual, the square commutes in the members,
and the run's next step is the diagram's left leg. -/
theorem exists_square_of_firesAt {q : RequirementData} {s : ℕ}
    (hfire : (schedule K W i).FiresAt (encode q) s)
    (hf : K.PartialIsEmbedding (q.chainMap (memberIdx K W i)))
    (hg : K.PartialIsEmbedding q.targetMap) :
    q.chainStage ≤ s ∧
      ∃ δ ∈ K.transportPart (run K W i s).stages q.chainStage s,
        δ.domIdx = memberIdx K W i q.chainStage ∧ δ.codIdx = memberIdx K W i s ∧
          K.PartialIsEmbedding δ ∧
          ∃ F ∈ K.compPart δ (q.chainMap (memberIdx K W i)), ∃ D : AmalgamationDiagramData,
            K.PartialIsEmbedding D.rightToApex ∧
              K.PartialCommutes (PotentialSpanData.ofPair (F, q.targetMap)) D ∧
                runStep K W i s = D.leftToApex := by
  have hp := firesAt_iff_pick.1 hfire
  obtain ⟨q', hq', hr, -, -, -⟩ := exists_decode_of_pick hp
  rw [RequirementData.decode_encode] at hq'
  obtain rfl := Option.some.inj hq'
  have hf' : K.PartialIsEmbedding (q.chainMap (run K W i s).dHist) := by
    rw [chainMap_run_eq hr]; exact hf
  obtain ⟨δ, hδ, F, hF, D, -, -, hright, hcomm, hmem⟩ :=
    exists_square_of_fire (W := W) (run_runInvariant s) hp (RequirementData.decode_encode q) hf' hg
  obtain ⟨δ', hδ', hdom, hcod, hemb⟩ :=
    (run_runInvariant (K := K) (W := W) (i := i) s).exists_transport hr
  obtain rfl := Part.mem_unique hδ hδ'
  have hS : run K W i (s + 1) = (run K W i s).capExtension (encode q) D :=
    Part.mem_unique (run_succ_mem s) hmem
  rw [chainMap_run_eq hr] at hF
  refine ⟨hr, δ, hδ, by rw [hdom, dHist_run_eq hr], hcod, hemb, F, hF, D, hright, hcomm, ?_⟩
  refine runStep_eq (rec := ⟨D.leftToApex.codIdx, D.leftToApex⟩) ?_
  rw [hS, RunState.stages_capExtension, ← run_stages_length (K := K) (W := W) (i := i) s]
  exact List.getElem?_concat_length

/-- An indexed realizer computes the application, at its named source index. -/
theorem PartialRealizesAt.mem_applyPotentialPart {F : PotentialEmbeddingData} {d a : ℕ}
    {f : (K.memberAt d).domain ↪[L] (K.memberAt a).domain} (hf : K.PartialRealizesAt F d a f)
    {x : ℕ} (hx : x ∈ (K.memberAt d).domain) :
    ((f ⟨x, hx⟩ : (K.memberAt a).domain) : ℕ) ∈ K.applyPotentialPart F x := by
  obtain ⟨rfl, rfl, h⟩ := hf
  exact K.applyPotentialPart_mem_realizer h hx

variable (Z : (runChain K W i hOE h0).LimitIn)

/-- **Transport identification, in the limit**: a realizer of the recorded transport from stage `r`
to stage `s` is the chain's transport there. -/
theorem stageEmbedding_transportPart {r s : ℕ} (hrs : r ≤ s) {δ : PotentialEmbeddingData}
    (hδ : δ ∈ K.transportPart (run K W i s).stages r s)
    {δr : (K.memberAt (memberIdx K W i r)).domain ↪[L] (K.memberAt (memberIdx K W i s)).domain}
    (hδr : K.PartialRealizesAt δ (memberIdx K W i r) (memberIdx K W i s) δr)
    (x : (K.memberAt (memberIdx K W i r)).domain) :
    Z.stageEmbedding r (runStageEquiv K W i hOE h0 r x) =
      Z.stageEmbedding s (runStageEquiv K W i hOE h0 s (δr x)) := by
  obtain ⟨_, hEq⟩ := Z.stageEmbedding_transport hrs (runStageEquiv K W i hOE h0 r x).2
    ((mem_transportTo_iff_transportPart hOE h0 hrs hδ x.2).2 (hδr.mem_applyPotentialPart x.2))
  exact hEq

/-- **The step, in the limit**: a realizer of the run's recorded step is the chain's step. -/
theorem stageEmbedding_runStep {s : ℕ} {Lp : PotentialEmbeddingData} (hL : runStep K W i s = Lp)
    {lr : (K.memberAt (memberIdx K W i s)).domain ↪[L]
      (K.memberAt (memberIdx K W i (s + 1))).domain}
    (hlr : K.PartialRealizesAt Lp (memberIdx K W i s) (memberIdx K W i (s + 1)) lr)
    (x : (K.memberAt (memberIdx K W i s)).domain) :
    Z.stageEmbedding s (runStageEquiv K W i hOE h0 s x) =
      Z.stageEmbedding (s + 1) (runStageEquiv K W i hOE h0 (s + 1) (lr x)) := by
  obtain ⟨_, hEq⟩ := Z.stageEmbedding_step (runStageEquiv K W i hOE h0 s x).2
    (y := ((lr x : (K.memberAt (memberIdx K W i (s + 1))).domain) : ℕ)) (by
      change _ ∈ K.applyPotentialPart (runStep K W i s) x.1
      rw [hL]
      exact hlr.mem_applyPotentialPart x.2)
  exact hEq

/-- The requirement coding `f : A_a ↪ A_{d r}` and `g : A_a ↪ A_b`: the images of `A_a`'s recorded
generators under each. -/
noncomputable def requirementOf {a b : ℕ} (r : ℕ)
    (f : (K.memberAt a).domain ↪[L] (K.memberAt (memberIdx K W i r)).domain)
    (g : (K.memberAt a).domain ↪[L] (K.memberAt b).domain) : RequirementData :=
  ⟨a, r, b, List.ofFn fun k ↦ ((f (K.gensView a k) : (K.memberAt (memberIdx K W i r)).domain) : ℕ),
    List.ofFn fun k ↦ ((g (K.gensView a k) : (K.memberAt b).domain) : ℕ)⟩

/-- A realizer's range tuple lands in its codomain member. -/
theorem PartialRealizes.carrierValid {F : PotentialEmbeddingData}
    {f : (K.memberAt F.domIdx).domain ↪[L] (K.memberAt F.codIdx).domain}
    (hf : K.PartialRealizes F f) : K.CarrierValid F := by
  obtain ⟨hlen, hcoord⟩ := hf
  intro x hx
  obtain ⟨k, rfl⟩ := List.mem_iff_get.1 hx
  rw [show F.rangeTuple.get k =
      ((f (K.gensView F.domIdx (Fin.cast hlen.symm k)) : (K.memberAt F.codIdx).domain) : ℕ) from
    (hcoord (Fin.cast hlen.symm k)).symm]
  exact (f _).2

/-- **The one-point extension property of the run.** For `f : A ↪ A_{d r}` and `g : A ↪ B` with
`B` recorded on one more generator than `A`, the coded requirement is admissible, so it fires at
some stage `s ≥ r`; the selector's diagram gives `h := ` its right leg into the member at `s + 1`,
and the member square becomes a limit square through transport identification and the step law. -/
theorem exists_one_point_extension {r a b : ℕ}
    (f : (K.memberAt a).domain ↪[L] (K.memberAt (memberIdx K W i r)).domain)
    (g : (K.memberAt a).domain ↪[L] (K.memberAt b).domain)
    (hw : (K.gens b).length = (K.gens a).length + 1) :
    ∃ s, r ≤ s ∧ ∃ h : (K.memberAt b).domain ↪[L] (K.memberAt (memberIdx K W i s)).domain,
      ∀ x, Z.stageEmbedding s (runStageEquiv K W i hOE h0 s (h (g x))) =
        Z.stageEmbedding r (runStageEquiv K W i hOE h0 r (f x)) := by
  have hf : K.PartialRealizes ((requirementOf r f g).chainMap (memberIdx K W i)) f :=
    ⟨List.length_ofFn.symm, fun k ↦ by
      show _ = (List.ofFn fun k ↦ ((f (K.gensView a k) : _) : ℕ)).get (Fin.cast _ k)
      rw [List.get_ofFn]
      rfl⟩
  have hg : K.PartialRealizes (requirementOf r f g).targetMap g :=
    ⟨List.length_ofFn.symm, fun k ↦ by
      show _ = (List.ofFn fun k ↦ ((g (K.gensView a k) : _) : ℕ)).get (Fin.cast _ k)
      rw [List.get_ofFn]
      rfl⟩
  have hadm : K.Admissible (memberIdx K W i) (requirementOf r f g) :=
    ⟨⟨List.length_ofFn, List.length_ofFn, hw⟩, hf.carrierValid, hg.carrierValid⟩
  obtain ⟨s, hfire⟩ := exists_firesAt_of_admissible (K := K) (W := W) (i := i) hadm
  obtain ⟨hrs, δ, hδ, hδdom, hδcod, ⟨δr₀, hδr₀⟩, F, hF, D, hright, hcomm, hstep⟩ :=
    exists_square_of_firesAt hfire ⟨f, hf⟩ ⟨g, hg⟩
  have hrs' : r ≤ s := hrs
  have hδ' : δ ∈ K.transportPart (run K W i s).stages r s := hδ
  obtain ⟨δr, hδr⟩ : ∃ δr : (K.memberAt (memberIdx K W i r)).domain ↪[L]
      (K.memberAt (memberIdx K W i s)).domain,
      K.PartialRealizesAt δ (memberIdx K W i r) (memberIdx K W i s) δr :=
    ⟨_, hδr₀.realizesAt_of_eq hδdom hδcod⟩
  -- the square, at named indices
  obtain ⟨d, m₁, m₂, apex, fl, fr, gl, gr, hfl, hfr, hgl, hgr, hsq⟩ := hcomm
  rw [PotentialSpanData.ofPair_left] at hfl
  rw [PotentialSpanData.ofPair_right] at hfr
  obtain ⟨v, hv, rfl⟩ := (K.mem_compPart_iff).1 hF
  obtain rfl : a = d := hfl.1
  obtain rfl : memberIdx K W i s = m₁ := hδcod.symm.trans hfl.2.1
  obtain rfl : b = m₂ := hfr.2.1
  obtain rfl : memberIdx K W i (s + 1) = apex := by rw [← hgl.2.1, ← hstep, runStep_codIdx]
  -- the legs are the composite and `g`
  have hfr' : fr = g := hfr.unique ⟨rfl, rfl, hg⟩
  have hfl' : fl = δr.comp f := by
    refine hfl.unique ⟨rfl, hδcod, List.length_ofFn.symm.trans hv.length_eq, fun k ↦ ?_⟩
    have hlen₁ : ((requirementOf r f g).chainMap (memberIdx K W i)).rangeTuple.length =
        (K.gens a).length :=
      List.length_ofFn
    have hk : k.1 < ((requirementOf r f g).chainMap (memberIdx K W i)).rangeTuple.length :=
      lt_of_lt_of_eq k.2 hlen₁.symm
    have h₁ := (List.forall₂_iff_get.1 hv).2 k.1 hk (by rw [← hv.length_eq]; exact hk)
    have h₂ : ((requirementOf r f g).chainMap (memberIdx K W i)).rangeTuple.get ⟨k.1, hk⟩ =
        ((f (K.gensView a k) : (K.memberAt (memberIdx K W i r)).domain) : ℕ) :=
      List.get_ofFn _ _
    rw [h₂] at h₁
    exact Part.mem_unique (hδr.mem_applyPotentialPart (f (K.gensView a k)).2) h₁
  have hsq' : ∀ x, gl (δr (f x)) = gr (g x) := fun x ↦ by
    have := DFunLike.congr_fun hsq x
    rw [hfl', hfr'] at this
    exact this
  refine ⟨s + 1, hrs'.trans (Nat.le_succ s), gr, fun x ↦ ?_⟩
  rw [← hsq' x, ← stageEmbedding_runStep hOE h0 Z hstep hgl (δr (f x)),
    ← stageEmbedding_transportPart hOE h0 Z hrs' hδ' hδr (f x)]

/-- **The run's one-point extension data.** -/
noncomputable def runOnePointExtension : K.OnePointExtension Z where
  idx := memberIdx K W i
  equiv := runStageEquiv K W i hOE h0
  one_point := fun _ _ _ f g hw ↦ exists_one_point_extension hOE h0 Z f g hw

/-! ### Step 3: Lemma 3.8 applied to the run -/

/-- **The chain hypotheses of Lemma 3.8 hold for the run**, under the mapped hereditary
property. -/
theorem runFraisseChainData (hHP : K.HasMappedHP) :
    CeStructureChainIn.LimitIn.FraisseChainData K Z :=
  (runOnePointExtension hOE h0 Z).toFraisseChainData hHP

/-- **Theorem 3.9, semantic half**: the Level-1 limit of the run is a Fraïssé limit of the
represented class, given the mapped hereditary property and semantic joint embedding. -/
theorem run_isFraisseLimit (hHP : K.HasMappedHP) (hJ : K.HasJEP) :
    L.IsFraisseLimit K.classSet Z.presentation.domain :=
  (runFraisseChainData hOE h0 Z hHP).isFraisseLimit hHP.hasHP hJ

/-- **The ω corollary**: under an infinitude certificate, the ω structure of the run's limit is a
Fraïssé limit of the represented class. -/
theorem omegaStructure_isFraisseLimit (hHP : K.HasMappedHP) (hJ : K.HasJEP)
    (cert : Z.presentation.InfinitudeCertificate) :
    letI : L.Structure ℕ := (Z.omegaStructure cert).inst
    L.IsFraisseLimit K.classSet ℕ :=
  letI : L.Structure ℕ := (Z.omegaStructure cert).inst
  (run_isFraisseLimit hOE h0 Z hHP hJ).of_equiv (Z.omegaEquiv cert)

end Run

end PartialAgeIn

end FirstOrder.Language
