/-
Copyright (c) 2026 Cameron Freer. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Cameron Freer
-/
import ComputableModelTheory.ModelTheory.Computable.CanonicalAge
import ComputableModelTheory.ModelTheory.Computable.RepresentationIso

/-!
# The generated-image isomorphism, and the cover onto `𝕂_𝒟` it assembles

The shared constructor behind both covers of CHMM Theorem 2.10(⇐):

> a uniformly computable embedding of a representation's members into `S` induces a
> `PartialCeIsoIn` onto the canonical-age member indexed by the **code of the generator-image
> tuple** — and, assembled, a `RepresentationCoverIn` into `𝕂_𝒟` that is generator-compatible.

**Why the target index is forced.** A member is generated by its recorded tuple, so an embedding's
range is the substructure generated by the image of that tuple — nothing else. `𝕂_𝒟`'s member at
`encode t` is the substructure generated by `t`, on the nose (`allTupleFor_encode`). So the target
index is not a choice: it is `encode` of the image tuple, and `range_embedding` is the theorem that
says the two carriers coincide. Generator compatibility then falls out definitionally, which is the
point of routing both covers through here rather than proving compatibility twice.

**The two halves of the isomorphism are asymmetric.** The forward map is the supplied program. The
backward map is a search: run the member's enumeration, push each value forward, and stop when it
matches. That search is an *honest* unbounded search rather than a dovetailing — every test halts,
because the enumeration is total `Option`-valued and the program halts on everything the
enumeration produces. Only its success is in question, and `range_embedding` is exactly what
decides it.

**Input shape: both sides of the map, as in Lemma 2.9.** The semantic embedding carries injectivity
and the structure laws (so none is re-proved here); the program carries effectivity; and
`map_apply_mem` ties them. `map_dom` is an **iff**, not one-way halting, because
`PartialCeIsoIn.toFun_dom` is an iff — a producer that only knows its map halts on the carrier does
not have enough to build an isomorphism.

The oracle boundary stays visible: the *isomorphisms* need no `O ⊆ E`, since they only run the
supplied program. Reading recorded generators and the enumeration is what touches presentation
data, so the index map's computability and the backward search's do need it.
-/

open Encodable Part FirstOrder Language

namespace FirstOrder.Language

variable {O E : Set (ℕ →. ℕ)} {L : Language} [L.EffectiveLanguage]

/-- **Both sides of a uniform embedding of a representation into a computable structure.** The
semantic embeddings supply injectivity and the structure laws; the programs supply effectivity;
`map_apply_mem` is the only statement relating them. The same shape Lemma 2.9's `LimitIn` carries,
which is why the ω-limit's stage embeddings assemble into one directly. -/
structure UniformEmbeddingIntoIn (E : Set (ℕ →. ℕ)) (A : PartialAgeIn O L)
    (S : ComputableStructureIn O L) where
  /-- The semantic embedding of each member into `S`. -/
  embedding : ∀ i, @Language.Embedding L (A.memberAt i).domain ℕ _ S.inst
  /-- Its program. -/
  map : ℕ → ℕ →. ℕ
  /-- Uniformly partial recursive in the index. Not implied by per-index proofs. -/
  map_uniform : RecursiveIn E fun p : ℕ × ℕ ↦ map p.1 p.2
  /-- **Exact** domain, since `PartialCeIsoIn.toFun_dom` is an iff. -/
  map_dom : ∀ i x, (map i x).Dom ↔ x ∈ A.domainAt i
  /-- The two sides agree. -/
  map_apply_mem : ∀ (i : ℕ) (x : (A.memberAt i).domain), embedding i x ∈ map i (x : ℕ)

namespace UniformEmbeddingIntoIn

variable {A : PartialAgeIn O L} {S : ComputableStructureIn O L}
variable (G : UniformEmbeddingIntoIn E A S)

/-! ### Reading the program through the embedding -/

theorem mem_domainAt_of_mem_map {i x y : ℕ} (hy : y ∈ G.map i x) : x ∈ A.domainAt i :=
  (G.map_dom i x).1 (Part.dom_iff_mem.2 ⟨y, hy⟩)

/-- Every value of the program is the embedding's value — single-valuedness of `Part` plus the
bridge. Every fact below reads the program only through this. -/
theorem eq_embedding {i x y : ℕ} (hy : y ∈ G.map i x) :
    y = G.embedding i ⟨x, G.mem_domainAt_of_mem_map hy⟩ :=
  Part.mem_unique hy (G.map_apply_mem i ⟨x, G.mem_domainAt_of_mem_map hy⟩)

theorem map_injOn {i x₁ x₂ y : ℕ} (h₁ : y ∈ G.map i x₁) (h₂ : y ∈ G.map i x₂) : x₁ = x₂ := by
  letI : L.Structure ℕ := S.inst
  exact congrArg Subtype.val
    ((G.embedding i).injective ((G.eq_embedding h₁).symm.trans (G.eq_embedding h₂)))

theorem map_recursiveIn (i : ℕ) : RecursiveIn E (G.map i) :=
  G.map_uniform.comp ((ComputableIn.const i).pair ComputableIn.id)

/-! ### The generator-image tuple -/

/-- The image of a member's recorded generators, as a program. -/
noncomputable def imageTuplePart (i : ℕ) : Part (Tuple ℕ) :=
  listMapPart (G.map i) (A.gens i)

/-- It always halts: every generator lies in the member's carrier. -/
theorem imageTuplePart_dom (i : ℕ) : (G.imageTuplePart i).Dom :=
  listMapPart_dom_iff.2 fun _ hx ↦ (G.map_dom i _).2 (A.mem_domainAt_of_mem_gens hx)

/-- **The generator-image tuple** — the code of which is the target index. -/
noncomputable def imageTuple (i : ℕ) : Tuple ℕ :=
  (G.imageTuplePart i).get (G.imageTuplePart_dom i)

/-- **The `Forall₂` specification.** The only place the traversal is opened. -/
theorem forall₂_imageTuple (i : ℕ) :
    List.Forall₂ (fun x y ↦ y ∈ G.map i x) (A.gens i) (G.imageTuple i) :=
  mem_listMapPart_iff.1 (Part.get_mem _)

theorem imageTuple_length (i : ℕ) : (G.imageTuple i).length = (A.gens i).length :=
  (G.forall₂_imageTuple i).length_eq.symm

/-- **The entries of the image tuple, indexed by the source generators.** The one place `Forall₂`,
`List.get` and a `Fin` cast meet; everything downstream uses the range form below. -/
theorem imageTuple_get (i : ℕ) (k : Fin (A.gens i).length) :
    (G.imageTuple i).get (Fin.cast (G.imageTuple_length i).symm k)
      = G.embedding i (A.gensView i k) := by
  obtain ⟨-, hget⟩ := List.forall₂_iff_get.1 (G.forall₂_imageTuple i)
  exact G.eq_embedding (hget k.1 k.2 (by rw [G.imageTuple_length]; exact k.2))

/-- **The range form**, which is what the closure computation needs: the image tuple's entries are
exactly the embedded generators. Length-agnostic, so no cast survives past this point. -/
theorem range_view_imageTuple (i : ℕ) :
    Set.range (Tuple.view (G.imageTuple i))
      = Set.range fun k ↦ (G.embedding i (A.gensView i k) : ℕ) := by
  ext y
  simp only [Set.mem_range]
  constructor
  · rintro ⟨k, rfl⟩
    have hk : (k : ℕ) < (A.gens i).length := by
      have hlt := k.2
      exact Nat.lt_of_lt_of_le hlt (le_of_eq (G.imageTuple_length i))
    exact ⟨⟨k, hk⟩, (G.imageTuple_get i ⟨k, hk⟩).symm⟩
  · rintro ⟨k, rfl⟩
    exact ⟨Fin.cast (G.imageTuple_length i).symm k, G.imageTuple_get i k⟩

/-! ### The range of the embedding is the canonical member

The theorem that forces the target index. Both inclusions are the same computation read in
opposite directions: a carrier element is a term over the generators, and the embedding carries
terms to terms. -/

/-- **The range of the embedding is exactly the carrier of the canonical member at the image
tuple's code.** This is what makes the target index forced rather than chosen, and it is what
decides the backward search's success. -/
theorem range_embedding (i : ℕ) :
    Set.range (fun x : (A.memberAt i).domain ↦ (G.embedding i x : ℕ))
      = S.canonicalAge.domainAt (encode (G.imageTuple i)) := by
  letI : L.Structure ℕ := S.inst
  rw [S.canonicalAge_domainAt_eq_closure, allTupleFor_encode, G.range_view_imageTuple]
  ext y
  rw [SetLike.mem_coe, mem_closure_range_iff_exists_term]
  constructor
  · rintro ⟨x, rfl⟩
    obtain ⟨T, rfl⟩ := PartialAgeIn.exists_realize_gensView x
    exact ⟨T, HomClass.realize_term (G.embedding i) (t := T) (v := A.gensView i)⟩
  · rintro ⟨T, rfl⟩
    exact ⟨T.realize (A.gensView i),
      (HomClass.realize_term (G.embedding i) (t := T) (v := A.gensView i)).symm⟩

/-- Forward values land in the canonical member. -/
theorem mem_canonicalAge_domainAt_of_mem_map {i x y : ℕ} (hy : y ∈ G.map i x) :
    y ∈ S.canonicalAge.domainAt (encode (G.imageTuple i)) := by
  rw [← G.range_embedding i]
  exact ⟨⟨x, G.mem_domainAt_of_mem_map hy⟩, (G.eq_embedding hy).symm⟩

/-- And every element of the canonical member is a forward value. -/
theorem exists_mem_map {i y : ℕ} (hy : y ∈ S.canonicalAge.domainAt (encode (G.imageTuple i))) :
    ∃ x ∈ A.domainAt i, y ∈ G.map i x := by
  obtain ⟨x, hx⟩ := (G.range_embedding i).symm ▸ hy
  exact ⟨x.1, x.2, hx ▸ G.map_apply_mem i x⟩

/-! ### The backward search

Every test halts, so this is an ordinary unbounded search: the enumeration is total
`Option`-valued, and the program halts on everything the enumeration produces. -/

/-- The test at enumeration step `m`: decode, push forward, compare. -/
noncomputable def testPart (i y m : ℕ) : Part Bool :=
  Option.casesOn (motive := fun _ ↦ Part Bool) (A.enum? i m) (Part.some false)
    fun x ↦ (G.map i x).map fun z ↦ decide (z = y)

/-- **Every test halts** — the fact that makes the search honest. -/
theorem testPart_dom (i y m : ℕ) : (G.testPart i y m).Dom := by
  rw [testPart]
  rcases h : A.enum? i m with - | x
  · exact trivial
  · exact (Part.dom_iff_mem.2 ⟨_, (Part.mem_map_iff _).2
      ⟨_, Part.get_mem ((G.map_dom i x).2 ⟨m, h⟩), rfl⟩⟩)

theorem mem_testPart_true_iff {i y m : ℕ} :
    true ∈ G.testPart i y m ↔ ∃ x, A.enum? i m = Option.some x ∧ y ∈ G.map i x := by
  rw [testPart]
  rcases h : A.enum? i m with - | x
  · simp
  · simp only [Option.some.injEq]
    constructor
    · intro hb
      obtain ⟨z, hz, hdec⟩ := (Part.mem_map_iff _).1 hb
      exact ⟨x, rfl, of_decide_eq_true hdec ▸ hz⟩
    · rintro ⟨x', rfl, hx'⟩
      exact (Part.mem_map_iff _).2 ⟨y, hx', by simp⟩

/-- The backward map: the least enumeration step whose value the program sends to `y`. -/
noncomputable def preimagePart (i y : ℕ) : Part ℕ :=
  (Nat.rfind (G.testPart i y)).bind fun m ↦ ((A.enum? i m : Option ℕ) : Part ℕ)

theorem mem_preimagePart {i y x : ℕ} (hx : x ∈ G.preimagePart i y) : y ∈ G.map i x := by
  obtain ⟨m, hm, hval⟩ := Part.mem_bind_iff.1 hx
  obtain ⟨x', hx', hmap⟩ := G.mem_testPart_true_iff.1 (Nat.rfind_spec hm)
  rw [Part.mem_ofOption, hx', Option.mem_def, Option.some_inj] at hval
  exact hval ▸ hmap

theorem preimagePart_dom_iff {i y : ℕ} :
    (G.preimagePart i y).Dom ↔ ∃ x, y ∈ G.map i x := by
  constructor
  · intro h
    obtain ⟨x, hx⟩ := Part.dom_iff_mem.1 h
    exact ⟨x, G.mem_preimagePart hx⟩
  · rintro ⟨x, hx⟩
    obtain ⟨m, hm⟩ := G.mem_domainAt_of_mem_map hx
    have hfind : (Nat.rfind (G.testPart i y)).Dom :=
      Nat.rfind_dom.2 ⟨m, G.mem_testPart_true_iff.2 ⟨x, hm, hx⟩,
        fun {k} _ ↦ G.testPart_dom i y k⟩
    obtain ⟨m₀, hm₀⟩ := Part.dom_iff_mem.1 hfind
    obtain ⟨x₀, hx₀, -⟩ := G.mem_testPart_true_iff.1 (Nat.rfind_spec hm₀)
    exact Part.dom_iff_mem.2 ⟨x₀, Part.mem_bind_iff.2 ⟨m₀, hm₀, Part.mem_ofOption.2 hx₀⟩⟩

/-- Uniformly partial recursive — the one place `O ⊆ E` enters the effective content, since the
search reads the family's enumeration. -/
theorem preimagePart_recursiveIn (hOE : O ⊆ E) :
    RecursiveIn E fun q : ℕ × ℕ ↦ G.preimagePart q.1 q.2 := by
  have henum : ComputableIn E fun p : ℕ × ℕ ↦ A.enum? p.1 p.2 :=
    RecursiveIn.mono hOE A.enum?_computableIn
  have htest : RecursiveIn E fun r : (ℕ × ℕ) × ℕ ↦ G.testPart r.1.1 r.1.2 r.2 := by
    refine RecursiveIn.option_casesOn_right (O := E) (α := (ℕ × ℕ) × ℕ) (β := ℕ) (σ := Bool)
      (o := fun r : (ℕ × ℕ) × ℕ ↦ A.enum? r.1.1 r.2)
      (f := fun _ ↦ false)
      (g := fun r x ↦ (G.map r.1.1 x).map fun z ↦ decide (z = r.1.2))
      (henum.comp ((ComputableIn.fst.comp ComputableIn.fst).pair ComputableIn.snd))
      (ComputableIn.const false) ?_
    exact (RecursiveIn.map
      (G.map_uniform.comp
        ((ComputableIn.fst.comp (ComputableIn.fst.comp ComputableIn.fst)).pair
          ComputableIn.snd))
      (((Primrec.eq (α := ℕ)).decide.to_comp.computableIn₂ (O := E)).comp
        ComputableIn.snd
        (ComputableIn.snd.comp
          (ComputableIn.fst.comp (ComputableIn.fst.comp ComputableIn.fst)))).to₂).to₂
  have hbody : RecursiveIn E fun r : (ℕ × ℕ) × ℕ ↦ ((A.enum? r.1.1 r.2 : Option ℕ) : Part ℕ) :=
    ComputableIn.ofOption
      (henum.comp ((ComputableIn.fst.comp ComputableIn.fst).pair ComputableIn.snd))
  exact RecursiveIn.bind (RecursiveIn.rfind htest.to₂) hbody.to₂

/-! ### The induced isomorphism -/

/-- **The generated-image isomorphism.** Needs no oracle inclusion: it only runs the supplied
program and the backward search, and the structure laws come from the semantic embedding. -/
noncomputable def isoAt (hOE : O ⊆ E) (i : ℕ) :
    PartialCeIsoIn E (A.memberAt i) (S.canonicalAge.memberAt (encode (G.imageTuple i))) where
  toFun := G.map i
  invFun := G.preimagePart i
  toFun_recursiveIn := G.map_recursiveIn i
  invFun_recursiveIn := (G.preimagePart_recursiveIn hOE).comp
    ((ComputableIn.const i).pair ComputableIn.id)
  toFun_dom := G.map_dom i
  invFun_dom := fun y ↦ by
    rw [G.preimagePart_dom_iff]
    constructor
    · rintro ⟨x, hx⟩
      exact G.mem_canonicalAge_domainAt_of_mem_map hx
    · intro hy
      obtain ⟨x, -, hx⟩ := G.exists_mem_map hy
      exact ⟨x, hx⟩
  toFun_mem := fun h ↦ G.mem_canonicalAge_domainAt_of_mem_map h
  invFun_toFun := fun {x y} h ↦ by
    have hdom : (G.preimagePart i y).Dom := G.preimagePart_dom_iff.2 ⟨x, h⟩
    obtain ⟨x', hx'⟩ := Part.dom_iff_mem.1 hdom
    exact (G.map_injOn (G.mem_preimagePart hx') h) ▸ hx'
  toFun_invFun := fun h ↦ G.mem_preimagePart h
  toFun_funMap := fun n f v w hw ↦ by
    letI : L.Structure ℕ := S.inst
    have hv : ∀ k, v k ∈ A.domainAt i := fun k ↦ G.mem_domainAt_of_mem_map (hw k)
    have hvw : w = fun k ↦ (G.embedding i ⟨v k, hv k⟩ : ℕ) :=
      funext fun k ↦ G.eq_embedding (hw k)
    subst hvw
    have hfm : @Structure.funMap L ℕ S.inst n f (fun k ↦ (G.embedding i ⟨v k, hv k⟩ : ℕ))
        = G.embedding i
          (@Structure.funMap L (A.memberAt i).domain _ n f fun k ↦ ⟨v k, hv k⟩) :=
      (HomClass.map_fun (G.embedding i) f fun k ↦ (⟨v k, hv k⟩ : (A.memberAt i).domain)).symm
    have hmem := G.map_apply_mem i
      (@Structure.funMap L (A.memberAt i).domain _ n f fun k ↦ ⟨v k, hv k⟩)
    rw [← hfm] at hmem
    exact hmem
  toFun_relMap := fun n R v w hw ↦ by
    letI : L.Structure ℕ := S.inst
    have hv : ∀ k, v k ∈ A.domainAt i := fun k ↦ G.mem_domainAt_of_mem_map (hw k)
    have hvw : w = fun k ↦ (G.embedding i ⟨v k, hv k⟩ : ℕ) :=
      funext fun k ↦ G.eq_embedding (hw k)
    subst hvw
    exact (G.embedding i).map_rel' R fun k ↦ (⟨v k, hv k⟩ : (A.memberAt i).domain)

@[simp] theorem isoAt_toFun (hOE : O ⊆ E) (i : ℕ) : (G.isoAt hOE i).toFun = G.map i := rfl

@[simp] theorem isoAt_invFun (hOE : O ⊆ E) (i : ℕ) :
    (G.isoAt hOE i).invFun = G.preimagePart i := rfl

/-! ### The assembled cover -/

/-- The target index is computable — where reading the recorded generators costs `O ⊆ E`. -/
theorem imageTuple_computableIn (hOE : O ⊆ E) : ComputableIn E fun i ↦ encode (G.imageTuple i) := by
  have hpart : RecursiveIn E fun i ↦ G.imageTuplePart i :=
    RecursiveIn.comp (O := E) (α := ℕ) (β := ℕ × Tuple ℕ) (σ := Tuple ℕ)
      (f := fun p : ℕ × Tuple ℕ ↦ listMapPart (G.map p.1) p.2)
      (g := fun i : ℕ ↦ (i, A.gens i))
      (RecursiveIn.listMapPart₂ (g := G.map) G.map_uniform)
      (ComputableIn.id.pair (RecursiveIn.mono hOE A.gens_computableIn))
  exact Computable.encode.computableIn.comp
    (RecursiveIn.computableIn_get hpart G.imageTuplePart_dom)

/-- **The cover onto `𝕂_𝒟`.** Its index map is `encode` of the generator-image tuple, so its
generator compatibility is definitional (`allTupleFor_encode`) — proved once here rather than at
each of the two covers. -/
noncomputable def toCanonicalAgeCover (hOE : O ⊆ E) :
    RepresentationCoverIn E A S.canonicalAge where
  indexMap i := encode (G.imageTuple i)
  indexMap_computableIn := G.imageTuple_computableIn hOE
  isoAt := G.isoAt hOE
  toFun_uniform := G.map_uniform
  invFun_uniform := G.preimagePart_recursiveIn hOE

@[simp] theorem toCanonicalAgeCover_indexMap (hOE : O ⊆ E) (i : ℕ) :
    (G.toCanonicalAgeCover hOE).indexMap i = encode (G.imageTuple i) :=
  rfl

/-- The cover's derived generator image *is* the image tuple: the cover's forward traversal is the
traversal `imageTuplePart` already performed. Definitional, so nothing can drift. -/
@[simp] theorem toCanonicalAgeCover_sourceGensImage (hOE : O ⊆ E) (i : ℕ) :
    (G.toCanonicalAgeCover hOE).sourceGensImage i = G.imageTuple i :=
  rfl

/-- **Generator compatibility, for free.** The target index is the image tuple's code and `𝕂_𝒟`
records `allTupleFor` at each index, so the matched member's recorded generators are the image
tuple on the nose — the one fact `CHPSeparationAudit` shows an arbitrary cover need not have, here
by construction. Proving it once here is the reason both covers route through this constructor. -/
theorem toCanonicalAgeCover_generatorCompatible (hOE : O ⊆ E) :
    (G.toCanonicalAgeCover hOE).GeneratorCompatible :=
  fun i ↦ (allTupleFor_encode (G.imageTuple i)).symm

end UniformEmbeddingIntoIn

end FirstOrder.Language
