/-
Copyright (c) 2026 Cameron Freer. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Cameron Freer
-/
import ComputableModelTheory.ModelTheory.Computable.GeneratedImageIso
import ComputableModelTheory.Util.AssertAxioms

/-!
# Audit: the generated-image isomorphism and the two covers it assembles

The row that carries the design is `test_range_embedding`: an embedding's range **is** the canonical
member at the image tuple's code. That is what makes the target index forced rather than chosen, and
everything else here is downstream of it — the backward search's success, the isomorphism's exact
domains, and both covers' generator compatibility.

Four rows record boundaries.

* `test_cover_uniform` reads the cover's uniformity fields back out. A family of per-index
  computability proofs is not a proof about the family; a constructor that produced only `isoAt`
  would not build a cover, and this row says these fields are supplied rather than hoped for.
* `test_maps_exposed` pins the executable maps as the supplied program and the search. Consumers
  compute with them, so they must not be hidden behind the bundle.
* `test_search_is_honest` states that **every** test of the backward search halts. Without it the
  search would be a dovetailing and its recursiveness a different theorem; with it, only success is
  in question, and `range_embedding` decides that.
* `test_two_covers_are_not_symmetrizations` records the shape of the two covers: the one into `𝕂_𝒟`
  needs `sourceIndex = id`, the one out of it needs self-matching image tuples, and the second is
  built from *per-query* isomorphisms inverted. `RepresentationCoverIn` has no `symm`, so a
  completed cover cannot be turned around; only `PartialCeIsoIn` can.

`test_from_cover_generatorCompatible` is the payoff on the forward side, and
`test_to_cover_generatorCompatible` on the backward. `CHPSeparationAudit` shows an arbitrary
representation isomorphism need not carry recorded generators to recorded generators; covers built
here always do — and on the `𝕂_𝒟 → A` side it is the *same* self-matching equality that fixes the
index map, so the two facts cannot come apart.

The fixture is `𝕂_𝒟` embedded into `S` by inclusion — the smallest instance where the answer is
known independently: the image of member `i`'s generators is `allTupleFor i`, so the induced index
map is `i ↦ encode (allTupleFor i)`, deliberately **not** the identity, and the self-matching
hypothesis holds, giving a concrete cover in each direction.
-/

open Encodable Part FirstOrder Language

namespace FirstOrder.Language

/-! ### The query-indexed core -/

namespace UniformSelectedEmbeddingIntoIn

variable {O E : Set (ℕ →. ℕ)} {L : Language} [L.EffectiveLanguage]
variable {A : PartialAgeIn O L} {S : ComputableStructureIn O L}
variable (G : UniformSelectedEmbeddingIntoIn E A S)

/-! #### The theorem that forces the target index -/

/-- **The range of the embedding is exactly the canonical member at the image tuple's code.** The
selected member is generated by its recorded tuple, so the range is generated by that tuple's
image — and `𝕂_𝒟` records `allTupleFor` at every index, so `encode` of the image tuple names
precisely that member. No other index could work. -/
theorem test_range_embedding (i : ℕ) :
    Set.range (fun x : (A.memberAt (G.sourceIndex i)).domain ↦ (G.embedding i x : ℕ))
      = S.canonicalAge.domainAt (encode (G.imageTuple i)) :=
  G.range_embedding i

/-- Both halves of that, in the form the isomorphism's domain fields consume. -/
theorem test_range_both_ways {i x y : ℕ} (hy : y ∈ G.map i x) :
    y ∈ S.canonicalAge.domainAt (encode (G.imageTuple i)) ∧
      ∀ z ∈ S.canonicalAge.domainAt (encode (G.imageTuple i)),
        ∃ w ∈ A.domainAt (G.sourceIndex i), z ∈ G.map i w :=
  ⟨G.mem_canonicalAge_domainAt_of_mem_map hy, fun _ hz ↦ G.exists_mem_map hz⟩

/-! #### The backward search -/

/-- **Every test halts**, so the search is an ordinary unbounded search rather than a dovetailing:
the enumeration is total `Option`-valued and the program halts on everything it produces. -/
theorem test_search_is_honest (i y m : ℕ) : (G.testPart i y m).Dom :=
  G.testPart_dom i y m

/-- Its exact success condition. -/
theorem test_preimage_dom_iff {i y : ℕ} :
    (G.preimagePart i y).Dom ↔ ∃ x, y ∈ G.map i x :=
  G.preimagePart_dom_iff

/-! #### The isomorphism -/

/-- **The executable maps stay exposed**: forward is the supplied program, backward is the search.
A consumer computes with these, so bundling must not hide them. -/
theorem test_maps_exposed (hOE : O ⊆ E) (i : ℕ) :
    (G.isoAt hOE i).toFun = G.map i ∧ (G.isoAt hOE i).invFun = G.preimagePart i :=
  ⟨rfl, rfl⟩

/-- **The isomorphism from the selected member onto the canonical member.** -/
theorem test_isoAt (hOE : O ⊆ E) (i : ℕ) :
    Nonempty (PartialCeIsoIn E (A.memberAt (G.sourceIndex i))
      (S.canonicalAge.memberAt (encode (G.imageTuple i)))) :=
  ⟨G.isoAt hOE i⟩

/-! #### The cover out of `𝕂_𝒟` -/

/-- **Self-matching identifies the index.** When a query's image tuple is the query's own recorded
tuple, the target index *is* the query — so the cover out of `𝕂_𝒟` can use `sourceIndex` as its
index map, with no inverse-index assumption anywhere. -/
theorem test_self_matching_fixes_index {e : ℕ} (he : G.imageTuple e = allTupleFor e) :
    encode (G.imageTuple e) = e :=
  encode_imageTuple_eq he

/-- The cover out of `𝕂_𝒟` exists, and its index map is `sourceIndex`. -/
theorem test_from_cover (hOE : O ⊆ E) (hself : ∀ e, G.imageTuple e = allTupleFor e) :
    Nonempty (RepresentationCoverIn E S.canonicalAge A) ∧
      ∀ e, (G.fromCanonicalAgeCover hOE hself).indexMap e = G.sourceIndex e :=
  ⟨⟨G.fromCanonicalAgeCover hOE hself⟩, fun _ ↦ rfl⟩

/-- **Generator compatibility on the `𝕂_𝒟 → A` side**, from the *same* self-matching equality that
fixed the index map: the query's recorded tuple is the forward image of the selected member's
generators, so pulling it back returns those generators. This is the compatibility CHMM's forward
implication assumes and its reverse implication must construct. -/
theorem test_from_cover_generatorCompatible (hOE : O ⊆ E)
    (hself : ∀ e, G.imageTuple e = allTupleFor e) :
    (G.fromCanonicalAgeCover hOE hself).GeneratorCompatible :=
  G.fromCanonicalAgeCover_generatorCompatible hOE hself

end UniformSelectedEmbeddingIntoIn

/-! ### The self-indexed specialization and the cover into `𝕂_𝒟` -/

namespace UniformEmbeddingIntoIn

variable {O E : Set (ℕ →. ℕ)} {L : Language} [L.EffectiveLanguage]
variable {A : PartialAgeIn O L} {S : ComputableStructureIn O L}
variable (G : UniformEmbeddingIntoIn E A S)

/-- The specialization is exactly `sourceIndex := id`, with the same program. -/
theorem test_toSelected : G.toSelected.sourceIndex = id ∧ G.toSelected.map = G.map :=
  ⟨rfl, rfl⟩

/-- The index map is the image tuple's code. -/
theorem test_cover_indexMap (hOE : O ⊆ E) (i : ℕ) :
    (G.toCanonicalAgeCover hOE).indexMap i = encode (G.toSelected.imageTuple i) :=
  rfl

/-- **The uniformity fields are supplied**, not recovered: a family of per-index recursiveness
proofs is not a proof about the family, so a constructor delivering only `isoAt` would not build a
cover at all. -/
theorem test_cover_uniform (hOE : O ⊆ E) :
    (RecursiveIn E fun p : ℕ × ℕ ↦ ((G.toCanonicalAgeCover hOE).isoAt p.1).toFun p.2) ∧
      RecursiveIn E fun p : ℕ × ℕ ↦ ((G.toCanonicalAgeCover hOE).isoAt p.1).invFun p.2 :=
  ⟨(G.toCanonicalAgeCover hOE).toFun_uniform, (G.toCanonicalAgeCover hOE).invFun_uniform⟩

/-- **Generator compatibility on the `A → 𝕂_𝒟` side, for free.** The target index is the image
tuple's code and `𝕂_𝒟` records `allTupleFor` at each index, so the matched member's recorded
generators are the image tuple on the nose. -/
theorem test_to_cover_generatorCompatible (hOE : O ⊆ E) :
    (G.toCanonicalAgeCover hOE).GeneratorCompatible :=
  G.toCanonicalAgeCover_generatorCompatible hOE

/-- **Neither cover is a symmetrization.** The two directions have different hypotheses — `A → 𝕂_𝒟`
needs the self-indexed shape, `𝕂_𝒟 → A` needs self-matching image tuples — and the second is built
from per-query `PartialCeIsoIn.symm`, never from a completed cover, which `RepresentationCoverIn`
does not support. This row typechecks only because the two are constructed independently. -/
theorem test_two_covers_are_not_symmetrizations (hOE : O ⊆ E)
    (hself : ∀ e, G.toSelected.imageTuple e = allTupleFor e) :
    Nonempty (RepresentationCoverIn E A S.canonicalAge) ∧
      Nonempty (RepresentationCoverIn E S.canonicalAge A) :=
  ⟨⟨G.toCanonicalAgeCover hOE⟩, ⟨G.toSelected.fromCanonicalAgeCover hOE hself⟩⟩

end UniformEmbeddingIntoIn

/-! ### Fixture: `𝕂_𝒟` embedded into `S` by inclusion

The smallest instance whose answer is known independently. Member `i` of `𝕂_𝒟` is a substructure of
`S` on the nose, so the inclusion is an embedding and the image of its generators is `allTupleFor i`
itself — making the induced index map `i ↦ encode (allTupleFor i)`, which is **not** the identity,
and making the self-matching hypothesis hold, so both covers land concretely. -/

namespace ComputableStructureIn

variable {O E : Set (ℕ →. ℕ)} {L : Language} [L.EffectiveLanguage]
variable (S : ComputableStructureIn O L)

/-- `𝕂_𝒟` embedded into `S`: semantically the carrier inclusion, effectively the family's
domain-restricted identity. -/
noncomputable def canonicalSelfEmbedding (hOE : O ⊆ E) :
    UniformEmbeddingIntoIn E S.canonicalAge S where
  embedding i := (S.canonicalAge.memberAt i).domainInclusion
  map i x := S.canonicalAge.idFun (i, x)
  map_uniform := RecursiveIn.mono hOE S.canonicalAge.idFun_recursiveIn
  map_dom := S.canonicalAge.idFun_dom
  map_apply_mem := fun _ x ↦ S.canonicalAge.mem_idFun.2 ⟨rfl, x.2⟩

/-- **The image of a member's generators is that member's own tuple.** The inclusion moves nothing,
so the traversal returns its input — which is what makes the fixture's index map predictable and
its self-matching hypothesis true. -/
theorem canonicalSelfEmbedding_imageTuple (hOE : O ⊆ E) (i : ℕ) :
    (S.canonicalSelfEmbedding (E := E) hOE).toSelected.imageTuple i = allTupleFor i := by
  have key : ∀ s t : List ℕ,
      List.Forall₂ (fun x y ↦ y ∈ S.canonicalAge.idFun (i, x)) s t → t = s := by
    intro s t hf
    induction hf with
    | nil => rfl
    | @cons x y s' t' hxy _ ih => exact congrArg₂ _ (S.canonicalAge.mem_idFun.1 hxy).1 ih
  exact key _ _ ((S.canonicalSelfEmbedding (E := E) hOE).toSelected.forall₂_imageTuple i)

/-- **The fixture's index map**, computed: `i ↦ encode (allTupleFor i)`. Not the identity, so this
row separates the constructor from one that returns its input index. -/
theorem test_canonicalSelf_indexMap (hOE : O ⊆ E) (i : ℕ) :
    ((S.canonicalSelfEmbedding (E := E) hOE).toCanonicalAgeCover hOE).indexMap i
      = encode (allTupleFor i) := by
  rw [UniformEmbeddingIntoIn.toCanonicalAgeCover_indexMap,
    S.canonicalSelfEmbedding_imageTuple hOE i]

/-- And the range theorem, concretely: member `i`'s carrier is the carrier of the member coded by
its own tuple. -/
theorem test_canonicalSelf_range (hOE : O ⊆ E) (i : ℕ) :
    Set.range (fun x : (S.canonicalAge.memberAt i).domain ↦
        ((S.canonicalSelfEmbedding (E := E) hOE).embedding i x : ℕ))
      = S.canonicalAge.domainAt (encode (allTupleFor i)) := by
  rw [← S.canonicalSelfEmbedding_imageTuple hOE i]
  exact (S.canonicalSelfEmbedding (E := E) hOE).toSelected.range_embedding i

/-- **Both covers, concretely, both generator-compatible.** The fixture satisfies the self-matching
hypothesis, so the `𝕂_𝒟 → 𝕂_𝒟` direction is available too — with index map the identity, since the
inclusion's selected member *is* the query. -/
theorem test_canonicalSelf_both_covers (hOE : O ⊆ E) :
    ((S.canonicalSelfEmbedding (E := E) hOE).toCanonicalAgeCover hOE).GeneratorCompatible ∧
      ((S.canonicalSelfEmbedding (E := E) hOE).toSelected.fromCanonicalAgeCover hOE
        (S.canonicalSelfEmbedding_imageTuple hOE)).GeneratorCompatible :=
  ⟨(S.canonicalSelfEmbedding (E := E) hOE).toCanonicalAgeCover_generatorCompatible hOE,
    (S.canonicalSelfEmbedding (E := E) hOE).toSelected.fromCanonicalAgeCover_generatorCompatible
      hOE (S.canonicalSelfEmbedding_imageTuple hOE)⟩

end ComputableStructureIn

end FirstOrder.Language

#assert_standard_axioms
  FirstOrder.Language.UniformSelectedEmbeddingIntoIn.test_range_embedding
#assert_standard_axioms
  FirstOrder.Language.UniformSelectedEmbeddingIntoIn.test_range_both_ways
#assert_standard_axioms
  FirstOrder.Language.UniformSelectedEmbeddingIntoIn.test_search_is_honest
#assert_standard_axioms
  FirstOrder.Language.UniformSelectedEmbeddingIntoIn.test_preimage_dom_iff
#assert_standard_axioms FirstOrder.Language.UniformSelectedEmbeddingIntoIn.test_maps_exposed
#assert_standard_axioms FirstOrder.Language.UniformSelectedEmbeddingIntoIn.test_isoAt
#assert_standard_axioms
  FirstOrder.Language.UniformSelectedEmbeddingIntoIn.test_self_matching_fixes_index
#assert_standard_axioms FirstOrder.Language.UniformSelectedEmbeddingIntoIn.test_from_cover
#assert_standard_axioms
  FirstOrder.Language.UniformSelectedEmbeddingIntoIn.test_from_cover_generatorCompatible
#assert_standard_axioms FirstOrder.Language.UniformEmbeddingIntoIn.test_toSelected
#assert_standard_axioms FirstOrder.Language.UniformEmbeddingIntoIn.test_cover_indexMap
#assert_standard_axioms FirstOrder.Language.UniformEmbeddingIntoIn.test_cover_uniform
#assert_standard_axioms
  FirstOrder.Language.UniformEmbeddingIntoIn.test_to_cover_generatorCompatible
#assert_standard_axioms
  FirstOrder.Language.UniformEmbeddingIntoIn.test_two_covers_are_not_symmetrizations
#assert_standard_axioms
  FirstOrder.Language.ComputableStructureIn.canonicalSelfEmbedding_imageTuple
#assert_standard_axioms FirstOrder.Language.ComputableStructureIn.test_canonicalSelf_indexMap
#assert_standard_axioms FirstOrder.Language.ComputableStructureIn.test_canonicalSelf_range
#assert_standard_axioms FirstOrder.Language.ComputableStructureIn.test_canonicalSelf_both_covers
