/-
Copyright (c) 2026 Cameron Freer. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Cameron Freer
-/
import ComputableModelTheory.ModelTheory.Computable.CanonicalAge
import ComputableModelTheory.ModelTheory.Computable.RepresentationIso

/-!
# The generated-image isomorphism, and the two covers it assembles

The shared constructor behind both covers of CHMM Theorem 2.10(⇐):

> a uniformly computable embedding of a representation's members into `S` induces a
> `PartialCeIsoIn` onto the canonical-age member indexed by the **code of the generator-image
> tuple**.

**Why the target index is forced.** A member is generated by its recorded tuple, so an embedding's
range is the substructure generated by the image of that tuple — nothing else. `𝕂_𝒟`'s member at
`encode t` is the substructure generated by `t`, on the nose (`allTupleFor_encode`). So the target
index is not a choice: it is `encode` of the image tuple, and `range_embedding` is the theorem that
says the two carriers coincide.

**The core is query-indexed.** `UniformSelectedEmbeddingIntoIn` carries a `sourceIndex`, because the
member that answers a query need not be the query itself: the forward cover's source member is
*selected* by the hereditary property from a canonical query, so it is indexed by that query rather
than by itself. `UniformEmbeddingIntoIn` is the `sourceIndex := id` specialization, which is what a
producer embedding each member on its own account supplies.

**The two covers come out in opposite directions, and neither is a symmetrization.**
`RepresentationCoverIn` deliberately has no `symm`; only the *per-query* isomorphism can be
inverted. So:

* `toCanonicalAgeCover` (`A → 𝕂_𝒟`) needs `sourceIndex = id`, and its generator compatibility is
  `allTupleFor_encode`;
* `fromCanonicalAgeCover` (`𝕂_𝒟 → A`) needs `imageTuple e = allTupleFor e` for every query, and
  that single equality does two jobs at once — it identifies the canonical source index (so the
  index map is `sourceIndex`) and it yields generator compatibility, by inverting the image
  traversal.

**The two halves of the isomorphism are asymmetric.** The forward map is the supplied program. The
backward map is a search: run the member's enumeration, push each value forward, and stop when it
matches. That search is an *honest* unbounded search rather than a dovetailing — every test halts,
because the enumeration is total `Option`-valued and the program halts on everything the
enumeration produces. Only its success is in question, and `range_embedding` is exactly what
decides it.

**Input shape: both sides of the map, as in Lemma 2.9.** The semantic embedding carries injectivity
and the structure laws (so none is re-proved here); the program carries effectivity; and
`map_apply_mem` ties them. `map_dom` is an **iff**, not one-way halting, because
`PartialCeIsoIn.toFun_dom` is an iff — a producer that only knows its map halts on the carrier does
not have enough to build an isomorphism.

**The oracle boundary.** What needs no `O ⊆ E` is the *supplied* data: the forward program and the
semantic embedding are used as given. Everything that reads presentation data does need it — the
recorded generators for the index map, and the family's enumeration for the backward search. So the
**complete** isomorphism needs the inclusion, and `isoAt` takes it: an isomorphism without its
inverse is not one.
-/

open Encodable Part FirstOrder Language

namespace FirstOrder.Language

variable {O E : Set (ℕ →. ℕ)} {L : Language} [L.EffectiveLanguage]

/-- **Both sides of a query-indexed uniform embedding of a representation into a computable
structure.** The semantic embeddings supply injectivity and the structure laws; the programs supply
effectivity; `map_apply_mem` is the only statement relating them — the same shape Lemma 2.9's
`LimitIn` carries.

`sourceIndex` is what makes this usable on the forward side: the member answering query `i` is
selected, and need not be `i`. -/
structure UniformSelectedEmbeddingIntoIn (E : Set (ℕ →. ℕ)) (A : PartialAgeIn O L)
    (S : ComputableStructureIn O L) where
  /-- Which member of `A` answers query `i`. -/
  sourceIndex : ℕ → ℕ
  sourceIndex_computableIn : ComputableIn E sourceIndex
  /-- The semantic embedding of the selected member into `S`. -/
  embedding : ∀ i, @Language.Embedding L (A.memberAt (sourceIndex i)).domain ℕ _ S.inst
  /-- Its program. -/
  map : ℕ → ℕ →. ℕ
  /-- Uniformly partial recursive in the query. Not implied by per-query proofs. -/
  map_uniform : RecursiveIn E fun p : ℕ × ℕ ↦ map p.1 p.2
  /-- **Exact** domain, since `PartialCeIsoIn.toFun_dom` is an iff. -/
  map_dom : ∀ i x, (map i x).Dom ↔ x ∈ A.domainAt (sourceIndex i)
  /-- The two sides agree. -/
  map_apply_mem : ∀ (i : ℕ) (x : (A.memberAt (sourceIndex i)).domain),
    embedding i x ∈ map i (x : ℕ)

/-- **The self-indexed specialization**: every member embedded on its own account. What the backward
cover's producer supplies, and the only shape from which a cover *into* `𝕂_𝒟` can be built, since a
cover's isomorphism at `i` must start at member `i`. -/
structure UniformEmbeddingIntoIn (E : Set (ℕ →. ℕ)) (A : PartialAgeIn O L)
    (S : ComputableStructureIn O L) where
  /-- The semantic embedding of each member into `S`. -/
  embedding : ∀ i, @Language.Embedding L (A.memberAt i).domain ℕ _ S.inst
  /-- Its program. -/
  map : ℕ → ℕ →. ℕ
  /-- Uniformly partial recursive in the index. Not implied by per-index proofs. -/
  map_uniform : RecursiveIn E fun p : ℕ × ℕ ↦ map p.1 p.2
  /-- **Exact** domain, since `PartialCeIsoIn.toFun_dom` is an iff. -/
  map_dom : ∀ i x, (map i x).Dom ↔ x ∈ A.domainAt i
  /-- The two sides agree. -/
  map_apply_mem : ∀ (i : ℕ) (x : (A.memberAt i).domain), embedding i x ∈ map i (x : ℕ)

namespace UniformSelectedEmbeddingIntoIn

variable {A : PartialAgeIn O L} {S : ComputableStructureIn O L}
variable (G : UniformSelectedEmbeddingIntoIn E A S)

/-! ### Reading the program through the embedding -/

theorem mem_domainAt_of_mem_map {i x y : ℕ} (hy : y ∈ G.map i x) :
    x ∈ A.domainAt (G.sourceIndex i) :=
  (G.map_dom i x).1 (Part.dom_iff_mem.2 ⟨y, hy⟩)

/-- Every value of the program is the embedding's value — single-valuedness of `Part` plus the
bridge. Every fact below reads the program only through this. -/
theorem eq_embedding {i x y : ℕ} (hy : y ∈ G.map i x) :
    y = G.embedding i ⟨x, G.mem_domainAt_of_mem_map hy⟩ :=
  Part.mem_unique hy (G.map_apply_mem i ⟨x, G.mem_domainAt_of_mem_map hy⟩)

theorem map_injOn {i x₁ x₂ y : ℕ} (h₁ : y ∈ G.map i x₁) (h₂ : y ∈ G.map i x₂) : x₁ = x₂ := by
  letI : L.Structure ℕ := S.inst
  exact congrArg Subtype.val
    ((G.embedding i).injective ((G.eq_embedding h₁).symm.trans (G.eq_embedding h₂)))

theorem map_recursiveIn (i : ℕ) : RecursiveIn E (G.map i) :=
  G.map_uniform.comp ((ComputableIn.const i).pair ComputableIn.id)

/-! ### The generator-image tuple -/

/-- The image of the selected member's recorded generators, as a program. -/
noncomputable def imageTuplePart (i : ℕ) : Part (Tuple ℕ) :=
  listMapPart (G.map i) (A.gens (G.sourceIndex i))

/-- It always halts: every generator lies in the member's carrier. -/
theorem imageTuplePart_dom (i : ℕ) : (G.imageTuplePart i).Dom :=
  listMapPart_dom_iff.2 fun _ hx ↦ (G.map_dom i _).2 (A.mem_domainAt_of_mem_gens hx)

/-- **The generator-image tuple** — the code of which is the target index. -/
noncomputable def imageTuple (i : ℕ) : Tuple ℕ :=
  (G.imageTuplePart i).get (G.imageTuplePart_dom i)

/-- **The `Forall₂` specification.** The only place the traversal is opened. -/
theorem forall₂_imageTuple (i : ℕ) :
    List.Forall₂ (fun x y ↦ y ∈ G.map i x) (A.gens (G.sourceIndex i)) (G.imageTuple i) :=
  mem_listMapPart_iff.1 (Part.get_mem _)

theorem imageTuple_length (i : ℕ) :
    (G.imageTuple i).length = (A.gens (G.sourceIndex i)).length :=
  (G.forall₂_imageTuple i).length_eq.symm

/-- **The entries of the image tuple, indexed by the source generators.** The one place `Forall₂`,
`List.get` and a `Fin` cast meet; everything downstream uses the range form below. -/
theorem imageTuple_get (i : ℕ) (k : Fin (A.gens (G.sourceIndex i)).length) :
    (G.imageTuple i).get (Fin.cast (G.imageTuple_length i).symm k)
      = G.embedding i (A.gensView (G.sourceIndex i) k) := by
  obtain ⟨-, hget⟩ := List.forall₂_iff_get.1 (G.forall₂_imageTuple i)
  exact G.eq_embedding (hget k.1 k.2 (by rw [G.imageTuple_length]; exact k.2))

/-- **The range form**, which is what the closure computation needs: the image tuple's entries are
exactly the embedded generators. Length-agnostic, so no cast survives past this point. -/
theorem range_view_imageTuple (i : ℕ) :
    Set.range (Tuple.view (G.imageTuple i))
      = Set.range fun k ↦ (G.embedding i (A.gensView (G.sourceIndex i) k) : ℕ) := by
  ext y
  simp only [Set.mem_range]
  constructor
  · rintro ⟨k, rfl⟩
    have hk : (k : ℕ) < (A.gens (G.sourceIndex i)).length := by
      have hlt := k.2
      exact Nat.lt_of_lt_of_le hlt (le_of_eq (G.imageTuple_length i))
    exact ⟨⟨k, hk⟩, (G.imageTuple_get i ⟨k, hk⟩).symm⟩
  · rintro ⟨k, rfl⟩
    exact ⟨Fin.cast (G.imageTuple_length i).symm k, G.imageTuple_get i k⟩

/-! ### The range of the embedding is the canonical member

The theorem that forces the target index. Both inclusions are the same computation read in
opposite directions: a carrier element is a term over the generators, and the embedding carries
terms to terms. -/

/-- **The range of the embedding is exactly the carrier of the canonical member at the image
tuple's code.** This is what makes the target index forced rather than chosen, and it is what
decides the backward search's success. -/
theorem range_embedding (i : ℕ) :
    Set.range (fun x : (A.memberAt (G.sourceIndex i)).domain ↦ (G.embedding i x : ℕ))
      = S.canonicalAge.domainAt (encode (G.imageTuple i)) := by
  letI : L.Structure ℕ := S.inst
  rw [S.canonicalAge_domainAt_eq_closure, allTupleFor_encode, G.range_view_imageTuple]
  ext y
  rw [SetLike.mem_coe, mem_closure_range_iff_exists_term]
  constructor
  · rintro ⟨x, rfl⟩
    obtain ⟨T, rfl⟩ := PartialAgeIn.exists_realize_gensView x
    exact ⟨T, HomClass.realize_term (G.embedding i) (t := T)
      (v := A.gensView (G.sourceIndex i))⟩
  · rintro ⟨T, rfl⟩
    exact ⟨T.realize (A.gensView (G.sourceIndex i)),
      (HomClass.realize_term (G.embedding i) (t := T)
        (v := A.gensView (G.sourceIndex i))).symm⟩

/-- Forward values land in the canonical member. -/
theorem mem_canonicalAge_domainAt_of_mem_map {i x y : ℕ} (hy : y ∈ G.map i x) :
    y ∈ S.canonicalAge.domainAt (encode (G.imageTuple i)) := by
  rw [← G.range_embedding i]
  exact ⟨⟨x, G.mem_domainAt_of_mem_map hy⟩, (G.eq_embedding hy).symm⟩

/-- And every element of the canonical member is a forward value. -/
theorem exists_mem_map {i y : ℕ} (hy : y ∈ S.canonicalAge.domainAt (encode (G.imageTuple i))) :
    ∃ x ∈ A.domainAt (G.sourceIndex i), y ∈ G.map i x := by
  obtain ⟨x, hx⟩ := (G.range_embedding i).symm ▸ hy
  exact ⟨x.1, x.2, hx ▸ G.map_apply_mem i x⟩

/-! ### The backward search

Every test halts, so this is an ordinary unbounded search: the enumeration is total
`Option`-valued, and the program halts on everything the enumeration produces. -/

/-- The test at enumeration step `m`: decode, push forward, compare. -/
noncomputable def testPart (i y m : ℕ) : Part Bool :=
  Option.casesOn (motive := fun _ ↦ Part Bool) (A.enum? (G.sourceIndex i) m) (Part.some false)
    fun x ↦ (G.map i x).map fun z ↦ decide (z = y)

/-- **Every test halts** — the fact that makes the search honest. -/
theorem testPart_dom (i y m : ℕ) : (G.testPart i y m).Dom := by
  rw [testPart]
  rcases h : A.enum? (G.sourceIndex i) m with - | x
  · exact trivial
  · exact (Part.dom_iff_mem.2 ⟨_, (Part.mem_map_iff _).2
      ⟨_, Part.get_mem ((G.map_dom i x).2 ⟨m, h⟩), rfl⟩⟩)

theorem mem_testPart_true_iff {i y m : ℕ} :
    true ∈ G.testPart i y m ↔
      ∃ x, A.enum? (G.sourceIndex i) m = Option.some x ∧ y ∈ G.map i x := by
  rw [testPart]
  rcases h : A.enum? (G.sourceIndex i) m with - | x
  · simp
  · simp only [Option.some.injEq]
    constructor
    · intro hb
      obtain ⟨z, hz, hdec⟩ := (Part.mem_map_iff _).1 hb
      exact ⟨x, rfl, of_decide_eq_true hdec ▸ hz⟩
    · rintro ⟨x', rfl, hx'⟩
      exact (Part.mem_map_iff _).2 ⟨y, hx', by simp⟩

/-- The backward map: the least enumeration step whose value the program sends to `y`. -/
noncomputable def preimagePart (i y : ℕ) : Part ℕ :=
  (Nat.rfind (G.testPart i y)).bind fun m ↦
    ((A.enum? (G.sourceIndex i) m : Option ℕ) : Part ℕ)

theorem mem_preimagePart {i y x : ℕ} (hx : x ∈ G.preimagePart i y) : y ∈ G.map i x := by
  obtain ⟨m, hm, hval⟩ := Part.mem_bind_iff.1 hx
  obtain ⟨x', hx', hmap⟩ := G.mem_testPart_true_iff.1 (Nat.rfind_spec hm)
  rw [Part.mem_ofOption, hx', Option.mem_def, Option.some_inj] at hval
  exact hval ▸ hmap

theorem preimagePart_dom_iff {i y : ℕ} :
    (G.preimagePart i y).Dom ↔ ∃ x, y ∈ G.map i x := by
  constructor
  · intro h
    obtain ⟨x, hx⟩ := Part.dom_iff_mem.1 h
    exact ⟨x, G.mem_preimagePart hx⟩
  · rintro ⟨x, hx⟩
    obtain ⟨m, hm⟩ := G.mem_domainAt_of_mem_map hx
    have hfind : (Nat.rfind (G.testPart i y)).Dom :=
      Nat.rfind_dom.2 ⟨m, G.mem_testPart_true_iff.2 ⟨x, hm, hx⟩,
        fun {k} _ ↦ G.testPart_dom i y k⟩
    obtain ⟨m₀, hm₀⟩ := Part.dom_iff_mem.1 hfind
    obtain ⟨x₀, hx₀, -⟩ := G.mem_testPart_true_iff.1 (Nat.rfind_spec hm₀)
    exact Part.dom_iff_mem.2 ⟨x₀, Part.mem_bind_iff.2 ⟨m₀, hm₀, Part.mem_ofOption.2 hx₀⟩⟩

/-- Uniformly partial recursive — the one place `O ⊆ E` enters the effective content, since the
search reads the family's enumeration. -/
theorem preimagePart_recursiveIn (hOE : O ⊆ E) :
    RecursiveIn E fun q : ℕ × ℕ ↦ G.preimagePart q.1 q.2 := by
  have henum : ComputableIn E fun r : (ℕ × ℕ) × ℕ ↦ A.enum? (G.sourceIndex r.1.1) r.2 :=
    (RecursiveIn.mono hOE A.enum?_computableIn).comp
      ((G.sourceIndex_computableIn.comp
        (ComputableIn.fst.comp ComputableIn.fst)).pair ComputableIn.snd)
  have htest : RecursiveIn E fun r : (ℕ × ℕ) × ℕ ↦ G.testPart r.1.1 r.1.2 r.2 := by
    refine RecursiveIn.option_casesOn_right (O := E) (α := (ℕ × ℕ) × ℕ) (β := ℕ) (σ := Bool)
      (o := fun r : (ℕ × ℕ) × ℕ ↦ A.enum? (G.sourceIndex r.1.1) r.2)
      (f := fun _ ↦ false)
      (g := fun r x ↦ (G.map r.1.1 x).map fun z ↦ decide (z = r.1.2))
      henum (ComputableIn.const false) ?_
    exact (RecursiveIn.map
      (G.map_uniform.comp
        ((ComputableIn.fst.comp (ComputableIn.fst.comp ComputableIn.fst)).pair
          ComputableIn.snd))
      (((Primrec.eq (α := ℕ)).decide.to_comp.computableIn₂ (O := E)).comp
        ComputableIn.snd
        (ComputableIn.snd.comp
          (ComputableIn.fst.comp (ComputableIn.fst.comp ComputableIn.fst)))).to₂).to₂
  have hbody : RecursiveIn E fun r : (ℕ × ℕ) × ℕ ↦
      ((A.enum? (G.sourceIndex r.1.1) r.2 : Option ℕ) : Part ℕ) :=
    ComputableIn.ofOption henum
  exact RecursiveIn.bind (RecursiveIn.rfind htest.to₂) hbody.to₂

/-! ### The induced isomorphism -/

/-- **The generated-image isomorphism.** Takes the oracle inclusion: the forward map is the supplied
program and needs none, but the inverse search reads the family's enumeration, and an isomorphism
without its inverse is not one. -/
noncomputable def isoAt (hOE : O ⊆ E) (i : ℕ) :
    PartialCeIsoIn E (A.memberAt (G.sourceIndex i))
      (S.canonicalAge.memberAt (encode (G.imageTuple i))) where
  toFun := G.map i
  invFun := G.preimagePart i
  toFun_recursiveIn := G.map_recursiveIn i
  invFun_recursiveIn := (G.preimagePart_recursiveIn hOE).comp
    ((ComputableIn.const i).pair ComputableIn.id)
  toFun_dom := G.map_dom i
  invFun_dom := fun y ↦ by
    rw [G.preimagePart_dom_iff]
    constructor
    · rintro ⟨x, hx⟩
      exact G.mem_canonicalAge_domainAt_of_mem_map hx
    · intro hy
      obtain ⟨x, -, hx⟩ := G.exists_mem_map hy
      exact ⟨x, hx⟩
  toFun_mem := fun h ↦ G.mem_canonicalAge_domainAt_of_mem_map h
  invFun_toFun := fun {x y} h ↦ by
    have hdom : (G.preimagePart i y).Dom := G.preimagePart_dom_iff.2 ⟨x, h⟩
    obtain ⟨x', hx'⟩ := Part.dom_iff_mem.1 hdom
    exact (G.map_injOn (G.mem_preimagePart hx') h) ▸ hx'
  toFun_invFun := fun h ↦ G.mem_preimagePart h
  toFun_funMap := fun n f v w hw ↦ by
    letI : L.Structure ℕ := S.inst
    have hv : ∀ k, v k ∈ A.domainAt (G.sourceIndex i) :=
      fun k ↦ G.mem_domainAt_of_mem_map (hw k)
    have hvw : w = fun k ↦ (G.embedding i ⟨v k, hv k⟩ : ℕ) :=
      funext fun k ↦ G.eq_embedding (hw k)
    subst hvw
    have hfm : @Structure.funMap L ℕ S.inst n f (fun k ↦ (G.embedding i ⟨v k, hv k⟩ : ℕ))
        = G.embedding i
          (@Structure.funMap L (A.memberAt (G.sourceIndex i)).domain _ n f
            fun k ↦ ⟨v k, hv k⟩) :=
      (HomClass.map_fun (G.embedding i) f
        fun k ↦ (⟨v k, hv k⟩ : (A.memberAt (G.sourceIndex i)).domain)).symm
    have hmem := G.map_apply_mem i
      (@Structure.funMap L (A.memberAt (G.sourceIndex i)).domain _ n f fun k ↦ ⟨v k, hv k⟩)
    rw [← hfm] at hmem
    exact hmem
  toFun_relMap := fun n R v w hw ↦ by
    letI : L.Structure ℕ := S.inst
    have hv : ∀ k, v k ∈ A.domainAt (G.sourceIndex i) :=
      fun k ↦ G.mem_domainAt_of_mem_map (hw k)
    have hvw : w = fun k ↦ (G.embedding i ⟨v k, hv k⟩ : ℕ) :=
      funext fun k ↦ G.eq_embedding (hw k)
    subst hvw
    exact (G.embedding i).map_rel' R
      fun k ↦ (⟨v k, hv k⟩ : (A.memberAt (G.sourceIndex i)).domain)

@[simp] theorem isoAt_toFun (hOE : O ⊆ E) (i : ℕ) : (G.isoAt hOE i).toFun = G.map i := rfl

@[simp] theorem isoAt_invFun (hOE : O ⊆ E) (i : ℕ) :
    (G.isoAt hOE i).invFun = G.preimagePart i := rfl

/-- The target index is computable — where reading the recorded generators costs `O ⊆ E`. -/
theorem imageTuple_computableIn (hOE : O ⊆ E) :
    ComputableIn E fun i ↦ encode (G.imageTuple i) := by
  have hpart : RecursiveIn E fun i ↦ G.imageTuplePart i :=
    RecursiveIn.comp (O := E) (α := ℕ) (β := ℕ × Tuple ℕ) (σ := Tuple ℕ)
      (f := fun p : ℕ × Tuple ℕ ↦ listMapPart (G.map p.1) p.2)
      (g := fun i : ℕ ↦ (i, A.gens (G.sourceIndex i)))
      (RecursiveIn.listMapPart₂ (g := G.map) G.map_uniform)
      (ComputableIn.id.pair
        ((RecursiveIn.mono hOE A.gens_computableIn).comp G.sourceIndex_computableIn))
  exact Computable.encode.computableIn.comp
    (RecursiveIn.computableIn_get hpart G.imageTuplePart_dom)

/-! ### The cover out of `𝕂_𝒟`

Available exactly when every query's image tuple is the query's own recorded tuple. That one
equality does two jobs: it identifies the canonical member the query names as the image of the
selected member, so the index map is `sourceIndex`; and it yields generator compatibility, by
inverting the image traversal. No inverse-index assumption is needed anywhere. -/

variable {G} in
/-- Under self-matching, the target index *is* the query. -/
theorem encode_imageTuple_eq {e : ℕ} (he : G.imageTuple e = allTupleFor e) :
    encode (G.imageTuple e) = e := by
  rw [he, allTupleFor, Denumerable.encode_ofNat]

variable {G} in
private theorem canonicalAge_memberAt_domain_eq {e : ℕ}
    (he : G.imageTuple e = allTupleFor e) :
    (S.canonicalAge.memberAt (encode (G.imageTuple e))).domain
      = (S.canonicalAge.memberAt e).domain := by
  rw [encode_imageTuple_eq he]

/-- The per-query isomorphism with its target index rewritten to the query itself. Only the two
domain fields change: `𝕂_𝒟`'s structure data is the same at every index, so the structure laws
transfer verbatim. -/
noncomputable def isoAtSelf (hOE : O ⊆ E) {e : ℕ} (he : G.imageTuple e = allTupleFor e) :
    PartialCeIsoIn E (A.memberAt (G.sourceIndex e)) (S.canonicalAge.memberAt e) where
  toFun := G.map e
  invFun := G.preimagePart e
  toFun_recursiveIn := G.map_recursiveIn e
  invFun_recursiveIn := (G.preimagePart_recursiveIn hOE).comp
    ((ComputableIn.const e).pair ComputableIn.id)
  toFun_dom := G.map_dom e
  invFun_dom := fun y ↦
    ((G.isoAt hOE e).invFun_dom y).trans
      (Set.ext_iff.1 (canonicalAge_memberAt_domain_eq (S := S) he) y)
  toFun_mem := fun h ↦
    (Set.ext_iff.1 (canonicalAge_memberAt_domain_eq (S := S) he) _).1
      ((G.isoAt hOE e).toFun_mem h)
  invFun_toFun := (G.isoAt hOE e).invFun_toFun
  toFun_invFun := (G.isoAt hOE e).toFun_invFun
  toFun_funMap := (G.isoAt hOE e).toFun_funMap
  toFun_relMap := (G.isoAt hOE e).toFun_relMap

@[simp] theorem isoAtSelf_toFun (hOE : O ⊆ E) {e : ℕ}
    (he : G.imageTuple e = allTupleFor e) : (G.isoAtSelf hOE he).toFun = G.map e := rfl

@[simp] theorem isoAtSelf_invFun (hOE : O ⊆ E) {e : ℕ}
    (he : G.imageTuple e = allTupleFor e) :
    (G.isoAtSelf hOE he).invFun = G.preimagePart e := rfl

/-- **The cover `𝕂_𝒟 → A`.** Built from the *per-query* isomorphisms inverted — not by
symmetrizing a cover, which `RepresentationCoverIn` deliberately does not support. -/
noncomputable def fromCanonicalAgeCover (hOE : O ⊆ E)
    (hself : ∀ e, G.imageTuple e = allTupleFor e) :
    RepresentationCoverIn E S.canonicalAge A where
  indexMap := G.sourceIndex
  indexMap_computableIn := G.sourceIndex_computableIn
  isoAt e := (G.isoAtSelf hOE (hself e)).symm
  toFun_uniform := G.preimagePart_recursiveIn hOE
  invFun_uniform := G.map_uniform

@[simp] theorem fromCanonicalAgeCover_indexMap (hOE : O ⊆ E)
    (hself : ∀ e, G.imageTuple e = allTupleFor e) (e : ℕ) :
    (G.fromCanonicalAgeCover hOE hself).indexMap e = G.sourceIndex e :=
  rfl

/-- **Generator compatibility of the cover out of `𝕂_𝒟`.** The same equality that fixed the index
map gives this: the query's recorded tuple *is* the forward image of the selected member's
generators, so pulling it back returns those generators. This is the compatibility CHMM's forward
implication assumes and its reverse implication must construct. -/
theorem fromCanonicalAgeCover_generatorCompatible (hOE : O ⊆ E)
    (hself : ∀ e, G.imageTuple e = allTupleFor e) :
    (G.fromCanonicalAgeCover hOE hself).GeneratorCompatible := by
  intro e
  refine Part.get_eq_of_mem (mem_listMapPart_iff.2 ?_) _
  refine List.Forall₂.flip ?_
  have h := G.forall₂_imageTuple e
  rw [hself e] at h
  exact h.imp fun {x y} hxy ↦ (G.isoAtSelf hOE (hself e)).invFun_toFun hxy

end UniformSelectedEmbeddingIntoIn

/-! ### The self-indexed specialization and the cover into `𝕂_𝒟` -/

namespace UniformEmbeddingIntoIn

variable {A : PartialAgeIn O L} {S : ComputableStructureIn O L}
variable (G : UniformEmbeddingIntoIn E A S)

/-- The query-indexed core, at `sourceIndex := id`. All of the machinery lives there; this is the
only bridge. -/
def toSelected : UniformSelectedEmbeddingIntoIn E A S where
  sourceIndex := id
  sourceIndex_computableIn := ComputableIn.id
  embedding := G.embedding
  map := G.map
  map_uniform := G.map_uniform
  map_dom := G.map_dom
  map_apply_mem := G.map_apply_mem

@[simp] theorem toSelected_sourceIndex : G.toSelected.sourceIndex = id := rfl

@[simp] theorem toSelected_map : G.toSelected.map = G.map := rfl

/-- **The cover onto `𝕂_𝒟`.** Only available at `sourceIndex = id`: a cover's isomorphism at index
`i` must start at member `i`. Its index map is `encode` of the generator-image tuple, so its
generator compatibility is definitional (`allTupleFor_encode`). -/
noncomputable def toCanonicalAgeCover (hOE : O ⊆ E) :
    RepresentationCoverIn E A S.canonicalAge where
  indexMap i := encode (G.toSelected.imageTuple i)
  indexMap_computableIn := G.toSelected.imageTuple_computableIn hOE
  isoAt i := G.toSelected.isoAt hOE i
  toFun_uniform := G.map_uniform
  invFun_uniform := G.toSelected.preimagePart_recursiveIn hOE

@[simp] theorem toCanonicalAgeCover_indexMap (hOE : O ⊆ E) (i : ℕ) :
    (G.toCanonicalAgeCover hOE).indexMap i = encode (G.toSelected.imageTuple i) :=
  rfl

/-- The cover's derived generator image *is* the image tuple: the cover's forward traversal is the
traversal `imageTuplePart` already performed. Definitional, so nothing can drift. -/
@[simp] theorem toCanonicalAgeCover_sourceGensImage (hOE : O ⊆ E) (i : ℕ) :
    (G.toCanonicalAgeCover hOE).sourceGensImage i = G.toSelected.imageTuple i :=
  rfl

/-- **Generator compatibility, for free.** The target index is the image tuple's code and `𝕂_𝒟`
records `allTupleFor` at each index, so the matched member's recorded generators are the image
tuple on the nose — the one fact `CHPSeparationAudit` shows an arbitrary cover need not have, here
by construction. -/
theorem toCanonicalAgeCover_generatorCompatible (hOE : O ⊆ E) :
    (G.toCanonicalAgeCover hOE).GeneratorCompatible :=
  fun i ↦ (allTupleFor_encode (G.toSelected.imageTuple i)).symm

end UniformEmbeddingIntoIn

end FirstOrder.Language
