/-
Copyright (c) 2026 Cameron Freer. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Cameron Freer
-/
import ComputableModelTheory.ModelTheory.Computable.CePresentation

/-!
# Possibly-empty c.e. presentations

The empty-capable presentation layer deferred by #16 to the age tranche: a
presentation whose enumeration is **Option-valued**, so the presented domain may be
empty. CHMM's ages contain structures generated by arbitrary finite tuples, and the
empty tuple matters twice — a nonempty structure may be generated through constants,
and in a constant-free relational language the empty tuple generates the empty
substructure. Neither case fits `CePresentationIn`, whose total enumeration forces a
nonempty domain.

`CePresentationIn.toPartial` embeds the nonempty layer (`toPartial_domain` is the
preservation theorem), and `PartialCePresentationIn.toCePresentation` recovers it
from any witness of nonemptiness of the enumeration — the two layers agree wherever
both apply.
-/

open Encodable Part FirstOrder Language

namespace FirstOrder.Language

variable {O : Set (ℕ →. ℕ)} {L : Language} [L.EffectiveLanguage]

/-- A possibly-empty c.e. presentation: `Option`-valued enumeration, structure data
total on codes, partial evaluators correct on-domain. The domain is the set of
enumerated values and may be empty. -/
structure PartialCePresentationIn (O : Set (ℕ →. ℕ)) (L : Language)
    [L.EffectiveLanguage] where
  /-- The structure data, total on codes; only its on-domain behavior is
  meaningful. -/
  str : L.Structure ℕ
  /-- The `Option`-valued enumeration; `none` steps enumerate nothing. -/
  enum? : ℕ → Option ℕ
  /-- The enumeration is computable in the oracle. -/
  enum?_computableIn : ComputableIn O enum?
  /-- The (possibly empty) domain is closed under function interpretations. -/
  domain_closed : ∀ (n : ℕ) (f : L.Functions n) (v : Fin n → ℕ),
    (∀ k, ∃ m, enum? m = Option.some (v k)) →
      ∃ m, enum? m = Option.some (@Structure.funMap L ℕ str n f v)
  /-- The partial function evaluator. -/
  funEval : FunctionApplicationData L ℕ →. ℕ
  funEval_recursiveIn : RecursiveIn O funEval
  funEval_correct : ∀ d : FunctionApplicationData L ℕ,
    (∀ k, ∃ m, enum? m = Option.some (d.args k)) →
      @FunctionApplicationData.funMap L ℕ str d ∈ funEval d
  /-- The partial relation decider. -/
  relEval : RelationApplicationData L ℕ →. Bool
  relEval_recursiveIn : RecursiveIn O relEval
  relEval_correct : ∀ d : RelationApplicationData L ℕ,
    (∀ k, ∃ m, enum? m = Option.some (d.args k)) →
      ∃ b ∈ relEval d, (b = true ↔ @RelationApplicationData.relMap L ℕ str d)

namespace PartialCePresentationIn

variable (P : PartialCePresentationIn O L)

/-- The domain: the enumerated values. May be empty. -/
def domain : Set ℕ :=
  {x | ∃ m, P.enum? m = Option.some x}

theorem mem_domain_iff {x : ℕ} : x ∈ P.domain ↔ ∃ m, P.enum? m = Option.some x :=
  Iff.rfl

theorem funMap_mem_domain {n : ℕ} (f : L.Functions n) {v : Fin n → ℕ}
    (hv : ∀ k, v k ∈ P.domain) :
    @Structure.funMap L ℕ P.str n f v ∈ P.domain :=
  P.domain_closed n f v hv

/-- The fallback enumeration's range is the domain, given any witnessed value. -/
theorem range_getD {m₀ x₀ : ℕ} (h₀ : P.enum? m₀ = Option.some x₀) :
    Set.range (fun n ↦ (P.enum? n).getD x₀) = P.domain := by
  ext x
  constructor
  · rintro ⟨m, hm⟩
    simp only [] at hm
    rcases he : P.enum? m with - | y
    · rw [he, Option.getD_none] at hm
      exact ⟨m₀, by rw [h₀, hm]⟩
    · rw [he, Option.getD_some] at hm
      exact ⟨m, by rw [he, hm]⟩
  · rintro ⟨m, hm⟩
    refine ⟨m, ?_⟩
    show (P.enum? m).getD x₀ = x
    rw [hm]
    rfl

/-- Recover a nonempty-layer presentation from a witnessed value of the
enumeration: enumeration steps that produce nothing fall back to the witness. -/
noncomputable def toCePresentation {m₀ x₀ : ℕ} (h₀ : P.enum? m₀ = Option.some x₀) :
    CePresentationIn O L where
  str := P.str
  enum n := (P.enum? n).getD x₀
  enum_computableIn :=
    (ComputableIn.option_casesOn P.enum?_computableIn (ComputableIn.const x₀)
      (ComputableIn.snd.to₂)).of_eq fun n ↦ by
        cases P.enum? n <;> rfl
  domain_closed := by
    intro n f v hv
    rw [P.range_getD h₀] at hv ⊢
    exact P.domain_closed n f v hv
  funEval := P.funEval
  funEval_recursiveIn := P.funEval_recursiveIn
  funEval_correct := fun d hd ↦
    P.funEval_correct d fun k ↦ (P.range_getD h₀ ▸ hd k : d.args k ∈ P.domain)
  relEval := P.relEval
  relEval_recursiveIn := P.relEval_recursiveIn
  relEval_correct := fun d hd ↦
    P.relEval_correct d fun k ↦ (P.range_getD h₀ ▸ hd k : d.args k ∈ P.domain)

/-- The recovered nonempty presentation has the same domain. -/
theorem toCePresentation_domain {m₀ x₀ : ℕ} (h₀ : P.enum? m₀ = Option.some x₀) :
    (P.toCePresentation h₀).domain = P.domain :=
  P.range_getD h₀

end PartialCePresentationIn

namespace CePresentationIn

variable (P : CePresentationIn O L)

/-- The embedding of the nonempty layer into the possibly-empty layer. -/
noncomputable def toPartial : PartialCePresentationIn O L where
  str := P.str
  enum? n := Option.some (P.enum n)
  enum?_computableIn := ComputableIn.option_some.comp P.enum_computableIn
  domain_closed := by
    intro n f v hv
    have hv' : ∀ k, v k ∈ P.domain := fun k ↦ by
      obtain ⟨m, hm⟩ := hv k
      exact ⟨m, Option.some_injective ℕ hm⟩
    obtain ⟨m, hm⟩ := P.domain_closed n f v hv'
    exact ⟨m, by rw [hm]⟩
  funEval := P.funEval
  funEval_recursiveIn := P.funEval_recursiveIn
  funEval_correct := fun d hd ↦ P.funEval_correct d fun k ↦ by
    obtain ⟨m, hm⟩ := hd k
    exact ⟨m, Option.some_injective ℕ hm⟩
  relEval := P.relEval
  relEval_recursiveIn := P.relEval_recursiveIn
  relEval_correct := fun d hd ↦ P.relEval_correct d fun k ↦ by
    obtain ⟨m, hm⟩ := hd k
    exact ⟨m, Option.some_injective ℕ hm⟩

/-- Preservation: the embedding keeps the domain. -/
@[simp]
theorem toPartial_domain : P.toPartial.domain = P.domain := by
  ext x
  exact ⟨fun ⟨m, hm⟩ ↦ ⟨m, Option.some_injective ℕ hm⟩,
    fun ⟨m, hm⟩ ↦ ⟨m, by rw [show P.toPartial.enum? m = Option.some (P.enum m) from rfl, hm]⟩⟩

end CePresentationIn

end FirstOrder.Language
