/-
Copyright (c) 2026 Cameron Freer. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Cameron Freer
-/
import ComputableModelTheory.ModelTheory.Computable.PartialCHP
import ComputableModelTheory.ModelTheory.Computable.PartialSameClass

/-!
# CHMM Theorem 2.8, empty-capable setting

The headline assembly. `PartialCHP B` packages what the effective half delivers — a
uniformly partial recursive selector which, on any tuple drawn from a member, halts and
returns a member recorded as generated by **exactly** that tuple, inside the same ambient
structure and with carrier contained in the given member's. The theorem is then

```
HasHP A → ∃ B, SameClass A B ∧ PartialCHP B
```

with witness `A.reindexed`.

The two conjuncts are proved independently: `reindexed_sameClass` consumes the hereditary
property and nothing else, `reindexed_partialCHP` consumes no hypothesis at all. This is
the statement to consume; the step lemmas of `PartialTupleReindex`, `PartialSameClass` and
`PartialCHP` remain reusable infrastructure.
-/

open Encodable Part FirstOrder Language

namespace FirstOrder.Language

variable {O : Set (ℕ →. ℕ)} {L : Language} [L.EffectiveLanguage]

namespace PartialAgeIn

/-- The **computable hereditary property** of an empty-capable family: a uniformly partial
recursive selector which, on any tuple `s` drawn from member `e`, halts and returns a
member recorded as generated by exactly the list `s` — order and multiplicity included —
carrying the same ambient structure data and a carrier contained in member `e`'s.

Nothing is asserted about the selector off these inputs: it is not total, and its domain is
not characterized. -/
def PartialCHP (B : PartialAgeIn O L) : Prop :=
  ∃ sel : ℕ → List ℕ →. ℕ,
    RecursiveIn O (fun p : ℕ × List ℕ ↦ sel p.1 p.2) ∧
      ∀ (e : ℕ) (s : List ℕ), (∀ x ∈ s, x ∈ B.domainAt e) →
        ∃ c ∈ sel e s, B.gens c = s ∧ B.structureAt c = B.structureAt e ∧
          B.domainAt c ⊆ B.domainAt e

/-- What the last two components of `PartialCHP` buy: the selected member embeds in the
given one by the identity on values. No nonemptiness is required, so an empty member
embeds in an empty member. -/
noncomputable def memberEmbedding {B : PartialAgeIn O L} {c e : ℕ}
    (hstr : B.structureAt c = B.structureAt e) (hsub : B.domainAt c ⊆ B.domainAt e) :
    (B.memberAt c).domain ↪[L] (B.memberAt e).domain :=
  PartialCePresentationIn.subsetDomainEmbedding hstr hsub

/-- The tuple re-indexing has the computable hereditary property — with **no** hypothesis
on `A`, in particular none about the semantic hereditary property. -/
theorem reindexed_partialCHP (A : PartialAgeIn O L) : A.reindexed.PartialCHP := by
  refine ⟨A.chpSelect, A.chpSelect_recursiveIn, fun e s hs ↦ ?_⟩
  obtain ⟨c, hc⟩ := Part.dom_iff_mem.1 (chpSelect_dom hs)
  refine ⟨c, hc, gens_of_mem_chpSelect hc, ?_, chpSelect_domainAt_subset hc hs⟩
  show A.structureAt (memberIndex c).1 = A.structureAt (memberIndex e).1
  rw [memberIndex_fst_of_mem_chpSelect hc]

/-! ### The paper-facing selector contract

`PartialCHP` is the *theorem-facing* interface: it records that the selected member's
generator tuple is **literally** the queried list, which is what the tuple re-indexing
delivers and what makes the located member a substructure on the nose.

CHMM's own hereditary-property contract asks for less: the selected member's recorded
generators need only **map coordinatewise** onto the queried tuple, that map extending to an
embedding. `MappedPartialCHP` is that weaker, paper-exact interface. Keeping the two apart
avoids both weakening the proved theorem and padding it with a redundant clause; the
implication runs one way and unconditionally. -/

/-- The **paper-exact** computable hereditary property: a uniformly partial recursive
selector which, on a tuple `s` drawn from member `e`, halts and returns a member whose
recorded generators map coordinatewise onto `s` via an embedding of its carrier into member
`e`'s.

Weaker than `PartialCHP`: the generators need not *equal* `s`, only map onto it in order. -/
def MappedPartialCHP (B : PartialAgeIn O L) : Prop :=
  ∃ sel : ℕ → List ℕ →. ℕ,
    RecursiveIn O (fun p : ℕ × List ℕ ↦ sel p.1 p.2) ∧
      ∀ (e : ℕ) (s : List ℕ), (∀ x ∈ s, x ∈ B.domainAt e) →
        ∃ c ∈ sel e s, ∃ hlen : (B.gens c).length = s.length,
          ∃ F : (B.memberAt c).domain ↪[L] (B.memberAt e).domain,
            ∀ k : Fin (B.gens c).length,
              ((F ⟨(B.gens c).get k, B.gens_mem_domainAt k⟩ : (B.memberAt e).domain) : ℕ) =
                s.get (Fin.cast hlen k)

/-- The theorem-facing contract implies the paper-facing one, **unconditionally**: exact
generator equality gives the coordinatewise map as the identity, and the carrier inclusion
gives the embedding. The converse is not part of this reconciliation — recovering exact
generator equality from a coordinatewise map would need an explicit strictification or
re-indexing hypothesis. -/
theorem PartialCHP.mappedPartialCHP {B : PartialAgeIn O L} (h : B.PartialCHP) :
    B.MappedPartialCHP := by
  obtain ⟨sel, hsel, hspec⟩ := h
  refine ⟨sel, hsel, fun e s hs ↦ ?_⟩
  obtain ⟨c, hc, hgens, hstr, hsub⟩ := hspec e s hs
  subst hgens
  exact ⟨c, hc, rfl, memberEmbedding hstr hsub, fun _ ↦ rfl⟩

/-- **CHMM Theorem 2.8, empty-capable setting.** A uniformly computable family of finitely
generated possibly-empty members with the semantic hereditary property is represented by a
family with the same isomorphism classes admitting a computable hereditary-property
selector. The witness is the tuple re-indexing.

Level 1 throughout: no member is claimed decidable, no isomorphism is claimed computable,
and the selector is partial. -/
theorem exists_sameClass_partialCHP (A : PartialAgeIn O L) (h : A.HasHP) :
    ∃ B : PartialAgeIn O L, A.SameClass B ∧ B.PartialCHP :=
  ⟨A.reindexed, (A.reindexed_sameClass h).symm, A.reindexed_partialCHP⟩

end PartialAgeIn

end FirstOrder.Language
