/-
Copyright (c) 2026 Cameron Freer. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Cameron Freer
-/
import ComputableModelTheory.ModelTheory.Computable.ComputableIso
import ComputableModelTheory.ModelTheory.Computable.PartialAgeSemantics

/-!
# Computable isomorphism of possibly-empty presentations

The empty-capable analogue of `CeIsoIn`: partial recursive back-and-forth maps between two
`PartialCePresentationIn` members, halting exactly on their domains.

Two things distinguish this from `CeIsoIn`.

**The map oracle is separate from the family oracle.** A `PartialCeIsoIn E P Q` has maps
recursive in `E`, while `P` and `Q` are presented relative to `O`. Nothing here relates the two.
A transport theorem that must *compute family data* while following the isomorphism carries
`O ⊆ E` as an explicit hypothesis rather than having it built into the interface — the same
discipline the witness interfaces already use.

**Empty domains are allowed.** If both domains are empty both maps are nowhere defined, which
the halting laws state exactly. This is what makes the notion usable at Definition 2.1, where
members include the substructure generated by the empty tuple.

This is a *single-member* building block. The paper-facing notion — CHMM Definition 2.3, an
isomorphism of whole representations — is built from it by supplying an index map and a family
of these, in each direction independently; see `RepresentationIso`.
-/

open Encodable Part FirstOrder Language

namespace FirstOrder.Language

variable {O E : Set (ℕ →. ℕ)} {L : Language} [L.EffectiveLanguage]

/-- **Computable isomorphism of possibly-empty presentations.** Partial recursive maps in `E`,
halting exactly on the two domains, mutually inverse there, preserving function interpretations
and preserving *and reflecting* relations on realized pairs.

Only the forward laws are fields; the inverse-side laws, injectivity and surjectivity are
derived, as for `CeIsoIn`. -/
structure PartialCeIsoIn (E : Set (ℕ →. ℕ)) (P Q : PartialCePresentationIn O L) where
  /-- The forward map. -/
  toFun : ℕ →. ℕ
  /-- The backward map. -/
  invFun : ℕ →. ℕ
  toFun_recursiveIn : RecursiveIn E toFun
  invFun_recursiveIn : RecursiveIn E invFun
  /-- The forward map halts exactly on the source domain — vacuous when that domain is
  empty. -/
  toFun_dom : ∀ x, (toFun x).Dom ↔ x ∈ P.domain
  /-- The backward map halts exactly on the target domain. -/
  invFun_dom : ∀ y, (invFun y).Dom ↔ y ∈ Q.domain
  /-- Forward values land in the target domain. -/
  toFun_mem : ∀ {x y}, y ∈ toFun x → y ∈ Q.domain
  /-- The backward map inverts the forward map. -/
  invFun_toFun : ∀ {x y}, y ∈ toFun x → x ∈ invFun y
  /-- The forward map inverts the backward map. -/
  toFun_invFun : ∀ {y x}, x ∈ invFun y → y ∈ toFun x
  /-- The forward map preserves function interpretations on realized pairs. -/
  toFun_funMap : ∀ (n : ℕ) (f : L.Functions n) (v w : Fin n → ℕ),
    (∀ k, w k ∈ toFun (v k)) →
      @Structure.funMap L ℕ Q.str n f w ∈ toFun (@Structure.funMap L ℕ P.str n f v)
  /-- The forward map preserves and reflects relation interpretations on realized pairs. -/
  toFun_relMap : ∀ (n : ℕ) (R : L.Relations n) (v w : Fin n → ℕ),
    (∀ k, w k ∈ toFun (v k)) →
      (@Structure.RelMap L ℕ Q.str n R w ↔ @Structure.RelMap L ℕ P.str n R v)

namespace PartialCeIsoIn

variable {P Q W : PartialCePresentationIn O L} (e : PartialCeIsoIn E P Q)

/-- Backward values land in the source domain. -/
theorem invFun_mem {y x : ℕ} (h : x ∈ e.invFun y) : x ∈ P.domain :=
  (e.toFun_dom x).1 (Part.dom_iff_mem.2 ⟨y, e.toFun_invFun h⟩)

/-- The inverse isomorphism: the two maps exchanged, with the derived laws becoming fields. -/
def symm : PartialCeIsoIn E Q P where
  toFun := e.invFun
  invFun := e.toFun
  toFun_recursiveIn := e.invFun_recursiveIn
  invFun_recursiveIn := e.toFun_recursiveIn
  toFun_dom := e.invFun_dom
  invFun_dom := e.toFun_dom
  toFun_mem := e.invFun_mem
  invFun_toFun := e.toFun_invFun
  toFun_invFun := e.invFun_toFun
  toFun_funMap := fun n f v w hw ↦ by
    have hv : ∀ k, v k ∈ e.toFun (w k) := fun k ↦ e.toFun_invFun (hw k)
    exact e.invFun_toFun (e.toFun_funMap n f w v hv)
  toFun_relMap := fun n R v w hw ↦ by
    have hv : ∀ k, v k ∈ e.toFun (w k) := fun k ↦ e.toFun_invFun (hw k)
    exact (e.toFun_relMap n R w v hv).symm

@[simp] theorem symm_toFun : e.symm.toFun = e.invFun := rfl
@[simp] theorem symm_invFun : e.symm.invFun = e.toFun := rfl

/-- The isomorphism is single-valued on the domain. -/
theorem toFun_unique {x y y' : ℕ} (h : y ∈ e.toFun x) (h' : y' ∈ e.toFun x) : y = y' :=
  Part.mem_unique h h'

/-- The isomorphism is injective where defined. -/
theorem toFun_injective {x x' y : ℕ} (h : y ∈ e.toFun x) (h' : y ∈ e.toFun x') : x = x' :=
  Part.mem_unique (e.invFun_toFun h) (e.invFun_toFun h')

/-- Every target-domain element is hit. -/
theorem exists_toFun {y : ℕ} (hy : y ∈ Q.domain) : ∃ x, y ∈ e.toFun x := by
  obtain ⟨x, hx⟩ := Part.dom_iff_mem.1 ((e.invFun_dom y).2 hy)
  exact ⟨x, e.toFun_invFun hx⟩

/-! ### The semantic content -/

/-- The value the isomorphism assigns to a domain element, as a target-domain element. -/
noncomputable def toSubtypeFun (x : P.domain) : Q.domain :=
  ⟨(e.toFun x.1).get ((e.toFun_dom x.1).2 x.2), e.toFun_mem (Part.get_mem _)⟩

theorem toSubtypeFun_mem (x : P.domain) : (e.toSubtypeFun x).1 ∈ e.toFun x.1 :=
  Part.get_mem _

/-- **The induced first-order equivalence.** The semantic content of a computable isomorphism
of possibly-empty presentations: the two carriers, with their induced structures, are
isomorphic. Vacuously so when both are empty. -/
noncomputable def toEquiv : P.domain ≃[L] Q.domain where
  toFun := e.toSubtypeFun
  invFun := e.symm.toSubtypeFun
  left_inv := fun x ↦ Subtype.ext
    (Part.mem_unique (e.symm.toSubtypeFun_mem (e.toSubtypeFun x))
      (e.invFun_toFun (e.toSubtypeFun_mem x)))
  right_inv := fun y ↦ Subtype.ext
    (Part.mem_unique (e.toSubtypeFun_mem (e.symm.toSubtypeFun y))
      (e.toFun_invFun (e.symm.toSubtypeFun_mem y)))
  map_fun' := fun {n} f v ↦ Subtype.ext
    (Part.mem_unique (e.toSubtypeFun_mem _)
      (e.toFun_funMap n f (fun k ↦ (v k : ℕ)) (fun k ↦ ((e.toSubtypeFun (v k) : Q.domain) : ℕ))
        fun k ↦ e.toSubtypeFun_mem (v k)))
  map_rel' := fun {n} R v ↦
    e.toFun_relMap n R (fun k ↦ (v k : ℕ))
      (fun k ↦ ((e.toSubtypeFun (v k) : Q.domain) : ℕ)) fun k ↦ e.toSubtypeFun_mem (v k)

@[simp] theorem toEquiv_apply (x : P.domain) : e.toEquiv x = e.toSubtypeFun x := rfl

/-! ### Two-ended conjugation

Transporting an embedding needs an isomorphism at **each end**, and the two are supplied
independently. That generality is not decoration: in a two-cover setting the source and target
ends may come from different covers, with unrelated index maps and no round-trip equation
between them. Tying both ends to one indexed family — the diagonal case — would silently assume
exactly the round trip CHMM Definition 2.3 declines to require. -/

/-- **Conjugate an embedding along isomorphisms at its two ends.** -/
noncomputable def conjugate {P Q P' Q' : PartialCePresentationIn O L}
    (σ : PartialCeIsoIn E P P') (τ : PartialCeIsoIn E Q Q')
    (f : P.domain ↪[L] Q.domain) : P'.domain ↪[L] Q'.domain :=
  (τ.toEquiv.toEmbedding.comp f).comp σ.toEquiv.symm.toEmbedding

@[simp] theorem conjugate_apply {P Q P' Q' : PartialCePresentationIn O L}
    (σ : PartialCeIsoIn E P P') (τ : PartialCeIsoIn E Q Q')
    (f : P.domain ↪[L] Q.domain) (y : P'.domain) :
    conjugate σ τ f y = τ.toEquiv (f (σ.toEquiv.symm y)) := rfl

/-- On the source isomorphism's image the conjugate is the target isomorphism's image of `f` —
the equation every coordinate computation reduces to. -/
theorem conjugate_toEquiv {P Q P' Q' : PartialCePresentationIn O L}
    (σ : PartialCeIsoIn E P P') (τ : PartialCeIsoIn E Q Q')
    (f : P.domain ↪[L] Q.domain) (x : P.domain) :
    conjugate σ τ f (σ.toEquiv x) = τ.toEquiv (f x) := by
  rw [conjugate_apply, Equiv.symm_apply_apply]

/-- **Composition.** Genuine reusable single-member API: the forward maps compose by `bind`,
the backward maps compose in the reverse order. -/
def trans {W : PartialCePresentationIn O L} (e : PartialCeIsoIn E P Q)
    (f : PartialCeIsoIn E Q W) : PartialCeIsoIn E P W where
  toFun x := (e.toFun x).bind f.toFun
  invFun z := (f.invFun z).bind e.invFun
  toFun_recursiveIn :=
    RecursiveIn.bind e.toFun_recursiveIn (f.toFun_recursiveIn.comp ComputableIn.snd).to₂
  invFun_recursiveIn :=
    RecursiveIn.bind f.invFun_recursiveIn (e.invFun_recursiveIn.comp ComputableIn.snd).to₂
  toFun_dom := fun x ↦ by
    rw [Part.dom_iff_mem]
    constructor
    · rintro ⟨z, hz⟩
      obtain ⟨y, hy, -⟩ := Part.mem_bind_iff.1 hz
      exact (e.toFun_dom x).1 (Part.dom_iff_mem.2 ⟨y, hy⟩)
    · intro hx
      have hd : (e.toFun x).Dom := (e.toFun_dom x).2 hx
      have hy : (e.toFun x).get hd ∈ e.toFun x := Part.get_mem hd
      obtain ⟨z, hz⟩ := Part.dom_iff_mem.1 ((f.toFun_dom _).2 (e.toFun_mem hy))
      exact ⟨z, Part.mem_bind_iff.2 ⟨_, hy, hz⟩⟩
  invFun_dom := fun z ↦ by
    rw [Part.dom_iff_mem]
    constructor
    · rintro ⟨x, hx⟩
      obtain ⟨y, hy, -⟩ := Part.mem_bind_iff.1 hx
      exact (f.invFun_dom z).1 (Part.dom_iff_mem.2 ⟨y, hy⟩)
    · intro hz
      have hd : (f.invFun z).Dom := (f.invFun_dom z).2 hz
      have hy : (f.invFun z).get hd ∈ f.invFun z := Part.get_mem hd
      obtain ⟨x, hx⟩ := Part.dom_iff_mem.1 ((e.invFun_dom _).2 (f.invFun_mem hy))
      exact ⟨x, Part.mem_bind_iff.2 ⟨_, hy, hx⟩⟩
  toFun_mem := fun h ↦ by
    obtain ⟨y, -, hz⟩ := Part.mem_bind_iff.1 h
    exact f.toFun_mem hz
  invFun_toFun := fun h ↦ by
    obtain ⟨y, hy, hz⟩ := Part.mem_bind_iff.1 h
    exact Part.mem_bind_iff.2 ⟨y, f.invFun_toFun hz, e.invFun_toFun hy⟩
  toFun_invFun := fun h ↦ by
    obtain ⟨y, hy, hx⟩ := Part.mem_bind_iff.1 h
    exact Part.mem_bind_iff.2 ⟨y, e.toFun_invFun hx, f.toFun_invFun hy⟩
  toFun_funMap := fun n g v w hw ↦ by
    choose u hu using fun k ↦ Part.mem_bind_iff.1 (hw k)
    have hu1 : ∀ k, u k ∈ e.toFun (v k) := fun k ↦ (hu k).1
    have hu2 : ∀ k, w k ∈ f.toFun (u k) := fun k ↦ (hu k).2
    exact Part.mem_bind_iff.2
      ⟨_, e.toFun_funMap n g v u hu1, f.toFun_funMap n g u w hu2⟩
  toFun_relMap := fun n R v w hw ↦ by
    choose u hu using fun k ↦ Part.mem_bind_iff.1 (hw k)
    exact (f.toFun_relMap n R u w fun k ↦ (hu k).2).trans
      (e.toFun_relMap n R v u fun k ↦ (hu k).1)

end PartialCeIsoIn

/-! ### The bridge from the nonempty layer

A `CeIsoIn` between all-carrier presentations is a `PartialCeIsoIn` between their images in the
possibly-empty layer. Stated at a single oracle: oracle monotonicity is a separate concern and
should not be smuggled into the bridge. -/

/-- Every computable isomorphism of nonempty presentations is one of the corresponding
possibly-empty presentations. -/
noncomputable def CeIsoIn.toPartialIso {P Q : CePresentationIn O L} (e : CeIsoIn P Q) :
    PartialCeIsoIn O P.toPartial Q.toPartial where
  toFun := e.toFun
  invFun := e.invFun
  toFun_recursiveIn := e.toFun_recursiveIn
  invFun_recursiveIn := e.invFun_recursiveIn
  toFun_dom := fun x ↦ (e.toFun_dom x).trans
    ⟨fun ⟨m, hm⟩ ↦ ⟨m, congrArg Option.some hm⟩,
      fun ⟨m, hm⟩ ↦ ⟨m, Option.some_injective ℕ hm⟩⟩
  invFun_dom := fun y ↦ (e.invFun_dom y).trans
    ⟨fun ⟨m, hm⟩ ↦ ⟨m, congrArg Option.some hm⟩,
      fun ⟨m, hm⟩ ↦ ⟨m, Option.some_injective ℕ hm⟩⟩
  toFun_mem := fun h ↦ by
    obtain ⟨m, hm⟩ := e.toFun_mem h
    exact ⟨m, congrArg Option.some hm⟩
  invFun_toFun := e.invFun_toFun
  toFun_invFun := e.toFun_invFun
  toFun_funMap := e.toFun_funMap
  toFun_relMap := e.toFun_relMap

end FirstOrder.Language
