/-
Copyright (c) 2026 Cameron Freer. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Cameron Freer
-/
import ComputableModelTheory.ModelTheory.Computable.PartialAgeSteps
import ComputableModelTheory.ModelTheory.Computable.PartialTermEvaluation
import ComputableModelTheory.ModelTheory.TupleClosure

/-!
# The generated enumeration inside an empty-capable member

The enumeration of the substructure of member `i` generated by an on-domain tuple, for
the tuple re-indexing of CHMM Theorem 2.8 at the empty-capable layer. Where the all-ℕ
construction (`ComputableStructureIn.genEnum?`) decodes a `Term (Fin t.length)` and
realizes it outright — legitimate there, since an all-ℕ member interprets everything —
the empty-capable member has only a **partial** evaluator, so the enumeration decodes an
`L.Term ℕ` and runs the partial machine of `PartialTermEvaluation`.

Two facts make that enumeration a total computable `Option`-valued function even though
its engine is partial:

* the environment `tupleAtSteps i steps` is on-domain **by construction**, and
* `Term.varsBelowBool` **decides** the halting condition (`partialRealize_dom_iff`).

So `termPlan` filters codes down to terms the machine provably halts on, and the guarded
call that follows is a partial recursive function that is in fact total — hence
computable. No step-bounded approximation and no halting oracle is involved.

The payoff is the range equality

```
range (genEnum? i steps) = Substructure.closure L (Set.range (tupleAtSteps i steps).view)
```

(`exists_genEnum?_eq_some_iff`), crossing between the natural-variable machine and the
fixed-width semantic gate `mem_closure_range_iff_exists_term` by the `restrictVar`/
`relabel` bridge. It is what identifies the re-indexed member with the generated
substructure it is supposed to be.
-/

open Encodable Part FirstOrder Language

namespace FirstOrder.Language

variable {O : Set (ℕ →. ℕ)} {L : Language} [L.EffectiveLanguage]

namespace Term

/-- The bounded decode: a code names a term only when every variable of that term is
addressable in an environment of the given length. This is the decidable guard that makes
the partial evaluator total on the codes it admits. -/
def boundedDecode (k m : ℕ) : Option (L.Term ℕ) :=
  (@decode (L.Term ℕ) Primcodable.toEncodable m).bind fun t ↦
    bif varsBelowBool k t then Option.some t else Option.none

theorem boundedDecode_eq_some_iff {k m : ℕ} {t : L.Term ℕ} :
    boundedDecode k m = Option.some t ↔
      (@decode (L.Term ℕ) Primcodable.toEncodable m) = Option.some t ∧ VarsBelow k t := by
  rw [boundedDecode, Option.bind_eq_some_iff]
  constructor
  · rintro ⟨u, hu, hcond⟩
    cases hb : varsBelowBool k u with
    | false =>
      rw [hb, cond_false] at hcond
      exact absurd hcond (by simp)
    | true =>
      rw [hb, cond_true, Option.some_inj] at hcond
      exact ⟨hcond ▸ hu, hcond ▸ (varsBelowBool_iff k u).1 hb⟩
  · rintro ⟨hd, hv⟩
    exact ⟨t, hd, by rw [(varsBelowBool_iff k t).2 hv, cond_true]⟩

/-- Every bounded term is named by some code. -/
theorem exists_boundedDecode_eq_some {k : ℕ} {t : L.Term ℕ} (ht : VarsBelow k t) :
    ∃ m, boundedDecode k m = Option.some t :=
  ⟨@encode (L.Term ℕ) Primcodable.toEncodable t,
    boundedDecode_eq_some_iff.2
      ⟨@Encodable.encodek (L.Term ℕ) Primcodable.toEncodable t, ht⟩⟩

/-- The bounded decode is primitive recursive, uniformly in the bound. -/
theorem primrec₂_boundedDecode : Primrec₂ (boundedDecode (L := L)) :=
  Primrec.option_bind ((Primrec.decode (α := L.Term ℕ)).comp Primrec.snd)
    ((Primrec.cond (primrec₂_varsBelowBool.comp (Primrec.fst.comp Primrec.fst) Primrec.snd)
      (Primrec.option_some.comp Primrec.snd) (Primrec.const Option.none)).to₂)

end Term

namespace PartialAgeIn

variable (A : PartialAgeIn O L)

/-! ### The generated enumeration -/

/-- The enumeration of the substructure of member `i` generated by the on-domain tuple
`tupleAtSteps i steps`: decode a bounded natural-variable term and realize it in the
environment given by that tuple. Codes that name no bounded term enumerate nothing — so
over an empty tuple in a constant-free relational language the enumeration is genuinely
empty.

The definition is semantic; the partial machine enters only in `genEnum?_computableIn`,
where it is what actually computes this. -/
noncomputable def genEnum? (i : ℕ) (steps : List ℕ) (m : ℕ) : Option ℕ :=
  (Term.boundedDecode (L := L) (A.tupleAtSteps i steps).length m).map fun t ↦
    @Term.realize L ℕ (A.structureAt i) ℕ
      (ComputableAgeIn.envFun (A.tupleAtSteps i steps)) t

variable {A}

/-- The environment of the generated enumeration is on-domain by construction — the
hypothesis every on-domain correctness statement of the machine needs. -/
theorem tupleAtSteps_mem_domainAt (i : ℕ) (steps : List ℕ) :
    ∀ x ∈ A.tupleAtSteps i steps, x ∈ A.domainAt i :=
  A.tupleAtSteps_forall_mem_domainAt steps

/-- The enumeration reports exactly the realizations of the bounded terms it admits. -/
theorem genEnum?_eq_some_iff {i : ℕ} {steps : List ℕ} {m x : ℕ} :
    A.genEnum? i steps m = Option.some x ↔
      ∃ t : L.Term ℕ,
        Term.boundedDecode (L := L) (A.tupleAtSteps i steps).length m = Option.some t ∧
          @Term.realize L ℕ (A.structureAt i) ℕ
            (ComputableAgeIn.envFun (A.tupleAtSteps i steps)) t = x := by
  rw [genEnum?, Option.map_eq_some_iff]

theorem genEnum?_of_boundedDecode {i : ℕ} {steps : List ℕ} {m : ℕ} {t : L.Term ℕ}
    (h : Term.boundedDecode (L := L) (A.tupleAtSteps i steps).length m = Option.some t) :
    A.genEnum? i steps m = Option.some (@Term.realize L ℕ (A.structureAt i) ℕ
      (ComputableAgeIn.envFun (A.tupleAtSteps i steps)) t) :=
  genEnum?_eq_some_iff.2 ⟨t, h, rfl⟩

/-- **The range equality.** The generated enumeration hits exactly the substructure
generated by the on-domain tuple: the term closure of `tupleAtSteps i steps` inside member
`i`. The natural-variable machine and the fixed-width semantic gate are matched by the
`restrictVar`/`relabel` bridge. -/
theorem exists_genEnum?_eq_some_iff {i : ℕ} {steps : List ℕ} {x : ℕ} :
    (∃ m, A.genEnum? i steps m = Option.some x) ↔
      x ∈ @Substructure.closure L ℕ (A.structureAt i)
        (Set.range (Tuple.view (A.tupleAtSteps i steps))) := by
  letI : L.Structure ℕ := A.structureAt i
  set env := A.tupleAtSteps i steps with henv
  rw [mem_closure_range_iff_exists_term]
  constructor
  · rintro ⟨m, hm⟩
    obtain ⟨t, hdec, hval⟩ := genEnum?_eq_some_iff.1 hm
    refine ⟨t.restrictVar fun v ↦
      (⟨v.1, (Term.boundedDecode_eq_some_iff.1 hdec).2 v.1 v.2⟩ : Fin env.length), ?_⟩
    rw [← hval]
    exact (Term.realize_envFun_restrictVar (env := env) rfl t
      (Term.boundedDecode_eq_some_iff.1 hdec).2).symm
  · rintro ⟨T, rfl⟩
    obtain ⟨m, hm⟩ :=
      Term.exists_boundedDecode_eq_some (Term.varsBelow_relabel_val (k := env.length) T)
    refine ⟨m, ?_⟩
    rw [genEnum?_of_boundedDecode hm, Term.realize_envFun_relabel_val (env := env) rfl T]
    rfl

/-- Every value of the generated enumeration lies in the ambient member's carrier: the
generated substructure sits inside the member. -/
theorem genEnum?_mem_domainAt {i : ℕ} {steps : List ℕ} {m x : ℕ}
    (h : A.genEnum? i steps m = Option.some x) : x ∈ A.domainAt i := by
  obtain ⟨t, hdec, rfl⟩ := genEnum?_eq_some_iff.1 h
  exact realize_mem_domainAt (tupleAtSteps_mem_domainAt i steps)
    (Term.boundedDecode_eq_some_iff.1 hdec).2

variable (A)

/-! ### Uniform computability of the generated enumeration

The engine is partial, but the enumeration is total: `Term.boundedDecode` admits only
codes the machine halts on, so the guarded call below is a partial recursive function that
is everywhere defined — and an everywhere-defined partial recursive function is
computable. -/

theorem genEnum?_computableIn :
    ComputableIn O fun p : (ℕ × List ℕ) × ℕ ↦ A.genEnum? p.1.1 p.1.2 p.2 := by
  have henv : ComputableIn O fun p : (ℕ × List ℕ) × ℕ ↦ A.tupleAtSteps p.1.1 p.1.2 :=
    A.tupleAtSteps_computableIn.comp ComputableIn.fst
  have hdec : ComputableIn O fun p : (ℕ × List ℕ) × ℕ ↦
      Term.boundedDecode (L := L) (A.tupleAtSteps p.1.1 p.1.2).length p.2 :=
    (Term.primrec₂_boundedDecode (L := L)).to_comp.computableIn₂.comp
      ((Computable.list_length.computableIn).comp henv) ComputableIn.snd
  have hcall : RecursiveIn O fun q : ((ℕ × List ℕ) × ℕ) × L.Term ℕ ↦
      A.partialRealize q.1.1.1 (A.tupleAtSteps q.1.1.1 q.1.1.2) q.2 :=
    RecursiveIn.comp (O := O) (α := ((ℕ × List ℕ) × ℕ) × L.Term ℕ)
      (β := (ℕ × Tuple ℕ) × L.Term ℕ) (σ := ℕ)
      (f := fun r : (ℕ × Tuple ℕ) × L.Term ℕ ↦ A.partialRealize r.1.1 r.1.2 r.2)
      (g := fun q : ((ℕ × List ℕ) × ℕ) × L.Term ℕ ↦
        ((q.1.1.1, A.tupleAtSteps q.1.1.1 q.1.1.2), q.2))
      A.partialRealize_recursiveIn
      (ComputableIn.pair (O := O) (α := ((ℕ × List ℕ) × ℕ) × L.Term ℕ)
        (β := ℕ × Tuple ℕ) (γ := L.Term ℕ)
        (f := fun q ↦ (q.1.1.1, A.tupleAtSteps q.1.1.1 q.1.1.2)) (g := fun q ↦ q.2)
        (ComputableIn.pair (O := O) (α := ((ℕ × List ℕ) × ℕ) × L.Term ℕ) (β := ℕ)
          (γ := Tuple ℕ)
          (f := fun q ↦ q.1.1.1) (g := fun q ↦ A.tupleAtSteps q.1.1.1 q.1.1.2)
          ((Primrec.fst.comp (Primrec.fst.comp Primrec.fst)).to_comp.computableIn)
          (henv.comp (ComputableIn.fst (O := O) (α := (ℕ × List ℕ) × ℕ) (β := L.Term ℕ))))
        (ComputableIn.snd (O := O) (α := (ℕ × List ℕ) × ℕ) (β := L.Term ℕ)))
  have hpart : RecursiveIn O fun p : (ℕ × List ℕ) × ℕ ↦
      Option.casesOn (motive := fun _ ↦ Part (Option ℕ))
        (Term.boundedDecode (L := L) (A.tupleAtSteps p.1.1 p.1.2).length p.2)
        (Part.some Option.none)
        fun t ↦ (A.partialRealize p.1.1 (A.tupleAtSteps p.1.1 p.1.2) t).map Option.some :=
    RecursiveIn.option_casesOn_right (O := O) (α := (ℕ × List ℕ) × ℕ) (β := L.Term ℕ)
      (σ := Option ℕ)
      (o := fun p ↦ Term.boundedDecode (L := L) (A.tupleAtSteps p.1.1 p.1.2).length p.2)
      (f := fun _ ↦ Option.none)
      (g := fun p t ↦ (A.partialRealize p.1.1 (A.tupleAtSteps p.1.1 p.1.2) t).map
        Option.some)
      hdec (ComputableIn.const Option.none)
      ((RecursiveIn.map (O := O) (α := ((ℕ × List ℕ) × ℕ) × L.Term ℕ) (β := ℕ)
        (σ := Option ℕ)
        (f := fun q ↦ A.partialRealize q.1.1.1 (A.tupleAtSteps q.1.1.1 q.1.1.2) q.2)
        (g := fun _ (v : ℕ) ↦ Option.some v)
        hcall (ComputableIn.option_some.comp ComputableIn.snd).to₂).to₂)
  refine hpart.of_eq fun p ↦ ?_
  show _ = Part.some (A.genEnum? p.1.1 p.1.2 p.2)
  rw [genEnum?]
  rcases h : Term.boundedDecode (L := L) (A.tupleAtSteps p.1.1 p.1.2).length p.2 with - | t
  · rfl
  · show (A.partialRealize p.1.1 (A.tupleAtSteps p.1.1 p.1.2) t).map Option.some = _
    rw [partialRealize_eq_some (tupleAtSteps_mem_domainAt p.1.1 p.1.2)
      (Term.boundedDecode_eq_some_iff.1 h).2]
    rfl

end PartialAgeIn

end FirstOrder.Language
