/-
Copyright (c) 2026 Cameron Freer. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Cameron Freer
-/
import ComputableModelTheory.ModelTheory.Computable.PartialPotentialTransport
import ComputableModelTheory.ModelTheory.Computable.SuccExample
import ComputableModelTheory.Computability.ListPredicates
import ComputableModelTheory.Util.AssertAxioms

/-!
# Audit module for applying potential embedding data

One fixture, the **successor tails**: member `i` is `{i, i+1, i+2, …}` inside the successor
structure, generated by the single recorded generator `[i]`.

The fixture is chosen so the headline row is about a **non-generator**. `applyPotentialPart` finds
a term over the recorded generators and re-realizes it against the range tuple; on a generator that
term is a variable and the row would pass even if the term search were skipped entirely. Member `0`
is all of `ℕ` and its only generator is `0`, so `5` is reached only through five applications of
the function symbol — and `5 ↦ 7` therefore exercises the whole route. The numbers are distinct
from each other and from the indices, so a shift in the wrong direction, or the identity, fails
numerically rather than symbolically.

Two further boundaries this family reaches that a finite fixture cannot: the carriers are infinite,
and they are *proper* subsets of `ℕ` for `i > 0`, so the search genuinely diverges below a
member's least element.
-/

open Encodable Part FirstOrder Language

namespace FirstOrder.Language

section

variable {O : Set (ℕ →. ℕ)}

attribute [local instance] succStructure

/-! ### The successor-tail family -/

/-- The `n`-fold successor of the single variable. -/
private def iterSucc : ℕ → succLang.Term (Fin 1)
  | 0 => Term.var 0
  | n + 1 => Term.func SuccFunctions.succ fun _ ↦ iterSucc n

private theorem iterSucc_realize (i n : ℕ) :
    @Term.realize succLang ℕ succStructure _ (Tuple.view [i]) (iterSucc n) = i + n := by
  induction n with
  | zero => rfl
  | succ n ih =>
    show @Term.realize succLang ℕ succStructure _ (Tuple.view [i]) (iterSucc n) + 1 = i + (n + 1)
    omega

/-- Every term over the single generator `i` realizes at or above `i`, by an explicit offset. -/
private theorem exists_realize_add (i : ℕ) (T : succLang.Term (Fin (List.length [i]))) :
    ∃ n, @Term.realize succLang ℕ succStructure _ (Tuple.view [i]) T = i + n := by
  induction T with
  | var v =>
    match v with
    | ⟨0, _⟩ => exact ⟨0, rfl⟩
  | @func n f ts ih =>
    match n, f with
    | 1, .succ =>
      obtain ⟨k, hk⟩ := ih 0
      refine ⟨k + 1, ?_⟩
      show @Term.realize succLang ℕ succStructure _ (Tuple.view [i]) (ts 0) + 1 = i + (k + 1)
      omega

/-- The evaluator's total work, extracted and fully typed: fusing it into the structure instance
below stalls at `whnf`, the established remedy for a composition whose input is a projection into
an `ofEquiv`-encoded type. -/
private theorem succArgHead_primrec :
    Primrec fun d : FunctionApplicationData succLang ℕ ↦ d.argsList[0]! + 1 :=
  Primrec.succ.comp
    ((Primrec.list_getElem! (β := ℕ)).comp FunctionApplicationData.primrec_argsList
      (Primrec.const 0))

private theorem succFunEval_computableIn :
    ComputableIn O fun p : ℕ × FunctionApplicationData succLang ℕ ↦ p.2.argsList[0]! + 1 :=
  ComputableIn.comp (O := O) (α := ℕ × FunctionApplicationData succLang ℕ)
    (β := FunctionApplicationData succLang ℕ) (σ := ℕ)
    (f := fun d : FunctionApplicationData succLang ℕ ↦ d.argsList[0]! + 1)
    (g := fun p ↦ p.2)
    succArgHead_primrec.to_comp.computableIn ComputableIn.snd

/-- **The successor tails.** Member `i` enumerates `{i, i+1, …}` in the successor structure and
records the single generator `[i]`. -/
def succTailAge : PartialAgeIn O succLang where
  structureAt _ := succStructure
  enum? i m := Option.some (i + m)
  enum?_computableIn := ComputableIn.option_some.comp Primrec.nat_add.to_comp.computableIn
  gens i := [i]
  gens_computableIn :=
    (Primrec.list_cons.comp Primrec.id (Primrec.const [])).to_comp.computableIn
  funEval _ d := Part.some (d.argsList[0]! + 1)
  funEval_recursiveIn := succFunEval_computableIn
  funEval_correct := fun _ d _ ↦ by
    match d with
    | ⟨1, .succ, _⟩ => exact Part.mem_some _
    | ⟨0, f, _⟩ => exact isEmptyElim f
    | ⟨_ + 2, f, _⟩ => exact isEmptyElim f
  relEval _ _ := Part.none
  relEval_recursiveIn := RecursiveIn.none
  relEval_correct := fun _ d _ ↦ isEmptyElim d
  generates := fun i x ↦ by
    constructor
    · rintro ⟨m, hm⟩
      exact ⟨iterSucc m, by rw [iterSucc_realize]; exact (Option.some_inj.1 hm).symm⟩
    · rintro ⟨T, hT⟩
      obtain ⟨n, hn⟩ := exists_realize_add i T
      exact ⟨n, by rw [hT, hn]⟩

/-- **The carriers are exactly the tails.** -/
theorem mem_succTailAge_domainAt_iff (i x : ℕ) :
    x ∈ (succTailAge (O := O)).domainAt i ↔ i ≤ x := by
  constructor
  · rintro ⟨m, hm⟩
    have : i + m = x := Option.some_inj.1 hm
    omega
  · intro h
    refine ⟨x - i, ?_⟩
    show Option.some (i + (x - i)) = Option.some x
    congr 1
    omega

/-! ### The shift, and the data naming it -/

/-- The underlying map of the shift. Split out with its three laws, each fully typed: assembling
them inline leaves `Subtype.ext`'s endpoints as placeholders inside the structure instance. -/
private def shiftFun (x : ((succTailAge (O := O)).memberAt 0).domain) :
    ((succTailAge (O := O)).memberAt 2).domain :=
  ⟨(x : ℕ) + 2, (mem_succTailAge_domainAt_iff (O := O) 2 ((x : ℕ) + 2)).2 (Nat.le_add_left 2 _)⟩

private theorem shiftFun_val (x : ((succTailAge (O := O)).memberAt 0).domain) :
    ((shiftFun x : ((succTailAge (O := O)).memberAt 2).domain) : ℕ) = (x : ℕ) + 2 := rfl

private theorem shiftFun_injective : Function.Injective (shiftFun (O := O)) := by
  intro x y h
  have hv : (x : ℕ) + 2 = (y : ℕ) + 2 := by
    rw [← shiftFun_val x, ← shiftFun_val y, h]
  exact Subtype.ext (by omega)

private theorem shiftFun_map_fun {n : ℕ} (f : succLang.Functions n)
    (v : Fin n → ((succTailAge (O := O)).memberAt 0).domain) :
    shiftFun (Structure.funMap f v) = Structure.funMap f (shiftFun ∘ v) := by
  match n, f with
  | 1, .succ =>
    refine Subtype.ext ?_
    show (v 0 : ℕ) + 1 + 2 = (v 0 : ℕ) + 2 + 1
    omega

/-- Shifting by `2` embeds member `0` (all of `ℕ`) into member `2` (`{2, 3, …}`). -/
def shiftBy2 :
    ((succTailAge (O := O)).memberAt 0).domain ↪[succLang]
      ((succTailAge (O := O)).memberAt 2).domain where
  toFun := shiftFun
  inj' := shiftFun_injective
  map_fun' := shiftFun_map_fun
  map_rel' {_} R _ := isEmptyElim R

/-- The data naming the shift: member `0`'s generator `[0]` goes to `[2]` in member `2`. -/
def shiftData : PotentialEmbeddingData := ⟨0, 2, [2]⟩

/-- Data pointing *out of* member `2`, used only for the divergence row. -/
def shiftedData : PotentialEmbeddingData := ⟨2, 4, [4]⟩

/-- The shift realizes the data — the hypothesis every correctness row consumes. -/
theorem shiftBy2_realizes : (succTailAge (O := O)).PartialRealizes shiftData shiftBy2 :=
  ⟨rfl, fun k ↦ by
    match k with
    | ⟨0, _⟩ => rfl⟩

/-! ### Gate 1: the abstract contracts -/

/-- **The application is partial recursive in the base oracle**, with no inclusion hypothesis. -/
theorem test_applyPotentialPart_recursiveIn {L : Language} [L.EffectiveLanguage]
    (A : PartialAgeIn O L) :
    RecursiveIn O fun p : PotentialEmbeddingData × ℕ ↦ A.applyPotentialPart p.1 p.2 :=
  A.applyPotentialPart_recursiveIn

/-- **The target half applies the realizer**, with no reference to the search. -/
theorem test_partialRealize_rangeTuple {L : Language} [L.EffectiveLanguage]
    {A : PartialAgeIn O L} {F : PotentialEmbeddingData}
    {f : (A.memberAt F.domIdx).domain ↪[L] (A.memberAt F.codIdx).domain}
    (hf : A.PartialRealizes F f) {t : L.Term ℕ}
    (ht : Term.VarsBelow (A.gens F.domIdx).length t) :
    A.partialRealize F.codIdx F.rangeTuple t =
      Part.some ((f ⟨A.gensRealize F.domIdx t, PartialAgeIn.gensRealize_mem_domainAt ht⟩ :
        (A.memberAt F.codIdx).domain) : ℕ) :=
  PartialAgeIn.partialRealize_rangeTuple_eq_some hf ht

/-- **The application computes the realizer** on the whole source carrier. -/
theorem test_applyPotentialPart_mem_realizer {L : Language} [L.EffectiveLanguage]
    {A : PartialAgeIn O L} {F : PotentialEmbeddingData}
    {f : (A.memberAt F.domIdx).domain ↪[L] (A.memberAt F.codIdx).domain}
    (hf : A.PartialRealizes F f) {x : ℕ} (hx : x ∈ (A.memberAt F.domIdx).domain) :
    ((f ⟨x, hx⟩ : (A.memberAt F.codIdx).domain) : ℕ) ∈ A.applyPotentialPart F x :=
  PartialAgeIn.applyPotentialPart_mem_realizer hf hx

/-- **Actual data makes the application total on the source carrier**, with no realizer in the
statement. -/
theorem test_dom_of_partialIsEmbedding {L : Language} [L.EffectiveLanguage]
    {A : PartialAgeIn O L} {F : PotentialEmbeddingData} (h : A.PartialIsEmbedding F) {x : ℕ}
    (hx : x ∈ (A.memberAt F.domIdx).domain) : (A.applyPotentialPart F x).Dom :=
  PartialAgeIn.applyPotentialPart_dom_of_partialIsEmbedding h hx

/-- **And the value lands in the target member**, again with no realizer in the statement. -/
theorem test_mem_domainAt_of_partialIsEmbedding {L : Language} [L.EffectiveLanguage]
    {A : PartialAgeIn O L} {F : PotentialEmbeddingData} (h : A.PartialIsEmbedding F) {x y : ℕ}
    (hx : x ∈ (A.memberAt F.domIdx).domain) (hy : y ∈ A.applyPotentialPart F x) :
    y ∈ (A.memberAt F.codIdx).domain :=
  PartialAgeIn.applyPotentialPart_mem_domainAt_of_partialIsEmbedding h hx hy

/-! ### Gate 2: the recorded generator -/

/-- On the recorded generator the application returns the recorded range entry. This row would
pass even with the term search stubbed out to "return the variable", which is why it is not the
headline. -/
theorem test_apply_generator :
    (succTailAge (O := O)).applyPotentialPart shiftData 0 = Part.some 2 :=
  Part.eq_some_iff.2 (PartialAgeIn.applyPotentialPart_mem_realizer (shiftBy2_realizes (O := O))
    ((mem_succTailAge_domainAt_iff (O := O) 0 0).2 (le_refl 0)))

/-! ### Gate 3: a genuine non-generator -/

/-- `5` is not among member `0`'s recorded generators — it is reached only through the function
symbol. -/
theorem test_five_not_generator : (5 : ℕ) ∉ (succTailAge (O := O)).gens 0 := by
  show (5 : ℕ) ∉ [0]
  simp

/-- **The headline row: `5 ↦ 7`.** The value is found by searching for a term over `[0]` — five
applications of the successor symbol — and re-realizing that term over the range tuple `[2]`
inside member `2`. Every number here is distinct, so the identity and the wrong-direction shift
both fail numerically. -/
theorem test_apply_non_generator :
    (succTailAge (O := O)).applyPotentialPart shiftData 5 = Part.some 7 :=
  Part.eq_some_iff.2 (PartialAgeIn.applyPotentialPart_mem_realizer (shiftBy2_realizes (O := O))
    ((mem_succTailAge_domainAt_iff (O := O) 0 5).2 (Nat.zero_le 5)))

/-! ### Gate 4: the search really is partial -/

/-- **Below the source member's least element the application diverges.** `applyPotentialPart` has
no exact-domain theorem — on malformed data it can halt accidentally — but divergence is still
forced wherever the *search* diverges, and this row exhibits that. It needs an infinite carrier
that is a proper subset of `ℕ`, which no finite fixture supplies. -/
theorem test_apply_below_carrier_diverges :
    ¬ ((succTailAge (O := O)).applyPotentialPart shiftedData 1).Dom := by
  intro h
  obtain ⟨y, hy⟩ := Part.dom_iff_mem.1 h
  obtain ⟨m, hm, -⟩ := Part.mem_bind_iff.1 hy
  have h2 : (1 : ℕ) ∈ (succTailAge (O := O)).domainAt 2 :=
    PartialAgeIn.gensTermCode_dom_iff.1 (Part.dom_iff_mem.2 ⟨m, hm⟩)
  exact absurd ((mem_succTailAge_domainAt_iff 2 1).1 h2) (by omega)

/-- And the search does halt on that member's own carrier — the same predicate, the other way. -/
theorem test_search_halts_on_carrier :
    ((succTailAge (O := O)).gensTermCode 2 5).Dom :=
  PartialAgeIn.gensTermCode_dom_iff.2 ((mem_succTailAge_domainAt_iff 2 5).2 (by omega))

end

end FirstOrder.Language

open FirstOrder.Language

#assert_standard_axioms FirstOrder.Language.test_applyPotentialPart_recursiveIn
#assert_standard_axioms FirstOrder.Language.test_partialRealize_rangeTuple
#assert_standard_axioms FirstOrder.Language.test_applyPotentialPart_mem_realizer
#assert_standard_axioms FirstOrder.Language.test_dom_of_partialIsEmbedding
#assert_standard_axioms FirstOrder.Language.test_mem_domainAt_of_partialIsEmbedding
#assert_standard_axioms FirstOrder.Language.test_apply_generator
#assert_standard_axioms FirstOrder.Language.test_five_not_generator
#assert_standard_axioms FirstOrder.Language.test_apply_non_generator
#assert_standard_axioms FirstOrder.Language.test_apply_below_carrier_diverges
#assert_standard_axioms FirstOrder.Language.test_search_halts_on_carrier
