/-
Copyright (c) 2026 Cameron Freer. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Cameron Freer
-/
import ComputableModelTheory.ModelTheory.Computable.PartialAgeSemantics
import ComputableModelTheory.ModelTheory.Computable.PartialTupleReindex

/-!
# The computable hereditary-property selector

CHMM Theorem 2.8's effective half for the empty-capable setting: given a re-indexed member
and a tuple `s` of its elements, *effectively locate* a re-indexed member generated by
exactly `s`. The selector is minimal —

```
((i, e), s)  ↦  stepsForTuple i s  ↦  (i, encode steps)
```

— and stays inside the **same ambient member** `i`, which is what makes the located member
a substructure of the current one rather than merely an abstract isomorphic copy.

What is claimed:

* `chpSelect_recursiveIn` — uniformly partial recursive in the oracle.
* `chpSelect_dom` — halts on every tuple lying in the current re-indexed member.
* `gens_of_mem_chpSelect` — the selected member's recorded generators are **literally the
  list `s`**, order and multiplicity included, not merely a tuple with the same range.
* `chpEmbedding` — the identity on values extends to an embedding of the selected member
  into the current one, by closure monotonicity.
* `chpSelect_nil` — `s = []` returns the empty step list, hence the empty-generated
  member; nothing here presumes a nonempty tuple.

What is **not** claimed: the selector is not total, and its domain is not characterized.
It is built from `stepsForTuple`, so it also halts on ambient-domain tuples lying outside
the current generated member; no exact-domain statement is made, and per the Level-1
boundary it cannot be promoted to a total `ComputableIn` selector, since tuple validity is
only c.e.

**Independence from the hereditary property.** Nothing here uses `HasHP`, and this file
does not import `PartialSameClass`. The hereditary property is needed only to show the
re-indexed family represents the same isomorphism classes; CHP soundness is a separate
fact, and Theorem 2.8 combines the two. (`PartialAgeSemantics` is imported for the
identity-on-values embedding bridge alone.)
-/

open Encodable Part FirstOrder Language

namespace FirstOrder.Language

variable {O : Set (ℕ →. ℕ)} {L : Language} [L.EffectiveLanguage]

namespace PartialAgeIn

/-- The re-indexed index naming the substructure of member `i` generated by the given
enumeration steps — a right inverse of `memberIndex`. -/
def reindexIndex (i : ℕ) (steps : List ℕ) : ℕ :=
  encode ((i, steps) : ℕ × List ℕ)

@[simp]
theorem memberIndex_reindexIndex (i : ℕ) (steps : List ℕ) :
    memberIndex (reindexIndex i steps) = (i, steps) := by
  simp [memberIndex, reindexIndex, Denumerable.ofNat_encode]

variable (A : PartialAgeIn O L)

/-- **The CHP selector.** From the index of a re-indexed member and a tuple `s`, search for
enumeration steps realizing `s` in the *same* ambient member, and return the re-indexed
member generated by those steps. Partial by design. -/
noncomputable def chpSelect (e : ℕ) (s : List ℕ) : Part ℕ :=
  (A.stepsForTuple (memberIndex e).1 s).map (reindexIndex (memberIndex e).1)

variable {A}

theorem mem_chpSelect_iff {e : ℕ} {s : List ℕ} {c : ℕ} :
    c ∈ A.chpSelect e s ↔
      ∃ steps ∈ A.stepsForTuple (memberIndex e).1 s,
        reindexIndex (memberIndex e).1 steps = c :=
  Part.mem_map_iff _

/-! ### The gates -/

variable (A)

/-- The selector is partial recursive uniformly in the oracle, in the current member index
and the queried tuple. -/
theorem chpSelect_recursiveIn :
    RecursiveIn O fun p : ℕ × List ℕ ↦ A.chpSelect p.1 p.2 := by
  have hsteps : RecursiveIn O fun p : ℕ × List ℕ ↦
      A.stepsForTuple (memberIndex p.1).1 p.2 :=
    RecursiveIn.comp (O := O) (α := ℕ × List ℕ) (β := ℕ × List ℕ) (σ := List ℕ)
      (f := fun q : ℕ × List ℕ ↦ A.stepsForTuple q.1 q.2)
      (g := fun p : ℕ × List ℕ ↦ ((memberIndex p.1).1, p.2))
      A.stepsForTuple_recursiveIn memberIndex_fst_pair_computableIn
  have hidx : ComputableIn₂ O fun (p : ℕ × List ℕ) (steps : List ℕ) ↦
      reindexIndex (memberIndex p.1).1 steps :=
    ((ComputableIn.encode (α := ℕ × List ℕ) (O := O)).comp
      ((ComputableIn.fst.comp
        (memberIndex_computableIn.comp (ComputableIn.fst.comp ComputableIn.fst))).pair
        ComputableIn.snd)).to₂
  exact (RecursiveIn.map (O := O) (α := ℕ × List ℕ) (β := List ℕ) (σ := ℕ)
    (f := fun p : ℕ × List ℕ ↦ A.stepsForTuple (memberIndex p.1).1 p.2)
    (g := fun (p : ℕ × List ℕ) (steps : List ℕ) ↦ reindexIndex (memberIndex p.1).1 steps)
    hsteps hidx).of_eq fun _ ↦ rfl

variable {A}

/-- The selector halts on every tuple drawn from the current re-indexed member. (It may
also halt elsewhere: it is built from `stepsForTuple`, which halts on every tuple of the
*ambient* member. No exact-domain claim is made.) -/
theorem chpSelect_dom {e : ℕ} {s : List ℕ}
    (hs : ∀ x ∈ s, x ∈ A.reindexed.domainAt e) : (A.chpSelect e s).Dom := by
  show (A.stepsForTuple (memberIndex e).1 s).Dom
  exact (A.stepsForTuple_dom_iff).2 fun x hx ↦ A.reindexed_domainAt_subset e (hs x hx)

/-- **The selected member is generated by `s` on the nose**: its recorded generator tuple
is literally the list `s` — same order, same multiplicity — not merely a tuple with the
same range. -/
theorem gens_of_mem_chpSelect {e : ℕ} {s : List ℕ} {c : ℕ} (h : c ∈ A.chpSelect e s) :
    A.reindexed.gens c = s := by
  obtain ⟨steps, hsteps, rfl⟩ := mem_chpSelect_iff.1 h
  rw [A.reindexed_gens, memberIndex_reindexIndex]
  exact A.tupleAtSteps_of_mem_stepsForTuple hsteps

/-- The selector stays inside the same ambient member — the reason the located member is a
substructure of the current one, not merely isomorphic to one. -/
theorem memberIndex_fst_of_mem_chpSelect {e : ℕ} {s : List ℕ} {c : ℕ}
    (h : c ∈ A.chpSelect e s) : (memberIndex c).1 = (memberIndex e).1 := by
  obtain ⟨steps, -, rfl⟩ := mem_chpSelect_iff.1 h
  rw [memberIndex_reindexIndex]

/-- The selected member's carrier sits inside the current member's, by closure
monotonicity: `s` lies in the current generated substructure, so the substructure `s`
generates does too. -/
theorem chpSelect_domainAt_subset {e : ℕ} {s : List ℕ} {c : ℕ} (h : c ∈ A.chpSelect e s)
    (hs : ∀ x ∈ s, x ∈ A.reindexed.domainAt e) :
    A.reindexed.domainAt c ⊆ A.reindexed.domainAt e := by
  obtain ⟨steps, hsteps, rfl⟩ := mem_chpSelect_iff.1 h
  letI : L.Structure ℕ := A.structureAt (memberIndex e).1
  rw [A.reindexed_domainAt_of_memberIndex (memberIndex_reindexIndex _ _),
    A.tupleAtSteps_of_mem_stepsForTuple hsteps]
  intro x hx
  have hx' : x ∈ Substructure.closure L (Set.range (Tuple.view s)) := hx
  have hgoal : x ∈ Substructure.closure L
      (Set.range (Tuple.view (A.tupleAtSteps (memberIndex e).1 (memberIndex e).2))) := by
    refine Substructure.closure_le.2 ?_ hx'
    intro y hy
    rw [Tuple.range_view] at hy
    have hy' := hs y hy
    rw [A.reindexed_domainAt e] at hy'
    exact hy'
  rw [A.reindexed_domainAt e]
  exact hgoal

/-- The identity on values extends to an embedding of the selected member into the current
one. This is the substructure statement CHP is for. -/
noncomputable def chpEmbedding {e : ℕ} {s : List ℕ} {c : ℕ} (h : c ∈ A.chpSelect e s)
    (hs : ∀ x ∈ s, x ∈ A.reindexed.domainAt e) :
    (A.reindexed.memberAt c).domain ↪[L] (A.reindexed.memberAt e).domain :=
  PartialCePresentationIn.subsetDomainEmbedding
    (show (A.reindexed.memberAt c).str = (A.reindexed.memberAt e).str by
      show A.structureAt (memberIndex c).1 = A.structureAt (memberIndex e).1
      rw [memberIndex_fst_of_mem_chpSelect h])
    (chpSelect_domainAt_subset h hs)

/-! ### The empty query tuple -/

@[simp]
theorem stepsForTuple_nil (i : ℕ) : A.stepsForTuple i [] = Part.some [] :=
  rfl

@[simp]
theorem tupleAtSteps_nil (i : ℕ) : A.tupleAtSteps i [] = [] :=
  rfl

/-- The empty query tuple returns the empty step list, hence the empty-generated member.
No nonemptiness is presumed anywhere in the selector. -/
theorem chpSelect_nil (e : ℕ) :
    A.chpSelect e [] = Part.some (reindexIndex (memberIndex e).1 []) := by
  rw [chpSelect, stepsForTuple_nil]
  rfl

/-- The member the empty query selects records the empty generator tuple. -/
theorem gens_chpSelect_nil (e : ℕ) :
    A.reindexed.gens (reindexIndex (memberIndex e).1 []) = [] := by
  rw [A.reindexed_gens, memberIndex_reindexIndex]
  rfl

end PartialAgeIn

end FirstOrder.Language
