/-
Copyright (c) 2026 Cameron Freer. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Cameron Freer
-/
import ComputableModelTheory.ModelTheory.Computable.ComputableAge
import ComputableModelTheory.ModelTheory.Computable.PartialCePresentation
import ComputableModelTheory.ModelTheory.Computable.TermEvaluation

/-!
# Tuple re-indexing: generated substructures inside age members (CHMM Theorem 2.8)

The construction underlying CHMM Theorem 2.8: inside each member `Bᵢ` of a computable
age presentation, the substructure `⟨t⟩` generated by a finite tuple `t` is a Level-1
c.e. presentation — the ambient structure data with the term-value enumeration of the
closure. Per the #16 obstruction, this is where the construction stops: no uniform
upgrade to a decidable initial segment exists, and none is claimed. Nor is `⟨t⟩`
claimed computably isomorphic to anything — Theorem 2.8 only needs that the
re-indexed family represents the same isomorphism classes.

The full construction ranges over **all** finite tuples — CHMM's enumeration
includes the empty tuple, which matters twice: constants can make the
empty-generated substructure nonempty, and in a constant-free relational language it
is genuinely empty. The construction therefore targets the possibly-empty layer
(`PartialCePresentationIn`): `generatedPresentationOf` takes any tuple, with no
fallback in its `Option`-valued enumeration. The nonempty-tuple specialization at
the `CePresentationIn` layer is retained (`generatedPresentation`), agreeing with
the full construction through the embedding.

This file: the per-index construction and its domain characterizations. The uniform
enumeration of the family, the same-class argument through HP, and the CHP selector
follow.
-/

open Encodable Part FirstOrder Language

namespace FirstOrder.Language

variable {O : Set (ℕ →. ℕ)} {L : Language} [L.EffectiveLanguage]

namespace ComputableAgeIn

variable (K : ComputableAgeIn O L)

/-- Each member of a computable age is a computable structure — the fixed-index
instance derived from the uniform fields. -/
theorem isComputableAt (i : ℕ) :
    @IsComputableStructureIn O L _ (K.structureAt i) :=
  @IsComputableStructureIn.mk O L _ (K.structureAt i)
    (K.funMap_computableIn.comp ((ComputableIn.const i).pair ComputableIn.id))
    (by
      obtain ⟨inst, hcomp⟩ := K.relMap_computablePredIn
      exact ⟨fun d ↦ inst (i, d),
        (hcomp.comp ((ComputableIn.const i).pair ComputableIn.id)).of_eq
          fun _ ↦ rfl⟩)

end ComputableAgeIn

/-- The enumeration of nonempty tuples: every nonempty tuple appears, and only
nonempty tuples appear. -/
def tupleFor (e : ℕ) : Tuple ℕ :=
  (Denumerable.ofNat (ℕ × List ℕ) e).1 :: (Denumerable.ofNat (ℕ × List ℕ) e).2

theorem tupleFor_ne_nil (e : ℕ) : tupleFor e ≠ [] := by
  simp [tupleFor]

theorem tupleFor_surjective {t : Tuple ℕ} (ht : t ≠ []) : ∃ e, tupleFor e = t := by
  rcases t with - | ⟨a, l⟩
  · exact absurd rfl ht
  · exact ⟨Encodable.encode ((a, l) : ℕ × List ℕ), by
      simp [tupleFor, Denumerable.ofNat_encode]⟩

theorem tupleFor_computableIn : ComputableIn O tupleFor :=
  (Computable.list_cons.computableIn₂).comp
    ((Computable.fst.computableIn).comp
      ((Computable.ofNat (ℕ × List ℕ)).computableIn))
    ((Computable.snd.computableIn).comp
      ((Computable.ofNat (ℕ × List ℕ)).computableIn))

namespace ComputableAgeIn

variable (K : ComputableAgeIn O L)

/-- The term-value enumeration of the substructure of `Bᵢ` generated by a nonempty
tuple: decode a term over the tuple's variables and realize it; undecodable codes
fall back to the tuple's head (itself a term value). -/
noncomputable def genEnum (i : ℕ) (t : Tuple ℕ) : ℕ → ℕ :=
  fun m ↦ ((@decode (L.Term (Fin t.length)) Primcodable.toEncodable m).map
    fun T ↦ @Term.realize L ℕ (K.structureAt i) _ (Tuple.view t) T).getD t.headI

/-- Every enumerated element is a term value. -/
theorem genEnum_is_term_value (i : ℕ) (t : Tuple ℕ) (ht : t ≠ []) (m : ℕ) :
    ∃ T : L.Term (Fin t.length),
      K.genEnum i t m = @Term.realize L ℕ (K.structureAt i) _ (Tuple.view t) T := by
  rw [genEnum]
  rcases hd : @decode (L.Term (Fin t.length)) Primcodable.toEncodable m with - | T
  · refine ⟨Term.var ⟨0, by
      rcases t with - | ⟨a, l⟩
      · exact absurd rfl ht
      · simp⟩, ?_⟩
    rcases t with - | ⟨a, l⟩
    · exact absurd rfl ht
    · rfl
  · exact ⟨T, rfl⟩

/-- Every term value is enumerated. -/
theorem term_value_mem_range_genEnum (i : ℕ) (t : Tuple ℕ)
    (T : L.Term (Fin t.length)) :
    @Term.realize L ℕ (K.structureAt i) _ (Tuple.view t) T
      ∈ Set.range (K.genEnum i t) := by
  refine ⟨@encode (L.Term (Fin t.length)) Primcodable.toEncodable T, ?_⟩
  rw [genEnum,
    @Encodable.encodek (L.Term (Fin t.length)) Primcodable.toEncodable T]
  rfl

/-- The range of the generated enumeration is exactly the term values over the
tuple. -/
theorem range_genEnum (i : ℕ) (t : Tuple ℕ) (ht : t ≠ []) :
    Set.range (K.genEnum i t)
      = {x | ∃ T : L.Term (Fin t.length),
          x = @Term.realize L ℕ (K.structureAt i) _ (Tuple.view t) T} := by
  ext x
  constructor
  · rintro ⟨m, rfl⟩
    exact K.genEnum_is_term_value i t ht m
  · rintro ⟨T, rfl⟩
    exact K.term_value_mem_range_genEnum i t T

private theorem decode_term_computableIn {O : Set (ℕ →. ℕ)} (k : ℕ) :
    ComputableIn O fun m : ℕ ↦ @decode (L.Term (Fin k)) Primcodable.toEncodable m :=
  (Computable.decode.computableIn (O := O)).of_eq fun _ ↦ rfl

attribute [local irreducible] Term.instPrimcodableTerm in
open Classical in
/-- The Level-1 generated-substructure presentation: the ambient member's structure
data, enumerated by term values over the tuple. Not upgraded to a decidable initial
segment — the #16 obstruction forbids doing so uniformly — and not claimed
isomorphic to the ambient member. -/
noncomputable def generatedPresentation (i : ℕ) (t : Tuple ℕ) (ht : t ≠ []) :
    CePresentationIn O L where
  str := K.structureAt i
  enum := K.genEnum i t
  enum_computableIn := by
    have hreal : ComputableIn O fun p : ℕ × L.Term (Fin t.length) ↦
        @Term.realize L ℕ (K.structureAt i) _ (Tuple.view t) p.2 :=
      ComputableIn.comp
        (f := fun q : L.Term (Fin t.length) × (Fin t.length → ℕ) ↦
          @Term.realize L ℕ (K.structureAt i) _ q.2 q.1)
        (g := fun p : ℕ × L.Term (Fin t.length) ↦ (p.2, Tuple.view t))
        (@Term.realize_computableIn L _ t.length O (K.structureAt i)
          (K.isComputableAt i))
        (ComputableIn.snd.pair (ComputableIn.const (Tuple.view t)))
    have hmap : ComputableIn O fun m : ℕ ↦
        (@decode (L.Term (Fin t.length)) Primcodable.toEncodable m).map
          fun T ↦ @Term.realize L ℕ (K.structureAt i) _ (Tuple.view t) T :=
      ComputableIn.option_map
        (f := fun m : ℕ ↦ @decode (L.Term (Fin t.length)) Primcodable.toEncodable m)
        (g := fun (_ : ℕ) (T : L.Term (Fin t.length)) ↦
          @Term.realize L ℕ (K.structureAt i) _ (Tuple.view t) T)
        (decode_term_computableIn t.length) hreal.to₂
    exact (ComputableIn.option_casesOn hmap (ComputableIn.const t.headI)
      (ComputableIn.snd.to₂)).of_eq fun m ↦ by
        rw [genEnum]
        cases (@decode (L.Term (Fin t.length)) Primcodable.toEncodable m).map
          fun T ↦ @Term.realize L ℕ (K.structureAt i) _ (Tuple.view t) T <;> rfl
  domain_closed := by
    intro n f v hv
    have hT : ∀ k, ∃ T : L.Term (Fin t.length),
        v k = @Term.realize L ℕ (K.structureAt i) _ (Tuple.view t) T := fun k ↦ by
      obtain ⟨m, hm⟩ := hv k
      exact hm ▸ K.genEnum_is_term_value i t ht m
    choose Ts hTs using hT
    have hfun : @Structure.funMap L ℕ (K.structureAt i) n f v
        = @Term.realize L ℕ (K.structureAt i) _
          (Tuple.view t) (Term.func f Ts) := by
      letI : L.Structure ℕ := K.structureAt i
      rw [Term.realize_func]
      exact congrArg _ (funext fun k ↦ hTs k)
    rw [hfun]
    exact K.term_value_mem_range_genEnum i t _
  funEval := (ComputableStructureIn.toCePresentation
    { inst := K.structureAt i, isComputable := K.isComputableAt i }).funEval
  funEval_recursiveIn := (ComputableStructureIn.toCePresentation
    { inst := K.structureAt i, isComputable := K.isComputableAt i }).funEval_recursiveIn
  funEval_correct := fun d _ ↦ (ComputableStructureIn.toCePresentation
    { inst := K.structureAt i,
      isComputable := K.isComputableAt i }).funEval_correct d
    fun k ↦ ⟨d.args k, rfl⟩
  relEval := (ComputableStructureIn.toCePresentation
    { inst := K.structureAt i, isComputable := K.isComputableAt i }).relEval
  relEval_recursiveIn := (ComputableStructureIn.toCePresentation
    { inst := K.structureAt i, isComputable := K.isComputableAt i }).relEval_recursiveIn
  relEval_correct := fun d _ ↦ (ComputableStructureIn.toCePresentation
    { inst := K.structureAt i,
      isComputable := K.isComputableAt i }).relEval_correct d
    fun k ↦ ⟨d.args k, rfl⟩

/-- The generated presentation keeps the ambient structure data. -/
@[simp]
theorem generatedPresentation_str (i : ℕ) (t : Tuple ℕ) (ht : t ≠ []) :
    (K.generatedPresentation i t ht).str = K.structureAt i :=
  rfl

/-- The domain of the generated presentation is exactly the term values — the
carrier of `⟨t⟩` inside `Bᵢ`. -/
theorem generatedPresentation_domain (i : ℕ) (t : Tuple ℕ) (ht : t ≠ []) :
    (K.generatedPresentation i t ht).domain
      = {x | ∃ T : L.Term (Fin t.length),
          x = @Term.realize L ℕ (K.structureAt i) _ (Tuple.view t) T} :=
  K.range_genEnum i t ht

/-- The generators lie in the generated domain. -/
theorem gens_mem_generatedPresentation_domain (i : ℕ) (t : Tuple ℕ) (ht : t ≠ [])
    (k : Fin t.length) :
    t.get k ∈ (K.generatedPresentation i t ht).domain := by
  rw [K.generatedPresentation_domain i t ht]
  exact ⟨Term.var k, rfl⟩

/-- A member generated by its own generator tuple has full domain: the whole member
reappears among the generated presentations. -/
theorem generatedPresentation_domain_of_gens (i : ℕ) (ht : K.gens i ≠ []) :
    (K.generatedPresentation i (K.gens i) ht).domain = Set.univ := by
  rw [K.generatedPresentation_domain i (K.gens i) ht]
  refine Set.eq_univ_of_forall fun x ↦ ?_
  obtain ⟨T, hT⟩ :=
    (@Tuple.generates_iff L ℕ (K.structureAt i) (K.gens i)).1 (K.generates i) x
  exact ⟨T, hT.symm⟩

/-- A member of a computable age, bundled with its fixed-index computability. -/
noncomputable def bundleAt (i : ℕ) : ComputableStructureIn O L :=
  { inst := K.structureAt i, isComputable := K.isComputableAt i }

end ComputableAgeIn

/-- The enumeration of **all** finite tuples, including the empty one. -/
def allTupleFor (e : ℕ) : Tuple ℕ :=
  Denumerable.ofNat (List ℕ) e

theorem allTupleFor_surjective (t : Tuple ℕ) : ∃ e, allTupleFor e = t :=
  ⟨Encodable.encode t, by simp [allTupleFor, Denumerable.ofNat_encode]⟩

theorem allTupleFor_computableIn : ComputableIn O allTupleFor :=
  (Computable.ofNat (List ℕ)).computableIn

namespace ComputableStructureIn

variable (S : ComputableStructureIn O L)

/-- The `Option`-valued term-value enumeration of the substructure generated by an
arbitrary tuple: decode a term and realize it; undecodable codes enumerate nothing.
For the empty tuple over a constant-free language no term decodes, and the
enumeration is empty. -/
noncomputable def genEnum? (t : Tuple ℕ) : ℕ → Option ℕ :=
  fun m ↦ (@decode (L.Term (Fin t.length)) Primcodable.toEncodable m).map
    fun T ↦ @Term.realize L ℕ S.inst _ (Tuple.view t) T

theorem genEnum?_eq_some_iff {t : Tuple ℕ} {m x : ℕ} :
    S.genEnum? t m = Option.some x ↔
      ∃ T : L.Term (Fin t.length),
        @decode (L.Term (Fin t.length)) Primcodable.toEncodable m = Option.some T ∧
          @Term.realize L ℕ S.inst _ (Tuple.view t) T = x := by
  rw [genEnum?, Option.map_eq_some_iff]

/-- The generated domain is exactly the term values over the tuple. -/
theorem exists_genEnum?_eq_some_iff {t : Tuple ℕ} {x : ℕ} :
    (∃ m, S.genEnum? t m = Option.some x) ↔
      ∃ T : L.Term (Fin t.length),
        @Term.realize L ℕ S.inst _ (Tuple.view t) T = x := by
  constructor
  · rintro ⟨m, hm⟩
    obtain ⟨T, -, hT⟩ := S.genEnum?_eq_some_iff.1 hm
    exact ⟨T, hT⟩
  · rintro ⟨T, hT⟩
    exact ⟨@encode (L.Term (Fin t.length)) Primcodable.toEncodable T,
      S.genEnum?_eq_some_iff.2 ⟨T,
        @Encodable.encodek (L.Term (Fin t.length)) Primcodable.toEncodable T, hT⟩⟩

attribute [local irreducible] Term.instPrimcodableTerm in
/-- The generated-substructure presentation of an **arbitrary** tuple, at the
possibly-empty layer: the full CHMM Theorem 2.8 construction, per tuple. Still
Level 1, still no isomorphism claim. -/
noncomputable def generatedPresentationOf (t : Tuple ℕ) :
    PartialCePresentationIn O L where
  str := S.inst
  enum? := S.genEnum? t
  enum?_computableIn := by
    have hreal : ComputableIn O fun p : ℕ × L.Term (Fin t.length) ↦
        @Term.realize L ℕ S.inst _ (Tuple.view t) p.2 :=
      ComputableIn.comp
        (f := fun q : L.Term (Fin t.length) × (Fin t.length → ℕ) ↦
          @Term.realize L ℕ S.inst _ q.2 q.1)
        (g := fun p : ℕ × L.Term (Fin t.length) ↦ (p.2, Tuple.view t))
        (@Term.realize_computableIn L _ t.length O S.inst S.isComputable)
        (ComputableIn.snd.pair (ComputableIn.const (Tuple.view t)))
    exact ComputableIn.option_map
      (f := fun m : ℕ ↦ @decode (L.Term (Fin t.length)) Primcodable.toEncodable m)
      (g := fun (_ : ℕ) (T : L.Term (Fin t.length)) ↦
        @Term.realize L ℕ S.inst _ (Tuple.view t) T)
      (ComputableAgeIn.decode_term_computableIn t.length) hreal.to₂
  domain_closed := by
    intro n f v hv
    have hT : ∀ k, ∃ T : L.Term (Fin t.length),
        @Term.realize L ℕ S.inst _ (Tuple.view t) T = v k :=
      fun k ↦ S.exists_genEnum?_eq_some_iff.1 (hv k)
    choose Ts hTs using hT
    refine S.exists_genEnum?_eq_some_iff.2 ⟨Term.func f Ts, ?_⟩
    letI : L.Structure ℕ := S.inst
    rw [Term.realize_func]
    exact congrArg _ (funext fun k ↦ hTs k)
  funEval := (ComputableStructureIn.toCePresentation S).funEval
  funEval_recursiveIn := (ComputableStructureIn.toCePresentation S).funEval_recursiveIn
  funEval_correct := fun d _ ↦
    (ComputableStructureIn.toCePresentation S).funEval_correct d
      fun k ↦ ⟨d.args k, rfl⟩
  relEval := (ComputableStructureIn.toCePresentation S).relEval
  relEval_recursiveIn := (ComputableStructureIn.toCePresentation S).relEval_recursiveIn
  relEval_correct := fun d _ ↦
    (ComputableStructureIn.toCePresentation S).relEval_correct d
      fun k ↦ ⟨d.args k, rfl⟩

/-- The generated presentation keeps the ambient structure data. -/
@[simp]
theorem generatedPresentationOf_str (t : Tuple ℕ) :
    (S.generatedPresentationOf t).str = S.inst :=
  rfl

/-- The domain of the full construction: exactly the term values over the tuple —
possibly empty, exactly when no closed term exists over an empty tuple. -/
theorem generatedPresentationOf_domain (t : Tuple ℕ) :
    (S.generatedPresentationOf t).domain
      = {x | ∃ T : L.Term (Fin t.length),
          x = @Term.realize L ℕ S.inst _ (Tuple.view t) T} := by
  ext x
  rw [PartialCePresentationIn.mem_domain_iff]
  rw [show (S.generatedPresentationOf t).enum? = S.genEnum? t from rfl]
  rw [S.exists_genEnum?_eq_some_iff]
  exact ⟨fun ⟨T, h⟩ ↦ ⟨T, h.symm⟩, fun ⟨T, h⟩ ↦ ⟨T, h.symm⟩⟩

end ComputableStructureIn

namespace ComputableAgeIn

variable (K : ComputableAgeIn O L)

/-- The tuple-re-indexed family member `A_{i,e} = ⟨tupleFor e⟩` inside `Bᵢ`, over all
tuples including the empty one. -/
noncomputable def generatedAt (i : ℕ) (t : Tuple ℕ) : PartialCePresentationIn O L :=
  (K.bundleAt i).generatedPresentationOf t

/-- Every original member reappears — with **no** hypothesis on its recorded
generator tuple: the member generated by its own generators has full domain. -/
theorem generatedAt_domain_of_gens (i : ℕ) :
    (K.generatedAt i (K.gens i)).domain = Set.univ := by
  rw [generatedAt, (K.bundleAt i).generatedPresentationOf_domain (K.gens i)]
  refine Set.eq_univ_of_forall fun x ↦ ?_
  obtain ⟨T, hT⟩ :=
    (@Tuple.generates_iff L ℕ (K.structureAt i) (K.gens i)).1 (K.generates i) x
  exact ⟨T, hT.symm⟩

/-- The nonempty-layer specialization agrees with the full construction through the
embedding: same domains on nonempty tuples. -/
theorem generatedPresentation_toPartial_domain (i : ℕ) (t : Tuple ℕ) (ht : t ≠ []) :
    (K.generatedPresentation i t ht).toPartial.domain = (K.generatedAt i t).domain := by
  rw [CePresentationIn.toPartial_domain, K.generatedPresentation_domain i t ht,
    generatedAt, (K.bundleAt i).generatedPresentationOf_domain t]
  rfl

end ComputableAgeIn

end FirstOrder.Language
